### PR TITLE
shell: Fix escaped newlines and add more tests

### LINKED ISSUE #9879: Spaces in directory break `bun run`
### What version of Bun is running?

1.1.0

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Attempt running `bun run dev` in a directory containing a space with the following scripts in package.json:
```
"scripts": {
    "extension-dev": "cd src/extension && webpack -w --config webpack.config.ts",
    "program-dev": "cd src/program && nodemon -e rs --watch src --exec cargo run --target-dir ../../dist/program",
    "dev": "concurrently -n EXT,PRO -c cyan,magenta \"npm run extension-dev\" \"npm run program-dev\""
}
```
(Replacing `npm run` with `bun run` yields the same result)

### What is the expected behavior?

Bun to run properly and account for the spaces.

### What do you see instead?

```
X:\Some Useful Stuff\Applications\Web\Slash-Playlist>bun run dev
$ concurrently -n EXT,PRO -c cyan,magenta "bun run extension-dev" "bun run program-dev"
'X:\Some' is not recognized as an internal or external command,
operable program or batch file.
error: script "dev" exited with code 1
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zackradisic**
### What does this PR do?
- [x] Code changes

Fixes escaped newlines in Bun shell not giving the correct output

This also adds some escaping/quoting tests ported from GNU bash's test suite

Fixes #9879

### How did you verify your code works?

- [x] I included a test for the new code, or existing tests cover it
- [x] I ran my tests locally and they pass (`bun-debug test test-file-name.test`)

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I included a test for the new code, or an existing test covers it
- [x] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

### CODE REVIEW

File: src/shell/interpreter.zig [hunk 1]
```diff
@@ -1065,6 +1065,20 @@ pub const Interpreter = struct {
             return shell.ParseError.Lex;
         }
 
+        if (comptime bun.Environment.allow_assert) {
+            const print = bun.Output.scoped(.ShellTokens, true);
+            var test_tokens = std.ArrayList(shell.Test.TestToken).initCapacity(arena.allocator(), lex_result.tokens.len) catch @panic("OOPS");
```
Comment (jdalton) [inline src/shell/interpreter.zig:1070]:
```suggestion
            var test_tokens = std.ArrayList(shell.Test.TestToken).initCapacity(arena.allocator(), lex_result.tokens.len) catch bun.outOfMemory()
```

File: src/shell/interpreter.zig [hunk 2]
```diff
@@ -1065,6 +1065,20 @@ pub const Interpreter = struct {
...
+            defer test_tokens.deinit();
+            for (lex_result.tokens) |tok| {
+                const test_tok = shell.Test.TestToken.from_real(tok, lex_result.strpool);
+                test_tokens.append(test_tok) catch @panic("OOPS");
+            }
+
+            const str = std.json.stringifyAlloc(bun.default_allocator, test_tokens.items[0..], .{}) catch @panic("OOPS");
```
Comment (jdalton) [inline src/shell/interpreter.zig:1077]: The oops's to `bun.outOfMemory()`'s

File: src/shell/interpreter.zig [hunk 3]
```diff
@@ -1065,6 +1065,20 @@ pub const Interpreter = struct {
             return shell.ParseError.Lex;
         }
 
+        if (comptime bun.Environment.allow_assert) {
+            const print = bun.Output.scoped(.ShellTokens, true);
+            var test_tokens = std.ArrayList(shell.Test.TestToken).initCapacity(arena.allocator(), lex_result.tokens.len) catch @panic("OOPS");
+            defer test_tokens.deinit();
+            for (lex_result.tokens) |tok| {
+                const test_tok = shell.Test.TestToken.from_real(tok, lex_result.strpool);
+                test_tokens.append(test_tok) catch @panic("OOPS");
```
Comment (Jarred-Sumner) [inline src/shell/interpreter.zig:1074]:
```suggestion
                test_tokens.append(test_tok) catch bun.outOfMemory();
```

**Comment by Jarred-Sumner** [comment]
Thank you
