### PR TITLE
Pass `test-crypto-keygen-*` tests

### LINKED ISSUE #9657: CryptoKey objects cannot be cloned
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

Linux 6.1.0-1029-oem x86_64 x86_64

### What steps can reproduce the bug?

```sh
$ bun init
```
In `index.ts`:
```typescript
const algo = { name: "HMAC", hash: "SHA-256" };
const key = await crypto.subtle.generateKey(algo, false, ["sign"]);
const cloned_key = structuredClone(key);
```
```sh
$ bun ./index.ts
```

### What is the expected behavior?

No errors, as with `node`

### What do you see instead?

`DataCloneError: The object can not be cloned.`

### Additional information

This is blocking passing keys to workers.

> CryptoKey objects can be stored using the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)

according to https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

Similar issue with Deno: https://github.com/denoland/deno/issues/12734

### LINKED ISSUE #10475: crypto createPrivateKey elliptic curve "Invalid EC private key"
### What version of Bun is running?

1.1.4

### What platform is your computer?

Linux 6.5.0-28-generic x86_64 x86_64

### What steps can reproduce the bug?

Below is a code snippet to reproduce the error:
```
import { createPrivateKey } from 'crypto';
import elliptic from 'elliptic';

const getSigningKey = (key: string, secret: string) => {
	const pubKey = new elliptic.ec('p256').keyFromPublic(Buffer.from(key, 'base64'));
	const x = Buffer.from(pubKey.getPublic().getX().toBuffer()).toString('base64');
	const y = Buffer.from(pubKey.getPublic().getY().toBuffer()).toString('base64');
	return createPrivateKey({
    key: { kty: 'EC', crv: 'P-256', x, y, d: secret },
    format: 'jwk',
  })
};

const key = getSigningKey('A3DCYHILTmyFdTD+HS/5qzBPzW04RweI0fzQeny3qmSu', 'IXotyQe5J6jmiSc76GtwdfmWRfPEUPJRgEJGYKxjUFY')
console.log(`🐃 ~ key:`, key)
```

### What is the expected behavior?

The code snippet (example.ts) produces a key object in ts-node:
```
🐃 ~ key: PrivateKeyObject [KeyObject] { [Symbol(kKeyType)]: 'private' }
```

### What do you see instead?

But, in bun I get this error:
```
 9 |     key: { kty: 'EC', crv: 'P-256', x, y, d: secret },
10 |     format: 'jwk',
11 |   })
12 | };
13 | 
14 | const key = getSigningKey('A3DCYHILTmyFdTD+HS/5qzBPzW04RweI0fzQeny3qmSu', 'IXotyQe5J6jmiSc76GtwdfmWRfPEUPJRgEJGYKxjUFY')
                 ^
TypeError: Invalid EC private key
      at node:crypto:48:63
      at /home/$USER/code/example.ts:14:13
```

### Additional information

migrating to bun, if this is working :)

### Edit: The below code snippet seems to work, changing base64 encodings to base64url
```
import { createPrivateKey } from 'crypto';
import elliptic from 'elliptic';

const getSigningKey = (key: string, secret: string) => {
	const pubKey = new elliptic.ec('p256').keyFromPublic(Buffer.from(key, 'base64url'));
	const x = Buffer.from(pubKey.getPublic().getX().toBuffer()).toString('base64url');
	const y = Buffer.from(pubKey.getPublic().getY().toBuffer()).toString('base64url');
	return createPrivateKey({
    key: { kty: 'EC', crv: 'P-256', x, y, d: secret },
    format: 'jwk',
  })
};

const key = getSigningKey('A3DCYHILTmyFdTD+HS/5qzBPzW04RweI0fzQeny3qmSu', 'IXotyQe5J6jmiSc76GtwdfmWRfPEUPJRgEJGYKxjUFY')
console.log(`🐃 ~ key:`, key)
```

### LINKED ISSUE #14682: crypto.createPublicKey Invalid EC public key
### What version of Bun is running?

1.1.31+e448c4cc3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Run these commands to generate cert.pem.
```
openssl ecparam -name prime256v1 -genkey -noout -out key.pem
openssl req -new -x509 -key key.pem -out cert.pem -days 365 -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=CommonName"
```

and run this code.
```
import fs from 'fs';
import crypto from 'crypto';

const publicKey = crypto.createPublicKey(fs.readFileSync('cert.pem'));
console.log(publicKey.type);
```

### What is the expected behavior?

In Node.js, it should console.log like this.
```
public
```

### What do you see instead?

```
1 | import fs from 'fs';
2 | import crypto from 'crypto';
3 |
4 | const publicKey = crypto.createPublicKey(fs.readFileSync('cert.pem'));
                             ^
TypeError: Invalid EC public key
      at _createPublicKey (node:crypto:112:26)
      at C:\ecPublicKeyIssue.js:4:26

Bun v1.1.31 (Windows x64)
```

### Additional information

`crypto.createPrivateKey(fs.readFileSync('key.pem'))` works without any issue.

the same cert.pem does work with Bun.serve without any issue as well.
```
Bun.serve({
    port: 443,
    key: Bun.file('key.pem'),
    cert: Bun.file('cert.pem'),
    fetch: () => {
        return Response('Hello World');
    }
});
```

prime256v1 / secp384r1 / secp521r1 doesn't change the behavior.

I only tested it on the Windows platform, I didn't test it on Linux/macOS.

### LINKED ISSUE #16652: x509.publicKey should be of type `KeyObject` but is `CryptoKey`
### What version of Bun is running?

1.2.0+b0c5a7655

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { X509Certificate } from "crypto";
const url = "https://www.apple.com/appleca/AppleIncRootCertificate.cer";
const response = await fetch(url);
const rootCert = Buffer.from(await response.arrayBuffer());
const x509 = new X509Certificate(rootCert);
console.log(x509.publicKey);
```
### What is the expected behavior?

The `@apple/app-store-server-library` expects `x509.publicKey` to be a `KeyObject`. See: https://github.com/apple/app-store-server-library-node/blob/main/jws_verification.ts#L194

### What do you see instead?

It is of type `CryptoKey` which cannot be exported in this manner:

```ts
        const encodedKey = publicKey.export({
          type: "spki",
          format: "pem"
        });
```

```ts
➜  bun-publickey-export-repro bun index.ts
CryptoKey {
  type: "public",
  extractable: true,
  algorithm: {
    name: "RSA-OAEP",
    modulusLength: 2048,
    publicExponent: Uint8Array(3) [ 1, 0, 1 ],
    hash: {
      name: "SHA-1",
    },
  },
  usages: [ "decrypt", "deriveBits", "deriveKey", "encrypt", "sign", "unwrapKey", "verify", "wrapKey" ],
}
```

### Additional information

_No response_

### LINKED ISSUE #18998: The `X509Certificate.checkPrivateKey` function must not modify the private key object passed to it.
### What version of Bun is running?

1.2.9

### What platform is your computer?

Tested on both Darwin 24.3.0 x86_64 i386 and Microsoft Windows NT 10.0.26100.0 x64

### What steps can reproduce the bug?

Consider the following code snippet:

```ts
import { X509Certificate } from 'crypto';
import { createPrivateKey } from 'crypto';

const privKey = createPrivateKey(
{
  key:
`-----BEGIN PRIVATE KEY-----
YOUR PRIVATE KEY CONTENT
-----END PRIVATE KEY-----`,
  format: 'pem',
});

const cert = new X509Certificate(
`-----BEGIN CERTIFICATE-----
YOUR PUBLIC KEY CONTENT
-----END CERTIFICATE-----`
);

console.log('Before: ', privKey.asymmetricKeyDetails);
cert.checkPrivateKey(privKey);
console.log('After: ', privKey.asymmetricKeyDetails);
```

Run it with Bun (`bun ./cert.ts`).

### What is the expected behavior?

Private key object variable (`privKey`) should not get modified when passed to the `checkPrivateKey` function. The expected output is:

```
Before:  {
  modulusLength: 2048,
  publicExponent: 65537n,
}
After:  {
  modulusLength: 2048,
  publicExponent: 65537n,
}
```

### What do you see instead?

The `privKey` variable is not usable after the call to the `checkPrivateKey` function. For instance, using it to sign data will fail. Output from the above code snippet is:

```
Before:  {
  modulusLength: 2048,
  publicExponent: 65537n,
}
After:  undefined
```

### Additional information

Also tested it with the Node.js v23.3.0 (e.g. `npx tsx ./cert.ts`) and the output is okay:

```
Before:  { modulusLength: 2048, publicExponent: 65537n }
After:  { modulusLength: 2048, publicExponent: 65537n }
```

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
- Implements the `(Secret/Public/Private)KeyObject` class hierarchy.
- Adds async tasks for `crypto.generateKey(Pair)`, `crypto.diffieHellman`, `crypto.sign`, and `crypto.verify`.
- Adds `structuredClone` support for `CryptoKey` and `(Secret/Public/Private)KeyObject`.
```js
const secretKey = crypto.generateKeySync("aes", { length: 128 });
const { publicKey, privateKey } = crypto.generateKeyPairSync("rsa", { modulusLength: 2048 });
const secretKeyClone = structuredClone(secretKey);
const publicKeyClone = structuredClone(publicKey);
const privateKeyClone = structuredClone(privateKey);
console.log(
    publicKey.equals(publicKeyClone),
    privateKey.equals(privateKeyClone),
    secretKey.equals(secretKeyClone)
); // true true true
```
- Fixes `crypto.generatePrime(Sync)` where return value was a `Buffer` instead of an `ArrayBuffer`
```js
const prime = crypto.generatePrimeSync(512);
console.log(prime instanceof ArrayBuffer); // true
```

Fixes #18998
Fixes #16652
Fixes #14682
Fixes #10475
Fixes #9657

Concludes #13681. There will still be some remaining javascript in our `node:crypto` implementation, but all of crypto-browserify has been removed.

### How did you verify your code works?
Added node tests

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 12:21 PM PT - Apr 15th, 2025</sup></div>

@dylan-conway, your commit 86d21f7423fb7a01d076ea14cf63cc69e4b4055e is building: [`#14961`](https://buildkite.com/bun/bun/builds/14961)

File: src/bun.js/bindings/ErrorCode.cpp [hunk 1]
```diff
@@ -874,7 +897,7 @@ JSC::EncodedJSValue INVALID_ARG_VALUE(JSC::ThrowScope& throwScope, JSC::JSGlobal
     return {};
 }
 
-JSC::EncodedJSValue INVALID_ARG_VALUE(JSC::ThrowScope& throwScope, JSC::JSGlobalObject* globalObject, WTF::ASCIILiteral name, WTF::ASCIILiteral reason, JSC::JSValue value, const WTF::Vector<ASCIILiteral>& oneOf)
+JSC::EncodedJSValue INVALID_ARG_VALUE(JSC::ThrowScope& throwScope, JSC::JSGlobalObject* globalObject, WTF::ASCIILiteral name, WTF::ASCIILiteral reason, JSC::JSValue value, const WTF::FixedVector<ASCIILiteral>& oneOf)
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/ErrorCode.cpp]:
```suggestion
JSC::EncodedJSValue INVALID_ARG_VALUE(JSC::ThrowScope& throwScope, JSC::JSGlobalObject* globalObject, WTF::ASCIILiteral name, WTF::ASCIILiteral reason, JSC::JSValue value, const std::span<ASCIILiteral> oneOf)
```

File: src/bun.js/bindings/ErrorCode.cpp [hunk 2]
```diff
@@ -902,6 +925,32 @@ JSC::EncodedJSValue INVALID_ARG_VALUE(JSC::ThrowScope& throwScope, JSC::JSGlobal
     return {};
 }
 
+JSC::EncodedJSValue INVALID_ARG_VALUE(JSC::ThrowScope& throwScope, JSC::JSGlobalObject* globalObject, WTF::ASCIILiteral name, WTF::ASCIILiteral reason, JSC::JSValue value, const WTF::FixedVector<int32_t>& oneOf)
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/ErrorCode.cpp]:
```suggestion
JSC::EncodedJSValue INVALID_ARG_VALUE(JSC::ThrowScope& throwScope, JSC::JSGlobalObject* globalObject, WTF::ASCIILiteral name, WTF::ASCIILiteral reason, JSC::JSValue value, const std::span<int32_t> oneOf)
```

File: src/bun.js/bindings/node/crypto/CryptoDhJob.cpp [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+        return JSValue::encode(jsUndefined());
+    }
+
+    ctx->runTask(lexicalGlobalObject);
+
+    if (!ctx->m_result) {
+        return ERR::CRYPTO_OPERATION_FAILED(scope, lexicalGlobalObject, "diffieHellman operation failed"_s);
+    }
+
+    RefPtr<ArrayBuffer> buf = ArrayBuffer::tryCreateUninitialized(ctx->m_result.size(), 1);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/node/crypto/CryptoDhJob.cpp]:
```suggestion
    JSValue result = WebCore::createBuffer(lexicalGlobalObject, ctx->m_result)
```
