### PR TITLE
fix sys.dup on windows and make console-iterator work

### LINKED ISSUE #8449: [windows] console-iterator test failure
```ts
bun-debug test test\js\bun\console\console-iterator.test.ts
```

```
bun test v1.0.25-canary.50 (e8e84a37)




21 |         stdin: Buffer.from(input),
22 |         env: {
23 |           BUN_DEBUG_QUIET_LOGS: "1",
24 |         },
25 |       });
26 |       expect(stdout.toString()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:26:7
✗ should work for static input > hello world [60.91ms]


21 |         stdin: Buffer.from(input),
22 |         env: {
23 |           BUN_DEBUG_QUIET_LOGS: "1",
24 |         },
25 |       });
26 |       expect(stdout.toString()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:26:7
✗ should work for static input > hello world\n [61.22ms]


21 |         stdin: Buffer.from(input),
22 |         env: {
23 |           BUN_DEBUG_QUIET_LOGS: "1",
24 |         },
25 |       });
26 |       expect(stdout.toString()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:26:7
✗ should work for static input > hello world\n\n [57.62ms]


21 |         stdin: Buffer.from(input),
22 |         env: {
23 |           BUN_DEBUG_QUIET_LOGS: "1",
24 |         },
25 |       });
26 |       expect(stdout.toString()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:26:7
✗ should work for static input > hello world\n\n\n [63.77ms]


21 |         stdin: Buffer.from(input),
22 |         env: {
23 |           BUN_DEBUG_QUIET_LOGS: "1",
24 |         },
25 |       });
26 |       expect(stdout.toString()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "HelloWorld"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:26:7
✗ should work for static input > Hello\nWorld\n [56.70ms]


21 |         stdin: Buffer.from(input),
22 |         env: {
23 |           BUN_DEBUG_QUIET_LOGS: "1",
24 |         },
25 |       });
26 |       expect(stdout.toString()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "1"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:26:7
✗ should work for static input > 1 [60.10ms]


21 |         stdin: Buffer.from(input),
22 |         env: {
23 |           BUN_DEBUG_QUIET_LOGS: "1",
24 |         },
25 |       });
26 |       expect(stdout.toString()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "💕 Red Heart ✨ Sparkles 🔥 Fire💕 Red Heart ✨ Sparkles💕 Red Heart💕normal"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:26:7
✗ should work for static input > 💕 Red Heart ✨ Sparkles 🔥 Fire\n💕 Red Heart ✨ Sparkles\n💕 Red Heart\n💕\n\nnormal [54.42ms]
1 | for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run.ts:1:18


55 |       await new Promise(resolve => setTimeout(resolve, 1));
56 |       stdin.write(input.slice((input.length / 2) | 0));
57 |       stdin.flush();
58 |       stdin.end();
59 | 
60 |       expect(await new Response(stdout).text()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:60:7
✗ should work for streaming input > hello world [56.96ms]
1 | for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run.ts:1:18


55 |       await new Promise(resolve => setTimeout(resolve, 1));
56 |       stdin.write(input.slice((input.length / 2) | 0));
57 |       stdin.flush();
58 |       stdin.end();
59 | 
60 |       expect(await new Response(stdout).text()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:60:7
✗ should work for streaming input > hello world\n [52.09ms]
1 | for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run.ts:1:18


55 |       await new Promise(resolve => setTimeout(resolve, 1));
56 |       stdin.write(input.slice((input.length / 2) | 0));
57 |       stdin.flush();
58 |       stdin.end();
59 | 
60 |       expect(await new Response(stdout).text()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:60:7
✗ should work for streaming input > hello world\n\n [52.42ms]
1 | for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run.ts:1:18


55 |       await new Promise(resolve => setTimeout(resolve, 1));
56 |       stdin.write(input.slice((input.length / 2) | 0));
57 |       stdin.flush();
58 |       stdin.end();
59 | 
60 |       expect(await new Response(stdout).text()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "hello world"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:60:7
✗ should work for streaming input > hello world\n\n\n [51.59ms]
1 | for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run.ts:1:18


55 |       await new Promise(resolve => setTimeout(resolve, 1));
56 |       stdin.write(input.slice((input.length / 2) | 0));
57 |       stdin.flush();
58 |       stdin.end();
59 | 
60 |       expect(await new Response(stdout).text()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "HelloWorld"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:60:7
✗ should work for streaming input > Hello\nWorld\n [51.16ms]
1 | for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run.ts:1:18


55 |       await new Promise(resolve => setTimeout(resolve, 1));
56 |       stdin.write(input.slice((input.length / 2) | 0));
57 |       stdin.flush();
58 |       stdin.end();
59 | 
60 |       expect(await new Response(stdout).text()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "1"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:60:7
✗ should work for streaming input > 1 [58.97ms]
1 | for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run.ts:1:18


55 |       await new Promise(resolve => setTimeout(resolve, 1));
56 |       stdin.write(input.slice((input.length / 2) | 0));
57 |       stdin.flush();
58 |       stdin.end();
59 | 
60 |       expect(await new Response(stdout).text()).toBe(input.replaceAll("\n", ""));
           ^
error: expect(received).toBe(expected)

Expected: "💕 Red Heart ✨ Sparkles 🔥 Fire 💕 Red Heart ✨ Sparkles 💕 Red Heart 💕 normal"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:60:7
✗ should work for streaming input > 💕 Red Heart ✨ Sparkles 🔥 Fire\n 💕 Red Heart ✨ Sparkles\n 💕 Red Heart\n 💕 \n\nnormal [55.10ms]
1 | async function readInput() {
2 |   let items = [];
3 |   for await (const line of console) {
                        ^
EACCES: Permission denied
   errno: -13
 syscall: "dup"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run-2.ts:3:20
      at readInput (D:\a\bun\bun\test\js\bun\console\console-iterator-run-2.ts:1:25)
      at D:\a\bun\bun\test\js\bun\console\console-iterator-run-2.ts:12:17


76 |   const { stdout, stdin } = proc;
77 |   stdin.write("hello\nworld\nbreak\nanother\nbreak\n");
78 |   stdin.flush();
79 |   stdin.end();
80 | 
81 |   expect(await new Response(stdout).text()).toBe('["hello","world"]["another"]');
       ^
error: expect(received).toBe(expected)

Expected: "[\"hello\",\"world\"][\"another\"]"
Received: ""

      at D:\a\bun\bun\test\js\bun\console\console-iterator.test.ts:81:3
✗ can use the console iterator more than once [54.32ms]



 0 pass
 15 fail
 15 expect() calls
Ran 15 tests across 1 files. [890.00ms]
```

### PR DESCRIPTION
**Pull request by gvilums**
### What does this PR do?
Fixes `sys.dup` on windows (the function was previously nonsense as it returned a boolean return value as a file descriptor).
Also makes some changes in `streams.zig` to make iterating over consoles work.

One nasty bug remains: For some reason, when using the console iterator, `console.write` doesn't work as intended. All writes happen normally, but no content shows up in the console.

Partially fixes #8449

### CODE REVIEW

File: src/bun.js/webcore/streams.zig [hunk 1]
```diff
@@ -4541,7 +4543,7 @@ pub const File = struct {
         var fd = if (file.pathlike != .path)
             // We will always need to close the file descriptor.
             switch (Syscall.dup(file.pathlike.fd)) {
-                .result => |_fd| _fd,
+                .result => |_fd| if (Environment.isWindows) bun.toLibUVOwnedFD(_fd) else _fd,
```
Comment (jdalton) [inline src/bun.js/webcore/streams.zig:4546]: Learning bit for me: When does something need to be `bun.toLibUVOwnedFD(_fd)` vs. say a regular `bun.toFD` bun descriptor?

Comment (gvilums) [reply src/bun.js/webcore/streams.zig:4546]: from my understanding native windows fds can't be passed to libuv functions. in this case the downstream code uses libuv to do the reading, so we have to convert the fd before using it

Comment (paperclover) [reply src/bun.js/webcore/streams.zig:4546]: FileDescriptor on windows is a union type between a UV/C-runtime fd int (c_int) and a Windows handle (*anyopaque)

converting uv -> windows is ok but uv owns the descriptor
converting windows -> uv moves ownership to uv/crt.

bun.toLibUVOwnedFD consumes the input FileDescriptor and returns a new FileDescriptor that is always a libuv one. it is expected that this new one will eventually be `close()`d
