### PR TITLE
fix `bunx` on windows with postinstall scripts

### LINKED ISSUE #9841: `bunx` postinstall throws "could not determine executable to run for package exec"
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. ```bun create vite```
   1. Project Name - reproduce-bun-bug
   2. Select Framework - Vue
   3. Select a variant - Customize with create-vue
   4. Select the options you need
   5. ```bun install```
2. Following the [shadcn-vue installation guide](https://www.shadcn-vue.com/docs/installation/vite.html)
  1. bunx --bun shadcn-vue@latest init

### What is the expected behavior?

[Successful launch of cli shadcn-vue](https://www.shadcn-vue.com/docs/installation/vite.html#run-the-cli)

### What do you see instead?

```bash
$ bunx --bun shadcn-vue@latest init
  ⚙️  vue-demi [1/1] error: could not determine executable to run for package exec      

error: postinstall script from "vue-demi" exited with 1
```

### Additional information

[Issue thread in discord](https://discord.com/channels/876711213126520882/1224594606512017460)

### LINKED ISSUE #10068: `bunx bun@1.1.2` throws "could not determine executable to run for package exec" on Windows
image
image

### LINKED ISSUE #12336: Windows: bunx postinstall error | reference: #9841
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. ```bun create vite```
   1. Project Name - reproduce-bun-bug
   2. Select Framework - Vue
   3. Select a variant - Customize with create-vue
   4. Select the options you need
   5. ```bun install```
2. Following the [shadcn-vue installation guide](https://www.shadcn-vue.com/docs/installation/vite.html)
  1. bunx --bun shadcn-vue@latest init

### What is the expected behavior?

[Successful launch of cli shadcn-vue](https://www.shadcn-vue.com/docs/installation/vite.html#run-the-cli)

### What do you see instead?

```bash
$ bunx --bun shadcn-vue@latest init
  ⚙️  vue-demi [1/1] error: could not determine executable to run for package exec      

error: postinstall script from "vue-demi" exited with 1
```

### Additional information

[Original issue](https://github.com/oven-sh/bun/issues/9841)
_This is just a reference for a past issue, as the problem still persists._

# 🚧Workaround:
**Use ```bun x``` instead of the alias ```bunx```**

### LINKED ISSUE #14848: Error while runing bunx scripts
### What version of Bun is running?

1.1.33

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Create a repository with bunx create-t3-app@latest (next v14)
Run `bunx storybook@latest init`

### What is the expected behavior?

To run the installation storybook as npx does

### What do you see instead?

⚙️  esbuild [1/1] Resolving dependencies
Resolved, downloaded and extracted [4]
Saved lockfile
error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1

### Additional information

_No response_

### LINKED ISSUE #15562: `bunx` Fail to execute packages
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Microsoft Windows NT 10.0.26100.0 x64

### What steps can reproduce the bug?

Create **Nuxt** project:
- `bunx nuxi@latest init <project_name>` then select `bun` (was failing too but i after install `NodeJS` it works!)
- `bunx nuxi@latest module add @nuxtjs/tailwindcss`
- `bunx nuxi@latest module add color-mode`
- `bunx nuxi@latest module add shadcn-nuxt`
- `bunx shadcn-vue@latest init` OR `bunx --bun shadcn-vue@latest init`

```shell
# bunx shadcn-vue@latest init
  ⚙️  vue-demi [1/2] error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1
```

### What is the expected behavior?

Image

### What do you see instead?

Image

### Additional information

_No response_

### LINKED ISSUE #15783: Compatibility issues with react-scan
### What version of Bun is running?

1.1.38

### What platform is your computer?

Windows

### What steps can reproduce the bug?

`bunx react-scan@latest http://localhost:3000/`

### What is the expected behavior?

Should start scanning as with `npx react-scan@latest http://localhost:3000/`

### What do you see instead?

```
  ⚙️  esbuild [1/2] error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1
```

### Additional information

I don't know if this is directly related to Node.js compatibility with Bun, but it seems to work with any other Package Manager.

### PR DESCRIPTION
**Pull request by RiskyMH**
fixes #9841
<sub>fixes #15783, fixes #15562, fixes #14848, fixes #12336, fixes #10068<sub>

context behind change is it runs `<current-exe> exec` on windows which would be `bunx exec` but as that subcommand wasn't resolvable it just tried to run `exec` as a package:

https://github.com/oven-sh/bun/blob/1ccc13ecf79861eb0b5a697c0b5571772d42a28d/src/install/lifecycle_script_runner.zig#L166-L176

---

will try to add tests which fail without this

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 4:49 AM PT - Feb 5th, 2025</sup></div>

@RiskyMH, your commit c37d0e45bf541e8c18afc1561b34a5b726ef2497 is building: [`#11128`](https://buildkite.com/bun/bun/builds/11128)

**Comment by hakimio** [comment]
Maybe there should be some test for this?

**Comment by RiskyMH** [comment]
> will try to add tests which fail without this

Yeah i will. Just investigating more rn. Also going to sleep soon, but I wanted to find the cause of this as it was buging me.

Seems simple to add test though, im surprised it hasn't failed anything already but the tests probably don't have `bunx` simlink and instead rely on effectively `bun x`.

**Review by dylan-conway — APPROVED** [review]
Looks good. @paperclover should take a look too

File: src/cli.zig [hunk 1]
```diff
@@ -1636,10 +1636,12 @@ pub const Command = struct {
             // if we are bunx, but NOT a symlink to bun. when we run `<self> install`, we dont
             // want to recursively run bunx. so this check lets us peek back into bun install.
             if (args_iter.next()) |next| {
-                if (bun.strings.eqlComptime(next, "add") and
-                    bun.getenvZ("BUN_INTERNAL_BUNX_INSTALL") != null)
-                {
-                    return .AddCommand;
+                if (bun.getRuntimeFeatureFlag("BUN_INTERNAL_BUNX_INSTALL")) {
```
Comment (paperclover) [inline src/cli.zig]: the original ordering of these operations was intentional. the environment variable shouldn't get queried if the command doesn't match. can we do the lame code dupe and have two if statements that do `if (eqlComptime(next, "...") and env check)`

**Review by paperclover — CHANGES_REQUESTED** [review]
great find

File: src/cli.zig (hunk 1 above)
Comment (RiskyMH) [reply src/cli.zig]: cool cool, i wasn't the perf and if runtime feature flag was more efficient (should i still use it as it appears what most new stuff checking env var is using?)
