### PR TITLE
fix(windows): build all dependencies with proper cpu target

### LINKED ISSUE #10435: Illegal instruction bun
### How can we reproduce the crash?

C:\Users\seia\Desktop\projet\devika\ui>bun install
bun install v1.1.5 (ab79940e)
  🚚 to-regex-range... ============================================================
Bun v1.1.5 (ab79940e) Windows x64 (baseline)
Args: "C:\node-v20.12.2-win-x64\\node_modules\bun\bin\bun.exe", "install"
Elapsed: 2411ms | User: 171ms | Sys: 250ms
RSS: 66.42MB | Peak: 66.42MB | Commit: 121.58MB | Faults: 16434

panic(thread 4660): Illegal instruction at address 0x7FF63200D4F1
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.5 ([#10417](https://github.com/oven-sh/bun/pull/10417)) on windows x86_64_baseline [UpgradeCommand]

Illegal instruction at address 0x7FF63200D4F1

- [`tccgen.c:6586`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/tinycc/tccgen.c#L6586): `expr_const`
- [`libtcc.c:190`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/tinycc/libtcc.c#L190): `pstrcpy`
- [`js_ast.zig:3038`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/js_ast.zig#L3038): `assert`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`fmt.zig:595`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/fmt.zig#L595): `formatType`
- [`writer.zig:22`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/io/writer.zig#L22): `writeAll`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`fmt.zig:596`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/fmt.zig#L596): `formatType`
- `??`
- `??`

Features:

### LINKED ISSUE #10460: Illegal instruction on windows x64 baseline
### How can we reproduce the crash?

Running any command would produce the same error, this is already very documented and a problem in all versions since 1.0

### Relevant log output

```shell
λ bun i
[3.00ms] ".env"
bun install v1.1.5-canary.1 (68c13f2a)
  � eslint-plugin-react-refresh [40/135] ============================================================
Bun v1.1.5-canary.1 (68c13f2a) Windows x64 (baseline)
Features: dotenv
Elapsed: 3856ms | User: 359ms | Sys: 546ms
RSS: 97.26MB | Peak: 101.76MB | Commit: 0.16GB | Faults: 31967

panic(thread 6196): Illegal instruction at address 0x7FF71CF0B831
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.5 ([`68c13f2`](https://github.com/oven-sh/bun/tree/68c13f2af5dde2053e2a27859e42b31d8c9a193e)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF64C5BB831

- [`libtcc.c:189`](https://github.com/oven-sh/bun/blob/68c13f2af5dde2053e2a27859e42b31d8c9a193e/src/deps/tinycc/libtcc.c#L189): `pstrcpy`
- [`tccpp.c:408`](https://github.com/oven-sh/bun/blob/68c13f2af5dde2053e2a27859e42b31d8c9a193e/src/deps/tinycc/tccpp.c#L408): `cstr_reset`
- [`migration.zig:631`](https://github.com/oven-sh/bun/blob/68c13f2af5dde2053e2a27859e42b31d8c9a193e/src/install/migration.zig#L631): `migrateNPMLockfile`
- [`pdq.zig:26`](https://github.com/oven-sh/bun/blob/68c13f2af5dde2053e2a27859e42b31d8c9a193e/src/deps/zig/lib/std/sort/pdq.zig#L26): `swap`
- [`npm.zig:661`](https://github.com/oven-sh/bun/blob/68c13f2af5dde2053e2a27859e42b31d8c9a193e/src/install/npm.zig#L661): `writeFile`
- [`array_hash_map.zig:685`](https://github.com/oven-sh/bun/blob/68c13f2af5dde2053e2a27859e42b31d8c9a193e/src/deps/zig/lib/std/array_hash_map.zig#L685): `getOrPutContext`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

Features: dotenv

### LINKED ISSUE #10545: bun upgrade Error
### How can we reproduce the crash?

_No response_

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.5 ([#10527](https://github.com/oven-sh/bun/pull/10527)) on windows x86_64_baseline [UpgradeCommand]

Illegal instruction at address 0x7FF67B6B8831

- [`tccgen.c:4947`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L4947): `post_type`
- [`tccgen.c:5051`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L5051): `post_type`
- [`Allocator.zig:314`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/mem/Allocator.zig#L314): `free`
- [`fmt.zig:661`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/fmt.zig#L661): `formatType`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`fmt.zig:583`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/fmt.zig#L583): `formatType`
- [`fmt.zig:659`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/fmt.zig#L659): `formatType`
- [`writer.zig:28`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/io/writer.zig#L28): `print`
- `??`
- `??`

### LINKED ISSUE #10546: bun install -g <package>
### How can we reproduce the crash?

same as the prior bun upgrade error number #10545

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.5 ([#10527](https://github.com/oven-sh/bun/pull/10527)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF67B6B8831

- [`tccgen.c:4947`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L4947): `post_type`
- [`tccgen.c:5051`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L5051): `post_type`
- [`Allocator.zig:314`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/mem/Allocator.zig#L314): `free`
- [`semver.zig:827`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/install/semver.zig#L827): `order`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`multi_array_list.zig:74`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/multi_array_list.zig#L74): `items`
- ??? at `0x153e0` in /KERNEL32.DLL
- ??? at `0x485b` in /ntdll.dll

### LINKED ISSUE #10547: bun install ERROR
### How can we reproduce the crash?

same cause as in `#10546` and `#10545`

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.5 ([#10527](https://github.com/oven-sh/bun/pull/10527)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF67B6B8831

- [`tccgen.c:4947`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L4947): `post_type`
- [`tccgen.c:5051`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L5051): `post_type`
- [`Allocator.zig:314`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/mem/Allocator.zig#L314): `free`
- [`semver.zig:827`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/install/semver.zig#L827): `order`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`multi_array_list.zig:74`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/multi_array_list.zig#L74): `items`
- ??? at `0x153e0` in /KERNEL32.DLL
- ??? at `0x485b` in /ntdll.dll

### LINKED ISSUE #10578: segfaults on any commands
### How can we reproduce the crash?

Run any command like `bun i`

### Relevant log output

```shell
λ bun i
[21.01ms] ".env"
bun install v1.1.6-canary.1 (cc8cdf6c)
  � fraction.js [18/48] ============================================================
Bun v1.1.6-canary.1 (cc8cdf6c) Windows x64 (baseline)
Features: dotenv
Elapsed: 1161ms | User: 140ms | Sys: 156ms
RSS: 84.18MB | Peak: 88.67MB | Commit: 0.15GB | Faults: 26309

panic(thread 10476): Illegal instruction at address 0x7FF6C39843C1
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([#10575](https://github.com/oven-sh/bun/pull/10575)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF6C39843C1

- [`tccgen.c:4067`](https://github.com/oven-sh/bun/blob/cc8cdf6c51e7729575924d101aa2cbaf0964fa5f/src/deps/tinycc/tccgen.c#L4067): `check_fields`
- [`tccgen.c:694`](https://github.com/oven-sh/bun/blob/cc8cdf6c51e7729575924d101aa2cbaf0964fa5f/src/deps/tinycc/tccgen.c#L694): `sym_push`
- [`Allocator.zig:205`](https://github.com/oven-sh/bun/blob/cc8cdf6c51e7729575924d101aa2cbaf0964fa5f/src/deps/zig/lib/std/mem/Allocator.zig#L205): `allocAdvancedWithRetAddr`
- [`semver.zig:729`](https://github.com/oven-sh/bun/blob/cc8cdf6c51e7729575924d101aa2cbaf0964fa5f/src/install/semver.zig#L729): `orderWithoutTag`
- [`writer.zig:32`](https://github.com/oven-sh/bun/blob/cc8cdf6c51e7729575924d101aa2cbaf0964fa5f/src/deps/zig/lib/std/io/writer.zig#L32): `writeByte`
- [`array_hash_map.zig:804`](https://github.com/oven-sh/bun/blob/cc8cdf6c51e7729575924d101aa2cbaf0964fa5f/src/deps/zig/lib/std/array_hash_map.zig#L804): `ensureTotalCapacityContext`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

Features: dotenv

### LINKED ISSUE #10583: Illegal instruction on Windows - Bun crash
### How can we reproduce the crash?

- Install Bun
- Launch the Bun JS engine (by running a .js file, by running ``bun create [whatever]``, by installing a package)
- See the crash happen :)

### Relevant log output

```shell
C:\Users\xxx>bun create vite
  🔍 Resolving [1/1] ============================================================
Bun v1.1.5 (b257a309) Windows x64 (baseline)
Args: "C:\Users\xxx\AppData\Roaming\npm\node_modules\bun\bin\bun.exe", "add", "create-vite@latest", "--no-summary", "--no-cache", "--force"
Elapsed: 228ms | User: 46ms | Sys: 109ms
RSS: 62.28MB | Peak: 62.28MB | Commit: 117.47MB | Faults: 15434

panic(thread 2744): Illegal instruction at address 0x7FF7C5B18831
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.5/eI1b257a30AAijkicgtlic6gj+G2xggGkrjiGky+qKCa\KERNEL32.DLLo05FCU\ntdll.dllirzUA3u//B/875p6B
```

### Stack Trace (bun.report)

Bun v1.1.5 ([#10527](https://github.com/oven-sh/bun/pull/10527)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF7ADE08831

- [`tccgen.c:4947`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L4947): `post_type`
- [`tccgen.c:5051`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L5051): `post_type`
- [`Allocator.zig:314`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/mem/Allocator.zig#L314): `free`
- [`semver.zig:827`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/install/semver.zig#L827): `order`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`multi_array_list.zig:74`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/multi_array_list.zig#L74): `items`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

### LINKED ISSUE #10615: Bun has crashed on `bun install`
### How can we reproduce the crash?

```cmd
bun init
bun install
```

### Relevant log output

```shell
bun install v1.1.6 (e58d67b4)
  🚚 bun-types [2/5] ============================================================
Bun v1.1.6 (e58d67b4) Windows x64 (baseline)
Args: "D:\path\to\bun.exe", "install"
Elapsed: 26534ms | User: 46ms | Sys: 31ms
RSS: 64.30MB | Peak: 64.30MB | Commit: 111.63MB | Faults: 15903

panic(thread 4608): Illegal instruction at address 0x7FF79D705541
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF67CD85541

- [`tccgen.c:4964`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4964): `post_type`
- [`tccgen.c:5046`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L5046): `post_type`
- [`math.zig:436`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/math.zig#L436): `mul`
- [`sort.zig:48`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/sort.zig#L48): `insertionContext`
- [`fmt.zig:1173`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/fmt.zig#L1173): `format`
- [`multi_array_list.zig:540`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/multi_array_list.zig#L540): `capacityInBytes`
- ??? at `0x1257d` in /KERNEL32.DLL
- ??? at `0x5aa48` in /ntdll.dll

### LINKED ISSUE #10629: bun crash
### How can we reproduce the crash?

bun create hono
bun install

### Relevant log output

```shell
🔍 Resolving [1/1] ============================================================
Bun v1.1.6 (e58d67b4) Windows x64 (baseline)
Args: "C:\Users\Admin\.bun\bin\bun.exe", "add", "create-hono@latest", "--no-summary", "--no-cache", "--force"
Elapsed: 351ms | User: 156ms | Sys: 78ms
RSS: 63.31MB | Peak: 63.31MB | Commit: 117.99MB | Faults: 15666

panic(thread 4368): Illegal instruction at address 0x7FF648875541
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF648875541

- [`tccgen.c:4964`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4964): `post_type`
- [`tccgen.c:5046`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L5046): `post_type`
- [`math.zig:436`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/math.zig#L436): `mul`
- [`sort.zig:48`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/sort.zig#L48): `insertionContext`
- [`fmt.zig:1173`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/fmt.zig#L1173): `format`
- [`multi_array_list.zig:540`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/multi_array_list.zig#L540): `capacityInBytes`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

### LINKED ISSUE #10700: Same segfault problem
### How can we reproduce the crash?

Run any command, like `bun i`

### Relevant log output

```shell
bun install v1.1.7-canary.1 (18261046)
  � esbuild [7/18] ============================================================
Bun v1.1.7-canary.1 (18261046) Windows x64 (baseline)
Elapsed: 1510ms | User: 390ms | Sys: 375ms
RSS: 0.16GB | Peak: 0.18GB | Commit: 0.33GB | Faults: 54123

panic(thread 9428): Illegal instruction at address 0x7FF7D42CFC11
oh no: Bun has crashed. This indicates a bug in Bun, not your code
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`1826104`](https://github.com/oven-sh/bun/tree/18261046eee7d4906ea865fcc8a420ebd810ce93)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF7D42CFC11

- [`tccgen.c:4971`](https://github.com/oven-sh/bun/blob/18261046eee7d4906ea865fcc8a420ebd810ce93/src/deps/tinycc/tccgen.c#L4971): `post_type`
- [`tccpp.c:1043`](https://github.com/oven-sh/bun/blob/18261046eee7d4906ea865fcc8a420ebd810ce93/src/deps/tinycc/tccpp.c#L1043): `tok_str_free_str`
- [`Allocator.zig:341`](https://github.com/oven-sh/bun/blob/18261046eee7d4906ea865fcc8a420ebd810ce93/src/deps/zig/lib/std/mem/Allocator.zig#L341): `log2a`
- [`semver.zig:728`](https://github.com/oven-sh/bun/blob/18261046eee7d4906ea865fcc8a420ebd810ce93/src/install/semver.zig#L728): `orderWithoutTag`
- [`fmt.zig:1173`](https://github.com/oven-sh/bun/blob/18261046eee7d4906ea865fcc8a420ebd810ce93/src/fmt.zig#L1173): `format`
- [`array_hash_map.zig:1721`](https://github.com/oven-sh/bun/blob/18261046eee7d4906ea865fcc8a420ebd810ce93/src/deps/zig/lib/std/array_hash_map.zig#L1721): `insertAllEntriesIntoNewHeaderGeneric`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

### LINKED ISSUE #10755: Illegal instruction at address when using `bun install`
## Version
1.1.6

## Platform
Microsoft Windows 10 Home
10.0.19045 N/A Build 19045
Intel64 Family 6 Model 122 Stepping 8 GenuineIntel ~1101 Mhz
x64-based PC

## What steps will reproduce the bug?

# From Origin (Through Turborepo)
+ Same platform
+ `npm install -g bun@1.1.6`
+ `npx create-turbo@latest -e with-svelte`
+ select workspace `.`
+ continue with bun (beta)

# Through `bun install`
+ `bun install`

## How often does it reproduce? Is there a required condition?
I believe it is an issue with my device platform, issue happens any time I attempt to install package.json dependencies using `bun install`. Similar errors also occur for bun versions from v1.1.0 to latest version v1.1.6. Error originated from trying to start a new Turborepo with svelte via bun. Issue does not seem to rise from other device platform.

## What is the expected behavior?
No response

## Relevant log output (Turborepo)

```shell
bun install v1.1.6 (e58d67b4)
  ≡ƒÜÜ @vitest/expect [105/357] ============================================================
  ≡ƒöì postcss-scss [163/416] Bun v1.1.6 (e58d67b4) Windows x64 (baseline)
  ≡ƒöì @rollup/rollup-linux-riscv64-gnu [237/502] "C:\Users\REDACTED\AppData\Ro  ≡ƒÜÜ prelude-ls [256/521] "
Elapsed: 3618ms | User: 671ms | Sys: 687ms
RSS: 109.52MB | Peak: 109.52MB | Commit: 0.15GB | Faults: 28806

panic(thread 25456): Illegal instruction at address 0x7FF636C25541
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

https://bun.report/1.1.6/ei1e58d67bAAi0qlcg+rlc66j+G2uggGkojiGkmurKCa\KERNEL32.DLLo05FCU\ntdll.dllirzUA3s//Bi0qp42B

  ≡ƒÜÜ ufo [287/552] panic(thread 23888)oh no: multiple threads are crashing
: Illegal instruction at address 0x7FF636C25541
 https://bun.report/1.1.6/ei1e58d67bAAi0qlcg+rlc66j+G2uggGkojiGkmurKCa\KERNEL32.DLLo05FCU\ntdll.dllirzUA3s//Bi0qp42B

  ≡ƒÜÜ @polka/url [292/557] panic(thread 20328)oh no: multiple threads are crashing
: Illegal instruction at address 0x7FF636C25541
 https://bun.report/1.1.6/ei1e58d67bAAi0qlcg+rlc66j+G2uggGkojiGkmurKCa\KERNEL32.DLLo05FCU\ntdll.dllirzUA3s//Bi0qp42B
```

## Relevant log output (bun install)

```shell
bun install v1.1.6 (e58d67b4)
  🔍 svelte-check [24/154] ============================================================
Bun v1.1.6 (e58d67b4) Windows x64 (baseline)
Args: "C:\Users\REDACTED\AppData\Roaming\npm\\node_modules\bun\bin\bun.exe", "install"
Elapsed: 1725ms | User: 109ms | Sys: 406ms
RSS: 78.34MB | Peak: 78.34MB | Commit: 111.37MB | Faults: 19919

panic(thread 19364): Illegal instruction at address 0x7FF626945541
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.6/ei1e58d67bAAi0qlcg+rlc66j+G2uggGkojiGkmurKCa\KERNEL32.DLLo05FCU\ntdll.dllirzUA3s//Bi0qxymB
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF648875541

- [`tccgen.c:4964`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4964): `post_type`
- [`tccgen.c:5046`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L5046): `post_type`
- [`math.zig:436`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/math.zig#L436): `mul`
- [`sort.zig:48`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/sort.zig#L48): `insertionContext`
- [`fmt.zig:1173`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/fmt.zig#L1173): `format`
- [`multi_array_list.zig:540`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/multi_array_list.zig#L540): `capacityInBytes`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

### LINKED ISSUE #10756: Another segfault when running commands
### How can we reproduce the crash?

Run any command like `bun i`

### Relevant log output

```shell
bun install v1.1.7-canary.1 (79c7abe5)
  ­ƒöì @effect/schema [49/83] ============================================================
Bun v1.1.7-canary.1 (79c7abe5) Windows x64 (baseline)
Elapsed: 3178ms | User: 593ms | Sys: 468ms
RSS: 0.14GB | Peak: 0.19GB |   ­ƒöì path-browserify [51/89]

panic(thread 8028): Illegal instruction at address 0x7FF74754B0B1
oh no: Bun has crashed. This indicates a bug in Bun, not your code
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`79c7abe`](https://github.com/oven-sh/bun/tree/79c7abe595972d24e6a69f1f0290452be5ee78c4)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF74754B0B1

- [`tccgen.c:4072`](https://github.com/oven-sh/bun/blob/79c7abe595972d24e6a69f1f0290452be5ee78c4/src/deps/tinycc/tccgen.c#L4072): `check_fields`
- [`tccgen.c:4923`](https://github.com/oven-sh/bun/blob/79c7abe595972d24e6a69f1f0290452be5ee78c4/src/deps/tinycc/tccgen.c#L4923): `post_type`
- [`logger.zig:216`](https://github.com/oven-sh/bun/blob/79c7abe595972d24e6a69f1f0290452be5ee78c4/src/logger.zig#L216): `cloneLineText`
- [`pdq.zig:230`](https://github.com/oven-sh/bun/blob/79c7abe595972d24e6a69f1f0290452be5ee78c4/src/deps/zig/lib/std/sort/pdq.zig#L230): `partialInsertionSort`
- [`npm.zig:620`](https://github.com/oven-sh/bun/blob/79c7abe595972d24e6a69f1f0290452be5ee78c4/src/install/npm.zig#L620): `writeArray`
- [`array_hash_map.zig:182`](https://github.com/oven-sh/bun/blob/79c7abe595972d24e6a69f1f0290452be5ee78c4/src/deps/zig/lib/std/array_hash_map.zig#L182): `getOrPut`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

### LINKED ISSUE #10790: Illegal instruction at address 0x7FF684285541
### How can we reproduce the crash?

crash when install `express` library
```bash
> bun add express
```

### Relevant log output

```shell
bun add v1.1.6 (e58d67b4)
[0.87ms] migrated lockfile from package-lock.json
  🚚 array-flatten [18/51] ============================================================
Bun v1.1.6 (e58d67b4) Windows x64 (baseline)
Args: "C:\Users\msi\.bun\bin\bun.exe", "add", "express"
Features: lockfile_migration_from_package_lock
Elapsed: 29025ms | User: 140ms | Sys: 93ms
RSS: 70.38MB | Peak: 70.46MB | Commit: 129.91MB | Faults: 17805

panic(thread 10828): Illegal instruction at address 0x7FF684285541
oh no: Bun has crashed. This indicates a bug in Bun, not your code
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF684285541

- [`tccgen.c:4886`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4886): `post_type`
- [`tccgen.c:4938`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4938): `post_type`
- [`Allocator.zig:193`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/mem/Allocator.zig#L193): `alignedAlloc`
- [`semver.zig:726`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/semver.zig#L726): `orderWithoutTag`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`multi_array_list.zig:540`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/multi_array_list.zig#L540): `capacityInBytes`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

### LINKED ISSUE #10798: bun install error on `1.1.7`
### How can we reproduce the crash?

i have a already downloaded the packages using npm, when I used `bun install` this error happend and here is the package.json:
```json
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "autoprefixer": "^10.4.18",
        "axios": "^1.6.4",
        "daisyui": "^4.7.3",
        "laravel-vite-plugin": "^1.0.0",
        "postcss": "^8.4.35",
        "tailwindcss": "^3.4.1",
        "vite": "^5.0.0"
    },
    "dependencies": {
        "gsap": "^3.12.5",
        "howler": "^2.2.4"
    }
}
```

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF7257EFA41

- [`tccgen.c:849`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L849): `vsetc`
- [`tccgen.c:852`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L852): `vsetc`
- [`logger.zig:216`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L216): `cloneLineText`
- [`semver.zig:827`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/semver.zig#L827): `order`
- [`pdq.zig:122`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/sort/pdq.zig#L122): `pdqContext`
- [`logger.zig:1126`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L1126): `addWarning`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

### LINKED ISSUE #10841: crashed on running command bun install
### How can we reproduce the crash?

image

image

### JavaScript/TypeScript code that reproduces the crash?

_No response_

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF61037FA41

- [`libtcc.c:188`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/libtcc.c#L188): `pstrcpy`
- [`tccgen.c:5018`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L5018): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L993): `addRangeErrorFmt`
- [`semver.zig:268`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/semver.zig#L268): `slice`
- [`math.zig:452`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/math.zig#L452): `sub`
- [`bun.zig:1754`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L1754): `insert`
- ??? at `0x153e0` in KERNEL32.DLL
- ??? at `0x485b` in ntdll.dll

### LINKED ISSUE #10853: panic(thread 14156): Illegal instruction at address 0x7FF65688FA41
### How can we reproduce the crash?

 bunx create astro@latest
  🚚 create-astro [4/6] ============================================================
Bun v1.1.7 (b0b7db5c) Windows x64 (baseline)
Args: "C:\Users\aas09\AppData\Roaming\npm\node_modules\bun\bin\bun.exe", "add", "create-astro@latest", "--no-summary", "--no-cache", "--force"
Elapsed: 1197ms | User: 187ms | Sys: 125ms
RSS: 64.97MB | Peak: 65.23MB | Commit: 122.91MB | Faults: 16302

panic(thread 14156): Illegal instruction at address 0x7FF65688FA41
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

### JavaScript/TypeScript code that reproduces the crash?

```shell
in windows
```

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF7D672FA41

- [`libtcc.c:188`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/libtcc.c#L188): `pstrcpy`
- [`tccgen.c:5018`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L5018): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L993): `addRangeErrorFmt`
- [`semver.zig:268`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/semver.zig#L268): `slice`
- [`math.zig:452`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/math.zig#L452): `sub`
- [`bun.zig:1754`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L1754): `insert`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

### LINKED ISSUE #10856: Is our TinyCC build on Windows setting `-march` correctly?
Where are we setting C flags when building TinyCC? How are we making sure that baseline builds are working correctly with TinyCC?

https://github.com/oven-sh/bun/blob/830af23742c957296db4cd7a5ffe25c1bac143db/scripts/build-tinycc.ps1#L20-L25

It feels highly suspicious that so many of the "Illegal instruction" errors include a stack trace that points to TinyCC. Either something is going wrong while generating the stacktrace, or something is wrong with the TinyCC build. 

Related issues:
- https://github.com/oven-sh/bun/issues/10435
- https://github.com/oven-sh/bun/issues/10460
- https://github.com/oven-sh/bun/issues/10545
- https://github.com/oven-sh/bun/issues/10546
- https://github.com/oven-sh/bun/issues/10547
- https://github.com/oven-sh/bun/issues/10578
- https://github.com/oven-sh/bun/issues/10583
- https://github.com/oven-sh/bun/issues/10615
- https://github.com/oven-sh/bun/issues/10629
- https://github.com/oven-sh/bun/issues/10700
- https://github.com/oven-sh/bun/issues/10755
- https://github.com/oven-sh/bun/issues/10756
- https://github.com/oven-sh/bun/issues/10788
- https://github.com/oven-sh/bun/issues/10790
- https://github.com/oven-sh/bun/issues/10798
- https://github.com/oven-sh/bun/issues/10841
- https://github.com/oven-sh/bun/issues/10853

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Fixes #10856
Fixes #10435
Fixes #10460
Fixes #10545
Fixes #10546
Fixes #10547
Fixes #10578
Fixes #10583
Fixes #10615
Fixes #10629
Fixes #10700
Fixes #10755
Fixes #10756
For #10788, this will resolve their third point.
Fixes #10790
Fixes #10798
Fixes #10841
Fixes #10853

Besides 10788, all of the above are the same exact issue report.

What went wrong is when compiling dependencies is the logic in every dependency script is
```ps1
. (Join-Path $PSScriptRoot "env.ps1")
```

This overrides the baseline state of the shell to haswell, which will unintentionally compile newer code for older cpus.

We also never even tried compiling tcc correctly. The proper flags are added.

When using SDE, I noticed a very odd failure reported in `WTF::initialize`, which names the current thread. This applies for any JS entrypoint, which is different from the mostly install-related ones above (makes sense, since `libarchive` is a notable dependency, while the js runtime in general is mostly just JSC + our own code + simdutf). I dont think the change in JSC is significant but it is definetly on the safer side to do this.

### CODE REVIEW

File: src/bun.js/bindings/ZigGlobalObject.cpp [hunk 1]
```diff
@@ -213,11 +213,15 @@ extern "C" void JSCInitialize(const char* envp[], size_t envc, void (*onCrash)(c
     if (has_loaded_jsc)
         return;
     has_loaded_jsc = true;
+    printf("1: a\n");
```
Comment (dylan-conway) [inline src/bun.js/bindings/ZigGlobalObject.cpp]: printf

Comment (Jarred-Sumner) [inline src/bun.js/bindings/ZigGlobalObject.cpp]:
```suggestion

```

File: src/bun.js/bindings/ZigGlobalObject.cpp [hunk 2]
```diff
@@ -213,11 +213,15 @@ extern "C" void JSCInitialize(const char* envp[], size_t envc, void (*onCrash)(c
...
     JSC::Config::enableRestrictedOptions();
 
     std::set_terminate([]() { Zig__GlobalObject__onCrash(); });
+    printf("1: a\n");
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/ZigGlobalObject.cpp]:
```suggestion

```

File: src/bun.js/bindings/ZigGlobalObject.cpp [hunk 3]
```diff
@@ -213,11 +213,15 @@ extern "C" void JSCInitialize(const char* envp[], size_t envc, void (*onCrash)(c
...
     WTF::initializeMainThread();
+    printf("1: b\n");
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/ZigGlobalObject.cpp]:
```suggestion

```

File: src/bun.js/bindings/ZigGlobalObject.cpp [hunk 4]
```diff
@@ -213,11 +213,15 @@ extern "C" void JSCInitialize(const char* envp[], size_t envc, void (*onCrash)(c
...
     JSC::initialize();
+    printf("1: c\n");
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/ZigGlobalObject.cpp]:
```suggestion

```

File: src/bun.js/bindings/ZigGlobalObject.cpp [hunk 5]
```diff
@@ -257,6 +261,7 @@ extern "C" void JSCInitialize(const char* envp[], size_t envc, void (*onCrash)(c
         }
         JSC::Options::assertOptionsAreCoherent();
     }
+    printf("1: d\n");
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/ZigGlobalObject.cpp]:
```suggestion

```

File: src/output.zig [hunk 6]
```diff
@@ -16,7 +16,7 @@ const SystemTimer = @import("./system_timer.zig").Timer;
 
 // These are threadlocal so we don't have stdout/stderr writing on top of each other
 threadlocal var source: Source = undefined;
-threadlocal var source_set: bool = false;
+pub threadlocal var source_set: bool = false;
```
Comment (Jarred-Sumner) [inline src/output.zig]: does this need to be pub?

Comment (paperclover) [reply src/output.zig]: the goal was to make crash_handler not use output if the source was not set, but i didn't keep that behavior.

Comment (Jarred-Sumner) [reply src/output.zig]: okay so can we remove this change?
