### PR TITLE
Fixes #10624

### LINKED ISSUE #10624: error when use bun build express.ts --compile --minify --sourcemap --outfile dist/express
### How can we reproduce the crash?

_No response_

### Relevant log output

```shell
============================================================
Bun v1.1.6 (e58d67b4) Windows x64
Args: "C:\Program Files\nodejs\node_modules\bun\bin\bun.exe", "build", "express.ts", "--compile", "--minify", "--sourcemap", "--outfile", "dist/express"
Features: bunfig define dotenv tsconfig(9) 
Elapsed: 6791ms | User: 6125ms | Sys: 0ms
RSS: 120.21MB | Peak: 120.29MB | Commit: 0.22GB | Faults: 30391

panic(thread 3616): integer overflow
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`sourcemap.zig:443`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/sourcemap.zig#L443): `advance`
- [`sourcemap.zig:418`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/sourcemap.zig#L418): `advance`
- [`bundle_v2.zig:6365`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bundler/bundle_v2.zig#L6365): `generateChunkJS`
- [`output.zig:402`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/output.zig#L402): `flush`
- ??? at `0x1257d` in /KERNEL32.DLL
- ??? at `0x5aa48` in /ntdll.dll

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #10624

### How did you verify your code works?

There is an integration test

### CODE REVIEW

**Review by dylan-conway — APPROVED** [review]
Looks good. We might want to change `CodepointIterator.next()` to fill the cursor with width 1 in this situation because a null byte isn't zero width

File: src/sourcemap/sourcemap.zig [hunk 1]
```diff
@@ -449,6 +449,16 @@ pub const LineColumnOffset = struct {
...
             _ = iter.next(&cursor);
+
+            // Given a null byte, cursor.width becomes 0
+            // This can lead to integer overflow, crashes, or hangs.
+            // https://github.com/oven-sh/bun/issues/10624
+            if (cursor.width == 0) {
+                columns += 1;
+                offset = i + 1;
+                continue;
+            }
```
Comment (gvilums) [inline src/sourcemap/sourcemap.zig:460]: I think we should use the return value of `iter.next` (which returns `false` on a byte sequence length of 0) to detect the invalid case, e.g.
```suggestion
            // Given a null byte, cursor.width becomes 0
            // This can lead to integer overflow, crashes, or hangs.
            // https://github.com/oven-sh/bun/issues/10624
            if (!iter.next(&cursor)) {
                columns += 1;
                offset = i + 1;
                continue;
             }            
```
This would also make the code less likely to break if we change the default `width` value in `CodepointIterator.Cursor`

Comment (Jarred-Sumner) [reply src/sourcemap/sourcemap.zig:460]: .next() returns false when it reaches the end

It shouldn't advance columns by 1 when the end is reached

Comment (gvilums) [reply src/sourcemap/sourcemap.zig:460]: makes sense 👍
