### PR TITLE
[install] fix run-time module loading

### LINKED ISSUE #3507: Auto-install fails to run twice
### What version of Bun is running?

0.6.12

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Create a new folder, write test.ts, run `bun run test.ts` twice
Code:
```
import { say } from "cowsay";

console.log(say({ text: "grazing in the browser" }));
```

### What is the expected behavior?

Both steps execute and display:
```
< grazing in the browser >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### What do you see instead?

First run work as expected, second show an error

```
▶ bun run test.ts                                                    
  🔍 require-main-filename [1/1]  ________________________
< grazing in the browser >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

/git/buntest     
▶ bun run test.ts


error: Unexpected pending import in "/home/rfiszel/.bun/install/cache/cowsay@1.5.0/lib/balloon.js". To automatically install npm packages with Bun, please use an import statement instead of require() or dynamic import().
This error can also happen if dependencies import packages which are not referenced anywhere. Worst case, run `bun install` and opt-out of the node_modules folder until we come up with a better way to handle this error.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alexlamsl**
- fix version buffer confusion
- improve workaround to handle cached modules

fixes #3507

### CODE REVIEW

File: src/install/install.zig [hunk 1]
```diff
@@ -1742,55 +1742,51 @@ pub const PackageManager = struct {
...
+            const dep = dummy.cloneWithDifferentBuffers(name, version_buf, @TypeOf(&builder), &builder) catch unreachable;
+            builder.clamp();
+            const index = this.lockfile.buffers.dependencies.items.len;
+            this.lockfile.buffers.dependencies.append(this.allocator, dep) catch unreachable;
+            this.lockfile.buffers.resolutions.append(this.allocator, invalid_package_id) catch unreachable;
+            if (comptime Environment.allow_assert) std.debug.assert(this.lockfile.buffers.dependencies.items.len == this.lockfile.buffers.resolutions.items.len);
+            break :brk index;
+        });
+
+        if (this.lockfile.buffers.resolutions.items[dep_id] == invalid_package_id) {
```
Comment (Jarred-Sumner) [inline src/install/install.zig:1777]: What happens when the dependency is pending install?

File: src/install/install.zig [hunk 2]
```diff
@@ -1742,55 +1742,51 @@ pub const PackageManager = struct {
...
-            failRootResolution,
-        ) catch |err| {
-            return .{ .failure = err };
-        };
+            builder.allocate() catch |err| return .{ .failure = err };
+
+            const dep = dummy.cloneWithDifferentBuffers(name, version_buf, @TypeOf(&builder), &builder) catch unreachable;
+            builder.clamp();
+            const index = this.lockfile.buffers.dependencies.items.len;
+            this.lockfile.buffers.dependencies.append(this.allocator, dep) catch unreachable;
```
Comment (Jarred-Sumner) [inline src/install/install.zig:1771]: this always leaks the dependency right?

Comment (alexlamsl) [reply src/install/install.zig:1771]: It follows the allocation lifecycle of the `Lockfile` instance.

File: src/install/install.zig (hunk 1 above)
Comment (alexlamsl) [reply src/install/install.zig:1777]: Even within `bun install` we would call `enqueueDependencyWithMainAndSuccessFn()` on the same dependency multiple times, e.g. various processing stages for `.npm`, so we should be safe here.

Comment (Jarred-Sumner) [reply src/install/install.zig:1777]: yes but we wouldn't append to the list of dependencies if it already existed

Comment (alexlamsl) [reply src/install/install.zig:1777]: And we don't - we look for and reference an existing dependency here:
https://github.com/oven-sh/bun/pull/3510/files#diff-2d4db027e059280840de7dfe46dda1752467e66c1c3014369ed701b026cd06fcR1751

After that search fails (which also means there can't be pending since it doesn't exist before), then we create a new one.

**Comment by Jarred-Sumner** [comment]
Thank you
