### PR TITLE
shell: Fix #11554 and #11561

### LINKED ISSUE #11554: $.escape invalid UTF-16
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

1 - `echo "✔" > test.txt`
2- `vim bug.ts`
```ts
import { $ } from 'bun';
const file = "test.txt";
const content = await Bun.file(file).text();
console.log("Escaping", $.escape( content ) );
```
3 - `bun run bug.ts`

### What is the expected behavior?

Escapes the output

### What do you see instead?

```
➜  ~ bun run bug.ts
1 | import { $ } from 'bun';
2 | const file = "ubuntu.txt";
3 | const content = await Bun.file(file).text();
4 | // const content = await $`cat ${file}`.text();
5 | console.log("Escaping", $.escape( content ) );
                            ^
error: String has invalid utf-16: '
```

### Additional information

This happens on MacOS and on Ubuntu.

Originally asked as a Discord conversation: https://discord.com/channels/876711213126520882/1246075889842655262/1246075889842655262

## Test on Ubuntu

I also tried this on an Ubuntu machine (VM on a home server):
Linux 5.15.0-100-generic x86_64 x86_64

Seems like this wasn't a problem in `1.0.26`, but in 1.1.2 it's broken:

```
➜  ~ bun -v
1.0.26
➜  ~ cat "✔" > ubuntu.txt
cat: ✔: No such file or directory
➜  ~ echo "✔" > ubuntu.txt
➜  ~ vim bug.ts
➜  ~ bun run bug.ts
Escaping "'
"
➜  ~ bun upgrade
Bun v1.1.12 is out! You're on 1.0.26
[2.17s] Upgraded.

➜  ~ bun run bug.ts
1 | import { $ } from 'bun';
2 | const file = "ubuntu.txt";
3 | const content = await Bun.file(file).text();
4 | // const content = await $`cat ${file}`.text();
5 | console.log("Escaping", $.escape( content ) );
                            ^
error: String has invalid utf-16: '

      at /home/n/bug.ts:5:25

Bun v1.1.12 (Linux x64)
```

### LINKED ISSUE #11561: Shell: panic: No arguments provided
### How can we reproduce the crash?

Just create a ts file with await $`$(/bin/bash script.sh)` and all the required imports

Even if the script is not found, it throws the same error

### JavaScript/TypeScript code that reproduces the crash?

```shell
await $`$(/bin/bash script.sh)`
```

### Relevant log output

```shell
Bun v1.1.12 (43f0913c) Linux x64
Args: "./wics-cli-converter"
Features: jsc Bun.stderr(29) Bun.stdin(2) Bun.stdout(29) shell(41) spawn(41) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:util" "node:util/types" 
Elapsed: 15889ms | User: 255ms | Sys: 63ms
RSS: 1.07GB | Peak: 83.86MB | Commit: 1.07GB | Faults: 0

panic(main thread): No arguments provided
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/l_143f0913A+gggM6h8+lDyqrqmD265m7C+l2pmDq6jwjDst2y7Cg93tkD2igs6C0ptu/Dowgk0CA0eNrzy1dILEovzU3NKylWKCjKL8tMSU0BAFeTCDE

Illegal instruction
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [_]

**panic**: No arguments provided

- [`fmt.zig:1426`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/fmt.zig#L1426>): `src.output.print__anon_430212`
- [`string_immutable.zig:3377`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/string_immutable.zig#L3377>): `src.shell.interpreter.Interpreter.Expansion.next`
- [`array_list.zig:1157`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/array_list.zig#L1157>): `src.bun.js.api.bun.process.ProcessExitHandler.call`
- [`module_loader.zig:393`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/module_loader.zig#L393>): `src.bun.js.module_loader.RuntimeTranspilerStore.TranspilerJob.runFromJSThread`
- [`tagged_pointer.zig:40`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/tagged_pointer.zig#L40>): `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_363385`
- [`unbounded_queue.zig:114`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/unbounded_queue.zig#L114>): `src.bun.js.event_loop.EventLoop.tick`
- [`options.zig:2060`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/options.zig#L2060>): `src.bun.js.event_loop.AnyTask.New`
- [`javascript.zig:948`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/javascript.zig#L948>): `src.bun.js.javascript.OpaqueWrap__anon_53035__struct_285803.callback`
- [`EnsureStillAliveHere.h:39`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/JavaScriptCore/EnsureStillAliveHere.h#L39>): `JSC__JSPromise__resolvedPromiseValue`
- [`cli.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L0>): `src.cli.Cli.start`

### PR DESCRIPTION
**Pull request by zackradisic**
### What does this PR do?

Fixes some bugs related to $.escape

And removes a panic when a command name gets expanded to nothing

Fixes #11554
Fixes #11561

### CODE REVIEW

File: src/shell/interpreter.zig [hunk 1]
```diff
@@ -2121,6 +2121,13 @@ pub const Interpreter = struct {
                     assert(this.child_state == .cmd_subst);
                 }
 
+                if (exit_code != 0 and
```
Comment (Jarred-Sumner) [inline src/shell/interpreter.zig:2132]: When does this happen? I think a comment showing an example where this case would happen would be helpful

File: src/shell/interpreter.zig [hunk 2]
```diff
@@ -4544,6 +4552,14 @@ pub const Interpreter = struct {
                     this.writeFailingError("{s}", .{buf});
                     return;
                 }
+                const e: *Expansion = child.ptr.as(Expansion);
+                if (this.state == .expanding_args and
```
Comment (Jarred-Sumner) [inline src/shell/interpreter.zig:4571]: Please add a comment here as well

File: src/shell/interpreter.zig [hunk 3]
```diff
@@ -4574,8 +4590,9 @@ pub const Interpreter = struct {
                 }
 
                 const first_arg = this.args.items[0] orelse {
-                    // If no args then this is a bug
-                    @panic("No arguments provided");
+                    // Sometimes the expansion can result in an empty string
```
Comment (Jarred-Sumner) [inline src/shell/interpreter.zig:4608]:
```suggestion
                    // Sometimes the expansion can result in an empty string
                    //  For example:
                    //
                    //     await $`echo "" > script.sh`
                    //     await $`(bash ./script.sh)`
                    //
```

**Review by Jarred-Sumner — APPROVED** [review]

**Review by paperclover — APPROVED** [review]
