### PR TITLE
fix: large `bunx` changes, mostly for better windows support

### LINKED ISSUE #4974: Unknown option `--bun`
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.0-83-generic x86_64 x86_64

### What steps can reproduce the bug?

I was trying the [Build a frontend using Vite and Bun](https://bun.sh/guides/ecosystem/vite).
According to the document
//package.json
Attempt 1:
"scripts": {
  "dev": "bunx --bun vite",
  "build": "vite build",
  "serve": "vite preview"
},

Attempt 2:
"scripts": {
  "dev": "bun x --bun vite",
  "build": "vite build",
  "serve": "vite preview"
},

I know it has not been heavily optimized, nor has Vite been adapted to use Bun's bundler, module resolver, or transpiler.
But maybe fixing this initial issues might save some headache.

### What is the expected behavior?

**VITE** v4.x.x ready in 100ms
-> Local:   http://localhost:5173/

### What do you see instead?

Attempt 1 Result:
bunx: comand not found

Attempt 1 Result:
CACError: Unknown option `--bun`

### Additional information

Possible Fix for "dev":
//package.json
"scripts": {
  "dev": "bun x vite",
  "build": "vite build",
  "serve": "vite preview"
},

### LINKED ISSUE #5030: bunx behaviour, cli inconsistencies with bun x
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.5.1 x86_64 unknown

### What steps can reproduce the bug?

```
$ bunx --bun echo

$ bun x --bun echo
--bun

$ bun --bun x echo

$ bunx -b echo   
-b

$ bun x -b echo   
-b

$ bun -b x echo   
-b

$ bunx --help echo --help echo --help   
--help --help echo --help

$ bunx /usr/bin/env echo
error: unrecognised dependency format: @/usr/bin/env

$ bunx env echo         

```

### What is the expected behavior?
The following assumes that echo is a npm package that prints CLI arguments, instead of an actual echo package.
In reality it should show `error: could not determine executable to run for package echo`
```
$ bunx --bun echo

$ bun x --bun echo

$ bun --bun x echo

$ bunx -b echo   

$ bun x -b echo   

$ bun -b x echo

$ bunx --help echo --help echo --help   
usage: bunx [bun flags]... package[@version] [flags or arguments to pass through]...

bunx runs an npm package executable, automatically installing into a global shared cache if not installed in node_modules.

...omitted

$ bunx /usr/bin/env echo
error: unrecognised dependency format: @/usr/bin/env

$ bunx env echo         
error: could not determine executable to run for package env
```

There a many points for consideration, npm and pnpm are weird in their CLI.

I suggest the following:
1. correctly add `-b` flag as alias for `--bun`
2. every argument that starts with `-` is a flag to bun until a required flag that starts with anything else is encountered
   `bunx [bun_flags]... package[@version] [pkg_args]...`
   `bun [bun_flags]... x [bun_flags]... package[@version] [pkg_args]...`

3. `bunx` and `bun x` should have exactly the same behaviour, note that this is not the case for npm or pnpm
4. add npm `-c` flag alternative to run files in the shell, my suggestion is
  `bun shell [-p <pkg>]... [cmd_and_args]...`
5. add `exec` command and make `x` an alias of it

Point [4] requires standalone issue.

### What do you see instead?

_No response_

### Additional information

Related issue https://github.com/oven-sh/bun/issues/4972

### LINKED ISSUE #6215: `--bun` option before `create` command crashes while `--bun` after `create` works fine
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I'm using `quasar` as the template, but it's not actually relevant to the error, only the expected outcome. 
Run this in your terminal:
```bash
docker run -it oven/bun bun --bun create quasar
```

### What is the expected behavior?

Output should be like the `bun create --bun quasar` command:
```bash
$ docker run -it oven/bun bun create --bun quasar

 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

? What would you like to build? › - Use arrow-keys. Return to submit.
❯   App with Quasar CLI, let's go!
    spa/pwa/ssr/bex/electron/capacitor/cordova
    AppExtension (AE) for Quasar CLI
    Quasar UI kit

```

### What do you see instead?

Instead I see `TypeError` is thrown from the `fs-extra` module:

```bash
$  docker run -it oven/bun bun --bun create quasar
11 |         }
12 |         arguments.length++
13 |         fn.apply(this, arguments)
14 |       })
15 |     }
16 |   }, 'name', { value: fn.name })
                          ^
TypeError: undefined is not an object (evaluating 'fn.name')
      at /tmp/create-create@latest--bunx/node_modules/universalify/index.js:16:22
      at /tmp/create-create@latest--bunx/node_modules/fs-extra/lib/fs/index.js:49:20
      at forEach (:1:20)
      at /tmp/create-create@latest--bunx/node_modules/fs-extra/lib/fs/index.js:48:0
      at globalThis (/tmp/create-create@latest--bunx/node_modules/fs-extra/lib/fs/index.js:60:3)
      at require (:1:20)
      at /tmp/create-create@latest--bunx/node_modules/fs-extra/lib/index.js:8:7
      at globalThis (/tmp/create-create@latest--bunx/node_modules/fs-extra/lib/index.js:22:17)
```

### Additional information

Additional platform info, I'm on Ubuntu's official WSL2 distribution:
```bash
$  cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

I'm using docker desktop as the container runtime.

> [!NOTE]
> the following fails in the same way - `bun --bun create` which makes me thing the `create` command is not being processed at all.

`bun --bun run ..` and `bun run --bun` are equivalent, so my expectation was that `create` would be the same. I haven't checked the other commands, but the same issue might be there as well for all I know.

I apologize if this is previously reported or discussed, I couldn't see anything for it when I was looking though.

### LINKED ISSUE #6458: bunx <package> hangs
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 6.5.4-1-default x86_64 x86_64

### What steps can reproduce the bug?

Similar problem to this issue: https://github.com/oven-sh/bun/issues/5831
This command hangs for very long time, at least 10 min without positive result.

$ bun x github:piuccio/cowsay
🔍 Resolving [1/1]
🚚 github:piuccio/cowsay [2/2]
🔍 string-width [4/7]
🔍 strip-final-newline [11/14]

### What is the expected behavior?

The package should run immediately.

### What do you see instead?

Bun gets stuck for minutes.

### Additional information

_No response_

### LINKED ISSUE #8795: windows: bunx fails when node is not installed
### What version of Bun is running?

_No response_

### What platform is your computer?

_No response_

### What steps can reproduce the bug?

install fresh windows and only install bun

`bun create vite`

### What is the expected behavior?

it to work

### What do you see instead?

```
error: interpreter executable could not be found

Bun failed to remap this bin to it's proper location within node_modules.
This is an indication of a corrupted node_modules directory.

Please run 'bun install --force' in the project root and try
it again. If this message persists, please open an issue:
https://github.com/oven-sh/bun/issues
```

### Additional information

This is a bug in `bunx` code that doesnt ensure a node binary exists before starting the bin.

It is also technically a fault of bun_shim_impl for not having a fallback for when `node.exe` is requested but not found. these are technically separate concerns.

### LINKED ISSUE #8918: windows: add the `.bunx` fast path to `bunx`
### What is the problem this feature would solve?

5ms faster bunx on windows

### What is the feature you are proposing to solve the problem?

check for a `.bunx` file when launching instead of using `which`, then launching it.

### What alternatives have you considered?

_No response_

### LINKED ISSUE #9056: bunx create-next-app@latest freezes
### What version of Bun is running?

1.0.28-canary.13+260572289

### What platform is your computer?

x64

### What steps can reproduce the bug?

I don't know how to resolve the issue, since it didn't even return any error

### What is the expected behavior?

Running bunx create-next-app@latest should start building a Next-js project by asking some questions about the project setup

### What do you see instead?

when i run bunx create-next-app@latest it freezes for a little bit and then exit to start a new command

```
khair@khaireddine MINGW64 ~/OneDrive/Desktop/Portfolio Projects/revamp (master)
$ bunx create-next-app@latest 

khair@khaireddine MINGW64 ~/OneDrive/Desktop/Portfolio Projects/revamp (master)
$
```
Screenshot 2024-02-23 013203

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
- [x] A one line bug was fixed that prevented bunx from working. Fixes #8795
- [x] Make it so the bun shim will detect when spawning `node.exe` failed due to not found, then it retries once with bun.
- [x] If spawning with bun failed, it prints a very particular message with the install instructions.
- [x] environment was not being inherited by the bunx fast path
- [x] bunx fast path must fallback when a version difference is detected
- [x] make the interpreter not found error line print the interpreter it tried.
- [X] Fixes #8918
- [x] Fixes #9056
- [x] improve bunx's cli parsing a lot, mainly fixing `--bun`. TODO: verify this closes the following issues on all platforms:
  - [x] ~~#6340~~ Not a bug in Bun.
  - [x] Fixes #4974
  - [x] Fixes #5030
  - [x] Fixes #6215
- [x] `--verbose` passes verbose to the package manager
- [x] why does FailedToOpenSocket happen?
  - [x] print a better error in debug for this
- [x] error.NoError -> null
- [X] Support github / tarball urls
  - [X] Fixes #6458

stuff like this works now:
image

### CODE REVIEW

**Comment by paperclover** [comment]
another fix done
image

File: src/cli/run_command.zig [hunk 1]
```diff
@@ -772,9 +814,11 @@ pub const RunCommand = struct {
             original_path.* = PATH;
         }
 
+        const bun_node_exe = try bunNodeFileUtf8(ctx.allocator);
+        const bun_node_dir_win = bun.Dirname.dirname(u8, bun_node_exe) orelse return error.FailedToGetTempPath;
```
Comment (dylan-conway) [inline src/cli/run_command.zig:867]: if `TEMP` or any of the temp env variables are `C:\` on windows, dirname will return null. It's unlikely but we probably want to allow this situation

File: src/cli/upgrade_command.zig [hunk 2]
```diff
@@ -845,13 +845,17 @@ pub const UpgradeCommand = struct {
                     }
 
                     Output.errGeneric(
-                        \\Failed to move new version of Bun due to {s}
+                        \\Failed to move new version of Bun to {s} to {s}
```
Comment (dylan-conway) [inline src/cli/upgrade_command.zig:868]:
```suggestion
                        \\Failed to move new version of Bun to {s} due to {s}
```

File: src/cli/run_command.zig (hunk 1 above)
Comment (paperclover) [reply src/cli/run_command.zig:867]: bun_node_exe is the path to `node.exe`, which should always have a dirname. i will verify this is true

**Comment by paperclover** [comment]
image
i am removing this because unreachable here does not do any optimization and unlike in zig we cannot do noreturn.

File: src/cli/run_command.zig (hunk 1 above)
Comment (paperclover) [reply src/cli/run_command.zig:867]: yep not a bug.
image

File: src/deps/uws.zig [hunk 3]
```diff
@@ -539,6 +539,7 @@ pub fn NewSocketHandler(comptime is_ssl: bool) type {
                 @sizeOf(*anyopaque),
             ) orelse {
                 if (Environment.isWindows) {
+                    std.debug.print("Thread {d} Failure HTTP\n", .{std.Thread.getCurrentId()});
```
Comment (Jarred-Sumner) [inline src/deps/uws.zig]: did you mean to leave this in here

File: src/http.zig [hunk 4]
```diff
@@ -737,6 +731,7 @@ pub const HTTPThread = struct {
         });
 
         if (Environment.isWindows) {
+            std.debug.print("Thread {d} init HTTP\n", .{std.Thread.getCurrentId()});
```
Comment (Jarred-Sumner) [inline src/http.zig]: did you mean to leave this in here

**Comment by paperclover** [comment]
Many test failures to fix first

File: src/install/install.zig [hunk 5]
```diff
@@ -4692,7 +4690,7 @@ pub const PackageManager = struct {
                                     null,
                                     logger.Loc.Empty,
                                     manager.allocator,
-                                    "<r><yellow>warn:<r> {s} downloading package manifest <b>{s}<r>",
+                                    "{s}  downloading package manifest <b>{s}<r>",
```
Comment (Jarred-Sumner) [inline src/install/install.zig]:
```suggestion
                                    "{s} downloading package manifest <b>{s}<r>",
```

File: src/install/windows-shim/BinLinkingShim.zig [hunk 6]
```diff
@@ -202,6 +207,21 @@ pub const Shebang = struct {
         return try Shebang.init(line, false);
     }
 
+    pub fn coerceNodeToBun(self: Shebang, buf: *[32766]u8) Shebang {
```
Comment (Jarred-Sumner) [inline src/install/windows-shim/BinLinkingShim.zig]: :scissors:

**Comment by Jarred-Sumner** [comment]
Assuming the test failures are gone, looks great.

File: src/install/windows-shim/bun_shim_impl.zig [hunk 7]
```diff
@@ -675,51 +749,114 @@ fn launcher(bun_ctx: anytype) noreturn {
...
 
-    var exit_code: w.DWORD = 255;
-    _ = k32.GetExitCodeProcess(process.hProcess, &exit_code);
+        var exit_code: w.DWORD = 255;
+        _ = k32.GetExitCodeProcess(process.hProcess, &exit_code);
 
-    _ = nt.NtClose(process.hProcess);
-    _ = nt.NtClose(process.hThread);
+        _ = nt.NtClose(process.hProcess);
+        _ = nt.NtClose(process.hThread);
```
Comment (Jarred-Sumner) [inline src/install/windows-shim/bun_shim_impl.zig:854]: @paperdave was it intentional we close the thread handle only after the process has exited instead of immediately? since this handle is not used, couldn't we close it immediately?

File: src/install/windows-shim/bun_shim_impl.zig [hunk 8]
```diff
@@ -675,51 +749,114 @@ fn launcher(bun_ctx: anytype) noreturn {
...
-            // This likely will not be an issue anyone runs into for a while, because it implies
-            // the shebang depends on something that requires UAC, which .... why?
-            //
-            // https://learn.microsoft.com/en-us/windows/security/application-security/application-control/user-account-control/how-it-works#user
-            // https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew
-            .ELEVATION_REQUIRED => fail(.ElevationRequired),
+    inline for (.{ 0, 1 }) |attempt_number| iteration: {
+        if (dbg)
+            debug("lpCommandLine: {}\n", .{fmt16(std.mem.span(spawn_command_line))});
+        const did_process_spawn = k32.CreateProcessW(
```
Comment (Jarred-Sumner) [inline src/install/windows-shim/bun_shim_impl.zig:756]: maybe we should get/set the codepage before & after?
