### PR TITLE
fix macro string escaping

### LINKED ISSUE #3957: macro serialization broken for when returning escaped string
### What version of Bun is running?

0.7.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

see the screenshot for a complete repro

image

### What is the expected behavior?

it should not fail (it works if I remove escaping) and I think it should not even un-escape the saved result/ast - or at least it should definitely not do so for `\\`

### What do you see instead?

`bun run` fails

### Additional information

@dylan-conway

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?

strings passed as arguments to macros and strings returned from macros are escaped correctly

### How did you verify your code works?
added macro tests for escape characters

fixes #3957

### CODE REVIEW

File: src/js_lexer.zig [hunk 1]
```diff
@@ -75,6 +75,19 @@ pub const JSONOptions = struct {
     was_originally_macro: bool = false,
 };
 
+pub fn decodeUTF8(bytes: string, allocator: std.mem.Allocator) ![]const u16 {
```
Comment (Jarred-Sumner) [inline src/js_lexer.zig:78]: `decodeWTF8`
