### PR TITLE
fix(expect): bug in string handling in toContain and return undefined in all matchers

### LINKED ISSUE #7144: `expect(...)toContain("")` handles `""` incorrectly
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 6.1.0-0.deb11.11-amd64 x86_64 unknown

### What steps can reproduce the bug?

```console
$ bun add -d fast-check
```
Create `string.test.ts` with this contents

```ts
import { describe, it, expect, test } from "bun:test";
import fc from "fast-check";

describe("The empty string", () => {
  const emptyString = "";
  it("has a 0 length", () => expect(emptyString).toHaveLength(0));
  it("is found in all strings", () => {
    fc.assert(
      fc.property(fc.string(), (string: string) => {
        expect(string.indexOf(emptyString)).toBe(0);
        expect(string).toContain(emptyString);
      })
    );
  });

  describe('forms the (strings, concatenation, "") monoid', () => {
    const cat = (a: string, b: string) => a + b;

    test("concatenation is associative on string", () => {
      fc.assert(
        fc.property(
          fc.string(),
          fc.string(),
          fc.string(),
          (a: string, b: string, c: string) =>
            expect(cat(cat(a, b), c)).toBe(cat(a, cat(b, c)))
        )
      );
    });

    test('concatenation with "" is identity', () => {
      fc.assert(
        fc.property(fc.string(), (a: string) => {
          expect(cat(a, emptyString)).toBe(a);
          expect(cat(emptyString, a)).toBe(a);
        })
      );
    });
  });
}
```

### What is the expected behavior?

These tests should pass.

### What do you see instead?

```console
bun test v1.0.11 (f7f6233e)

string.test.ts:
121 |     }
122 |     return defaultReportMessageInternal(out, stringifySecond);
123 | }
124 | function buildError(errorMessage, out) {
125 |     if (!out.runConfiguration.errorWithCause) {
126 |         throw new Error(errorMessage);
                  ^
error: Property failed after 1 tests
{ seed: 2018390894, path: "0:0:0:0", endOnFailure: true }
Counterexample: ["","",""]
Shrunk 3 time(s)
Got error: Property failed by returning false

Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:126:14)
      at throwIfFailed (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:138:10)
      at assert (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:69:8)
      at /home/chars/tmp/bun_playground/string.test.ts:20:6
✗ The empty string > forms the (strings, concatenation, "") monoid > concatenation is associative on string [6.69ms]
✓ The empty string > forms the (strings, concatenation, "") monoid > concatenation with "" is identity [5.09ms]
✓ The empty string > has a 0 length [0.07ms]
121 |     }
122 |     return defaultReportMessageInternal(out, stringifySecond);
123 | }
124 | function buildError(errorMessage, out) {
125 |     if (!out.runConfiguration.errorWithCause) {
126 |         throw new Error(errorMessage);
                  ^
error: Property failed after 1 tests
{ seed: 773790787, path: "0:1:1", endOnFailure: true }
Counterexample: [" "]
Shrunk 2 time(s)
Got error: expect(received).toContain(expected)

Expected to contain: ""
Received: " "

    at toContain (native)
    at <anonymous> (/home/chars/tmp/bun_playground/string.test.ts:12:4)
    at run (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/property/Property.generic.js:46:37)
    at runIt (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:18:12)
    at check (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:61:160)
    at assert (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:65:17)
    at <anonymous> (/home/chars/tmp/bun_playground/string.test.ts:9:15)

Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:126:14)
      at throwIfFailed (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:138:10)
      at assert (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:69:8)
      at /home/chars/tmp/bun_playground/string.test.ts:8:4
✗ The empty string > is found in all strings [3.03ms]

 2 pass
 2 fail
 217 expect() calls
Ran 4 tests across 1 files. [105.00ms]
```

### Additional information

The tests pass when run with `bun x jest`

### PR DESCRIPTION
**Pull request by DontBreakAlex**
### What does this PR do?

This changes toContains to pass when the needle is an empty string. [ref](https://tc39.es/ecma262/2023/#sec-stringindexof).
This also changes all matchers to return undefined on success instead of returning expect.

fixes #7144 

### How did you verify your code works?

I wrote automated tests

### CODE REVIEW

**Comment by CharString** [comment]
Cool. This fixes part of #7144. It doesn't fix the failing associativity test of string concatenation.

File: src/bun.js/test/expect.zig [hunk 1]
```diff
@@ -4092,7 +4093,7 @@ pub const Expect = struct {
 
         const not = this.flags.not;
         if (not) pass = !pass;
-        if (pass) return thisValue;
+        if (pass) return .undefined;
```
Comment (jdalton) [inline src/bun.js/test/expect.zig:4096]: There is an audit to avoid use or `undefined`. Not sure if `.undefined` is different... https://github.com/oven-sh/bun/issues/4426

Comment (paperclover) [reply src/bun.js/test/expect.zig:4096]: .undefined is an enum literal, which refers to `JSValue.undefined`. this is safe.

**Comment by jdalton** [comment]
> Cool. This fixes part of #7144. It doesn't fix the failing associativity test of string concatenation.

Let's split that out into a separate issue.

File: src/bun.js/test/expect.zig (hunk 1 above)
Comment (jdalton) [reply src/bun.js/test/expect.zig:4096]: This LGTM!

**Review by jdalton — APPROVED** [review]

**Comment by dylan-conway** [comment]
Thank you
