### PR TITLE
make V8StackTraceIterator frame parser more robust

### LINKED ISSUE #8714: [windows] Fix source paths in error messages, it says `D:` as the file path
image

### PR DESCRIPTION
**Pull request by nektro**
Fixes #8714

fixes the more naive frame line parsing to be more resilient to windows paths and missing numbers

### CODE REVIEW

**Comment by nektro** [comment]
windows traces after this change:

image

File: src/bun.js/bindings/bindings.cpp [hunk 1]
```diff
@@ -4048,37 +4072,79 @@ class V8StackTraceIterator {
             return false;
         }
 
-        auto firstColon = line.find(':', openingParenthese + 1);
+        auto lineInner = StringView_slice(line, openingParenthese + 1, closingParenthese);
+        auto colonCount = StringView_count(lineInner, ':', 0);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp]: This is going to make it a _lot_ slower. Do we really need an exact count? Or can we get away with finding the last 2 colons?

File: src/bun.js/bindings/bindings.cpp [hunk 2]
```diff
@@ -4048,37 +4072,79 @@ class V8StackTraceIterator {
...
-            // at foo (/path/to/file.js:
-            frame.sourceURL = line.substring(openingParenthese + 1, firstColon - openingParenthese - 1);
+        case 1: {
+            // /path/to/file.js:
+            // /path/to/file.js:1
+            // node:child_process
+            // C:\Users\dave\bun\file.js
+
+            auto marker1 = 0;
+            auto marker2 = lineInner.find(':', marker1);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp:4061]: First we get a count which gets the index of every colon (on line 4076)

Then we get the first colon again right here

Do we need to duplicate this work?

File: src/bun.js/bindings/bindings.cpp [hunk 3]
```diff
@@ -4048,37 +4072,79 @@ class V8StackTraceIterator {
...
+            // /path/to/file.js:1:
+            // /path/to/file.js:1:2
+            // node:child_process:1:2
+            // C:\Users\dave\bun\file.js:
+            // C:\Users\dave\bun\file.js:1
+            // C:\Users\dave\bun\file.js:1:2
+
+            auto linenoColon = lineInner.find(':', 0);
+            for (size_t i = 0; i < colonCount - 2; i++) {
+                linenoColon = lineInner.find(':', linenoColon + 1);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp]: This finds every colon until the 2nd to last colon

That's a lot of duplicate work

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
Please find a way to do this without making the stack trace parser slower

error.stack is used very frequently by HTTP libraries so we have to be careful

File: src/bun.js/bindings/bindings.cpp [hunk 4]
```diff
@@ -100,6 +100,11 @@
 #include "JavaScriptCore/InternalFieldTuple.h"
 #include "wtf/text/StringToIntegerConversion.h"
 
+static WTF::StringView StringView_slice(WTF::StringView sv, unsigned start, unsigned end)
+{
+    return sv.substring(start, end - start);
+}
```
Comment (jdalton) [inline src/bun.js/bindings/bindings.cpp:106]: This is a great helper. Do we have a WTF like place for it. (... guessing this may be it)

File: src/bun.js/bindings/bindings.cpp [hunk 5]
```diff
@@ -4048,38 +4054,78 @@ class V8StackTraceIterator {
...
-        auto firstColon = line.find(':', openingParenthese + 1);
+        auto lineInner = StringView_slice(line, openingParenthese + 1, closingParenthese);
 
-        // if there is no colon, that means we only have a filename and no line number
+        {
+            auto marker1 = 0;
+            auto marker2 = lineInner.find(':', marker1);
 
-        //   at foo (native)
-        if (firstColon == WTF::notFound) {
```
Comment (jdalton) [inline src/bun.js/bindings/bindings.cpp:4056]: I find the comments that bread crumb where we are in the parsing of the stack trace helpful. The more the merrier. We should also add a note that if the stack trace format changes this is also needs updating. Or... can we comment referencing the V8 code we are mimicking.

File: src/bun.js/bindings/bindings.cpp [hunk 6]
```diff
@@ -4048,38 +4054,78 @@ class V8StackTraceIterator {
...
-            frame.sourceURL = line.substring(openingParenthese + 1, closingParenthese - openingParenthese - 1);
-        } else {
-            // at foo (/path/to/file.js:
-            frame.sourceURL = line.substring(openingParenthese + 1, firstColon - openingParenthese - 1);
-        }
+            if (marker2 == WTF::notFound) {
```
Comment (jdalton) [inline src/bun.js/bindings/bindings.cpp:4063]: Can you add a comment somewhere (relevant) that explains why we are doing the search this way (making it more robust). This will help future us when we want to try to optimize smth and we can see oohh ya we do it this way for cross-platform goodness.

**Comment by jdalton** [comment]
Does this unblock a unit test? Is there a test for this robustness (like a test on Windows or something). 
(Indirectly asking if we have a test to cover this and if not to please add one 🥺 )

**Comment by Jarred-Sumner** [comment]
I'm going to merge this but @nektro please address the feedback in a follow-up PR
