### PR TITLE
fix(cli/pack): excluded entries nested within included dirs

### LINKED ISSUE #18505: `bun publish` does not respect excluded `files` nested within included directories
### What version of Bun is running?

1.2.7-canary.16+57cda4a44

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

In the Bun, repo, run the following:
```sh
cd packages/bun-plugin-svelte
bun publish --dry-run
```

### What is the expected behavior?

```
bun publish v1.2.7-canary.16 (57cda4a4)

packed 0.98KB package.json
packed 1.94KB README.md
packed 4.88KB src/index.ts
packed 78B src/modules.d.ts
packed 3.87KB src/options.ts
packed 0.82KB tsconfig.json

Total files: 6
Shasum: c9a6adc41875bb0259c08004cfd3e9adc09307f0
Integrity: sha512-HuEDvOieVwXvh[...]0WlBd8SjgrnGQ==
Unpacked size: <size>KB
Packed size: <size>KB
Tag: latest
Access: default
Registry: https://registry.npmjs.org/

 + bun-plugin-svelte@0.0.6
```

### What do you see instead?

```
bun publish v1.2.7-canary.16 (57cda4a4)

packed 0.98KB package.json
packed 1.94KB README.md
packed 0.84KB src/index.spec.ts
packed 4.88KB src/index.ts
packed 78B src/modules.d.ts
packed 1.79KB src/options.spec.ts
packed 3.87KB src/options.ts
packed 0.82KB tsconfig.json

Total files: 8
Shasum: c9a6adc41875bb0259c08004cfd3e9adc09307f0
Integrity: sha512-HuEDvOieVwXvh[...]0WlBd8SjgrnGQ==
Unpacked size: 15.20KB
Packed size: 5.21KB
Tag: latest
Access: default
Registry: https://registry.npmjs.org/

 + bun-plugin-svelte@0.0.6
```

### Additional information

Here's the `files`s in this package's `package.json`. Note the `!src/**/*.spec.ts` glob at the bottom:

```jsonc
{
  // ...
  "files": [
    "README.md",
    "bunfig.toml",
    "tsconfig.json",
    "modules.d.ts",
    "dist",
    "src",
    "!src/**/*.spec.ts"
  ]
}
```

### PR DESCRIPTION
**Pull request by DonIsaac**
### What does this PR do?
Fixes #18505

Other changes:
- Pack `Pattern`'s boolean fields into a packed `Flags` struct

### How did you verify your code works?
I have added a test

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 4:00 PM PT - Mar 26th, 2025</sup></div>

@DonIsaac, your commit 377b796886f1d463f063ad194e9b7e9643ed57d4 is building: [`#14008`](https://buildkite.com/bun/bun/builds/14008)

File: src/cli/pack_command.zig [hunk 1]
```diff
@@ -2123,18 +2164,22 @@ pub const PackCommand = struct {
...
+        const Flags = packed struct {
+            /// beginning or middle slash (leading slash was trimmed)
+            rel_path: bool,
+            // can only match directories (had an ending slash, also trimmed)
+            dirs_only: bool,
+
+            @"leading **/": bool,
+            /// true if the pattern starts with `!`
+            negated: bool,
+        };
```
Comment (dylan-conway) [inline src/cli/pack_command.zig:2183]: This actually won't change the size of Pattern because Pattern remains a normal zig struct. Both versions of this should be 24 bytes (16 for `[]const u8` and 8 for flags + padding)

File: src/cli/pack_command.zig [hunk 2]
```diff
@@ -2189,9 +2234,26 @@ pub const PackCommand = struct {
...
+                    .negated = add_negate,
+                },
+            };
+        }
+
+        /// Invert a negated pattern to a positive pattern
+        pub fn asPositive(this: *const Pattern) Pattern {
+            bun.assertWithLocation(this.flags.negated and this.glob.len > 0, @src());
+            return Pattern{
+                .glob = this.glob[1..], // remove the leading `!`
```
Comment (dylan-conway) [inline src/cli/pack_command.zig]: If `asPositive` is called on a pattern, `deinit` will free the wrong pointer due to `.glob = this.glob[1..]`

File: src/glob/match.zig [hunk 3]
```diff
@@ -139,6 +139,7 @@ pub fn match(_: Allocator, glob: []const u8, path: []const u8) MatchResult {
     // TODO: consider just returning a bool
     // return matched != negated;
     if (negated) {
+        // FIXME(@DonIsaac): This looks backwards to me
```
Comment (dylan-conway) [inline src/glob/match.zig:142]: maybe better names are `no_match_due_to_negation` and `match_due_to_negation`

File: src/cli/pack_command.zig [hunk 4]
```diff
@@ -2380,6 +2444,25 @@ pub const PackCommand = struct {
...
+            strings.eqlCaseInsensitiveASCIIICheckLength;
+
+        return filename.len > 5 and (eql(filename, "package.json") or
+            eql(filename, "LICENSE") or
+            eql(filename, "LICENCE") or
+            eql(filename, "README") or
+            filename.len > "README.".len and eql(filename[0.."README.".len], "README."));
+        //or
+        // eql(filename, "CHANGELOG") or
+        // filename.len > "CHANGELOG.".len and eql(filename[0.."CHANGELOG.".len], "CHANGELOG."));
```
Comment (dylan-conway) [inline src/cli/pack_command.zig]: Looks like originally `CHANGELOG.*` was checked in `isExcluded()`. This looks like it would allow excluding it through .npmignore? We should add a test for this

File: src/cli/pack_command.zig (hunk 1 above)
Comment (DonIsaac) [reply src/cli/pack_command.zig:2183]: Hmm true if this is 8 byte aligned

File: src/cli/pack_command.zig (hunk 2 above)
Comment (DonIsaac) [reply src/cli/pack_command.zig]: This is true; pattern doesn't carry around an ownership flag. Should we use `CowSlice`?

File: src/glob/match.zig (hunk 3 above)
Comment (DonIsaac) [reply src/glob/match.zig:142]: I agree, but I don't plan on modifying glob code in this PR

File: src/cli/pack_command.zig (hunk 4 above)
Comment (DonIsaac) [reply src/cli/pack_command.zig]: Fixed + test added

File: src/cli/pack_command.zig (hunk 2 above)
Comment (DonIsaac) [reply src/cli/pack_command.zig]: Fixed by using `CowString`

File: src/cli/pack_command.zig [hunk 5]
```diff
@@ -2380,6 +2445,32 @@ pub const PackCommand = struct {
 
         Output.flush();
     }
+
+    /// Some files are always packed, even if they are explicitly ignored or not
+    /// included in package.json "files".
+    fn isUnconditionallyIncludedFile(filename: []const u8) bool {
+        return filename.len > 5 and (stringsEql(filename, "package.json") or
+            isSpecialFileOrVariant(filename, "LICENSE") or
```
Comment (dylan-conway) [inline src/cli/pack_command.zig:2453]: This will change the behavior, allowing `LICENSE.foo`. We should check if npm does the same, and if not change to so it only matches `LICENSE` exactly.

**Review by dylan-conway — COMMENTED** [review]
After `LICENSE` comment is addressed this looks good to go

**Review by dylan-conway — APPROVED** [review]
