### PR TITLE
Use error handling callback in more places, emit 1015 when WSS TLS handshaking fails, micro-optimize ServerWebSocket, fix bug in util.inspect exceptions

### LINKED ISSUE #10619: windows client websocket on error event causes crash
### What version of Bun is running?

1.1.6

### What platform is your computer?

windows 11

### What steps can reproduce the bug?

Upon error handling, when using the value of event in any kind, bun crashes,

Code used for testing:
```ts
const socket = new WebSocket("wss://127.0.0.1:1000", "json")

socket.addEventListener("open", ev => {
    console.log("websocket open", ev)
})  

socket.addEventListener("message", ev => {
    console.log("messaged recieved", ev)
})

socket.addEventListener("close", ev => {
    console.log("websocket closed", ev)
})

socket.addEventListener("error", ev => {
    console.log("websocket errored!")
    console.log(ev)
});
```

### What is the expected behavior?

Not crashing. 

### What do you see instead?

The following error message:

```
websocket errored!
============================================================
Bun v1.1.6 (e58d67b4) Windows x64
Args: "C:\Users\Main1\.bun\bin\bun.exe", "run", "test.ts"
Builtins: "bun:main" 
Elapsed: 2130ms | User: 62ms | Sys: 15ms
RSS: 96.36MB | Peak: 96.36MB | Commit: 0.14GB | Faults: 23735

panic(main thread): attempt to use null value
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

...
```
### Additional information

Only occurs on windows, everything is working fine on linux based systems.

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

- Prepare for #5091 by swapping almost all usages of `vm.runErrorHandler` to `vm.onError` which calls the currently registered error handler instead of the global one. This may cause test failures, we will see.
- Shrink `ServerWebSocket` struct size from 28 bytes -> 24 bytes, which should slightly improve performance (rounding to alignment it was probably 32 bytes before)
- Micro-optimize console.log on objects which implement util.inspect.custom by caching the structure. This was barely measurable, might not be worth it
- Fixes a bug where throwing while logging a custom inspect would print `[native code]` because it was not correctly checking for exceptions
- This adds a test for `onConnectError` and fixes a double free there. Fixes #10619. 
- `WebSocket` now emits close code 1015 for TLS handshaking failure (cc @cirospaciari). Browsers do not do this. But on a server, this is useful information (image from the websocket spec).
image

Along the way, noticed a bug with unhandled errors. We seem to continue executing in cases where we should not continue executing. I think it's simple to fix, but it is very much a breaking change until we do #5091

### How did you verify your code works?

There are tests

### CODE REVIEW

**Review by cirospaciari — APPROVED** [review]

File: src/bun.js/bindings/webcore/WebSocket.cpp [hunk 1]
```diff
@@ -1158,15 +1143,19 @@ void WebSocket::didReceiveBinaryData(const AtomString& eventName, const std::spa
...
 }
 
-void WebSocket::didReceiveClose(CleanStatus wasClean, unsigned short code, WTF::String reason)
+void WebSocket::didReceiveClose(CleanStatus wasClean, unsigned short code, WTF::String reason, bool isConnectionError)
 {
     // LOG(Network, "WebSocket %p didReceiveErrorMessage()", this);
     // queueTaskKeepingObjectAlive(*this, TaskSource::WebSocket, [this, reason = WTFMove(reason)] {
     if (m_state == CLOSED)
         return;
+    const bool wasConnecting = m_state == CONNECTING;
```
Comment (dylan-conway) [inline src/bun.js/bindings/webcore/WebSocket.cpp:1152]: can't this be `isConnectionError` when the function is called instead?
```
 didReceiveClose(CleanStatus::NotClean, 1006, message, m_state == CONNECTING);
 ```

Comment (Jarred-Sumner) [reply src/bun.js/bindings/webcore/WebSocket.cpp:1152]: no, see the next line
