### PR TITLE
Fixes #16671

### LINKED ISSUE #2200: Segmentation fault when calling `Bun.resolveSync` within `PluginBuilder.onResolve`
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.15.0-58-generic x86_64 x86_64

### What steps can reproduce the bug?

I am attempting to sidestep Bun's handling of `.css` imports. I run with `bun -e *.css` to do so. As the `PluginBuilder.onLoad` callback will give me the import specifier unresolved, I try to call onResolve and switch the extension to `.js` in order to use `Bun.resolveSync` without causing an infinite loop, then back to `.css`, so that `onLoad` then sees the true absolute path.

```ts
Bun.plugin({
  name: "css",
  async setup(builder) {
    const { readFileSync } = await import("fs")

    builder.onResolve({ filter: /\.css$/ }, ({ path, importer }) => {
      const absolute = Bun.resolveSync(path.replace(/\.css$/, ".js"), importer).replace(/\.js$/, ".css")
      return {
        path: absolute,
        namespace: "css",
      }
    })

    builder.onLoad({ filter: /\.css$/, namespace: "css" }, ({ path }) => {
      const css = readFileSync(path, "utf8")
      return {
        loader: "object",
        exports: { default: css },
      }
    })
  },
})
```

### What is the expected behavior?

`Bun.resolveSync` returns an absolute path.

### What do you see instead?

The call to `Bun.resolveSync` immediately causes:

`1090991 Segmentation fault      (core dumped)`

### Additional information

_No response_

### LINKED ISSUE #16671: Bun.plugin segfault
### How can we reproduce the crash?

`plugin.ts`
```ts
import { writeFileSync } from "fs";
import { dirname, resolve } from "path";

Bun.plugin({
  name: "toml",
  setup(build) {
    build.onResolve({ filter: /\.toml$/ }, (args) => {
      const path = resolve(dirname(args.importer), args.path);
      writeFileSync(
        `${path}.d.ts`,
        `export default ${JSON.stringify(require(path))}`
      );
      return { path };
    });
  },
});
```

then register it as a plugin with `bunfig.toml`:

```toml
preload = "./plugin.ts"
```

and run this code:

`test.ts`
```ts
import bunfig from "./bunfig.toml";
console.log(bunfig);
```

### Relevant log output

i sometimes also got this:

```shell

1 | import bunfig from "./bunfig.toml";
2 | console.log(bunfig);
    ^
SyntaxError: Unexpected token ')'
      at <parse> (/home/hussein/project/test.ts:2:1)
```

### Stack Trace (bun.report)
Bun v1.2.10 ([`db2e7d7`](<https://github.com/oven-sh/bun/tree/db2e7d7f748dd3951ac0c983de73e75df51bb735>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x00000000

- *1 unknown/js code*
- `Bun::V::validateArray`
- `Bun::V::validateArray`
- `JSC__JSValue__getIfPropertyExistsFromPath`
- `transpiler.PluginRunner.onResolve`
- `linker.Linker.link__anon_39823`
- `comptime_string_map.ComptimeStringMapWithKeyType`
- `string.String.eqlComptime__anon_1315335`
- `JSC::JSValue Bun::fetchCommonJSModuleNonBuiltin<false>`
- `Bun::formatStackTrace`

Features: tsconfig, bunfig, jsc

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Adds missing exception checks to onLoad & onResolve plugin handling code. Also adds missing exception checks to JS builtin errors (useful for debug). 

Fixes #16671
Fixes #2200 

Potentially breaking change: using getOwnPropertyNames instead of getPropertyNames for builtin exports objects. This should be fine, but we will see if CI disagrees.

### How did you verify your code works?

There is a test.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 1:28 PM PT - Apr 23rd, 2025</sup></div>

@Jarred-Sumner, your commit dfa8a324bcbb4611f78a402da6bd32c8dfd3f181 is building: [`#15373`](https://buildkite.com/bun/bun/builds/15373)

File: src/bun.js/bindings/JSGlobalObject.zig [hunk 1]
```diff
@@ -230,20 +230,28 @@ pub const JSGlobalObject = opaque {
     extern fn Bun__runOnLoadPlugins(*JSC.JSGlobalObject, ?*const bun.String, *const bun.String, BunPluginTarget) JSValue;
     extern fn Bun__runOnResolvePlugins(*JSC.JSGlobalObject, ?*const bun.String, *const bun.String, *const String, BunPluginTarget) JSValue;
 
-    pub fn runOnLoadPlugins(this: *JSGlobalObject, namespace_: bun.String, path: bun.String, target: BunPluginTarget) ?JSValue {
+    pub fn runOnLoadPlugins(this: *JSGlobalObject, namespace_: bun.String, path: bun.String, target: BunPluginTarget) !?JSValue {
```
Comment (dylan-conway) [inline src/bun.js/bindings/JSGlobalObject.zig]:
```suggestion
    pub fn runOnLoadPlugins(this: *JSGlobalObject, namespace_: bun.String, path: bun.String, target: BunPluginTarget) bun.JSError!?JSValue {
```

File: src/bun.js/bindings/JSGlobalObject.zig [hunk 2]
```diff
@@ -230,20 +230,28 @@ pub const JSGlobalObject = opaque {
...
+        }
         if (result.isEmptyOrUndefinedOrNull()) {
             return null;
         }
 
         return result;
     }
 
-    pub fn runOnResolvePlugins(this: *JSGlobalObject, namespace_: bun.String, path: bun.String, source: bun.String, target: BunPluginTarget) ?JSValue {
+    pub fn runOnResolvePlugins(this: *JSGlobalObject, namespace_: bun.String, path: bun.String, source: bun.String, target: BunPluginTarget) !?JSValue {
```
Comment (dylan-conway) [inline src/bun.js/bindings/JSGlobalObject.zig]:
```suggestion
    pub fn runOnResolvePlugins(this: *JSGlobalObject, namespace_: bun.String, path: bun.String, source: bun.String, target: BunPluginTarget) bun.JSError!?JSValue {
```

**Review by dylan-conway — APPROVED** [review]
