### PR TITLE
fix findBestMatch so it finds the best match and not the first match

### LINKED ISSUE #3873: Installing deps with range ^ doesn't pick the latest available version
### What version of Bun is running?

v0.6.15 (17903570)

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Create a package with a `package.json` like:

```
{
  "name": "my-package",
  "dependencies": {
    "minimatch": "^3.0.4"
  }
}
```

Then run `bun install`

### What is the expected behavior?

I'd expect to have `minimatch@3.1.2` as a dependency, as it is the highest available version that matches the range `^3.0.4`, as shown by `npm info minimatch versions`:

image

### What do you see instead?

`minimatch@3.0.8` is installed, as shown by `bun pm ls --all`:

image

### Additional information

Checking the ranges and versions in https://semver.npmjs.com/ for `minimatch` and `^3.0.4`, I saw `3.0.8` is listed _after_ `3.1.2`:

image

Looks like it was released later too:

image

No idea if this is related or is a red herring

### LINKED ISSUE #5504: bun install with no bun.lockb should assume --latest
### What is the problem this feature would solve?

People like @SindreSorhus are [updating their modules to support Bun](https://github.com/sindresorhus/callsites/releases/tag/v4.1.0), however bun's default behavior of not downloading the latest semver compatible version means developers are getting a poor first-time experience as their code fails because of outdated dependencies or dependencies-of-dependencies.

Because of bugs like https://github.com/oven-sh/bun/issues/5413, we need to delete the `bun.lockb` frequently, and if we forgot to `--latest`, it means we're chasing bugs that have already been fixed.

### What is the feature you are proposing to solve the problem?

I understand not wanting `--latest` for installs when there is a lockfile, that would defeat the purpose of the lockfile.

But when there is no lockfile, then default to `--latest`.

### What alternatives have you considered?

Alias `bi` to `bun install --latest`.

### LINKED ISSUE #5506: bun install --latest  is not installing the latest
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

`parse-json@5.2.0` has [a dependency on lines-and-columns `^1.1.6`](https://github.com/sindresorhus/parse-json/blob/b778e2eb368a0b935e0a999f6366e9edd95e4dc7/package.json#L38)

Install with no lock file or cache. 

```sh
bun pm cache rm && rm -rf bun.lockb yarn.lock node_modules && bun install --latest
```

### What is the expected behavior?

Bun installs the latest compatible version to `^1.1.6`, which is `lines-and-columns@1.2.4`.

### What do you see instead?

Bun installs `lines-and-columns@1.2.0`, which happens to be a broken version. 

This happens every time in our monorepo, but not standalone.

The package that leads to this is [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/package.json), but installing it in other monorepos doesn't cause this problem. There are no packages that depend on `lines-and-columns@1.2.0`, as you can see in the yarn.lock output.

### Additional information

From the yarn.lock, these are the only entries for both modules. 

This is AFTER the install runs with no lock file and no cache.

```
lines-and-columns@^1.1.6:
  version "1.2.0"
  resolved "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.2.0.tgz"
  integrity sha512-.....
```
....
```
parse-json@^5.0.0, parse-json@^5.2.0:
  version "5.2.0"
  resolved "https://artifactory.company.com/api/npm/virtual-npm/parse-json/-/parse-json-5.2.0.tgz"
  integrity sha512-....
  dependencies:
    "@babel/code-frame" "^7.0.0"
    error-ex "^1.3.1"
    json-parse-even-better-errors "^2.3.0"
    lines-and-columns "^1.1.6"
```

yarn is using the same registry and creditials as bun.

```
yarn info lines-and-columns
yarn info v1.22.19
{
  name: 'lines-and-columns',
  description: 'Maps lines and columns to character offsets and back.',
  'dist-tags': {
    v11x: '1.1.11',
    v12x: '1.2.4',
    latest: '2.0.3'
  },
  versions: [
    '1.0.0',
    '1.0.1',
    '1.0.2',
    '1.1.0',
    '1.1.1',
    '1.1.2',
    '1.1.3',
    '1.1.4',
    '1.1.5',
    '1.1.6',
    '1.1.7',
    '1.1.8',
    '1.1.9',
    '1.1.10',
    '1.1.11',
    '1.2.0',  // <-- Why is this version being installed?
    '1.2.1',
    '1.2.2',
    '1.2.3',
    '1.2.4',  // <-- Instead of this version?
    '2.0.0',
    '2.0.1',
    '2.0.2',
    '2.0.3'
  ],
  maintainers: [
    {
      name: 'eventualbuddha',
      email: 'brian@donovans.cc'
    }
  ],
  author: {
    name: 'Brian Donovan',
    email: 'brian@donovans.cc'
  },
  time: {
    modified: '2022-06-19T12:31:51.246Z',
    '2.0.0': '2021-11-20T22:27:07.947Z',
    '2.0.1': '2021-11-20T22:42:19.703Z',
    '1.1.10': '2021-11-21T00:32:46.542Z',
    created: '2015-12-02T19:57:59.708Z',
    '1.1.11': '2021-11-21T03:30:36.129Z',
    '2.0.2': '2021-11-20T23:28:46.961Z',
    '2.0.3': '2021-11-23T03:15:17.010Z',
    '1.1.2': '2016-06-24T03:36:31.344Z',
    '1.2.1': '2021-11-20T23:17:19.625Z',
    '1.1.3': '2016-06-24T03:52:38.515Z',
    '1.2.2': '2021-11-21T00:28:55.542Z',
    '1.1.4': '2016-06-26T16:57:46.382Z',
    '1.2.3': '2021-11-21T00:30:55.831Z',
    '1.1.5': '2016-06-26T21:54:01.493Z',
    '1.2.4': '2021-11-21T03:31:07.871Z',  // <-- Instead of this version?
    '1.1.6': '2016-12-20T17:32:14.921Z',
    '1.1.7': '2021-11-20T22:15:14.474Z',
    '1.1.8': '2021-11-20T23:09:10.780Z',
    '1.1.9': '2021-11-20T23:15:03.350Z',
    '1.0.0': '2015-12-02T19:57:59.708Z',
    '1.0.1': '2015-12-02T20:00:17.654Z',
    '1.1.0': '2016-03-09T01:49:47.038Z',
    '1.0.2': '2015-12-05T19:32:05.157Z',
    '1.1.1': '2016-03-09T01:56:07.519Z',
    '1.2.0': '2021-11-20T22:23:35.670Z'.  // <-- Why is this version being installed?
  },
  repository: {
````

### LINKED ISSUE #5914: Sometimes not installing latest semver-compat version
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a (and 1.0.0, 1.0.1, 1.0.2)

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

```toml
[install.lockfile]
print = "yarn"
```

```sh
$ bun pm cache rm
$ rm -rf bun.lockb yarn.lock node_modules
$ bun install --verbose --latest
```

This is happening in a monorepo with many dependencies on different versions of `parse-json`, which depends on `lines-and-columns@^1.1.6`.

<details>
<summary>some of the dependencies that use `parse-json`</summary>

```
   read-pkg-up
   load-json-file
   lerna
   jest
   react-dev-utils
   @lerna/command
   read-pkg
   read-pkg-up
   conventional-changelog
```
</details>

### What is the expected behavior?

The newest version compatible with `^1.1.6` is installed, which is `1.2.4`.

### What do you see instead?

* `1.2.0` is installed.
* This is not the latest semver-compatible version.
* This version is not requested by any other modules.
* This version is not the cache.
* This version is marked as `deprecated` (displaying deprecation notices is a separate discussion).

```
Request: GET /api/npm/virtual-npm/lines-and-columns
	Authorization: Basic xxxxxxxxxxxxxxxxxxx==
	npm-auth-type: legacy
	Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
	Connection: keep-alive
	User-Agent: Bun/1.0.3
	Host: artifactory.company.com
	Accept-Encoding: gzip, deflate
```

(log cut)

```
>    - "lines-and-columns": "^1.1.6" - lines-and-columns@1.2.0
```

### Additional information

<details>
<summary>Bun's request as a curl command</summary>

```sh
curl -X GET \
  https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns \
  -H 'Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxx==' \
  -H 'npm-auth-type: legacy' \
  -H 'Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*' \
  -H 'Connection: keep-alive' \
  -H 'User-Agent: Bun/1.0.3' \
  -H 'Host: artifactory.company.com'
```
</details>

<details>
<summary>JSON Result from Curl</summary>

This is coming from Artifactory. I don't see any problems with the data, and it works fine in `yarn@v1` and `pnpm`.

```json
{
  "name" : "lines-and-columns",
  "dist-tags" : {
    "v11x" : "1.1.11",
    "v12x" : "1.2.4",
    "latest" : "2.0.3"
  },
  "versions" : {
    "2.0.0" : {
      "name" : "lines-and-columns",
      "version" : "2.0.0",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-2.0.0.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "deprecated" : "please 2.0.1 or later",
      "_hasShrinkwrap" : false
    },
    "2.0.1" : {
      "name" : "lines-and-columns",
      "version" : "2.0.1",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-2.0.1.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "_hasShrinkwrap" : false
    },
    "1.1.10" : {
      "name" : "lines-and-columns",
      "version" : "1.1.10",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.10.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cu=="
      },
      "_hasShrinkwrap" : false
    },
    "1.1.11" : {
      "name" : "lines-and-columns",
      "version" : "1.1.11",
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.11.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "_hasShrinkwrap" : false
    },
    "2.0.2" : {
      "name" : "lines-and-columns",
      "version" : "2.0.2",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-2.0.2.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "_hasShrinkwrap" : false
    },
    "2.0.3" : {
      "name" : "lines-and-columns",
      "version" : "2.0.3",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-2.0.3.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "_hasShrinkwrap" : false
    },
    "1.1.2" : {
      "name" : "lines-and-columns",
      "version" : "1.1.2",
      "devDependencies" : {
        "babel" : "^6.5.2",
        "babel-plugin-syntax-class-properties" : "^6.8.0",
        "babel-plugin-transform-class-properties" : "^6.10.2",
        "babel-plugin-transform-es2015-block-scoping" : "^6.10.1",
        "babel-plugin-transform-es2015-classes" : "^6.9.0",
        "babel-plugin-transform-es2015-destructuring" : "^6.9.0",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.10.3",
        "babel-plugin-transform-es2015-shorthand-properties" : "^6.8.0",
        "babel-plugin-transform-flow-strip-types" : "^6.8.0",
        "babel-plugin-transform-strict-mode" : "^6.8.0",
        "cz-conventional-changelog" : "^1.1.6",
        "flow-bin" : "^0.27.0",
        "mocha" : "^2.5.3",
        "rollup" : "^0.33.0",
        "rollup-plugin-babel" : "^2.6.1",
        "semantic-release" : "^4.3.5"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.2.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.2.1" : {
      "name" : "lines-and-columns",
      "version" : "1.2.1",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.2.1.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "deprecated" : "use 1.2.3 or later",
      "_hasShrinkwrap" : false
    },
    "1.1.3" : {
      "name" : "lines-and-columns",
      "version" : "1.1.3",
      "devDependencies" : {
        "babel" : "^6.5.2",
        "babel-plugin-syntax-class-properties" : "^6.8.0",
        "babel-plugin-transform-class-properties" : "^6.10.2",
        "babel-plugin-transform-es2015-block-scoping" : "^6.10.1",
        "babel-plugin-transform-es2015-classes" : "^6.9.0",
        "babel-plugin-transform-es2015-destructuring" : "^6.9.0",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.10.3",
        "babel-plugin-transform-es2015-shorthand-properties" : "^6.8.0",
        "babel-plugin-transform-flow-strip-types" : "^6.8.0",
        "babel-plugin-transform-strict-mode" : "^6.8.0",
        "cz-conventional-changelog" : "^1.1.6",
        "flow-bin" : "^0.27.0",
        "mocha" : "^2.5.3",
        "rollup" : "^0.33.0",
        "rollup-plugin-babel" : "^2.6.1",
        "semantic-release" : "^4.3.5"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.3.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.2.2" : {
      "name" : "lines-and-columns",
      "version" : "1.2.2",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.2.2.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "deprecated" : "use 1.2.3 or later",
      "_hasShrinkwrap" : false
    },
    "1.1.4" : {
      "name" : "lines-and-columns",
      "version" : "1.1.4",
      "devDependencies" : {
        "babel" : "^6.5.2",
        "babel-plugin-syntax-class-properties" : "^6.8.0",
        "babel-plugin-transform-class-properties" : "^6.10.2",
        "babel-plugin-transform-es2015-block-scoping" : "^6.10.1",
        "babel-plugin-transform-es2015-classes" : "^6.9.0",
        "babel-plugin-transform-es2015-destructuring" : "^6.9.0",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.10.3",
        "babel-plugin-transform-es2015-shorthand-properties" : "^6.8.0",
        "babel-plugin-transform-flow-strip-types" : "^6.8.0",
        "babel-plugin-transform-strict-mode" : "^6.8.0",
        "cz-conventional-changelog" : "^1.1.6",
        "flow-bin" : "^0.27.0",
        "mocha" : "^2.5.3",
        "rollup" : "^0.33.0",
        "rollup-plugin-babel" : "^2.6.1",
        "semantic-release" : "^4.3.5"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.4.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.2.3" : {
      "name" : "lines-and-columns",
      "version" : "1.2.3",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.2.3.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "_hasShrinkwrap" : false
    },
    "1.1.5" : {
      "name" : "lines-and-columns",
      "version" : "1.1.5",
      "devDependencies" : {
        "babel" : "^6.5.2",
        "babel-plugin-syntax-class-properties" : "^6.8.0",
        "babel-plugin-transform-class-properties" : "^6.10.2",
        "babel-plugin-transform-es2015-block-scoping" : "^6.10.1",
        "babel-plugin-transform-es2015-classes" : "^6.9.0",
        "babel-plugin-transform-es2015-destructuring" : "^6.9.0",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.10.3",
        "babel-plugin-transform-es2015-shorthand-properties" : "^6.8.0",
        "babel-plugin-transform-flow-strip-types" : "^6.8.0",
        "babel-plugin-transform-strict-mode" : "^6.8.0",
        "cz-conventional-changelog" : "^1.1.6",
        "flow-bin" : "^0.27.0",
        "mocha" : "^2.5.3",
        "rollup" : "^0.33.0",
        "rollup-plugin-babel" : "^2.6.1",
        "semantic-release" : "^4.3.5"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.5.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.2.4" : {
      "name" : "lines-and-columns",
      "version" : "1.2.4",
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.2.4.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "_hasShrinkwrap" : false
    },
    "1.1.6" : {
      "name" : "lines-and-columns",
      "version" : "1.1.6",
      "devDependencies" : {
        "@types/mocha" : "^2.2.34",
        "@types/node" : "^6.0.52",
        "mocha" : "^3.2.0",
        "semantic-release" : "^6.3.2",
        "ts-node" : "^1.7.2",
        "tslint" : "^4.1.1",
        "typescript" : "^2.1.4"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.6.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.1.7" : {
      "name" : "lines-and-columns",
      "version" : "1.1.7",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.7.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "deprecated" : "please use 1.1.8 or 2.0.1 or later",
      "_hasShrinkwrap" : false
    },
    "1.1.8" : {
      "name" : "lines-and-columns",
      "version" : "1.1.8",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.8.tgz",
        "shasum" : "bcc1795411871b77192d8235a37b37f0c077f279",
        "integrity" : "sha512-cut=="
      },
      "deprecated" : "use 1.1.10 or later",
      "_hasShrinkwrap" : false
    },
    "1.1.9" : {
      "name" : "lines-and-columns",
      "version" : "1.1.9",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.9.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "deprecated" : "use 1.1.10 or later",
      "_hasShrinkwrap" : false
    },
    "1.0.0" : {
      "name" : "lines-and-columns",
      "version" : "1.0.0",
      "engines" : {
        "node" : ">=4.0.0"
      },
      "devDependencies" : {
        "babel" : "^6.1.18",
        "babel-plugin-transform-es2015-destructuring" : "^6.1.18",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.2.0",
        "babel-plugin-transform-flow-strip-types" : "^6.1.18",
        "babel-plugin-transform-strict-mode" : "^6.2.0",
        "mocha" : "^2.3.4",
        "rollup" : "^0.21.0",
        "rollup-plugin-babel" : "^2.1.0"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.0.0.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.0.1" : {
      "name" : "lines-and-columns",
      "version" : "1.0.1",
      "engines" : {
        "node" : ">=4.0.0"
      },
      "devDependencies" : {
        "babel" : "^6.1.18",
        "babel-plugin-transform-es2015-destructuring" : "^6.1.18",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.2.0",
        "babel-plugin-transform-flow-strip-types" : "^6.1.18",
        "babel-plugin-transform-strict-mode" : "^6.2.0",
        "mocha" : "^2.3.4",
        "rollup" : "^0.21.0",
        "rollup-plugin-babel" : "^2.1.0"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.0.1.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.1.0" : {
      "name" : "lines-and-columns",
      "version" : "1.1.0",
      "devDependencies" : {
        "babel" : "^6.5.2",
        "babel-plugin-syntax-class-properties" : "^6.5.0",
        "babel-plugin-transform-class-properties" : "^6.6.0",
        "babel-plugin-transform-es2015-block-scoping" : "^6.7.0",
        "babel-plugin-transform-es2015-classes" : "^6.6.5",
        "babel-plugin-transform-es2015-destructuring" : "^6.6.5",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.7.0",
        "babel-plugin-transform-es2015-shorthand-properties" : "^6.5.0",
        "babel-plugin-transform-flow-strip-types" : "^6.7.0",
        "babel-plugin-transform-strict-mode" : "^6.6.5",
        "mocha" : "^2.4.5",
        "rollup" : "^0.25.4",
        "rollup-plugin-babel" : "^2.4.0"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.0.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.0.2" : {
      "name" : "lines-and-columns",
      "version" : "1.0.2",
      "engines" : {
        "node" : ">=4.0.0"
      },
      "devDependencies" : {
        "babel" : "^6.1.18",
        "babel-plugin-transform-es2015-destructuring" : "^6.1.18",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.2.0",
        "babel-plugin-transform-flow-strip-types" : "^6.1.18",
        "babel-plugin-transform-strict-mode" : "^6.2.0",
        "mocha" : "^2.3.4",
        "rollup" : "^0.21.0",
        "rollup-plugin-babel" : "^2.1.0"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.0.2.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.1.1" : {
      "name" : "lines-and-columns",
      "version" : "1.1.1",
      "devDependencies" : {
        "babel" : "^6.5.2",
        "babel-plugin-syntax-class-properties" : "^6.5.0",
        "babel-plugin-transform-class-properties" : "^6.6.0",
        "babel-plugin-transform-es2015-block-scoping" : "^6.7.0",
        "babel-plugin-transform-es2015-classes" : "^6.6.5",
        "babel-plugin-transform-es2015-destructuring" : "^6.6.5",
        "babel-plugin-transform-es2015-modules-commonjs" : "^6.7.0",
        "babel-plugin-transform-es2015-shorthand-properties" : "^6.5.0",
        "babel-plugin-transform-flow-strip-types" : "^6.7.0",
        "babel-plugin-transform-strict-mode" : "^6.6.5",
        "mocha" : "^2.4.5",
        "rollup" : "^0.25.4",
        "rollup-plugin-babel" : "^2.4.0"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.1.1.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      }
    },
    "1.2.0" : {
      "name" : "lines-and-columns",
      "version" : "1.2.0",
      "engines" : {
        "node" : "^12.20.0 || ^14.13.1 || >=16.0.0"
      },
      "devDependencies" : {
        "@types/jest" : "^27.0.3",
        "@types/node" : "^16.11.9",
        "@typescript-eslint/eslint-plugin" : "^5.4.0",
        "@typescript-eslint/parser" : "^5.4.0",
        "esbuild" : "^0.13.15",
        "esbuild-runner" : "^2.2.1",
        "eslint" : "^8.2.0",
        "eslint-config-prettier" : "^8.3.0",
        "eslint-plugin-prettier" : "^4.0.0",
        "is-ci-cli" : "^2.2.0",
        "jest" : "^27.3.1",
        "prettier" : "^2.4.1",
        "semantic-release" : "^18.0.0",
        "typescript" : "^4.5.2"
      },
      "directories" : { },
      "dist" : {
        "tarball" : "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.2.0.tgz",
        "shasum" : "cut",
        "integrity" : "sha512-cut=="
      },
      "deprecated" : "please use 1.2.1 or later",
      "_hasShrinkwrap" : false
    }
  }
}
```
</details>

<details>
<summary>bun's generated yarn.lock only has one entry for lines-and-columns</summary>

```yaml
limiter@^1.0.5:
  version "1.1.1"
  resolved "https://artifactory.company.com/api/npm/virtual-npm/limiter/-/limiter-1.1.1.tgz"
  integrity sha512-cut==

lines-and-columns@^1.1.6:
  version "1.2.0"
  resolved "https://artifactory.company.com/api/npm/virtual-npm/lines-and-columns/-/lines-and-columns-1.2.0.tgz"
  integrity sha512-cut==

linkify-urls@^4.1.0:
  version "4.1.0"
  resolved "https://artifactory.company.com/api/npm/virtual-npm/linkify-urls/-/linkify-urls-4.1.0.tgz"
  integrity sha512-cut==
  dependencies:
    create-html-element "^4.0.1"

```

</details>

<details>
<summary>yarn why lines-and-columns in same monorepo installed with yarn v1</summary>

```sh
yarn why lines-and-columns
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "lines-and-columns"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "lines-and-columns@1.2.4"
info Reasons this module exists
   - "_project_#parse-json" depends on it
   - Hoisted from "_project_#parse-json#lines-and-columns"
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "24KB"
info Disk size with transitive dependencies: "24KB"
info Number of shared dependencies: 0
=> Found "nx#lines-and-columns@2.0.3"
info This module exists because "_project_#lerna#nx" depends on it.
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "28KB"
info Disk size with transitive dependencies: "28KB"
info Number of shared dependencies: 0
```
</details>

### PR DESCRIPTION
**Pull request by dylang**
### What does this PR do?

Fixes `findBestMatch`.

### Bug Explained

`findBestMatch` was picking the *first* version that satisfies semver range, but registries don't return versions in any particular order. 

This was easily repeatable with `lines-and-columns@^1.1.6`, it would always pick the first version `1.2.0`, which happens to be deprecated and broken, instead of the _best_ match, which is `1.2.4`.

This PR should help with a bunch of install-related bugs:
* fixes #5914
* fixes #5506
* fixes #5504
* fixes #3873
* fixes #6489
* And probably others...

- [X] Code changes

### How did you verify your code works?

- This includes a test that was failing before this PR was added: #6489

### This modifies zig code

- [ ] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [X] I or my editor ran `zig fmt` on the changed files
- [X] I included a test for the new code, or an existing test covers it

### First time Zig user

I've contributed to Bun before, but this is my first time contributing to the zig code. I installed Zig and its dependencies this morning. I'm happy to accept input to improve this PR!

### CODE REVIEW

File: src/install/npm.zig [hunk 1]
```diff
@@ -824,15 +824,24 @@ pub const PackageManifest = struct {
...
             // For now, this is the dumb way
             while (i > 0) : (i -= 1) {
                 const version = releases[i - 1];
-                const packages = this.pkg.releases.values.get(this.package_versions);
 
-                if (group.satisfies(version)) {
-                    return .{ .version = version, .package = &packages[i - 1] };
+                // If we find one that matches, save it, but keep looping because we might find a newer match.
+                // The versions from the registry are not in any particular order.
+                if (group.satisfies(version) and (bestMatchVersion == null or Semver.Version.gt(version, bestMatchVersion.?))) {
```
Comment (Jarred-Sumner) [inline src/install/npm.zig]: Can this use `version.order` instead of `.gt`? Something like this (but not 100% right)
```suggestion
                if (group.satisfies(version) and (bestMatchVersion == null or (version.order(best_match_version.?, string_bytes, string_bytes) == .gt)) ) {
```

Or alternatively, `gt` could be something like
```zig
pub fn gt(this: Version, rhs: Version, lhs_bytes: []const u8, rhs_bytes: []const u8) bool {
  return this.order(rhs, lhs_bytes, rhs_bytes) == .gt;
}
```

File: src/install/npm.zig [hunk 2]
```diff
@@ -824,15 +824,24 @@ pub const PackageManifest = struct {
...
+                    bestMatchVersion = version;
+                    bestMatchPackage = this.pkg.releases.values.get(this.package_versions)[i - 1];
                 }
             }
+
+            if (bestMatchVersion != null and bestMatchPackage != null) {
+                return .{ .version = bestMatchVersion.?, .package = &bestMatchPackage.? };
```
Comment (Jarred-Sumner) [inline src/install/npm.zig]: `&bestMatchPackage.?` is a pointer to stack memory, which is invalid and will eventually cause a segfault. This is a very common mistake to make for people new to Zig (and something Zig should make easier, IMO)

Related to:
- https://github.com/ziglang/zig/issues/5725 
- https://github.com/ziglang/zig/issues/2646 
- https://github.com/ziglang/zig/issues/2301

File: src/install/npm.zig (hunk 1 above)
Comment (dylang) [reply src/install/npm.zig]: Thanks for the quick review @Jarred-Sumner!

I started with `version.order` but my bun-foo was lacking for how to use it. I'll give it another try.

File: src/install/npm.zig [hunk 3]
```diff
@@ -824,15 +824,24 @@ pub const PackageManifest = struct {
         {
             const releases = this.pkg.releases.keys.get(this.versions);
             var i = releases.len;
+
+            var bestMatchVersion: ?Semver.Version = null;
```
Comment (Jarred-Sumner) [inline src/install/npm.zig]: In Zig, the convention is to use snake_case for variable names, PascalCase for type names, and camelCase for function names.

We don't strictly adhere to this, and ultimately this kind of code style critique should really be handled by a linter and not humans (both fixing and flagging). Feel free to change it but no worries if you don't want to

```suggestion
            var best_match_version: ?Semver.Version = null;
```

File: src/install/npm.zig (hunk 2 above)
Comment (dylang) [reply src/install/npm.zig]: That makes sense, but does that mean the existing code is broken too?

> return .{ .version = version, .package = &packages[i - 1] };

* https://github.com/oven-sh/bun/blob/main/src/install/npm.zig#L833
* https://github.com/oven-sh/bun/blob/main/src/install/npm.zig#L846

Comment (Jarred-Sumner) [reply src/install/npm.zig]: Those pointers are not allocated on the stack, they are allocated on the heap. Their lifetime is tied to the lifetime of the `packages` array, which is longer than the current stack (the function call)

Comment (Jarred-Sumner) [reply src/install/npm.zig]: This for example is valid:
```zig
var packages = try bun.default_allocator.alloc(u32, 100);
return &packages[1];
```

This is invalid:
```zig
var packages = [_]u32{0} ** 100;
return &packages[1];
```

Comment (dylang) [reply src/install/npm.zig]: ooooh, the problem isn't the pointer, it's the local variable!

Sorry, I haven't used pointers since college in the late 90's!

File: src/install/npm.zig [hunk 4]
```diff
@@ -824,15 +824,26 @@ pub const PackageManifest = struct {
         {
             const releases = this.pkg.releases.keys.get(this.versions);
             var i = releases.len;
+
+            var best_match_version: ?Semver.Version = null;
+            var best_match_package: ?PackageVersion = null;
```
Comment (Jarred-Sumner) [inline src/install/npm.zig]:
```suggestion
            var best_match_package: ?*PackageVersion = null;
```

File: src/install/npm.zig [hunk 5]
```diff
@@ -824,15 +824,26 @@ pub const PackageManifest = struct {
...
 
-                if (group.satisfies(version)) {
-                    return .{ .version = version, .package = &packages[i - 1] };
+                // If we find one that matches, save it, but keep looping because we might find a newer match.
+                // The versions from the registry are not in any particular order.
+                if (group.satisfies(version) and (best_match_version == null or
+                    (Semver.Version.order(version, best_match_version.?, "", "") == .gt)))
+                {
+                    best_match_version = version;
+                    best_match_package = this.pkg.releases.values.get(this.package_versions)[i - 1];
```
Comment (Jarred-Sumner) [inline src/install/npm.zig]:
```suggestion
                    best_match_package = &this.pkg.releases.values.get(this.package_versions)[i - 1];
```

File: src/install/npm.zig [hunk 6]
```diff
@@ -824,15 +824,26 @@ pub const PackageManifest = struct {
...
                 }
             }
+
+            if (best_match_version != null and best_match_package != null) {
+                return .{ .version = best_match_version.?, .package = &best_match_package.? };
```
Comment (Jarred-Sumner) [inline src/install/npm.zig]:
```suggestion
                return .{ .version = best_match_version.?, .package = best_match_package };
```

File: src/install/npm.zig (hunk 3 above)
Comment (dylang) [reply src/install/npm.zig]: Funny, I changed it before I saw this comment as I saw your example to me used snake case!

**Comment by dylang** [comment]
Thanks again for the review @Jarred-Sumner. I've made the changes requested. It's a lot cleaner now thanks to your feedback, and I understand even more!

File: src/install/npm.zig [hunk 7]
```diff
@@ -823,16 +823,26 @@ pub const PackageManifest = struct {
...
             // For now, this is the dumb way
             while (i > 0) : (i -= 1) {
                 const version = releases[i - 1];
-                const packages = this.pkg.releases.values.get(this.package_versions);
 
-                if (group.satisfies(version)) {
-                    return .{ .version = version, .package = &packages[i - 1] };
+                // If we find one that matches, save it, but keep looping because we might find a newer match.
+                // The versions from the registry are not in any particular order.
+                if (group.satisfies(version) and (best_match_version == null or Semver.Version.order(version, best_match_version.?, "", "") == .gt)) {
```
Comment (Jarred-Sumner) [inline src/install/npm.zig:836]: Do we need to account for pre/post tags? Usually the way we do this is to get the string buffer from `lockfile.buffers.string_bytes.items` and pass that to the parent function
 
```suggestion
                if (group.satisfies(version) and (best_match_version == null or Semver.Version.order(version, best_match_version.?, string_bytes, string_bytes) == .gt)) {
```

**Comment by Jarred-Sumner** [comment]
I have some changes I'd like to make to this PR but it's a great start so I'm going to go ahead and merge it and then apply my changes afterwards. Thank you.
