### PR TITLE
fix(bun-test): test title in results

### LINKED ISSUE #1533: Test title only shows the last `describe` block
When the following code is run:

```js
import { expect, describe, test } from "bun:test";

describe("1", () => {
  describe("2", () => {
    describe("3", () => {
      test("4", () => {
        expect(1).toBe(1);
      });
    });
  });
});
```

It outputs:

```
✓ 3 > 4

 1 pass
 0 fail
 1 expect() calls
 Ran 1 tests across 1 files [211.00ms]
```

However the title should be:

```
✓ 1 > 2 > 3 > 4
```

### PR DESCRIPTION
**Pull request by ethanburrell**
This PR fixes #1533.

Instead of printing just the test name in a test success or failure, bun-test will now print the full path of scopes for the test.

Previously:
```
✓ inner most describe 1 > first
```

Now:
```
✓ outer most describe > mid describe 1 > inner most describe 1 > first
```

### CODE REVIEW

File: src/bun.js/test/jest.zig [hunk 1]
```diff
@@ -1549,7 +1549,7 @@ pub const DescribeScope = struct {
         var scope = allocator.create(DescribeScope) catch unreachable;
         scope.* = .{
             .label = (label.toSlice(allocator).cloneIfNeeded(allocator) catch unreachable).slice(),
-            .parent = this,
+            .parent = active,
```
Comment (Jarred-Sumner) [inline src/bun.js/test/jest.zig]: i think this needs to be `active orelse this`

**Comment by Jarred-Sumner** [comment]
Thank you
