### PR TITLE
`bun audit` add more filtering options

### LINKED ISSUE #21813: Implement level and ignore options for bun audit
### What is the problem this feature would solve?

Currently, `bun audit` fails if it discovers any vulnerability. This makes audit difficult to use, because even low level vulnerabilities make a non-zero exit. There are reasons to allow them (dev only packages that won't be shipped to prod, packages with not known fixes, or vulnerabilities that are not applicable to your use case), but we currently don't have any control over what is acceptable for each use case.

This is an important feature in many regulated companies (for example, in the fintech space in which I'm active on) and a requirement for many regulators. While it is true that vulnerability scan can happen after (for example, with Github Security Scan in search of CVE), having a proactive instance of searching for CVEs on PR is considered a good practice.

### What is the feature you are proposing to solve the problem?

I propose something similar to [PNPM](https://pnpm.io/cli/audit):
- `--audit-level <severity>` flag: Only print (and consequently, fails with) advisories with severity greater than or equal to <severity>. We can default to `low`, same as PNPM, to maintain the current behaviour.
- Add an "ignoreList" property to bunfig.toml (or package.json, same `trustedDependencies`), specifying package name and (optionally) version of said package, to ignore from the audit.
- `--prod` flag: Only consider prod dependencies.

### What alternatives have you considered?

None

### PR DESCRIPTION
**Pull request by RiskyMH**
### What does this PR do?

fixes #21813

`--audit-level=high`,  `--prod` and `--ignore=cve` filters

### How did you verify your code works?

tests

### CODE REVIEW

File: src/cli/audit_command.zig [hunk 1]
```diff
@@ -188,7 +188,56 @@ fn buildDependencyTree(allocator: std.mem.Allocator, pm: *PackageManager) bun.OO
...
+    const packages = pm.lockfile.packages.slice();
+    const pkg_names = packages.items(.name);
+    const pkg_dependencies = packages.items(.dependencies);
+    const pkg_resolutions = packages.items(.resolutions);
+    const buf = pm.lockfile.buffers.string_bytes.items;
+    const dependencies = pm.lockfile.buffers.dependencies.items;
+    const resolutions = pm.lockfile.buffers.resolutions.items;
+    const root_id = pm.root_package_id.get(pm.lockfile, pm.workspace_name_hash);
+
+    var queue = std.ArrayList(u32).init(allocator);
```
Comment (Jarred-Sumner) [inline src/cli/audit_command.zig:201]: This should use std.fifo.LinearFifo

File: src/install/PackageManager/CommandLineArguments.zig [hunk 2]
```diff
@@ -234,6 +237,30 @@ message: ?string = null,
...
+audit_ignore_list: []const string = &.{},
+
+pub const AuditLevel = enum {
+    low,
+    moderate,
+    high,
+    critical,
+
+    pub fn fromString(str: []const u8) ?AuditLevel {
+        if (bun.strings.eqlComptime(str, "low")) return .low;
```
Comment (Jarred-Sumner) [inline src/install/PackageManager/CommandLineArguments.zig:251]: this shoudl use the map thing

**Comment by Jarred-Sumner** [comment]
This isn't great code, but I think since it's contained to `bun audit` and not a pattern created elsewhere that's okay
