### PR TITLE
fix(env_loader): Ignore spaces before equals sign

### LINKED ISSUE #519: Unable to access env values
I tried to access env keys but returned undefined
Screenshot 2022-07-09 at 23 46 48

OS : MacOS M1
Bun : v0.1.2

### PR DESCRIPTION
**Pull request by FinnRG**
Closes #519. Before this PR, ``.env`` files like ``PORT =8080`` wouldn't get parsed.

### CODE REVIEW

File: src/env_loader.zig [hunk 1]
```diff
@@ -273,6 +273,7 @@ pub const Lexer = struct {
                 'a'...'z', 'A'...'Z', '0'...'9', '_', '-', '.' => {
                     this.start = this.current;
                     this.step();
+                    var key_end: u8 = 0;
```
Comment (Jarred-Sumner) [inline src/env_loader.zig]: this hsould be a `usize` instead of a `u8`, as it could overflow if the file is longer than 255 chars

**Comment by Jarred-Sumner** [comment]
Thank you
