### PR TITLE
fix `--print process.argv <args>`

### LINKED ISSUE #8381: Bun.argv not correct with `bun -e`
### What version of Bun is running?

1.0.25

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

Run with `bun -e 'console.log(Bun.argv)' first second third`, and output as following

```
[ "/Users/xxx/.bun/bin/bun", "/Users/xxx/demo/[eval]",
  "second", "third"
]
```

and `first` param is ignored. 

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### LINKED ISSUE #12209: bun --eval ignores first command line arg
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Linux 5.4.0-186-generic x86_64 x86_64

### What steps can reproduce the bug?

```sh
chris@eggnog:~$ bun -e "console.log(process.argv)" 1 2 3
[ "/home/chris/.bun/bin/bun", "/home/chris/[eval]", "2", "3" ]
chris@eggnog:~$ node -e "console.log(process.argv)" 1 2 3
[ '/home/chris/.nvm/versions/node/v20.14.0/bin/node', '1', '2', '3' ]
chris@eggnog:~$ bun --version
1.1.17
```

### What is the expected behavior?

Should match node and not ignore the first argument.

### What do you see instead?

First argument missing.

### Additional information

Similarly for `bun --print`.

My workaround is to just include a placeholder arg and modify argv:
```sh
chris@eggnog:~$ bun -e "process.argv.splice(1, 1); console.log(process.argv)" skip 1 2 3
[ "/home/chris/.bun/bin/bun", "1", "2", "3" ]
chris@eggnog:~$ node -e "process.argv.splice(1, 1); console.log(process.argv)" skip 1 2 3
[ '/home/chris/.nvm/versions/node/v20.14.0/bin/node', '1', '2', '3' ]
```

### LINKED ISSUE #17236: Create react-app using --bun is broken
### What version of Bun is running?

1.2.0

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

1. Install `bun` globally
2. **Run:** `bun --bun create react-app my-react-app` on terminal
3. Errors and doesn't create anything inside the directory (my-react-app) except `package-lock.json`

### What is the expected behavior?

- Should work, without errors
- Should generate all the necessary files
- Should install all dependencies with its latest stable versions (e.g. react 19) using `bun`

### What do you see instead?

**Currently outputs:**
```shell
Creating a new React app in <pwd>/react-app-19-bun-cli.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

⠏
added 1326 packages in 19s

268 packages are looking for funding
  run `npm fund` for details
1 | 
2 |         const init = require('react-scripts/scripts/init.js');
3 |         init.apply(null, JSON.parse(process.argv[1]));
                                  ^
SyntaxError: JSON Parse error: Unrecognized token '/'
      at <pwd>/react-app-19-bun-cli/[eval]:3:31

Bun v1.2.0 (macOS arm64)

Aborting installation.
  node  has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Done.
``` 

### Additional information

Currently `next-app` is working fine with `bun`. Below is an output from my machine.
```shell
❯ bun --bun create next-app next-app-bun-app-with-bun-cli 
✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like your code inside a `src/` directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to use Turbopack for `next dev`? … No / Yes
✔ Would you like to customize the import alias (`@/*` by default)? … No / Yes
Creating a new Next.js app in <pwd>/next-app-bun-app-with-bun-cli.

Using bun.

Initializing project with template: app-tw 


Installing dependencies:
- react
- react-dom
- next

Installing devDependencies:
- typescript
- @types/node
- @types/react
- @types/react-dom
- postcss
- tailwindcss
- eslint
- eslint-config-next
- @eslint/eslintrc

bun install v1.2.0 (b0c5a765)

+ @eslint/eslintrc@3.2.0
+ @types/node@20.17.17 (v22.13.1 available)
+ @types/react@19.0.8
+ @types/react-dom@19.0.3
+ eslint@9.20.0
+ eslint-config-next@15.1.6
+ postcss@8.5.1
+ tailwindcss@3.4.17 (v4.0.6 available)
+ typescript@5.7.3
+ next@15.1.6
+ react@19.0.0
+ react-dom@19.0.0

360 packages installed [2.52s]
Initialized a git repository.

Success! Created next-app-bun-app-with-bun-cli at <pwd>/next-app-bun-app-with-bun-cli
```

### PR DESCRIPTION
**Pull request by RiskyMH**
### What does this PR do?

2 fixes:
1. include the 1st command name in argv (with `--print`, clap gets confused)
2. if the filename ends in `/[eval]` or `/[stdin]`, then don't include the path in argv, like node

fixes #12209, fixes #8381, fixes #17236

### How did you verify your code works?

manually and made tests

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 9:03 PM PT - Feb 10th, 2025</sup></div>

@RiskyMH, your commit 9e36b1745522bed996038d617dddf958d50b055e is building: [`#11428`](https://buildkite.com/bun/bun/builds/11428)

File: src/js/node/child_process.ts [hunk 1]
```diff
@@ -748,20 +750,19 @@ function fork(modulePath, args = [], options) {
...
+    const index = ArrayPrototypeLastIndexOf.$call(execArgv, process._eval);
+    if (index > 0) {
+      // Remove the -e switch to avoid fork bombing ourselves.
+      execArgv = ArrayPrototypeSlice.$call(execArgv);
+      ArrayPrototypeSplice.$call(execArgv, index - 1, 2);
+    }
+  }
 
-  args = [/*...execArgv,*/ modulePath, ...args];
+  args = [...execArgv, modulePath, ...args];
```
Comment (RiskyMH) [inline src/js/node/child_process.ts]: undoes commenting in #5843

File: test/cli/run/run-eval.test.ts [hunk 2]
```diff
@@ -43,6 +43,25 @@ for (const flag of ["-e", "--print"]) {
...
+
+        expect(stderr.toString("utf8")).toBe("");
+        expect(JSON.parse(stdout.toString("utf8"))).toEqual(expected);
+        expect(exitCode).toBe(0);
+      }
+
+      testProcessArgv([], [bunExe()]);
+      testProcessArgv(["abc", "def"], [bunExe(), "abc", "def"]);
+      testProcessArgv(["--", "abc", "def"], [bunExe(), "abc", "def"]);
+      // testProcessArgv(["--", "abc", "--", "def"], [bunExe(), "abc", "--", "def"]);
```
Comment (RiskyMH) [inline test/cli/run/run-eval.test.ts:63]: not sure why this doesn't work in Bun, but it is valid in node

File: src/js/node/child_process.ts (hunk 1 above)
Comment (RiskyMH) [reply src/js/node/child_process.ts]: decided to leave this for another pr

File: test/cli/run/run-eval.test.ts [hunk 3]
```diff
@@ -43,6 +43,25 @@ for (const flag of ["-e", "--print"]) {
...
+
+        expect(stderr.toString("utf8")).toBe("");
+        expect(JSON.parse(stdout.toString("utf8"))).toEqual(expected);
+        expect(exitCode).toBe(0);
+      }
+
+      testProcessArgv([], [JSON.stringify(bunExe())]);
+      testProcessArgv(["abc", "def"], [JSON.stringify(bunExe()), "abc", "def"]);
+      testProcessArgv(["--", "abc", "def"], [JSON.stringify(bunExe()), "abc", "def"]);
+      // testProcessArgv(["--", "abc", "--", "def"], [JSON.stringify(bunExe()), "abc", "--", "def"]);
```
Comment (RiskyMH) [inline test/cli/run/run-eval.test.ts:63]: not sure why this doesn't work in Bun, but it is valid in node

File: test/cli/run/run-eval.test.ts [hunk 4]
```diff
@@ -43,6 +43,27 @@ for (const flag of ["-e", "--print"]) {
...
+        expect(exitCode).toBe(0);
+      }
+
+      // replace the trailin
+      const exe = isWindows ? bunExe().replace("/", "\\") : bunExe();
+      testProcessArgv([], [exe]);
+      testProcessArgv(["abc", "def"], [exe, "abc", "def"]);
+      testProcessArgv(["--", "abc", "def"], [exe, "abc", "def"]);
+      // testProcessArgv(["--", "abc", "--", "def"], [exe, "abc", "--", "def"]);
+    });
```
Comment (RiskyMH) [inline test/cli/run/run-eval.test.ts]: not sure why this last test doesn't work in Bun, but it is valid in node

**Review by paperclover — APPROVED** [review]
