### PR TITLE
fix(child_process): match Node's promisified exec fn

### LINKED ISSUE #2127: Promisified exec from child_spawn different from Node
### What version of Bun is running?

0.5.6

### What platform is your computer?

docker Linux 6.0.12-76060006-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
import { exec } from "node:child_process";
import { promisify } from "node:util";

const __exec = promisify(exec);

console.log(await __exec("echo hi"));
```

### What is the expected behavior?

```
{ stdout: 'hi\n', stderr: '' }
```

### What do you see instead?

```
hi

```

### Additional information

The bun implementation of `exec` probably doesn't use the `util.promisify.custom` symbol: https://nodejs.org/api/util.html#custom-promisified-functions

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #2127

### CODE REVIEW

File: src/bun.js/child_process.exports.js [hunk 1]
```diff
@@ -6,9 +6,47 @@ const {
 const {
   constants: { signals },
 } = import.meta.require("node:os");
+const { promisify } = import.meta.require("node:util");
 
 const { ArrayBuffer } = import.meta.primordials;
```
Comment (Jarred-Sumner) [inline src/bun.js/child_process.exports.js:11]: each of the below globalThis getters can be from primordials
