### PR TITLE
Bundler changes to bring us closer to esbuild's api

### LINKED ISSUE #9862: Runtime plugin `onResolve` behaves incorrectly for asynchronous imports
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

See the reproduction repository: https://github.com/TomasHubelbauer/bun-runtime-plugin-onResolve-sync-async-import

Make a plugin that uses `onResolve` to map non-existent paths to existent paths:

```typescript
import { plugin } from "bun";

await plugin({
  name: "test",
  async setup(build) {
    console.log('Plugin loaded');

    build.onResolve({ filter: /\.demo$/ }, ({ path }) => {
      console.log('onResolve called', path);
      switch (path) {
        case './sync.demo': {
          return { path: './sync.ts' };
        }
        case './async.demo': {
          return { path: './async.ts' };
        }
        default: {
          throw new Error(`Unknown path: ${path}`);
        }
      }
    });
  },
});
```

Register it in `bunfig.toml`:

```toml
preload = ["./plugin.ts"]
```

Come up with a script that has sync and async imports matching the plugin's `onResolve` `filter`:

```typescript
import syncDemo from './sync.demo';

console.log('Sync demo', syncDemo);

try {
  const asyncDemo = await import('./async.demo');
  console.log('Async demo', asyncDemo);
}
catch (error) {
  console.error('Error loading async demo', error);
}
```

Run the script: `bun index.ts`:

```
Plugin loaded
onResolve called ./sync.demo
Sync demo Hello, sync!
onResolve called ./async.demo
Error loading async demo error: ENOENT reading "file:./async.ts"
```

### What is the expected behavior?

The async import should resolve to `./async.ts` (which it seems to be doing) and then the built-in loader for `*.ts` should pick it up as it does with the sync import. The output should be this:

```
Plugin loaded
onResolve called ./sync.demo
Sync demo Hello, sync!
Async demo Module {
  default: "Hello, async!",
}
```

### What do you see instead?

```
Plugin loaded
onResolve called ./sync.demo
Sync demo Hello, sync!
onResolve called ./async.demo
Error loading async demo error: ENOENT reading "file:./async.ts"
```

### Additional information

This seems to be specifically related to async imports.

### LINKED ISSUE #20806: Plugin `bun.build` onResolve/onLoad hooks are not called for entrypoint files (unlike esbuild)
###  What version of Bun is running?
Bun v1.2.18 (and latest canary)

### What platform is your computer?
Windows

###  What steps can reproduce the bug?
Suppose you have the following `build.ts`:

```js
await Bun.build({
    entrypoints: ["index.ts"],
    outdir: "out-bun",
    target: "bun",
    plugins: [pluginA()]
});
```

And a plugin like this (`pluginA`):

```js
{
        name: "pluginA",
        setup(build) {
            build.onResolve({ filter: /\.ts$/ }, async (args) => {
                console.log("pluginA onResolve called for", args.path);
                return { path: args.path, namespace: "pluginA" };
            });

            build.onLoad({ filter: /\.ts$/, namespace: "pluginA" }, async (args) => {
                console.log("pluginA onLoad called for", args.path);
                return { contents: await Bun.file(args.path).text(), loader: "ts" };
            });
}

```

When you run Bun:

```sh
bun build.ts
```

### What is the expected behavior?
You should see both `console.log` statements from the plugin:
- `pluginA onResolve called for ./index.ts`
- `pluginA onLoad called for ./index.ts`

###  What do you see instead?
Nothing is logged. The entrypoint `"index.ts"` is not handled by the plugin's `onResolve` or `onLoad` hooks.

#### Comparison with esbuild

When running the same plugin with esbuild:

```js
esbuild.build({
    entryPoints: ["input.ts"],
    bundle: true,
    outfile: "dist/out.js",
    plugins: [pluginA()]
})
```

You will see both `console.log` outputs as expected for the resolve and load hooks.

- This makes it impossible for plugins to handle entrypoints or perform custom logic for them.
- The behavior differs from esbuild, where entrypoints are always passed through the resolve/load plugin hooks.

imports from the entry point, do go through the plugin hooks

### LINKED ISSUE #22061: Support `onEnd` in our Plugin API

### PR DESCRIPTION
**Pull request by alii**
### What does this PR do?

- Implements .onEnd

Fixes #22061

Once #22144 is merged, this also fixes:
Fixes #9862
Fixes #20806

### How did you verify your code works?

Tests

---

TODO in a followup (#22144)
> ~~Make all entrypoints be called in onResolve~~
> ~~Fixes # 9862~~
> ~~Fixes # 20806~~

### CODE REVIEW

File: src/bun.js/bindings/JSBundlerPlugin.cpp [hunk 1]
```diff
@@ -652,6 +668,36 @@ extern "C" void JSBundlerPlugin__tombstone(Bun::JSBundlerPlugin* plugin)
     plugin->plugin.tombstone();
 }
 
+extern "C" JSC::EncodedJSValue JSBundlerPlugin__runOnEndCallbacks(Bun::JSBundlerPlugin* plugin, JSC::EncodedJSValue encodedBuildResult)
+{
+    auto& vm = plugin->vm();
+    auto scope = DECLARE_THROW_SCOPE(vm);
+    auto* globalObject = plugin->globalObject();
+
+    JSC::JSValue onEndCallbacksValue = plugin->getDirect(vm, Identifier::fromString(vm, String("onEndCallbacks"_s)));
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/JSBundlerPlugin.cpp]:
```suggestion
    JSC::JSValue onEndCallbacksValue = plugin->onEndCallbacks.get(plugin);
```

File: src/bun.js/bindings/JSBundlerPlugin.cpp [hunk 2]
```diff
@@ -652,6 +668,36 @@ extern "C" void JSBundlerPlugin__tombstone(Bun::JSBundlerPlugin* plugin)
...
+
+    if (!onEndCallbacksValue.isObject()) {
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/JSBundlerPlugin.cpp]:
```suggestion
    if (!onEndCallbacksValue.isObject()) [[unlikely]] {
```

File: src/bun.js/bindings/JSBundlerPlugin.cpp [hunk 3]
```diff
@@ -652,6 +668,36 @@ extern "C" void JSBundlerPlugin__tombstone(Bun::JSBundlerPlugin* plugin)
...
+        return JSValue::encode(jsUndefined());
+    }
+
+    auto* runOnEndCallbacksFn = JSC::JSFunction::create(vm, globalObject,
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/JSBundlerPlugin.cpp:664]:
```suggestion
    // TODO: have a prototype for JSBundlerPlugin that this is put on instead of re-creating the function on each usage
    auto* runOnEndCallbacksFn = JSC::JSFunction::create(vm, globalObject,
```

File: src/bun.js/bindings/JSBundlerPlugin.cpp [hunk 4]
```diff
@@ -652,6 +668,36 @@ extern "C" void JSBundlerPlugin__tombstone(Bun::JSBundlerPlugin* plugin)
...
+    JSC::CallData callData = JSC::getCallData(runOnEndCallbacksFn);
+    if (callData.type == JSC::CallData::Type::None) {
+        return JSValue::encode(jsUndefined());
+    }
+
+    MarkedArgumentBuffer arguments;
+    arguments.append(onEndCallbacksValue);
+    arguments.append(JSValue::decode(encodedBuildResult));
+
+    auto result = JSC::profiledCall(globalObject, ProfilingReason::API, runOnEndCallbacksFn, callData, plugin, arguments);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/JSBundlerPlugin.cpp]:
```suggestion
    // TODO: use AsyncContextFrame?
    auto result = JSC::profiledCall(globalObject, ProfilingReason::API, runOnEndCallbacksFn, callData, plugin, arguments);
```

File: src/js/builtins/BundlerPlugin.ts [hunk 5]
```diff
@@ -105,6 +106,33 @@ export function loadAndResolvePluginsForServe(
   return promiseResult;
 }
 
+export async function runOnEndCallbacks(
+  this: BundlerPlugin,
+  callbacks: AnyFunction[],
+  buildResult: Bun.BuildOutput,
+): Promise<void> {
+  if (!callbacks || !Array.isArray(callbacks)) {
```
Comment (Jarred-Sumner) [inline src/js/builtins/BundlerPlugin.ts]:
```suggestion

```

File: src/js/builtins/BundlerPlugin.ts [hunk 6]
```diff
@@ -222,6 +250,21 @@ export function runSetupFunction(
     return this;
   }
 
+  function onEnd(this: PluginBuilder, callback): PluginBuilder {
+    if (!$isCallable(callback)) {
+      throw new TypeError("callback must be a function");
```
Comment (Jarred-Sumner) [inline src/js/builtins/BundlerPlugin.ts]:
```suggestion
      throw $ERR_INVALID_ARG_TYPE()
```

File: test/bundler/expectBundled.ts [hunk 7]
```diff
@@ -1100,11 +1100,16 @@ for (const [key, blob] of build.outputs) {
         try {
           build = await Bun.build(buildConfig);
         } catch (e) {
-          const err = e as AggregateError;
+          if (!(e instanceof AggregateError)) {
+            throw e;
+          }
+
+          console.error("Bun.build threw error:", e);
```
Comment (Jarred-Sumner) [inline test/bundler/expectBundled.ts]:
```suggestion

```

File: src/bundler/bundle_v2.zig [hunk 8]
```diff
@@ -1637,7 +1707,20 @@ pub const BundleV2 = struct {
     ) OOM!bun.jsc.JSValue {
         const completion = try createAndScheduleCompletionTask(config, plugins, globalThis, event_loop, alloc);
         completion.promise = jsc.JSPromise.Strong.init(globalThis);
-        return completion.promise.value();
+
+        const onEndCallbacksPromise = bun.jsc.JSPromise.Strong.init(globalThis);
```
Comment (Jarred-Sumner) [inline src/bundler/bundle_v2.zig]: This is a memory leak. I think we can avoid creating this Promise altogether too. Instead, when there are onEnd callbacks to run, we can call `runOnEndCallbacks` and pass that the original `Promise` we returned to the user. it can use `$fulfillPromise` or `$rejectPromise` to call the equivalent of promise.resolve or promise.reject once it's promise completes. The `Promise.all` can .then the result so it gets added to the microtask queue and eventually completed. 

From there, we can delete a bunch of this code. We won't need the `onEndReject`or the`onEndResolve` functions above. Nor will we need the onBuildEnd / onBuildResolve. 

The tests are good to have though. I suggest also adding a test for the throwOnError: false case just so we know it doesn't break or skip calling the onEnd callbacks.

File: src/bun.js/bindings/ZigGlobalObject.h [hunk 9]
```diff
@@ -383,7 +383,7 @@ class GlobalObject : public Bun::GlobalScope {
         Bun__FileSink__onResolveStream,
         Bun__FileSink__onRejectStream,
     };
-    static constexpr size_t promiseFunctionsSize = 36;
+    static constexpr size_t promiseFunctionsSize = 40;
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/ZigGlobalObject.h]: This can be reverted right?

File: src/bundler/bundle_v2.zig [hunk 10]
```diff
@@ -1893,6 +1892,12 @@ pub const BundleV2 = struct {
...
 
+        /// Returns true if the promises were handled and resolved from BundlePlugin.ts, returns false if the caller should imediately resolve
+        fn runOnEndCallbacks(globalThis: *jsc.JSGlobalObject, plugin: *bun.jsc.API.JSBundler.Plugin, root_obj: jsc.JSValue, promise: *jsc.JSPromise) bool {
+            const value = plugin.runOnEndCallbacks(globalThis, root_obj, promise);
+            return value != .js_undefined;
+        }
+
         fn toJSError(this: *JSBundleCompletionTask, promise: *jsc.JSPromise, globalThis: *jsc.JSGlobalObject) void {
             if (this.config.throw_on_error) {
                 promise.reject(globalThis, this.log.toJSAggregateError(globalThis, bun.String.static("Bundle failed")));
```
Comment (Jarred-Sumner) [inline src/bundler/bundle_v2.zig]: missing this case.

File: src/js/builtins/BundlerPlugin.ts [hunk 11]
```diff
@@ -105,6 +106,38 @@ export function loadAndResolvePluginsForServe(
...
+
+  if (promises.length > 0) {
+    return Promise.all(promises).then(
+      () => {
+        $resolvePromise(buildPromise, buildResult);
+      },
+      e => {
+        $rejectPromise(buildPromise, e);
+      },
+    ); // return this promise - it gets "awaited" in the bundler before the whole build ends
```
Comment (Jarred-Sumner) [inline src/js/builtins/BundlerPlugin.ts]: it does not get awaited, we just don't do anything with it

File: src/bun.js/bindings/ZigGlobalObject.h (hunk 9 above)
Comment (alii) [reply src/bun.js/bindings/ZigGlobalObject.h]: Yeah

File: src/js/builtins/BundlerPlugin.ts (hunk 11 above)
Comment (alii) [reply src/js/builtins/BundlerPlugin.ts]: it was a leftover comment from previous attempt, will remove. thx

File: packages/bun-types/bun.d.ts [hunk 12]
```diff
@@ -5562,6 +5564,24 @@ declare module "bun" {
      * @returns `this` for method chaining
      */
     onStart(callback: OnStartCallback): this;
+    /**
+     * Register a callback which will be invoked when bundling ends. This is
+     * called after all modules have been bundled and the build is complete.
+     *
+     * @example
+     * ```ts
+     * Bun.plugin({
```
Comment (Jarred-Sumner) [inline packages/bun-types/bun.d.ts]: `Bun.plugin` is for runtime plugins. Bun.build plugins do not work in Bun.plugin.

File: docs/bundler/index.md [hunk 13]
```diff
@@ -1259,6 +1259,33 @@ $ bun build ./index.tsx --outdir ./out --drop=console --drop=debugger --drop=any
 
 {% /codetabs %}
 
+### `throw`
```
Comment (Jarred-Sumner) [inline docs/bundler/index.md:1262]: This hsould go somewhere towards the bottom, where people will likely not pay much attention because this option isn't important

Comment (alii) [reply docs/bundler/index.md:1262]: sure
