### PR TITLE
fix: require.extensions uses Strong instead of being clever

### LINKED ISSUE #19228: `module._extensions` index out of bounds
repro:
```
git clone https://github.com/googleapis/nodejs-pubsub
npm i && bun --bun c8 mocha build/test --recursive
```

Likely a good fix for this is changing the implementation to use just one hashmap in zig (also storing the jsvalue) instead of a `Vector<WriteBarrier>` in cpp and a hashmap in zig

### PR DESCRIPTION
**Pull request by paperclover**
Fixes #19228

The intent behind the package.json change is the fact you can install zig master, and run the check step with that compiler. It provides an amazing terminal watch experience that made this refactor easy to do.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 3:41 PM PT - Apr 23rd, 2025</sup></div>

@paperclover, your commit 92baeae811243868b0cfb94371a2ae8627a30fdf is building: [`#15391`](https://buildkite.com/bun/bun/builds/15391)

File: src/bun.js/bindings/NodeModuleModule.zig [hunk 1]
```diff
@@ -153,53 +116,44 @@ fn onRequireExtensionModify(global: *JSC.JSGlobalObject, str: []const u8, kind:
             if (is_built_in) {
                 vm.has_mutated_built_in_extensions += 1;
             }
-            gop.value_ptr.* = .pack(switch (loader) {
```
Comment (dylan-conway) [inline src/bun.js/bindings/NodeModuleModule.zig:156]: above this the `errordefer` can be deleted

Comment (paperclover) [reply src/bun.js/bindings/NodeModuleModule.zig:156]: its a nice pattern to have since zig will just not analyze it if it's unreachable. tho its not something we do alot

Comment (dylan-conway) [reply src/bun.js/bindings/NodeModuleModule.zig:156]: oh neat, makes sense

**Review by dylan-conway — APPROVED** [review]
