### PR TITLE
fix(ipc): add `json` ipc type + buffer incoming messages until a listener is attached.

### LINKED ISSUE #1472: Support Next.js
### What is the problem this feature would solve?

The create bun next app will install NextJs 12.x.x

### What is the feature you are proposing to solve the problem?

Support for NextJs 13 on create bun next app

### What alternatives have you considered?

_No response_

### LINKED ISSUE #3351: Process.binding error during `bunx --bun create-next-app`
### What version of Bun is running?

0.6.9

### What platform is your computer?

Microsoft Windows NT 10.0.19044.0 x64, Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run `bunx --bun create-next-app@latest`

### What is the expected behavior?

Run (or start at least) next.js installer successfully

### What do you see instead?

```
TypeError: process.binding() is not supported in Bun. If that breaks something, please file an issue and include a reproducible code sample.
      at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:106:491
      at __nccwpck_require__ (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:43870)
      at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:299:3377
      at __nccwpck_require__ (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:43870)
      at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:299:2962
      at __nccwpck_require__ (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:43870)
      at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:15529
      at __nccwpck_require__ (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:43870)
      at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:44739
      at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:44781
      at (eval) (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:325:44785)
```

### Additional information

I looked into topmost file in error and here is the line. It happens for `const o=process.binding("fs");`
```js
*/var n=r(12294);function FragmentCache(e){this.caches=e||{}}FragmentCache.prototype={cache:function(e){return this.caches[e]||(this.caches[e]=new n)},set:function(e,t,r){var n=this.cache(e);n.set(t,r);return n},has:function(e,t){return typeof this.get(e,t)!=="undefined"},get:function(e,t){var r=this.cache(e);if(typeof t==="string"){return r.get(t)}return r}};t=e.exports=FragmentCache},90036:(e,t,r)=>{"use strict";const n=r(67097);const s=r(82361).EventEmitter;const i=r(57147);
const o=process.binding("fs");const a=o.writeBuffers;const c=o.FSReqWrap||o.FSReqCallback;
```

### LINKED ISSUE #3776: Support Next.js 13 in Bun
Known major blockers:
- [x] Submit PR to next to use bun's `undici` override (instead of a prebundled version) in Bun
- [x] Submit PR to next to use bun's `ws` override (instead of a prebundled version) in Bun
- [x] jest-worker needs to work, which depends on child_process.fork(). possibly worker_threads
- [ ] Fix any napi bugs uncovered when testing Turbopack

The first issue is here:
```js
17 | class NotImplementedError extends Error {
18 |   code;
19 |   constructor(feature, issue) {
20 |
21 |     super(feature + " is not yet implemented in Bun." + (issue ? " Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/" + issue : ""));
       ^
NotImplementedError: node:diagnostics_channel is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2688
 code: "ERR_NOT_IMPLEMENTED"

      at new NotImplementedError (node:diagnostics_channel:21:4)
      at throwNotImplemented (node:diagnostics_channel:8:8)
      at channel (node:diagnostics_channel:30:2)
      at 4822 (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:2:163873)
      at __nccwpck_require__ (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:13952)
      at 4475 (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:6547)
      at __nccwpck_require__ (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:13952)
      at 9002 (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:1:27356)
      at __nccwpck_require__ (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:13952)
      at /Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:14201
```

Bun has a builtin polyfill for "undici" which uses the globals for `fetch`, `Request`, etc instead of a JS implementation. When run in Bun, next should use that. The same for `"ws"`.

### LINKED ISSUE #5814: NextJS Turborepo bug
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I had these errors when trying to run my [Turborepo starter project ](https://github.com/RobSchilderr/nextjs-native-starter/tree/bun) with Bun. If you go to the `bun` branch of that repo, you can see my changes and what I tried to achieve. You can also go back to the main branch and start over if you'd like.

```
er.development.js:6141:7)
next-web:build: Error: <Html> should not be imported outside of pages/_document.
next-web:build: Read more: https://nextjs.org/docs/messages/no-document-import-in-page
```

and
```
next-web:build: Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
next-web:build: Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
```

Steps to reproduce:

**1. Initial Setup:**
No package manager was set initially. Ran: `npx @turbo/codemod add-package-manager` and then `yarn global add @turbo/codemod`. This added a `packageManager` field to package.json.

**2. Switching to Bun:**
Updated package.json with: `"packageManager": "bun@1.0.2"`. Encountered a type error: `String does not match the pattern of "(npm|pnpm|yarn)@\d+\.\d+\.\d+(-.+)?".` This comes from the IDE so we can safely ignore for now.

**3. Cleaning Up:**
Removed `node_modules`, Ran `bun install`. Deleted yarn.lock and now have a `bun.lockb`.

**4. Building with Bun:**
Instead of yarn build, used `bun run turbo build`. Note: There's a difference in command syntax which caused a brief confusion.

**5. Result:**
The errors as shown above.

### What is the expected behavior?

Hoping to build the Turborepo with Bun.

### What do you see instead?

1. Prerendering Errors: There are errors occurring during the prerendering of several pages (/, /login, /register). Prerendering is a process where Next.js generates the HTML for a page at build time, which can help with performance and SEO. The specific error message is Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error.

2. NextRouter was not mounted: This error is occurring multiple times and suggests that the Next.js Router is being used outside of a component, or in a place where the React context provided by Next.js's <RouterProvider> is not available. The specific error message is Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted.

3. Build script exited with code 1 (SIGHUP): This indicates that the build script encountered an error and had to exit. The SIGHUP signal is often sent when a terminal window is closed, which can cause programs running in that terminal to exit.

4. Export encountered errors on following paths: This error indicates that Next.js encountered errors while trying to export certain pages as static HTML. The pages that had errors are listed after the error message.

### Additional information

You can easily just pull the `bun` branch of my repository [Nextjs Native starter](https://github.com/RobSchilderr/nextjs-native-starter/tree/bun)  and try it yourself.

### LINKED ISSUE #5956: `next/navigation` custom hook testing error
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Gist: https://gist.github.com/ImBIOS/5ac0dab356c92e16127f1c09419a36c2

1. Use code from provided gist
2. place it in next.js appDir project
3. run `bun test`

### What is the expected behavior?

- [ ] Test running without `invariant expected app router to be mounted` Error
- [ ] Test running properly
- [ ] All tests pass

### What do you see instead?

`invariant expected app router to be mounted` Error:

```
131 | }
132 | function useRouter() {
133 |     (0, _clienthookinservercomponenterror.clientHookInServerComponentError)("useRouter");
134 |     const router = (0, _react.useContext)(_approutercontext.AppRouterContext);
135 |     if (router === null) {
136 |         throw new Error("invariant expected app router to be mounted");
                  ^
error: invariant expected app router to be mounted
```

### Additional information

```

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 66.09 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.proto/bin/node
    npm: 8.19.4 - ~/.proto/bin/npm
    pnpm: 8.7.6 - ~/.proto/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.21.0 - /usr/local/go/bin/go
    Java: 17.0.8.1 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    PHP: 8.2.10 - /Users/USERNAME/Library/Application Support/Herd/bin/php
    Protoc: 3.21.9 - /usr/local/bin/protoc
    Python: 3.11.5 - /opt/homebrew/opt/python@3.11/libexec/bin/python
    Python3: 3.11.5 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.70.0 - /Users/USERNAME/.cargo/bin/rustc
  npmPackages:
    @chakra-ui/anatomy: ^2.1.2 => 2.2.1 
    @chakra-ui/cli: ^2.4.1 => 2.4.1 
    @chakra-ui/icons: ^2.0.17 => 2.1.1 
    @chakra-ui/next-js: ^2.1.4 => 2.1.5 
    @chakra-ui/react: ^2.8.0 => 2.8.1 
    @chakra-ui/stepper: ^2.3.0 => 2.3.1 
    @chakra-ui/theme-tools: ^2.0.17 => 2.1.1 
    @choc-ui/chakra-autocomplete: ^5.1.5 => 5.2.7 
    @emotion/react: ^11.10.5 => 11.11.1 
    @emotion/styled: ^11.10.5 => 11.11.0 
    @fontsource/roboto: ^4.5.8 => 4.5.8 
    @happy-dom/global-registrator: ^12.1.6 => 12.1.6 
    @next/env: ^13.4.19 => 13.5.2 
    @playwright/test: ^1.36.2 => 1.38.1 
    @testing-library/jest-dom: ^5.17.0 => 5.17.0 
    @testing-library/react: ^14.0.0 => 14.0.0 
    @testing-library/user-event: ^14.4.3 => 14.5.1 
    @types/jest: ^29.5.3 => 29.5.5 
    @types/lodash: ^4.14.197 => 4.14.198 
    @types/node: ^18.14.0 => 18.17.18 
    @types/react: ^18.0.28 => 18.2.22 
    @types/react-dom: ^18.0.11 => 18.2.7 
    @types/react-input-mask: ^3.0.2 => 3.0.2 
    @typescript-eslint/eslint-plugin: ^5.48.0 => 5.62.0 
    @typescript-eslint/parser: ^5.48.0 => 5.62.0 
    @uselessdev/datepicker: ^2.7.0 => 2.7.0 
    bun-types: ^1.0.2 => 1.0.2 
    chakra-react-select: ^4.5.0 => 4.7.2 
    date-fns: ^2.29.3 => 2.30.0 
    date-fns-tz: ^2.0.0 => 2.0.0 
    eslint: ^8.31.0 => 8.49.0 
    eslint-config-airbnb: ^19.0.4 => 19.0.4 
    eslint-config-airbnb-typescript: ^17.0.0 => 17.1.0 
    eslint-config-next: 13.4.3 => 13.4.3 
    eslint-config-prettier: ^8.8.0 => 8.10.0 
    eslint-plugin-import: ^2.26.0 => 2.28.1 
    eslint-plugin-import-helpers: ^1.3.1 => 1.3.1 
    eslint-plugin-jsx-a11y: ^6.6.1 => 6.7.1 
    eslint-plugin-react: ^7.31.11 => 7.33.2 
    eslint-plugin-simple-import-sort: ^10.0.0 => 10.0.0 
    framer-motion: ^6.5.1 => 6.5.1 
    husky: ^8.0.3 => 8.0.3 
    jest: ^29.6.2 => 29.7.0 
    jest-environment-jsdom: ^29.6.2 => 29.7.0 
    jspdf: ^2.5.1 => 2.5.1 
    lint-staged: ^13.2.0 => 13.3.0 
    lodash: ^4.17.21 => 4.17.21 
    next: 13.4.3 => 13.4.3 
    next-auth: ^4.23.1 => 4.23.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-hook-form: ^7.43.3 => 7.46.2 
    react-input-mask: ^2.0.4 => 2.0.4 
    react-nanny: ^2.15.0 => 2.15.0 
    sharp: ^0.31.3 => 0.31.3 
    typescript: ^4.9.5 => 4.9.5 


```

### LINKED ISSUE #7401: %f not correctly coercing object
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }
  [Symbol.toPrimitive]() {
    return this.num / this.den
  }
}
console.log("%f", new Frac(1, 2))
console.log("%f", 0.5)
```
```sh
bun testconsole.js
```

### What is the expected behavior?

```sh
jcbhmr@PIG-2016:~/Documents$ bun testconsole.js
0.5
0.5
```

### What do you see instead?

```sh
jcbhmr@PIG-2016:~/Documents$ bun testconsole.js
[Number (Frac): 0.5]
0.5
```

### Additional information

Chrome:
```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }
  [Symbol.toPrimitive]() {
    return this.num / this.den
  }
}
console.log("%f", new Frac(1, 2))
console.log("%f", 0.5)
VM47:10 0.5
VM47:11 0.5
```

Firefox:
```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }…
0.500000 [debugger eval code:10:9](chrome://devtools/content/webconsole/debugger%20eval%20code)
0.500000
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1846606

should follow this: https://console.spec.whatwg.org/#formatter

### LINKED ISSUE #7812: Bun.spawn IPC race condition with on message [v1.0.19]
### What version of Bun is running?

1.0.19+906f86d6f

### What platform is your computer?

Linux 6.2.0-39-generic x86_64 x86_64

### What steps can reproduce the bug?

```
export {};

const IS_CHILD = !!process.env.CHILD;

if (IS_CHILD) {
  await Bun.sleep(1_000); // will trigger race condition because we're not listening to messages yet

  process.on('message', async (msg) => {
    await Bun.sleep(1_000);

    process.send('PONG');
  });
} else {
  const child = Bun.spawn(process.argv, {
    env: {
      ...process.env,
      CHILD: 'true',
    },
    async ipc(msg) {
      console.log(msg);
      child.kill();
    },
  });

  child.send('PING');
  console.log('PING');

  await child.exited;

  console.log('exited');
}
```

### What is the expected behavior?

```
PING
PONG
exited
```

### What do you see instead?

```
PING
```

### Additional information

The example docs is misleading as any real app that must load dependencies will hit this race condition: https://bun.sh/guides/process/ipc

I suspect quite a few people are hitting this race condition randomly

### LINKED ISSUE #8725: bun --bun run build hangs with NextJS 14.1
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.5.0-1011-gcp x86_64 x86_64

### What steps can reproduce the bug?

1. `bun create next-app@14.1`. (I used TypeScript, no ESLint, no src dir, yes app dir, and no other customization.)
2. `bun i`.
3. `bun --bun run build`.

### What is the expected behavior?

The project should build.

### What do you see instead?

I get the following output, followed by the system sitting with all cores idle:

```console
% bun --bun run build
$ next build
 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
   ▲ Next.js 14.1.0

   Creating an optimized production build ...
```

### Additional information

Straight `bun run build` still works because node is apparently used instead of bun. But it will fail if building against the `oven/sh` Docker images. So this might also appear as "bun nextjs projects do not build on Docker."

This appears to be a regression between NextJS 14.0.4 and 14.1; bun will build a project based on 14.0.4.

### LINKED ISSUE #8955: Implement IPC for non-Bun processes
Just spoke with the NX team over on their discord. I can't wait for NX to be supported, but they say it can't be done until IPC can be used with non-Bun processes.

So this issue is for tracking support for that.

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

- Next.js App Router Works. Edge Runtime is not done
- serialization: json in child_process
- Fix console.log edge cases, and a crash when passing a non-object with %o.

Related Task: #5852
Might Fix, check #4795
Might Fix, check #4671
Fixes #1472
Fixes #5956
Fixes #5814
Fixes #3351
Fixes #3776
Fixes #8725
Fixes #7812
Fixes #8955 (by using json instead of `advanced`)
Fixes #7401 because i was bored

### CODE REVIEW

File: src/bun.js/api/bun/subprocess.zig [hunk 1]
```diff
@@ -2196,17 +2194,37 @@ pub const Subprocess = struct {
...
+                            // In the future, we should add a way to use a different IPC serialization format, specifically `json`.
+                            // but the only use case this has is doing interop with node.js IPC and other programs.
+                            ipc_mode = ipc_mode: {
+                                if (args.get(globalThis, "ipcMode")) |mode_val| {
+                                    if (mode_val.isString()) {
+                                        const mode_str = mode_val.toBunString(globalThis);
+                                        defer mode_str.deref();
+                                        const slice = mode_str.toUTF8(bun.default_allocator);
+                                        defer slice.deinit();
+                                        break :ipc_mode IPC.Mode.fromString(slice.slice()) orelse {
```
Comment (dylan-conway) [inline src/bun.js/api/bun/subprocess.zig]: `"none"` is also allowed?

Comment (paperclover) [reply src/bun.js/api/bun/subprocess.zig]: oops, removed.

File: src/bun.js/api/bun/subprocess.zig [hunk 2]
```diff
@@ -2505,14 +2523,13 @@ pub const Subprocess = struct {
...
         // When Bun.spawn() is given an `.ipc` callback, it enables IPC as follows:
         var socket: IPC.Socket = undefined;
-        if (ipc_mode != .none) {
-            if (comptime is_sync) {
-                globalThis.throwInvalidArguments("IPC is not supported in Bun.spawnSync", .{});
-                return .zero;
-            }
-
+        if ((comptime !is_sync) and ipc_mode != .none) {
             env_array.ensureUnusedCapacity(allocator, 2) catch |err| return globalThis.handleError(err, "in posix_spawn");
```
Comment (dylan-conway) [inline src/bun.js/api/bun/subprocess.zig]: this should be greater than 2 right? at least the length of `"NODE_CHANNEL_FD=3"` I think

Comment (dylan-conway) [reply src/bun.js/api/bun/subprocess.zig]: nvm lol

Comment (paperclover) [reply src/bun.js/api/bun/subprocess.zig]: number of slices not the slice content themselves. the slices are ro memory.
i will adjust this to 3 and document that the extra number is for the null at the end

File: docs/api/spawn.md [hunk 3]
```diff
@@ -237,6 +236,11 @@ process.send("Hello from child as string");
 process.send({ message: "Hello from child as object" });
 ```
 
+The `ipcMode` option controls the underlying communication format between the two processes:
```
Comment (Electroid) [inline docs/api/spawn.md:239]: What if we just called this `serialization` and match Node.js?

Comment (paperclover) [reply docs/api/spawn.md:239]: sure. can you mark this as "request changes" so that hopefully no one merges before i fix that

File: src/bun.js/api/bun/subprocess.zig [hunk 4]
```diff
@@ -2196,17 +2194,35 @@ pub const Subprocess = struct {
...
+                                return .zero;
+                            }
 
-                    if (val.isCell() and val.isCallable(globalThis.vm())) {
-                        // In the future, we should add a way to use a different IPC serialization format, specifically `json`.
-                        // but the only use case this has is doing interop with node.js IPC and other programs.
-                        ipc_mode = .bun;
-                        ipc_callback = val.withAsyncContextIfNeeded(globalThis);
+                            ipc_mode = ipc_mode: {
+                                if (args.get(globalThis, "ipcMode")) |mode_val| {
```
Comment (Electroid) [inline src/bun.js/api/bun/subprocess.zig]:
```suggestion
                                if (args.get(globalThis, "serialization")) |mode_val| {
```

**Review by Electroid — CHANGES_REQUESTED** [review]

**Comment by paperclover** [comment]
This PR now supercedes #7565
