### PR TITLE
fix(WebSocket) improve WebSocket Client

### LINKED ISSUE #6686: `WebSocket` client reliability
There are various issues with Bun's `WebSocket` client that have to do with parsing frames properly. We need to add the [Autobahn](https://github.com/crossbario/autobahn-testsuite/blob/master/autobahntestsuite/autobahntestsuite) to our tests and start fixing the bugs in [`websocket_http_client.zig`](https://github.com/oven-sh/bun/blob/149668129791d7dae6486368a2fbf50fdecd2efe/src/http/websocket_http_client.zig).

Note: this is not to be confused with Bun's `WebSocket` server, which is implemented by uWebSockets which uses the Autobahn test suite.

### PR DESCRIPTION
**Pull request by cirospaciari**
### What does this PR do?

Closes #6686 

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Added autobahn in `web/websocket/autobahn.test.ts`

### CODE REVIEW

File: src/string_immutable.zig [hunk 1]
```diff
@@ -3336,6 +3336,58 @@ pub const AsciiVectorU1Small = @Vector(8, u1);
...
+    // The second part is a transition table that maps a combination
+    // of a state of the automaton and a character class to a state.
+    0,  12, 24, 36, 60, 96, 84, 12, 12, 12, 48, 72, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0,  12, 12, 12, 12, 12, 0,
+    12, 0,  12, 12, 12, 24, 12, 12, 12, 12, 12, 24, 12, 24, 12, 12, 12, 12, 12, 12, 12, 12, 12, 24, 12, 12, 12, 12, 12, 24, 12, 12,
+    12, 12, 12, 12, 12, 24, 12, 12, 12, 12, 12, 12, 12, 12, 12, 36, 12, 36, 12, 12, 12, 36, 12, 12, 12, 12, 12, 36, 12, 36, 12, 12,
+    12, 36, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
+};
+
+pub fn decodeCheck(state: u8, byte: u8) u8 {
+    var char_type: u32 = utf8d[byte];
```
Comment (Jarred-Sumner) [inline src/string_immutable.zig]:
```suggestion
    const char_type: u32 = utf8d[byte];
```
