### PR TITLE
`node:crypto`: implement `hkdf` and `hkdfSync`

### LINKED ISSUE #15371: `crypto.hkdf` support for PASETO token support
### What version of Bun is running?

1.1.36+ededc168c

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

Import the `paseto` module from NPM (a better version of `jwt`), get this error:

```
18 | export default "internal:promisify";
           ^
TypeError: The "original" argument must be of type Function
      at promisify2 (internal:promisify:18:7)
      at /Users/airhorns/Code/gadget/node_modules/.pnpm/paseto@3.1.0/node_modules/paseto/lib/help/crypto_worker.js:14:17
      at anonymous (native:1:1)
      at /Users/airhorns/Code/gadget/node_modules/.pnpm/paseto@3.1.0/node_modules/paseto/lib/help/sign.js:1:9
      at anonymous (native:1:1)
      at /Users/airhorns/Code/gadget/node_modules/.pnpm/paseto@3.1.0/node_modules/paseto/lib/v1/sign.js:8:1
      at anonymous (native:1:1)
      at /Users/airhorns/Code/gadget/node_modules/.pnpm/paseto@3.1.0/node_modules/paseto/lib/v1/index.js:1:7
      at anonymous (native:1:1)
      at /Users/airhorns/Code/gadget/node_modules/.pnpm/paseto@3.1.0/node_modules/paseto/lib/index.js:1:1
      at unknown:11:43
      at processTicksAndRejections (unknown:7:39)

Bun v1.1.36 (macOS arm64)
```

the error comes from paseto calling `utils.promisify(crypto.hkdf)`, which is undefined in bun

### What is the expected behavior?

Module requires just fine because `crypto.hkdf` is defined.

### What do you see instead?

The above error

### Additional information

PASETO calls itself a modern replacement to JWT and claims to be better in just about every way -- it'd be great to get support for it for those of us with existing projects using it in Node!

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Adds `crypto.hkdf` and `crypto.hkdfSync`.

Closes #15371
Closes maybe #12178

TODO: some buffer optimizations

### How did you verify your code works?
Added `test-crypto-hkdf.js`

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 4:14 PM PT - Mar 19th, 2025</sup></div>

@dylan-conway, your commit f8edd65e6c783fa639000b3400a5d61b66648ef0 is building: [`#13544`](https://buildkite.com/bun/bun/builds/13544)

File: src/bun.js/bindings/node/crypto/CryptoPrimes.cpp [hunk 1]
```diff
@@ -93,7 +93,8 @@ JSC_DEFINE_HOST_FUNCTION(jsCheckPrimeSync, (JSC::JSGlobalObject * lexicalGlobalO
     int32_t checks = 0;
     if (optionsValue.isObject()) {
         JSObject* options = optionsValue.getObject();
-        JSValue checksValue = options->get(lexicalGlobalObject, Identifier::fromString(vm, "checks"_s));
+        auto clientData = WebCore::clientData(vm);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/node/crypto/CryptoPrimes.cpp:95]: if (auto* options = optionsValue.getObject9))
