### PR TITLE
fix(node/fetch): Make data URL fetch consistent with node

### LINKED ISSUE #5073: Fetch data URL text decoding works erratically depending on the presence of certain characters
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```
> fetch("data:application/json,%EF%BB%BF").then(r => r.text())  // ok
Promise { '' }
> fetch("data:application/json,%EF%BB%BF%7B%7D").then(r => r.text())  // ok
Promise { '{}' }
> fetch("data:application/json,%EF%BB%BFhello").then(r => r.text()) // ok
Promise { 'hello' }
> fetch("data:application/json,%EF%BB%BF{}").then(r => r.text())  // weird
Promise { '%EF%BB%BF{}' }
> fetch("data:application/json,{%7B%7D").then(r => r.text()) // weird
Promise { '{%7B%7D' }
```

### What is the expected behavior?

The "weird" results should probably decode the URL-escaped sequences.

At least `|`, `{`, `}`, `#` in the URL trigger this behavior; `,` and `/` don't. I didn't check exhaustively.

### Additional information

Found via #4876.

### PR DESCRIPTION
**Pull request by davidmhewitt**
### What does this PR do?
Fixes #5073 

Implements a non-strict mode of the percent encoding decoder that instead of immediately throwing an error and using the original data when there is non-URL safe character in a data URL, it passes the non-URL safe characters through and only replaces the percent encoded elements.

`test.mjs`:
```
console.log(await fetch("data:application/json,{%7B%7D}").then((r) => r.text()));
console.log(await fetch("data:application/json,{%%7B%7D%%}%%").then((r) => r.text()));
console.log(await fetch("data:,%20%😀").then((r) => r.text()));
```

Node output:
```
{{}}
{%{}%%}%%
 %😀
```

Bun before this commit:
```
{%7B%7D}
{%%7B%7D%%}%%
%20%😀
```

After this commit, the output from Bun matches Node.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I wrote automated tests

- [x] I or my editor ran Prettier on the changed files (or I ran `bun fmt`)
- [x] I or my editor ran `zig fmt` on the changed files
- [x] I included a test for the new code, or an existing test covers it

### CODE REVIEW

File: src/resolver/data_url.zig [hunk 1]
```diff
@@ -39,18 +39,24 @@ pub const PercentEncoding = struct {
...
     pub fn decode(allocator: Allocator, path: []const u8) EncodeError!?[]u8 {
+        return _decode(allocator, path, true);
+    }
+
+    /// Replaces percent encoded entities within `path` without throwing an error if other URL unsafe characters are present
+    pub fn decodeUnstrict(allocator: Allocator, path: []const u8) EncodeError!?[]u8 {
+        return _decode(allocator, path, false);
+    }
+
+    fn _decode(allocator: Allocator, path: []const u8, strict: bool) EncodeError!?[]u8 {
```
Comment (Jarred-Sumner) [inline src/resolver/data_url.zig:52]: we can make `strict` a `comptime` argument and then it maybe would produce better code 

but its fine to keep it also

**Review by Jarred-Sumner — APPROVED** [review]
LGTM. Thank you for this. Let's merge after tests run

**Comment by akx** [comment]
Thanks for picking up my issue 👍

**Comment by davidmhewitt** [comment]
Looking at the GitHub actions failures here, it looks like it may be a permissions thing with my account (as an outside contributor), rather than actual test failures. It seems to be the action being unable to comment on the PR with results that caused the overall failure.

It looks like the failed tests for linux-x64 were:
  - `test/js/node/dns/node-dns.test.js`
  - `test/js/third_party/postgres/postgres.test.ts`
  - `test/js/third_party/prisma/prisma.test.ts`

Unsure of the cause for the DNS test failure, but I imagine the other two are related to my GitHub account again not having permission to access the env variables for the Database secrets for those tests.
