### PR TITLE
fix(fs): `WriteStream` pending write fastpath

### LINKED ISSUE #16823: Vite build fails on 1.2.1
**Edit: fixed in #16856**, this will be part of Bun v1.2.2

original issue:

---

### What version of Bun is running?

1.2.1+ce532901c

### What platform is your computer?

Darwin 24.2.0 arm64 arm

### What steps can reproduce the bug?

Here's a trimmed down project that has the issue: https://github.com/LetrixZ/bun-issue

- Clone
- Install dependencies: `bun install`
- Run build command: `bun run build`

### What is the expected behavior?

Build succeeding like on 1.2.0 and previous versions

### What do you see instead?

Build fails with different issues. Examples:

```ts
error during build:
[vite-plugin-sveltekit-compile] [vite:esbuild-transpile] Transform failed with 1 error:
_app/immutable/chunks/user.!~{00b}~.js:14308:110: ERROR: Expected ")" but found "\x14"

Expected ")" but found "\x14"
14306|  		if ('transitionConfig' in $$new_props) $$invalidate(2, transitionConfig = $$new_props.transitionConfig);
14307|  		if ('inTransition' in $$new_props) $$invalidate(3, inTransition = $$new_props.inTransition);
14308|  		if ('inTransitionConfig' in $$new_props) $$invalidate(4, inTransitionConfig = $$new_props.inTransitionConfig);
   |                                                                                                                ^
14309|  		if ('outTransition' in $$new_props) $$invalidate(5, outTransition = $$new_props.outTransition);
14310|  		if ('outTransitionConfig' in $$new_props) $$invalidate(6, outTransitionConfig = $$new_props.outTransitionConfig);


Expected ")" but found "\x14"
14306|  		if ('transitionConfig' in $$new_props) $$invalidate(2, transitionConfig = $$new_props.transitionConfig);
14307|  		if ('inTransition' in $$new_props) $$invalidate(3, inTransition = $$new_props.inTransition);
14308|  		if ('inTransitionConfig' in $$new_props) $$invalidate(4, inTransitionConfig = $$new_props.inTransitionConfig);
   |                                                                                                                ^
14309|  		if ('outTransition' in $$new_props) $$invalidate(5, outTransition = $$new_props.outTransition);
14310|  		if ('outTransitionConfig' in $$new_props) $$invalidate(6, outTransitionConfig = $$new_props.outTransitionConfig);

[vite:esbuild-transpile] Transform failed with 1 error:
_app/immutable/chunks/user.!~{00b}~.js:14308:110: ERROR: Expected ")" but found "\x14"

Expected ")" but found "\x14"
14306|  		if ('transitionConfig' in $$new_props) $$invalidate(2, transitionConfig = $$new_props.transitionConfig);
14307|  		if ('inTransition' in $$new_props) $$invalidate(3, inTransition = $$new_props.inTransition);
14308|  		if ('inTransitionConfig' in $$new_props) $$invalidate(4, inTransitionConfig = $$new_props.inTransitionConfig);
   |                                                                                                                ^
14309|  		if ('outTransition' in $$new_props) $$invalidate(5, outTransition = $$new_props.outTransition);
14310|  		if ('outTransitionConfig' in $$new_props) $$invalidate(6, outTransitionConfig = $$new_props.outTransitionConfig);

    at failureErrorWithLog (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:1472:19)
    at <anonymous> (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:755:50)
    at <anonymous> (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:677:12)
    at readFromStdout (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:600:7)
    at emit (node:events:87:22)
    at addChunk (internal:streams/readable:265:47)
    at readableAddChunkPushByteMode (internal:streams/readable:243:18)
    at handleNumberResult (internal:streams/native-readable:69:18)
    at <anonymous> (internal:streams/native-readable:43:68)
```
```ts
error during build:
[vite-plugin-sveltekit-compile] [vite:esbuild-transpile] Transform failed with 1 error:
_app/immutable/chunks/user.!~{00b}~.js:17888:168: ERROR: Unterminated string literal

Unterminated string literal
17887|        default: "bg-primary text-primary-foreground hover:bg-primary/90",
17888|        "primary-outline": "border border-primary/50 bg-transparent text-foreground hover:bg-primary/20",
17889|        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
   |                                                                  ^
17890|        indigo: "bg-indigo-700 text-foreground hover:bg-indigo-700/90",
17891|        "indigo-outline": "border border-indigo-700/50 bg-transparent text-foreground hover:bg-indigo-700/20",


Unterminated string literal
17887|        default: "bg-primary text-primary-foreground hover:bg-primary/90",
17888|        "primary-outline": "border border-primary/50 bg-transparent text-foreground hover:bg-primary/20",
17889|        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
   |                                                                  ^
17890|        indigo: "bg-indigo-700 text-foreground hover:bg-indigo-700/90",
17891|        "indigo-outline": "border border-indigo-700/50 bg-transparent text-foreground hover:bg-indigo-700/20",

[vite:esbuild-transpile] Transform failed with 1 error:
_app/immutable/chunks/user.!~{00b}~.js:17888:168: ERROR: Unterminated string literal

Unterminated string literal
17887|        default: "bg-primary text-primary-foreground hover:bg-primary/90",
17888|        "primary-outline": "border border-primary/50 bg-transparent text-foreground hover:bg-primary/20",
17889|        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
   |                                                                  ^
17890|        indigo: "bg-indigo-700 text-foreground hover:bg-indigo-700/90",
17891|        "indigo-outline": "border border-indigo-700/50 bg-transparent text-foreground hover:bg-indigo-700/20",

    at failureErrorWithLog (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:1472:19)
    at <anonymous> (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:755:50)
    at <anonymous> (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:677:12)
    at readFromStdout (/Users/fermin/Downloads/bun-issue-main/node_modules/esbuild/lib/main.js:600:7)
    at emit (node:events:87:22)
    at addChunk (internal:streams/readable:265:47)
    at readableAddChunkPushByteMode (internal:streams/readable:243:18)
    at handleNumberResult (internal:streams/native-readable:69:18)
    at <anonymous> (internal:streams/native-readable:43:68)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?

Fixes out-of-order writes when `EAGAIN` is received.

Closes #16823 

### How did you verify your code works?
Added a vite integration test

### CODE REVIEW

File: src/io/PipeWriter.zig [hunk 1]
```diff
@@ -394,8 +394,8 @@ pub fn PosixStreamingWriter(
         is_done: bool = false,
         closed_without_reporting: bool = false,
 
-        // TODO:
-        chunk_size: usize = 0,
+        // TODO: configurable?
+        const chunk_size: usize = 1024 * 4;
```
Comment (paperclover) [inline src/io/PipeWriter.zig]: should be configurable, though it doesn't have to block this PR.

node:fs streams have this option. we can add an options argument into Bun.file().writer()

https://nodejs.org/api/fs.html#filehandlecreatewritestreamoptions

File: src/bun.js/webcore/streams.zig [hunk 2]
```diff
@@ -3841,6 +3891,7 @@ pub const FileSink = struct {
     pub fn deinit(this: *FileSink) void {
         this.pending.deinit();
         this.writer.deinit();
+        AutoFlusher.unregisterDeferredMicrotaskWithType(@This(), this, JSC.VirtualMachine.get());
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/streams.zig]: This needs to not run when it's the shell

File: src/bun.js/webcore/streams.zig [hunk 3]
```diff
@@ -3721,6 +3744,33 @@ pub const FileSink = struct {
...
+
+        const amt = switch (this.writer.flush()) {
+            .done, .wrote, .pending => |amt| amt,
+            else => 0,
+        };
+
+        if (amt == 0) {
+            this.updateRef(false);
+        } else {
+            this.runPending();
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/streams.zig]: We want to run pending when:
- `done`
- If we wrote part of the data

Instead, we should runPending when `!this.writer.hasPendingData()`

If this leads to a timeout in tests, it's likely due to not draining microtasks since this is being called after the microtask queue is over. If the developer immediately calls write every time the write Promise fulfills, that could maybe lead to an infinite loop but we will have to see.

I think both of these branches `if (amt == 0)` and this one should be removed. And instead

File: src/bun.js/webcore/streams.zig [hunk 4]
```diff
@@ -3989,37 +4038,43 @@ pub const FileReader = struct {
         pub fn openFileBlob(file: *Blob.FileStore) JSC.Maybe(OpenedFileBlob) {
             var this = OpenedFileBlob{ .fd = bun.invalid_fd };
             var file_buf: bun.PathBuffer = undefined;
-            var is_nonblocking_tty = false;
+            var is_nonblocking = false;
 
             const fd = if (file.pathlike == .fd)
                 if (file.pathlike.fd.isStdio()) brk: {
-                    if (comptime Environment.isPosix) {
+                    if (comptime Environment.isPosix and FeatureFlags.nonblocking_stdout_and_stderr_on_posix) {
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/streams.zig]:
```suggestion
                    if (comptime Environment.isPosix) {
```
