### PR TITLE
fix(windows): Implement `bun.sys.renameat` on Windows and fix crash during bun upgrade

### LINKED ISSUE #7989: Canary: thread panic on upgrade
### What version of Bun is running?

Bun v1.0.21-canary.55 

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun upgrade

upgraded recently on January 2nd 

### What is the expected behavior?

upgrade bun to the newest version

### What do you see instead?

Panic: invalid enum value

bun has crashed :'(

----- bun meta -----
Bun v1.0.21-canary.55 (837cbd60) Windows x64
UpgradeCommand:
Elapsed: 11309ms | User: 2250ms | Sys: 3343ms
RSS: 89.02MB | Peak: 111.56MB | Commit: 0.15GB | Faults: 34118
----- bun meta -----

0   00007FF73CF82268
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 6364 panic: invalid enum value
???:?:?: 0x7ff73bebd5dd in ??? (???)
???:?:?: 0x7ff73bebdd47 in ??? (???)
???:?:?: 0x7ff73becddbf in ??? (???)
???:?:?: 0x7ff73bd01492 in ??? (???)
???:?:?: 0x7ff73deae18f in ??? (???)
???:?:?: 0x7ffd4200257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffd435aaa57 in ??? (ntdll.dll)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Fixes #7989

### How did you verify your code works?

I ran `bun.exe upgrade` on a release build

### CODE REVIEW

File: src/windows_c.zig [hunk 1]
```diff
@@ -793,7 +793,7 @@ pub const SystemErrno = enum(u16) {
                 Win32Error.DIR_NOT_EMPTY => SystemErrno.ENOTEMPTY,
                 Win32Error.WSAENOTSOCK => SystemErrno.ENOTSOCK,
                 Win32Error.NOT_SUPPORTED => SystemErrno.ENOTSUP,
-                Win32Error.BROKEN_PIPE => SystemErrno.EOF,
+                Win32Error.BROKEN_PIPE => SystemErrno.EPIPE,
```
Comment (Jarred-Sumner) [inline src/windows_c.zig:796]: are you sure

Comment (paperclover) [reply src/windows_c.zig:796]: https://man7.org/linux/man-pages/man3/errno.3.html

image

**Comment by Jarred-Sumner** [comment]
yay
