### PR TITLE
Fix `new Request("/")` not working with `node-fetch`

### LINKED ISSUE #4947: Express+Apollo server with bun: Failed to construct 'Request': Invalid URL "/"
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

My project uses Express and Apollo server to provide a GraphQL API. With Bun, requests to the server are failing. Here's how I'm constructing and running the server:

```
const app = express();

const apolloServer = new ApolloServer({
  schema,
  context: (ctx) => contextFactory(ctx),
  plugins: [
    {
      requestDidStart: async () => {
        return {
          willSendResponse: ClearContainerCallback,
        };
      },
    },
  ],
  introspection: process.env.NODE_ENV !== "production",
});

(async () => {
  await apolloServer.start();

  apolloServer.applyMiddleware({ app, path: "/graphql" });

  const port = parseInt(process.env.PORT ?? "4000");

  app
    .listen(port, () => {
      console.log(`🚀 API ready at http://localhost:${port}/graphql`);
    })
    .on("error", (err) => {
      console.error(err);
    });
})();
```

### What is the expected behavior?

Everything should *just work*. When I run with node requests succeed and are responded to. 

### What do you see instead?

When running with Bun (`bun --watch ./src/main.ts`, I get the following error in the terminal with each request:

```
Error: Failed to construct 'Request': Invalid URL "/"
    at Request (native)
    at convertNodeHttpToRequest (/Users/***/repositories/backend/node_modules/apollo-server-core/dist/nodeHttpToRequest.js:16:8)
    at <anonymous> (/Users/***/repositories/backend/node_modules/apollo-server-express/dist/ApolloServer.js:81:58)
    at handle (/Users/***/repositories/backend/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:288:13)
    at process_params (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:349:6)
    at next (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (/Users/***/repositories/backend/node_modules/body-parser/lib/read.js:137:3)
    at runInAsyncScope (node:async_hooks:144:18)
    at invokeCallback (/Users/***/repositories/backend/node_modules/raw-body/index.js:237:31)
    at done (/Users/***/repositories/backend/node_modules/raw-body/index.js:229:13)
    at onEnd (/Users/***/repositories/backend/node_modules/raw-body/index.js:286:23)
    at emit (native)
    at endReadableNT (node:stream:2387:27)
    at processTicksAndRejections (:1:1302)
```

The requests never complete: when the error occurs, it never responds to the request. This is at odds with the behaviour I see with node, where even if an error should occur, a response is still sent to the client if possible. 

### Additional information

Apollo server version: `3.10.3`

### LINKED ISSUE #6301: Error while using Graphql
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Ubuntu 22.04.3 LTS

### What steps can reproduce the bug?

Creating a basic code to run a Graphql file 

```
const { ApolloServer, gql } = require('apollo-server');

const typeDefs = gql`
  type Query {
    firstName: String
    middleName: String
    lastName: String
  }
`;

const resolvers = {
  Query: {
    firstName: () => "YourFirstName",
    middleName: () => "YourMiddleName",
    lastName: () => "YourLastName"
  }
};

const server = new ApolloServer({ typeDefs, resolvers });

server.listen().then(({ url }) => {
  console.log(`Server ready at ${url}`);
});
```

### What is the expected behavior?

On testing in the graphql playground we must get  a valid response ie

```
{
  "data": {
    "firstName": "YourFirstName",
    "middleName": "YourMiddleName",
    "lastName": "YourLastName"
  }
}

```

### What do you see instead?

The error that comes in that playground is
```
 {
  "error": "Failed to fetch schema. Please check your connection"
}
```

and on the console 

```
Error: Failed to construct 'Request': Invalid URL "/"
    at Request (native)
    at convertNodeHttpToRequest (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-core/dist/nodeHttpToRequest.js:16:8)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-express/dist/ApolloServer.js:81:58)
    at handle (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:349:6)
    at next (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/body-parser/lib/read.js:137:3)
    at runInAsyncScope (node:async_hooks:144:18)
    at invokeCallback (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:237:31)
    at done (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:229:13)
    at onEnd (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:286:23)
    at emit (native)
    at endReadableNT (node:stream:2387:27)
    at processTicksAndRejections (:55:39)
Error: Failed to construct 'Request': Invalid URL "/"
    at Request (native)
    at convertNodeHttpToRequest (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-core/dist/nodeHttpToRequest.js:16:8)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-express/dist/ApolloServer.js:81:58)
    at handle (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:349:6)
    at next (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/body-parser/lib/read.js:137:3)
    at runInAsyncScope (node:async_hooks:144:18)
    at invokeCallback (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:237:31)
    at done (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:229:13)
    at onEnd (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:286:23)
    at emit (native)
    at endReadableNT (node:stream:2387:27)
    at processTicksAndRejections (:55:39)
Error: Failed to construct 'Request': Invalid URL "/"
    at Request (native)
    at convertNodeHttpToRequest (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-core/dist/nodeHttpToRequest.js:16:8)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-express/dist/ApolloServer.js:81:58)
    at handle (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:349:6)
    at next (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/body-parser/lib/read.js:137:3)
    at runInAsyncScope (node:async_hooks:144:18)
    at invokeCallback (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:237:31)
    at done (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:229:13)
    at onEnd (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:286:23)
    at emit (native)
    at endReadableNT (node:stream:2387:27)
    at processTicksAndRejections (:55:39)
Error: Failed to construct 'Request': Invalid URL "/"
    at Request (native)
    at convertNodeHttpToRequest (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-core/dist/nodeHttpToRequest.js:16:8)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-express/dist/ApolloServer.js:81:58)
    at handle (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:349:6)
    at next (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/body-parser/lib/read.js:137:3)
    at runInAsyncScope (node:async_hooks:144:18)
    at invokeCallback (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:237:31)
    at done (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:229:13)
    at onEnd (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:286:23)
    at emit (native)
    at endReadableNT (node:stream:2387:27)
    at processTicksAndRejections (:55:39)
Error: Failed to construct 'Request': Invalid URL "/"
    at Request (native)
    at convertNodeHttpToRequest (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-core/dist/nodeHttpToRequest.js:16:8)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/apollo-server-express/dist/ApolloServer.js:81:58)
    at handle (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:349:6)
    at next (/home/akash/Desktop/graphql benchmark test/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (/home/akash/Desktop/graphql benchmark test/node_modules/body-parser/lib/read.js:137:3)
    at runInAsyncScope (node:async_hooks:144:18)
    at invokeCallback (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:237:31)
    at done (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:229:13)
    at onEnd (/home/akash/Desktop/graphql benchmark test/node_modules/raw-body/index.js:286:23)
    at emit (native)
    at endReadableNT (node:stream:2387:27)
    at processTicksAndRejections (:55:39)

```

### Additional information

Screenshot from 2023-10-04 23-02-33

### PR DESCRIPTION
**Pull request by Electroid**
### What does this PR do?

* Fixes #4947
* Fixes #6301

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Added a regression test.

### CODE REVIEW

File: src/js/thirdparty/node-fetch.ts [hunk 1]
```diff
@@ -116,6 +123,29 @@ class Response extends WebResponse {
...
+
+class Request extends WebRequest {
+  [kUrl]: string;
+
+  constructor(input, init) {
+    // node-fetch is relaxed with the URL, for example, it allows "/" as a valid URL.
+    // If it's not a valid URL, use a placeholder URL during construction.
+    // See: https://github.com/oven-sh/bun/issues/4947
+    if (typeof input === "string" && !URL.canParse(input)) {
+      super("http://localhost/", init);
```
Comment (Jarred-Sumner) [inline src/js/thirdparty/node-fetch.ts]: This could potentially cause issues with `fetch` or any code which uses the underlying `url` from the Request object. 

Instead, could we join the URL with `http://localhost`?

```
super(new URL(input, "http://localhost/").href, init)
```

**Review by Jarred-Sumner — APPROVED** [review]
