### PR TITLE
Fixes #9851

### LINKED ISSUE #9851: Setting `install.cache.dir` with backslashes causes crash
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Windows 11 Enterprise 23H2 22631.3296
Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. install bun via `powershell -c "irm bun.sh/install.ps1 | iex"`
2. change directory to `D:\projects\bun-init-test`
3. execute `bun init` with defaults values by pressing enter a couple of times
4. create `D:\projects\bun-init-test\bunfig.toml` with the following contents:
```toml
[install.cache]
# custom global cache directory, the directory exists
dir = "D:\\.bun-cache"
```
5. execute `bun install`

### What is the expected behavior?

To have a working bun project with a global cache configured to run on a different drive.

### What do you see instead?

```powershell
PS D:\projects\bun-init-test> bun install

uh-oh: start index is larger than end index
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.0 (5903a614) Windows x64
InstallCommand:
Elapsed: 4ms | User: 0ms | Sys: 0ms
RSS: 26.08MB | Peak: 26.08MB | Commit: 72.30MB | Faults: 6510
----- bun meta -----

0   00007FF74480A4C8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???
14  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 27640 panic: start index is larger than end index
???:?:?: 0x7ff7431a4a94 in ??? (bun.exe)
???:?:?: 0x7ff7431abb3f in ??? (bun.exe)
???:?:?: 0x7ff7434a17bc in ??? (bun.exe)
???:?:?: 0x7ff7431ad510 in ??? (bun.exe)
???:?:?: 0x7ff74351b66b in ??? (bun.exe)
???:?:?: 0x7ff74351c2a4 in ??? (bun.exe)
???:?:?: 0x7ff7432c46b5 in ??? (bun.exe)
???:?:?: 0x7ff7433b239a in ??? (bun.exe)
???:?:?: 0x7ff7434654c2 in ??? (bun.exe)
???:?:?: 0x7ff743191603 in ??? (bun.exe)
???:?:?: 0x7ff745cc7e33 in ??? (bun.exe)
???:?:?: 0x7fff74f4257c in ??? (KERNEL32.DLL)
???:?:?: 0x7fff75e4aa57 in ??? (ntdll.dll)
```

### Additional information

Potentially related issue: https://github.com/oven-sh/bun/issues/9808

Other command that also crash (all with `panic: start index is larger than end index`):
* `PS D:\projects\bun-init-test> bun pm bin`
* `PS D:\projects\bun-init-test> bun pm cache`
```

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #9851

### How did you verify your code works?

There is a test

### CODE REVIEW

File: src/toml/toml_lexer.zig [hunk 1]
```diff
@@ -801,7 +805,7 @@ pub const Lexer = struct {
         var buf = buf_.*;
         defer buf_.* = buf;
 
-        const iterator = strings.CodepointIterator{ .bytes = text[start..], .i = 0 };
+        const iterator = strings.CodepointIterator{ .bytes = text, .i = 0 };
```
Comment (dylan-conway) [inline src/toml/toml_lexer.zig:808]: We don't need `[start..]`? My only concern is I see a few places in `next` where `string_literal_slice` is set with `start + 2..`

**Review by dylan-conway — APPROVED** [review]
