### PR TITLE
fix 14037

### LINKED ISSUE #10873: Crash when building a file that imports a wasm file
### How can we reproduce the crash?

```fish
# Create wasm file
touch a.zig
zig build-exe a.zig -target wasm32-freestanding -fno-entry -femit-bin=a.wasm
# Create bun file
echo 'import a from "./a.wasm";' > a.js
echo 'console.log(a);' >> a.js
```

Crashes:

```fish
bun build --target=bun a.js
```

Outputs the filename, rather than a `WebAssembly.Module` as [documentation](https://bun.sh/docs/bundler/loaders#wasm) would suggest:

```
bun a.js
```

### JavaScript/TypeScript code that reproduces the crash?

```shell
import a from "./a.wasm";
console.log(a);
```

### Relevant log output

```shell
============================================================
Bun v1.1.7 (b0b7db5c) macOS Silicon
Args: "bun", "build", "--target=bun", "a.js"
Elapsed: 24ms | User: 6ms | Sys: 13ms
RSS: 13.12MB | Peak: 13.12MB | Commit: 1.07GB | Faults: 292

panic(main thread): Internal error: missing asset file
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.7/Mb1b0b7db5AA2+jpnC23innC+uu/mCm8l3B2+04B+j/9BmwoB+wa__A0eNrzzCtJLcpLzFFILSrKL7JSyM0sLs7MS1dILC5OLVFIy8xJBQDiFgzc

fish: Job 1, 'bun build --target=bun a.js' terminated by signal SIGTRAP (Trace or breakpoint trap)
Exited with code [SIGTRAP]
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on macos aarch64 [BuildCommand]

**panic**: Internal error: missing asset file

- `debug.panicExtra__anon_315496`
- `debug.panic__anon_289796`
- `src.output.panic__anon_64972`
- `src.bundler.bundle_v2.Chunk.IntermediateOutput.code`
- `src.bundler.bundle_v2.LinkerContext.generateChunksInParallel`
- `src.cli.build_command.BuildCommand.exec`
- `src.cli.Cli.start`
- `main`
- *2 unknown/js code*

### LINKED ISSUE #13183: Bun build crash when try to import wasm
### How can we reproduce the crash?

`bun build --target=bun --outdir=dist index.ts`
```ts
import CanvasInitKit from "canvaskit-wasm";
import canvaskitwasm from "./node_modules/canvaskit-wasm/bin/canvaskit.wasm"

console.log(canvaskitwasm)
```

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on linux x86_64 [BuildCommand]

Segmentation fault at address 0x00000004

- `??`
- [`bundle_v2.zig:9221`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bundler/bundle_v2.zig#L9221>): `src.bundler.bundle_v2.LinkerContext.generateChunksInParallel`
- [`bundle_v2.zig:1075`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bundler/bundle_v2.zig#L1075>): `src.cli.build_command.BuildCommand.exec`
- [`cli.zig:1535`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/cli.zig#L1535>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/main.zig#L50>): `main`

### LINKED ISSUE #13398: Segmentation fault? from WASM?
### How can we reproduce the crash?

I'm still working on a reproduction. What I know:

1. I am executing bun test with a setup file
2. First, the setup file spins up @electric-sql/pglite
3. Tests work
4. I add code to initialize a complex elysia project that is typically deployed to cloudflare in said setup file.
5. When this code is added, bun either runs tests fine, segfaults, is killed, or throws a nonsense syntax error.
6. Initially, I believed that this segfault was due to complex wasm initialization for og image generation on a route:

```js
import satori, { init } from "satori/wasm";
import { Resvg, initWasm } from "@resvg/resvg-wasm";
import resvgwasm from "../../oss/node_modules/@resvg/resvg-wasm/index_bg.wasm";
import yogawasm from "../../oss/node_modules/yoga-wasm-web/dist/yoga.wasm";
import initYoga from "yoga-wasm-web";

const initialize = async () => {
  try {
    await initWasm(resvgwasm as WebAssembly.Module);
    const yoga = await initYoga(yogawasm as WebAssembly.Module);
    init(yoga);
  } catch (error) {
    console.error(error);
  }
}; 
```

7. However, I no longer believed this because when references to this codepath are removed from the router, the error still happens, and it seems like the test is flakey but in the sort of way it might work fine for 5 runs, segfault for the next 5, and start working again.
8. Of course, that then begs the question: does elysia actually have anything to do with this? The answer is yes, maybe indirectly, I think, because

```ts
// setup.ts
const db = new Kysely({
  dialect: new PgliteDialect({
    database: new PGlite(),
  }),
});
mock.module("../db", async () => {
  return {
    db: () => db,
    dbMiddleware: new Elysia({ name: "db" }).derive(
      { as: "global" },
      async () => {
        return {
          db: db,
        };
      }
    ),
  };
});
// only when the following code is added do we segfault
const c = client.decorate({
  env: {
    JWT_SECRET: "TESTING_JWT",
  },
});
```

9. So maybe the usage of db inside elysia causes this segfault? But it can't, because once I've reduced it down to the point where the elysia export is literally just this:

```ts
const app = new Elysia({
  aot: false,
}).use(helpers);
```

10. we still get segfaults (helpers doesn't touch db)
11. Ok, so its not the db because when all db references in elysia are removed the segfaults go away, and its not images because when all images references are removed it goes away...
12. And now I can't even reproduce it despite the codebase being at square one? Holy flake?? Edit: I did reproduce it again at square one:

<details>
<summary>eeek!</summary>

```
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
[ "", "" ]
prerun(C-node) worker= false
Running in main thread, faking onCustomMessage
^C
evan@EvanAir pinlog % bun test
bun test v1.1.24 (85a32991)

oss/server/middleware/auth.spec.ts:
============================================================
Bun v1.1.24 (85a32991) macOS Silicon
macOS v14.0
Args: "bun" "test"
Features: jsc(2) bunfig macros(5) transpiler_cache(3) tsconfig_paths(2) tsconfig(3) 
Builtins: "node:fs" "node:fs/promises" "node:os" "node:path" "node:string_decoder" "node:tty" "node:util/types" 
Elapsed: 806ms | User: 108ms | Sys: 97ms
RSS: 92.67MB | Peak: 92.67MB | Commit: 1.07GB | Faults: 1443

panic: Segmentation fault at address 0x8
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.24/Mt185a3299AiiggxD__+zt3Q214kV2463Qmg9kV2463Quv/lV+1q4Quml2QA2AQ

zsh: trace trap  bun test
```

</details>

---

I'm sorta really struggling to create a MRE here, I'm happy to do further debugging to your guidance. I wish I could point to the source repository as well but it isn't fully open source (50% of it is open source [here](https://github.com/toastclub/pinefore)). I *would* be willing to add you as a collaborator to the private repository if it is deemed necessary.

#### Edits

13. Looking around in the issues, it is possibly related to our use of macros as well? the syntax error in this file `/Users/evan/Code/pinlog/oss/mailer/index.ts:` (see below) would also [indicate](https://github.com/toastclub/pinefore/blob/4fd45e669742c70a293a0fc9cfd1b31a9ad67352/mailer/index.ts#L1) this. If that is the case, the error trace would look like `setup.ts > elysia > helpers > route > mailer/index.ts > {mocked db, macro}`

### Relevant log output

_No response_

### Stack Trace (bun.report)

```
Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on macos aarch64 [TestCommand]

Segmentation fault at address 0x1000003DF

- *2 unknown/js code*
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.Parser._parse__anon_112008`
- `src.cache.JavaScript.parse`

<!-- from bun.report: W3COj-T2xmYHM-8KEkH- -->
```

or

```
Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on macos aarch64 [TestCommand]

Segmentation fault at address 0xB8E8028812800008

- *2 unknown/js code*
- `src.js_printer.NewPrinter`
- `src.js_printer.NewPrinter`
- `src.js_printer.NewPrinter`
- `src.js_printer.NewPrinter`
- `src.js_printer.NewPrinter`
- `src.js_printer.NewPrinter`
- `src.js_printer.NewPrinter`
- `src.bundler.Bundler.printWithSourceMap__anon_92451`

<!-- from bun.report: ijE4bk7pPKxPwkB_jotH -->
```

or

```
zsh: illegal hardware instruction bun test
```

or, by far the weirdest one:

```
oss/server/middleware/auth.spec.ts:

# Unhandled error between tests
-------------------------------
33 |   "sign-up",
34 |   "deleted-account",
35 |   "prereg",
36 | ] as const;
37 | 
38 | let _templates = templates();
     ^
SyntaxError: Unexpected token '.'. Expected a ':' following the property name 'import'.
      at <parse> (/Users/evan/Code/pinlog/oss/mailer/index.ts:38:1)
-------------------------------
```

(this error is nonsensical)

*or* it just works

### LINKED ISSUE #13522: Segfault adding embedded file to `build --compile`
### How can we reproduce the crash?

Adding embedded file to `bun build --compile ...` from #13421 with the following pattern:

```json
    "bundle": "bun build src/**.ts src/**.tsx --splitting --outdir dist --target node",
    "postbundle": "cp node_modules/yoga-wasm-web/dist/yoga.wasm dist",
    "compile": "bun build --compile dist/bin.js dist/yoga.wasm --outfile dist/bin",
```

Running `bundle`:

```
dist
├── bin
├── bin.js
├── devtools-jk2ya82f.js
├── experiment-m3g28wzr.js
├── experiment-wfe5y8kq.js
├── experiment-znt6ydvp.js
├── experiment.js
├── test.js
└── yoga.wasm
```

Running `compile`:

```
$ bun build --compile dist/bin.js dist/yoga.wasm --outfile dist/bin
============================================================
Bun Canary v1.1.27-canary.3 (7529cd76) macOS Silicon
macOS v14.6.1
Args: "bun" "build" "--compile" "dist/bin.js" "dist/yoga.wasm" "--outfile" "dist/bin"
Features: define dotenv tsconfig_paths tsconfig 
Elapsed: 69ms | User: 72ms | Sys: 11ms
RSS: 69.21MB | Peak: 69.21MB | Commit: 1.07GB | Faults: 36

panic(main thread): Segmentation fault at address 0x4
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.27/Mb27529cd7AgsgggD__23umI2gnwI2l0xGmhmxG__A2AI

error: script "compile" was terminated by signal SIGTRAP (Trace or breakpoint trap)
Trace/BPT trap: 5
```

If we run without `dist/yoga.wasm`, we can compile it, but get the old error (and running `bun dist/bin.js` works without issue):

```
error: Cannot find module "./yoga.wasm" from "/$bunfs/root/bin"
```

### Relevant log output

```shell
bun build src/**.ts src/**.tsx --splitting --outdir dist --target node

  experiment.js             322.09 KB

  test.js                   2.09 KB

  bin.js                    282.77 KB

  devtools-jk2ya82f.js      681.75 KB

  experiment-m3g28wzr.js    1023.13 KB

  experiment-wfe5y8kq.js    1.12 KB

  experiment-znt6ydvp.js    0.24 KB
```

### Stack Trace (bun.report)

Bun v1.1.27-canary ([`7529cd7`](<https://github.com/oven-sh/bun/tree/7529cd76b54dee279e444c6996b1db3c201a2662>)) on macos aarch64 [BuildCommand]

Segmentation fault at address 0x00000004

- *2 unknown/js code*
- `src.bundler.bundle_v2.LinkerContext.generateChunksInParallel`
- `src.cli.build_command.BuildCommand.exec`
- `src.cli.Cli.start`
- `main`

Features: define, dotenv, tsconfig\_paths, tsconfig

### LINKED ISSUE #13582: Bun build crash when try to import wasm (on Mac)
### What version of Bun is running?

1.1.25+fe62a6140

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

`bun install @myriaddreamin/typst.ts @myriaddreamin/typst-ts-web-compiler @myriaddreamin/typst-ts-renderer`

`bun build typst.ts -outdir output`

where `typst.ts` is

```javascript
import { $typst } from '@myriaddreamin/typst.ts/dist/esm/contrib/snippet.mjs';
// The following paths come from https://github.com/Myriad-Dreamin/typst.ts/blob/main/packages/typst.ts/examples/all-in-one-lite.html
import typst_ts_web_compiler_bg from '@myriaddreamin/typst-ts-web-compiler/pkg/typst_ts_web_compiler_bg.wasm';
import typst_ts_renderer_bg from '@myriaddreamin/typst-ts-renderer/pkg/typst_ts_renderer_bg.wasm';

$typst.setCompilerInitOptions({
    getModule: () => typst_ts_web_compiler_bg,
});
$typst.setRendererInitOptions({
    getModule: () => typst_ts_renderer_bg,
});
```

### What is the expected behavior?

The WASMs loaded as strings to pass to `$typst.set*Options` functions.

### What do you see instead?

Bun v1.1.25 ([`fe62a61`](<https://github.com/oven-sh/bun/tree/fe62a614046948ebba260bed87db96287e67921f>)) on macos aarch64 [BuildCommand]

Segmentation fault at address 0x00000004

- *2 unknown/js code*
- `src.bundler.bundle_v2.LinkerContext.generateChunksInParallel`
- `src.cli.build_command.BuildCommand.exec`
- `src.cli.Cli.start`
- `main`

### Additional information

Similar to #13183 .

### LINKED ISSUE #13748: Bun.build (target:browser) segfaults when importing wasm module with default loader.
### How can we reproduce the crash?

I didn't have the time to delve too deeply into it, but this appears to only happen when I do a browser-targeted build of my codebase that directly imports a wasm module. If I change the wasm loader type to `file` the issue goes away, and it builds normally.

Not really an issue for me, since I need to use the file loader anyway so I can use the package in edge environments like Cloudflare's workers (which don't permit embedding wasm data directly), but probably still a case that should be at least be provided with a relevant error message.

---

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on macos aarch64 [RunCommand]

Segmentation fault at address 0x00000004

- *2 unknown/js code*
- `src.bundler.bundle_v2.LinkerContext.generateChunksInParallel`
- `Thread.PosixThreadImpl.spawn__anon_127898.Instance.entryFn`

### LINKED ISSUE #14037: Instant segfault when performing `Bun.build()` on a codebase.
### How can we reproduce the crash?

Clone the repository [randomx.js](https://github.com/l1mey112/randomx.js) at commit hash `9984d2f`. Then perform a simple bun build pointing at the library root, after running `make`.

```ts
await Bun.build({
	entrypoints: ['src/index.ts'],
	outdir: 'dist',
})
```

Keep in mind, `make` is needed to create the WASM files. You will need a simple clang installation, with the WABT and Binaryen toolchains installed.

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.28 ([`cf4e9cb`](<https://github.com/oven-sh/bun/tree/cf4e9cb69ee862037b09f2cd6668be76d2aca78d>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000004

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/cf4e9cb69ee862037b09f2cd6668be76d2aca78d/ld-temp.o#L0>): `WTF::SymbolRegistry::symbolForKey`
- `??`
- [`array_hash_map.zig:740`](<https://github.com/oven-sh/bun/blob/cf4e9cb69ee862037b09f2cd6668be76d2aca78d//opt/homebrew/etc/buildkite-agent/cache/https---github-com-oven-sh-bun-git/main/linux-x64-build-zig/vendor/zig/lib/std/array_hash_map.zig#L740>): `src.bundler.bundle_v2.LinkerContext.generateChunksInParallel`
- [`Mutex.zig:215`](<https://github.com/oven-sh/bun/blob/cf4e9cb69ee862037b09f2cd6668be76d2aca78d//opt/homebrew/etc/buildkite-agent/cache/https---github-com-oven-sh-bun-git/main/linux-x64-build-zig/vendor/zig/lib/std/Thread/Mutex.zig#L215>): `Thread.PosixThreadImpl.spawn__anon_168682.Instance.entryFn`

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
fixes #14037 
fixes #13748 
fixes #13398 
fixes #10873 
fixes #13582 
fixes #13522 
fixes #13183 

### How did you verify your code works?
added a test for importing wasm in a bundle

### CODE REVIEW

**Comment by robobun** [comment]
@dylan-conway, your commit 79cc625ae87c0a6442320ca0eeb5aaae4e5071d2 is building: [`#3612`](https://buildkite.com/bun/bun/builds/3612)

File: src/options.zig [hunk 1]
```diff
@@ -684,6 +684,8 @@ pub const Loader = enum(u8) {
             .napi,
             .sqlite,
             .sqlite_embedded,
+            // TODO: loader for reading bytes and creating module or instance
```
Comment (paperclover) [inline src/options.zig:687]: changing the default behavior of a loader after implementing is a breaking change. so implementing this todo would be a separate loader. like we could do `with { type: 'wasm' }`. not important now.

**Review by paperclover — APPROVED** [review]
cool
