### PR TITLE
fix(bundler): handle direct eval better

### LINKED ISSUE #2875: `eval` uses global scope instead of local scope
### What version of Bun is running?

0.6.0 canary

### What platform is your computer?

macos 10.14

### What steps can reproduce the bug?

given:
```
$ cat e.mjs
var a = "PASS";
function foo(s) {
    eval(`ba${s}()`);
}
function bar() {
    console.log(a);
}
function baz() {
}
export default foo("r");
```
expected:
```
$ node e.mjs 
PASS
```
actual:
```
$ bun run e.mjs
1 | bar()
   ^
ReferenceError: Can't find variable: bar
```

### What is the expected behavior?

No DCE or renaming of any identifiers reachable from `eval`.

### What do you see instead?

_No response_

### Additional information

Same bug exists in `bun build` and `bun build --minify`.

### LINKED ISSUE #7636: Bun.Transpiler does not generate evaluable code
### What version of Bun is running?

1.0.17+5e60861c3

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

Clone repository [https://github.com/Kleywalker/bun-eval](https://github.com/Kleywalker/bun-eval)

`bun install`

`bun run doesnotwork`

### What is the expected behavior?

console output "test-content"

### What do you see instead?

```sh
26 | } catch (error) {
27 |   console.log(error);
28 | }
29 | 
30 | try {
31 |   const bunResult = eval(bunTranspiled);
             ^
SyntaxError: Unexpected token '{'. import call expects one or two arguments.
      at /Users/stefan/code/github/bun-eval/index.ts:31:9
```

### Additional information

To see a working example node need to be installed.

Then run `bun run works`

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

do what esbuild does

Fixes #7636
Fixes #2875

### CODE REVIEW

File: src/js_parser.zig [hunk 1]
```diff
@@ -11637,7 +11637,7 @@ fn NewParser_(
                 notes[0] = logger.rangeData(p.source, where, why);
                 try p.log.addRangeErrorWithNotes(p.source, r, try std.fmt.allocPrint(p.allocator, "{s} cannot be used in strict mode", .{text}), notes);
             } else if (!can_be_transformed and p.isStrictModeOutputFormat()) {
-                try p.log.addRangeError(p.source, r, try std.fmt.allocPrint(p.allocator, "{s} cannot be used with esm due to strict mode", .{text}));
+                try p.log.addRangeError(p.source, r, try std.fmt.allocPrint(p.allocator, "{s} cannot be used with the ESM output format due to strict mode", .{text}));
```
Comment (Jarred-Sumner) [inline src/js_parser.zig]: Nice
