### PR TITLE
`bun install` correctly join dependency URLs

### LINKED ISSUE #3899: `bun install` uses incorrect url with private registry
### What version of Bun is running?

0.7.1

### What platform is your computer?

_No response_

### What steps can reproduce the bug?

Setup bunfig.toml for a private registry: 
`[install]
registry = {url="https://artifactory.xxx.yyy/artifactory/api/npm/my-npm/",token="..."}
`
run bun install

### What is the expected behavior?

Console logs show 
`GET https://artifactory.xxx.yyy/artifactory/api/npm/my-npm/@types/eslint-visitor-keys - 200
`
(or nothing)
packages are installed

### What do you see instead?

Console logs show 
`GET https://artifactory.xxx.yyy//artifactory/api/npm/my-npm/@types/eslint-visitor-keys - 500
`

packages are not installed

### Additional information

Private registry has a self signed cert, but shouldn't affect this behaviour.

### PR DESCRIPTION
**Pull request by Parzival-3141**
### What does this PR do?
Closes #3899
Registry and package URLs are now joined using `WTF`, instead of blindly format printing.
Errors are now reported when enqueuing dependencies as well.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?
I wrote automated tests.

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I or my editor ran `zig fmt` on the changed files
- [x] I included a test for the new code, or an existing test covers it

### CODE REVIEW

File: src/install/install.zig [hunk 1]
```diff
@@ -3432,7 +3398,18 @@ pub const PackageManager = struct {
                 i,
                 &dependency,
                 resolution,
-            ) catch {};
+            ) catch |err| {
+                this.log.addZigErrorWithNote(
```
Comment (Jarred-Sumner) [inline src/install/install.zig]: This will cause failing optional dependencies to fail the build and it should not 

Instead, I suggest setting level to warn if the dependency.behavior is optional or peer dependency

**Comment by Jarred-Sumner** [comment]
Can you remove the changes to builtins?

**Comment by Parzival-3141** [comment]
I rebased and removed the builtin changes. Just needs to be updated with`main`.

**Comment by Jarred-Sumner** [comment]
Thank you
