### PR TITLE
Fix loading react-jsxdev instead of react-jsx

### LINKED ISSUE #3768: Bun.build always assume "react-jsxdev" even when set "react-jsx"
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

run:
```
  await Bun.build({
    entrypoints: ["./index.tsx"],
    outdir: "./build",
    define: { "process.env.NODE_ENV": '"production"' },
  });
```
  make sure to set `{jsx: "react-jsx" } `in your tsconfig
  

### What is the expected behavior?

  You will see the output always use:  
  `jsx_dev_runtime.jsxDEV("div", {` 

### What do you see instead?

instead of 
  `jsx_runtime.jsx("div", {`

### Additional information

Why bun always use "react-jsxdev" instead of following tsconfig ?

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #3768

Fix loading react-jsxdev instead of react-jsx

The main bug: the state of the resolver sometimes got out of sync with the state of the transpiler for tracking if it should use development JSX or non-development JSX. This meant that setting `NODE_ENV` to a value in the parent process that is different than the environment seen from Bun.build would cause this to not work properly.

Separately, I also implemented tracking `react-jsx` and `react-jsxdev` to work as expected.

### How did you verify your code works?

There is a test that runs each permutation of `NODE_ENV` for runtime and bundler.

There is also a test for Bun.serve() `static`

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 6:08 AM PT - Feb 3rd, 2025</sup></div>

@Jarred-Sumner, your commit 194e4eafca42d9bd83ae1df350af7d91980db71a is building: [`#11052`](https://buildkite.com/bun/bun/builds/11052)

File: src/options.zig [hunk 1]
```diff
@@ -991,13 +991,18 @@ pub const ESMConditions = struct {
...
+    const RuntimeDevelopmentPair = struct {
+        runtime: JSX.Runtime,
+        development: ?bool,
+    };
+
+    pub const RuntimeMap = bun.ComptimeStringMap(RuntimeDevelopmentPair, .{
+        .{ "classic", RuntimeDevelopmentPair{ .runtime = .classic, .development = null } },
+        .{ "automatic", RuntimeDevelopmentPair{ .runtime = .automatic, .development = true } },
+        .{ "react", RuntimeDevelopmentPair{ .runtime = .classic, .development = null } },
+        .{ "react-jsx", RuntimeDevelopmentPair{ .runtime = .automatic, .development = true } },
```
Comment (paperclover) [inline src/options.zig:1003]: why is development true in this case?

File: src/options.zig [hunk 2]
```diff
@@ -1575,13 +1580,17 @@ pub const BundleOptions = struct {
 
     supports_multiple_outputs: bool = true,
 
+    force_development: ?bool = null,
```
Comment (paperclover) [inline src/options.zig]: it is not clear exactly what the difference between `null`, `false`, and `true` are.

**Review by paperclover — CHANGES_REQUESTED** [review]
review comments addressed in person. i will probably fix these last points

- convert ?bool into an enum tristate between unspecified, production, development
- document the behavior
