### PR TITLE
Fix cloning `File` with `structuredClone`

### LINKED ISSUE #11696: `structuredClone` does not properly clone `File`
### What version of Bun is running?

1.1.12

### What platform is your computer?

macOS 14.5

### What steps can reproduce the bug?

```js
const f1 = new File(['test'], 'foo.txt');
f1.size; // -> 4
f1.name; // -> 'foo.txt'
f1.lastModified; // -> 0
const f2 = structuredClone(f1);
f2.size; // -> 4
f2.name; // -> undefined
f2.lastModified; // -> 4503599627370495
```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Fixes #11696 

- bumps `Blob` serialization version to 2.
- now serializes a byte for whether it's a dom file, the length and bytes for `stored_name`, and a `f64` for `lastModified`.

Also sets `lastModified` to the current time in milliseconds if it's not in options when creating a `File`. Previously we set it to zero.

### How did you verify your code works?
added tests

### CODE REVIEW

File: src/bun.js/webcore/blob.zig [hunk 1]
```diff
@@ -1410,11 +1448,18 @@ pub const Blob = struct {
...
+                    set_last_modified = true;
                     blob.last_modified = last_modified.coerce(f64, globalThis);
                 }
             }
         }
 
+        if (!set_last_modified) {
+            // `lastModified` should be the current date in milliseconds if unspecified.
+            // https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified
+            blob.last_modified = @floatFromInt(std.time.milliTimestamp());
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/blob.zig:1460]:
```suggestion
            blob.last_modified = @floatFromInt(bun.timespec.now().ms());
```

Comment (Jarred-Sumner) [reply src/bun.js/webcore/blob.zig:1460]: actually im wrong!!
