### PR TITLE
fix(install): resolution order and unused resolutions

### LINKED ISSUE #16692: `bun install --frozen-lockfile` keeps reporting issues
### What version of Bun is running?

1.2.0+b0c5a7655

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

I tried this morning to upgrade our package manager version **bun** from `1.1.43` to `1.2.0`.

The goal was to use the new [bun.lock text-based lockfile](https://bun.sh/blog/bun-v1.2#introducing-bun-lock).

I simply ran `bun install --save-text-lockfile`
- It removed the `bun.lockb` file
- It created the `bun.lock` file

### What is the expected behavior?

It installs packages

### What do you see instead?

I got :
```
bun install v1.2.0 (b0c5a765)
error: lockfile had changes, but lockfile is frozen
note: try re-running without --frozen-lockfile and commit the updated lockfile
```

### Additional information

I tested all solutions, deleting `node_modules`, deleting `bun.lock` and run again `bun install`.

But I have always the same problem.

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Two changes:
- sort overrides before comparing
- even if the override is unused, add it to text lockfile

Fixes #16692

### How did you verify your code works?
Added tests for out of order resolutions and missing resolution.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 5:35 PM PT - Mar 27th, 2025</sup></div>

@dylan-conway, your commit 2625b8ce0362da6b4fca6f856cfef87ce7d7d0c1 is building: [`#14102`](https://buildkite.com/bun/bun/builds/14102)

File: src/install/lockfile.zig [hunk 1]
```diff
@@ -3019,6 +3019,29 @@ pub const OverrideMap = struct {
...
+                const deps = sorter.override_deps;
+                const l_dep = deps[l];
+                const r_dep = deps[r];
+
+                const buf = sorter.buf;
+                return l_dep.name.order(&r_dep.name, buf, buf) == .lt;
+            }
+        };
+
+        var ctx: Ctx = .{
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]:
```suggestion
        const ctx: Ctx = .{
```

File: src/install/lockfile.zig [hunk 2]
```diff
@@ -7092,10 +7117,17 @@ pub fn eql(l: *const Lockfile, r: *const Lockfile, cut_off_pkg_id: usize, alloca
     for (l.buffers.trees.items) |l_tree| {
         const rel_path, _ = Tree.relativePathAndDepth(l, l_tree.id, &path_buf, &depth_buf, .pkg_path);
         const tree_path = try allocator.dupe(u8, rel_path);
-        for (l_tree.dependencies.get(l_hoisted_deps)) |l_dep_id| {
-            if (l_dep_id == invalid_dependency_id) continue;
+        for (l_tree.dependencies.get(l_hoisted_deps), 0..) |l_dep_id, j| {
+            if (l_dep_id == invalid_dependency_id) {
+                std.debug.print("skipping invalid l dep_id: {d}\n", .{j});
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]:
```suggestion

```

File: src/install/lockfile.zig [hunk 3]
```diff
@@ -7092,10 +7117,17 @@ pub fn eql(l: *const Lockfile, r: *const Lockfile, cut_off_pkg_id: usize, alloca
...
+                continue;
+            }
             const l_pkg_id = l.buffers.resolutions.items[l_dep_id];
-            if (l_pkg_id == invalid_package_id or l_pkg_id >= cut_off_pkg_id) continue;
+            if (l_pkg_id == invalid_package_id or l_pkg_id >= cut_off_pkg_id) {
+                const l_dep = l.buffers.dependencies.items[l_dep_id];
+                std.debug.print("skipping l_dep: {s}, {}, {}\n", .{ l_dep.name.slice(l_string_buf), l_pkg_id == invalid_package_id, l_pkg_id >= cut_off_pkg_id });
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]:
```suggestion
```

File: src/install/lockfile.zig [hunk 4]
```diff
@@ -7109,10 +7141,17 @@ pub fn eql(l: *const Lockfile, r: *const Lockfile, cut_off_pkg_id: usize, alloca
     for (r.buffers.trees.items) |r_tree| {
         const rel_path, _ = Tree.relativePathAndDepth(r, r_tree.id, &path_buf, &depth_buf, .pkg_path);
         const tree_path = try allocator.dupe(u8, rel_path);
-        for (r_tree.dependencies.get(r_hoisted_deps)) |r_dep_id| {
-            if (r_dep_id == invalid_dependency_id) continue;
+        for (r_tree.dependencies.get(r_hoisted_deps), 0..) |r_dep_id, j| {
+            if (r_dep_id == invalid_dependency_id) {
+                std.debug.print("skipping invalid dep_id: {d}\n", .{j});
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]:
```suggestion

```

File: src/install/lockfile.zig [hunk 5]
```diff
@@ -7109,10 +7141,17 @@ pub fn eql(l: *const Lockfile, r: *const Lockfile, cut_off_pkg_id: usize, alloca
...
+                continue;
+            }
             const r_pkg_id = r.buffers.resolutions.items[r_dep_id];
-            if (r_pkg_id == invalid_package_id or r_pkg_id >= cut_off_pkg_id) continue;
+            if (r_pkg_id == invalid_package_id or r_pkg_id >= cut_off_pkg_id) {
+                const r_dep = r.buffers.dependencies.items[r_dep_id];
+                std.debug.print("skipping r_dep: {s}, {}, {}\n", .{ r_dep.name.slice(r_string_buf), r_pkg_id == invalid_package_id, r_pkg_id >= cut_off_pkg_id });
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]:
```suggestion

```
