### PR TITLE
Fix #1602

### LINKED ISSUE #1602: `fetch()` selecting incorrect header text encoding
### What version of Bun is running?

0.3.0

### What platform is your computer?

Linux, Fedora 37, x64, kernel 6.0.11

### What steps can reproduce the bug?

I'm fetching text over the network, extracting a portion of it using regex, and passing that value as a header in another fetch() request.

The recipient of this header receives a truncated version of it, with null bytes interspersed between the characters.

This does not happen if the regex match value is transformed in any way. It also doesn't happen if I copy/paste the same textual value into my code. My reproduction is larger than I'd like because how I get the value seems more important than the value itself.

console.log() shows I'm calling `fetch()` with the expected value in the header, and the original value does not contain any null bytes.

```js
const port = 3009;

const main = async () => {
  Bun.serve({
    fetch(req) {
      console.log(Object.fromEntries(req.headers.entries()));
      return new Response("");
    },
    port,
  });

  const pageSource = await (await fetch("https://twitter.com")).text();
  const [, brokenString] = pageSource.match(/gt=([0-9]+);/);
  console.log("Original value", brokenString);
  console.log(
    "Original byte sequence:",
    new TextEncoder().encode(brokenString)
  );

  await fetch(
    `http://localhost:${port}/`,
    {
      headers: {
        // Broken...
        "x-broken-string": brokenString,

        // ...but this works!
        //"x-broken-string": Array.from(brokenString).reverse().reverse().join(""),
      },
    },
    { verbose: true }
  );

  process.exit(0);
};

main();

```

### What is the expected behavior?

The server receives the original text value in the header

### What do you see instead?

A truncated header value:

```
$ bun run foo.js                                                                             
Original value 1601755857636786177          
Original byte sequence: Uint8Array(19) [ 49, 54, 48, 49, 55, 53, 53, 56, 53, 55, 54, 51, 54, 55, 56, 54, 49, 55, 55 ]
Request: GET /               
        x-broken-string: 1601755857
        Connection: keep-alive
        User-Agent: Bun/0.3.0         
        Accept: */*
        Host: localhost:3009
        Accept-Encoding: gzip, deflate
                                              
{                          
  accept: "*/*",         
  "accept-encoding": "gzip, deflate",
  connection: "keep-alive",               
  host: "localhost:3009",
  "user-agent": "Bun/0.3.0",
  "x-broken-string": "1\u00006\u00000\u00001\u00007\u00005\u00005\u00008\u00005\u00007"
}
Response: < 200 OK
<       Date: Sun, 11 Dec 2022 01:48:50 GMT
<       Content-Length: 0
```

### Additional information

Notes from Jarred in Discord:

> Most likely the bug is in the code which trims the final character(s) of incomplete broken UTF8 or UTF16 in certain cases during text encoding
>
> Hmm sounds like something is assuming text is always latin1 when it’s actually utf16 here and needs to be converted
>
> In JS every string can either be latin1 or utf16. Normally it chooses the smallest representation when possible (latin1) 
>
> This bug is probably some code assuming headers are always latin1 when in fact they are not
>
> 
> As a temporary workaround if you run the string through Buffer.from(match).toString or use a Headers object that should work instead

### PR DESCRIPTION
**Pull request by jwhear**
Fixes #1602 

This PR fixes a number of issues related to FetchHeader handling:
1) A test uncovered a possible segfault.  This was due to [non-exhaustive header conversion](https://github.com/oven-sh/bun/blob/56b75dbac32233b49b33c12ce25a07c9e9083dee/src/bun.js/webcore/response.zig#L1030-L1036) that could result in a null headers object but no exception thrown.  This is now covered by an `else return null`.
2) The C++ FetchHeader API makes extensive use of returning `ExceptionOr<void / String>` but most of these possible exceptions were not handled, which could lead to silent failures on append, put, get, etc.  These have been fixed to ensure that if there's an exception it is propagated as a error in JSC.  This has necessitated expanding the signature of many FetchHeader methods to include a global object parameter.
3) The FetchHeader and JSFetchHeader implementations make use of `convert` to wrangle the incoming JSValue.  These converts were using `IDLByteString` which throw a generic TypeError when encountering a non-Latin1 character.  To ensure more informative error messages, these have been changed to `IDLDOMString` and the FetchHeader `canWriteHeader` checks are now relied on to ensure that header names and values are valid.
4) The [translation of a FetchHeader from JSC](https://github.com/oven-sh/bun/blob/56b75dbac32233b49b33c12ce25a07c9e9083dee/src/bun.js/bindings/bindings.cpp#L762-L777) to actual strings for writing in the request did not check whether the encoding was 8 or 16 bit.  By slicing a string containing for instance, an emoji, it was possible to get an all-ASCII string encoded as UTF16.  I've added `is8Bit` checks and a conversion path if necessary for both header names and values.  This solves the primary problem uncovered by the original issue.  The `copyToUWS` function has been updated in a similar vein, but using `utf8()` to perform the conversion if needed.
5) The `isValidHTTPHeaderValue` function actually doesn't enforce Latin1 or ASCII because it appears that [the spec](https://fetch.spec.whatwg.org/#concept-header) doesn't require it.  However since Node and other common implementations disallow codepoints > 255, I have added a check to prevent the same.

### CODE REVIEW

File: src/bun.js/webcore/response.zig [hunk 1]
```diff
@@ -1153,9 +1154,9 @@ pub const Fetch = struct {
             .{ .method = method, .url = url, .headers = headers orelse Headers{
                 .allocator = bun.default_allocator,
             }, .body = body, .timeout = std.time.ns_per_hour, .disable_keepalive = disable_keepalive, .disable_timeout = disable_timeout, .follow_redirects = follow_redirects, .verbose = verbose, .proxy = proxy, .url_proxy_buffer = url_proxy_buffer },
-            JSC.JSValue.fromRef(deferred_promise),
+            promise_val,
         ) catch unreachable;
-        return deferred_promise;
+        return promise_val.asRef();
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/response.zig:1209]: I don't think this fixes the header issue, unless the header issue wasn't actually the issue here

Feels like we should run Valgrind on this function and see what it says

Comment (jwhear) [reply src/bun.js/webcore/response.zig:1209]: This commit only fixes the segfault.  Still tracing the original issue back, but at least part of the problem is that the header handling code above is not exhaustive.

File: src/bun.js/base.zig [hunk 2]
```diff
@@ -1718,6 +1718,12 @@ pub fn getAllocator(_: js.JSContextRef) std.mem.Allocator {
     return default_allocator;
 }
 
+/// Print a JSValue to stdout; this is only meant for debugging purposes
+pub fn dump(value: JSValue, ctx: js.JSContextRef) !void {
+    var formatter = JSC.ZigConsoleClient.Formatter{ .globalThis = ctx };
+    return std.io.getStdOut().writer().print("{}\n", .{value.toFmt(ctx, &formatter)});
```
Comment (Jarred-Sumner) [inline src/bun.js/base.zig]: This will have strange behavior with buffering of `Output`

Instead, `Output.errorWriter()` and Output.flush()

File: src/bun.js/bindings/bindings.cpp [hunk 3]
```diff
@@ -722,12 +722,29 @@ WebCore__FetchHeaders* WebCore__FetchHeaders__createFromJS(JSC__JSGlobalObject*
...
     auto* headers = new WebCore::FetchHeaders({ WebCore::FetchHeaders::Guard::None, {} });
-    if (init)
-        headers->fill(WTFMove(init.value()));
+    if (init) {
+        // `fill` doesn't set an exception on the VM if it fails, it returns an
+        //  ExceptionOr<void>.  So we need to check for the exception and, if set,
+        //  translate it to JSValue and throw it.
+        auto possibleException = headers->fill(WTFMove(init.value()));
+        if (possibleException.hasException()) {
+            auto message = Zig::toZigString(possibleException.releaseException().message());
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp]: Let's use JSC's exception code instead of ours, as ours just wraps JSC's

We already have a throwScope here

I think we can use `propagateException`:

```cpp
WebCore::propagateException(globalObject, throwScope, possibleException);
```

https://github.com/oven-sh/bun/blob/main/src/bun.js/bindings/JSDOMExceptionHandling.h#L79

File: src/bun.js/base.zig [hunk 4]
```diff
@@ -1718,6 +1718,12 @@ pub fn getAllocator(_: js.JSContextRef) std.mem.Allocator {
     return default_allocator;
 }
 
+/// Print a JSValue to stdout; this is only meant for debugging purposes
+pub fn dump(value: JSValue, ctx: js.JSContextRef) !void {
```
Comment (Jarred-Sumner) [inline src/bun.js/base.zig]: Let's make this `globalObject: *JSC.JSGlobalObject` instead of `ctx: js.JSContextRef`


The existence of `js.JSContextRef` is technical debt from JavaScriptCore's C API

File: src/bun.js/base.zig (hunk 2 above)
Comment (jwhear) [reply src/bun.js/base.zig]: updated

File: src/bun.js/bindings/bindings.cpp (hunk 3 above)
Comment (jwhear) [reply src/bun.js/bindings/bindings.cpp]: updated

File: src/bun.js/base.zig (hunk 4 above)
Comment (jwhear) [reply src/bun.js/base.zig]: updated

File: src/bun.js/bindings/bindings.cpp [hunk 5]
```diff
@@ -97,19 +97,19 @@ static void copyToUWS(WebCore::FetchHeaders* headers, UWSResponse* res)
     auto& internalHeaders = headers->internalHeaders();
 
     for (auto& value : internalHeaders.getSetCookieHeaders()) {
-        res->writeHeader(std::string_view("set-cookie", 10), std::string_view(reinterpret_cast<const char*>(value.characters8()), value.length()));
+        res->writeHeader(std::string_view("set-cookie", 10), std::string_view(value.utf8().data(), value.length()));
```
Comment (jwhear) [inline src/bun.js/bindings/bindings.cpp]: I did not dig into how WTFString lifetimes are managed; will the creation of this temporary leak?

File: src/bun.js/bindings/bindings.cpp [hunk 6]
```diff
@@ -764,14 +795,25 @@ void WebCore__FetchHeaders__copyTo(WebCore__FetchHeaders* headers, StringPointer
...
     unsigned count = 0;
+
     for (auto pair = iter.next(); pair; pair = iter.next()) {
         auto name = pair->key;
         auto value = pair->value;
         names[count] = { i, name.length() };
-        memcpy(&buf[i], name.characters8(), name.length());
+
+        if (name.is8Bit())
+            memcpy(&buf[i], name.characters16(), name.length());
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp]:
```suggestion
            memcpy(&buf[i], name.characters8(), name.length());
```

File: src/bun.js/bindings/bindings.cpp [hunk 7]
```diff
@@ -893,25 +936,43 @@ JSC__JSValue WebCore__FetchHeaders__createValue(JSC__JSGlobalObject* arg0, Strin
...
+        *arg2 = Zig::toZigString(result.releaseReturnValue());
 }
-bool WebCore__FetchHeaders__has(WebCore__FetchHeaders* headers, const ZigString* arg1)
+bool WebCore__FetchHeaders__has(WebCore__FetchHeaders* headers, const ZigString* arg1, JSC__JSGlobalObject* global)
 {
-    return headers->has(Zig::toString(*arg1)).releaseReturnValue();
+    auto throwScope = DECLARE_THROW_SCOPE(global->vm());
+    auto result = headers->has(Zig::toString(*arg1));
+    if (result.hasException())
+        WebCore::propagateException(*global, throwScope, result.releaseException());
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp:959]: we need to return a value even if there is an exception

Comment (jwhear) [reply src/bun.js/bindings/bindings.cpp:959]: Good catch, I'm too used to Zig catching this kind of thing.

File: src/bun.js/webcore/response.zig [hunk 8]
```diff
@@ -1031,8 +1031,12 @@ pub const Fetch = struct {
                             headers = Headers.from(headers__, bun.default_allocator) catch unreachable;
                             // TODO: make this one pass
                         } else if (FetchHeaders.createFromJS(ctx.ptr(), headers_)) |headers__| {
+                            defer headers__.deref();
                             headers = Headers.from(headers__, bun.default_allocator) catch unreachable;
-                            headers__.deref();
+                        } else {
+                            // Converting the headers failed; return null and
+                            //  let the set exception get thrown
+                            return null;
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/response.zig:1039]: do we need to cleanup response body?

File: test/bun.js/fetch_headers.test.js [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+    var decoder = new TextDecoder();
+    const roundTripString = decoder.decode(encoder.encode(origString));
+    console.log("origString = ", origString);
+    console.log("encoded = ", encoder.encode(origString));
+
+    expect(roundTripString).toBe(origString);
+
+    // This one will pass
+    expect(await fetchContent({"x-test": roundTripString})).toBe(roundTripString);
+    // This would hang
```
Comment (Jarred-Sumner) [inline test/bun.js/fetch_headers.test.js:46]: does it still hang?

Comment (jwhear) [reply test/bun.js/fetch_headers.test.js:46]: No, works great now; used to read "This will hang" :)

File: src/bun.js/webcore/response.zig (hunk 8 above)
Comment (jwhear) [reply src/bun.js/webcore/response.zig:1039]: If I'm reading this right, the `body` won't have been set yet.

File: test/bun.js/fetch_headers.test.js [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+  });
+});
+
+async function fetchContent(headers) {
+  const res = await fetch(
+    url,
+    { headers: headers },
+    { verbose: true }
+  );
+  console.log(res.status);
```
Comment (Jarred-Sumner) [inline test/bun.js/fetch_headers.test.js]: can we remove the console.log in these tests or switch to console.debug and later we can add a transpiler transform to automatically remove those

**Comment by Jarred-Sumner** [comment]
awesome
