### PR TITLE
check if key from `exports` can be printed as an identifier

### LINKED ISSUE #3026: exports with spaces doesn't work
### What version of Bun is running?

0.6.3

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

Install https://www.npmjs.com/package/webidl-conversions

```ts
function doStuff(x, y) {
    x = conversions["boolean"](x);
    y = conversions["unsigned long"](y);
}
```

And bundle it.

Node gives the following error:

```
  exports.unsigned short = createIntegerConversion(16, { unsigned: true });
                   ^^^^^

SyntaxError: Unexpected identifier
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
    at async link (node:internal/modules/esm/module_job:68:21)

```

### What is the expected behavior?

From esbuild bundle
```ts
    exports["unsigned short"] = createIntegerConversion(16, { unsigned: true });
    exports.long = createIntegerConversion(32, { unsigned: false });
    exports["unsigned long"] = createIntegerConversion(32, { unsigned: true });
    exports["long long"] = createLongLongConversion(64, { unsigned: false });
    exports["unsigned long long"] = createLongLongConversion(64, { unsigned: true });
```

### What do you see instead?

From bun bundle
```ts
  exports.unsigned short = createIntegerConversion(16, { unsigned: true });
  exports.long = createIntegerConversion(32, { unsigned: false });
  exports.unsigned long = createIntegerConversion(32, { unsigned: true });
  exports.long long = createLongLongConversion(64, { unsigned: false });
  exports.unsigned long long = createLongLongConversion(64, { unsigned: true });
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
fixes #3026

### CODE REVIEW

File: src/js_printer.zig [hunk 1]
```diff
@@ -1988,8 +1988,14 @@ fn NewPrinter(
...
                             if (p.options.commonjs_named_exports_deoptimized or value.needs_decl) {
                                 p.printSymbol(p.options.commonjs_named_exports_ref);
-                                p.print(".");
-                                p.print(key);
+                                if (p.canPrintIdentifier(key)) {
+                                    p.print(".");
+                                    p.print(key);
+                                } else {
+                                    p.print("[\"");
+                                    p.print(key);
```
Comment (Jarred-Sumner) [inline src/js_printer.zig]: This needs to potentially be escaped if `is_ascii_only`

Comment (dylan-conway) [reply src/js_printer.zig]: 👍
