### PR TITLE
fix(bun:test): fix `toContainKeys` with undefined and null

### LINKED ISSUE #9118: Segfault when using undefined in toContainKeys matcher
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

Run the following test 

````ts
import { describe, expect, it } from "bun:test";

describe("Base", () => {
  it("contains key segfaults with undefined", () => {
    expect(undefined).toContainKeys(["id"]);
  });
});
````

### What is the expected behavior?

Test to fail

### What do you see instead?

Test runner crashes with segfault

````
test/index.test.ts:
Segmentation fault
````

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
fixes #9118 

### How did you verify your code works?
added two tests

### CODE REVIEW

File: src/bun.js/bindings/bindings.cpp [hunk 1]
```diff
@@ -2497,9 +2497,13 @@ JSC__JSValue JSC__JSValue__keys(JSC__JSGlobalObject* globalObject, JSC__JSValue
 bool JSC__JSValue__hasOwnProperty(JSC__JSValue jsValue, JSC__JSGlobalObject* globalObject, ZigString key)
 {
     JSC::VM& vm = globalObject->vm();
+    auto scope = DECLARE_THROW_SCOPE(vm);
 
     JSC::JSValue value = JSC::JSValue::decode(jsValue);
-    return value.toObject(globalObject)->hasOwnProperty(globalObject, JSC::PropertyName(JSC::Identifier::fromString(vm, Zig::toString(key))));
+    JSObject* obj = value.toObject(globalObject);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp:2503]: This potentially coerces, it should be `!isObject` and return false

Comment (Jarred-Sumner) [reply src/bun.js/bindings/bindings.cpp:2503]:
```suggestion
     if (!value.isObject()) return false;
    JSObject* obj = value.getObject();
```

File: src/bun.js/bindings/bindings.cpp [hunk 2]
```diff
@@ -2497,9 +2497,13 @@ JSC__JSValue JSC__JSValue__keys(JSC__JSGlobalObject* globalObject, JSC__JSValue
...
+    RETURN_IF_EXCEPTION(scope, false);
+
+    RELEASE_AND_RETURN(scope, obj->hasOwnProperty(globalObject, JSC::PropertyName(JSC::Identifier::fromString(vm, Zig::toString(key)))));
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp]: ->hasOwnProperty can throw when its a proxy and I think its somewhat ambiguous whether it would throw here

File: src/bun.js/bindings/bindings.cpp (hunk 1 above)
Comment (dylan-conway) [reply src/bun.js/bindings/bindings.cpp:2503]: we need to coerce because given an array or string the indexes should become properties

File: src/bun.js/bindings/bindings.cpp (hunk 2 above)
Comment (dylan-conway) [reply src/bun.js/bindings/bindings.cpp]: yeah, I think in this case it shouldn't catch the exception because `toContainKey(s)` uses `hasOwnProperty` directly, but other internal uses of this function will probably want to catch it

Comment (jdalton) [reply src/bun.js/bindings/bindings.cpp]: If it was a proxy it would cause `Object.hasOwn` to throw and `.hasOwnProperty('x')` to throw. I think it's fine to blow up here too.. we can do what WebKit does and 

https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/runtime/ObjectConstructor.cpp#L1368-L1377
then goes to:
https://github.com/WebKit/WebKit/blob/e954cf3227f1d0672e1d61645e37400059d29e58/Source/JavaScriptCore/runtime/ObjectPrototype.cpp#L103-L121

Which does capture the ` thisObject->hasOwnProperty` in a throw scope. It also leverages a cache which is neeat.

Comment (jdalton) [reply src/bun.js/bindings/bindings.cpp]: The JS implementation does an odd check,  if the object has a truthy `.hasOwnProperty` (so not a null prototype) and then calls`Object.prototype.hasOwnProperty` so works with a `null` prototype. All instead using `Object.hasOwn`. We could PR that. https://github.com/jest-community/jest-extended/blob/711fdcc54d68c2b2c1992c7cfbdf0d0bd6be0f4d/src/matchers/toContainKeys.js#L1-L6

Comment (jdalton) [reply src/bun.js/bindings/bindings.cpp]: The JS implementation allows `falsey` to pass through meaning they don't allow things like `''` or `0` to go through. I'm guessing their intention is to really only support objects but because JS is wiggly other stuff like strings is doable.

File: src/bun.js/bindings/bindings.cpp [hunk 3]
```diff
@@ -2497,9 +2497,13 @@ JSC__JSValue JSC__JSValue__keys(JSC__JSGlobalObject* globalObject, JSC__JSValue
 bool JSC__JSValue__hasOwnProperty(JSC__JSValue jsValue, JSC__JSGlobalObject* globalObject, ZigString key)
 {
     JSC::VM& vm = globalObject->vm();
+    auto scope = DECLARE_THROW_SCOPE(vm);
```
Comment (jdalton) [inline src/bun.js/bindings/bindings.cpp:2500]: ~~`hasOwnProperty` should be a separate concern from `toContainKeys`. We should use `hasOwnProperty` or equiv but not make the changes within it directly.~~

Comment (Jarred-Sumner) [reply src/bun.js/bindings/bindings.cpp:2500]: ~I think the jest implementation of `toContainKeys` calls `hasOwnProperty`~

ah you linked to it earlier

File: src/bun.js/bindings/bindings.cpp (hunk 2 above)
Comment (dylan-conway) [reply src/bun.js/bindings/bindings.cpp]: > Which does capture the ` thisObject->hasOwnProperty` in a throw scope. It also leverages a cache which is neeat.

oh nice, yeah we should use `objectPrototypeHasOwnProperty()` for the cache

Comment (dylan-conway) [reply src/bun.js/bindings/bindings.cpp]: > The JS implementation does an odd check, if the object has a truthy `.hasOwnProperty` (so not a null prototype) and then calls`Object.prototype.hasOwnProperty` so works with a `null` prototype. All instead using `Object.hasOwn`. We could PR that. https://github.com/jest-community/jest-extended/blob/711fdcc54d68c2b2c1992c7cfbdf0d0bd6be0f4d/src/matchers/toContainKeys.js#L1-L6

yep, will update to check for this before `hasOwnProperty` else it will throw when it shouldn't

File: test/js/bun/test/expect.test.js [hunk 4]
```diff
@@ -2421,6 +2424,13 @@ describe("expect()", () => {
     expect({ a: "foo", 1: "test" }).toContainKeys(["a", 1]);
     expect({ a: "foo", b: "bar", c: "baz" }).not.toContainKeys(["a", "b", "e"]);
     expect({ a: "foo", b: "bar", c: "baz" }).not.toContainKeys(["z"]);
+
```
Comment (jdalton) [inline test/js/bun/test/expect.test.js:2427]: We should add a test for `'', false` too.

File: test/js/bun/test/expect.test.js [hunk 5]
```diff
@@ -2421,6 +2424,13 @@ describe("expect()", () => {
...
+    expect(() => {
+      expect(undefined).toContainKeys(["id"]);
+    }).toThrow();
+    expect(() => {
+      expect(null).toContainKeys(["id"]);
+    }).toThrow();
```
Comment (jdalton) [inline test/js/bun/test/expect.test.js]: We could detect the actual message as the error could be anything.
```js
let m = '';
try {
    expect(null).toContainKeys(['a', 'b']);
} catch (e) { 
    m = `${e?.message}`;
}
expect(stripAnsi(m)).toMatch(new RegExp(`Received:\\s+${v}`));
```

File: src/bun.js/bindings/bindings.cpp (hunk 3 above)
Comment (jdalton) [reply src/bun.js/bindings/bindings.cpp:2500]: I see now that our `hadOwnPropertyValue` is really more generic for the JSValue which is less solid around type (ex: can detect isString but not length) so is more forgiving.

**Review by jdalton — APPROVED** [review]
If the tests pass it LGTM :)
