### PR TITLE
Encode slashes in package names in the registry manifest request

### LINKED ISSUE #5076: Private registry scoped package add fails due to forward slash not being encoded
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

MacOS - Darwin 22.1.0 x86_64 i386

### What steps can reproduce the bug?

Private NPM Registry AWS CodeArtifact, used for both private packages and to proxy public.

**bunfig.toml**
```toml
[install]
registry = {
	url = "https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/",
	token = "eabyJ2 ... w7d5Hy4A"
}
```
(also tried many, many varied configuration syntax)
```toml
[install]
registry = {
	url = "https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/:_authToken=eabyJ2 ... w7d5Hy4A"
}
```

Install **any** scoped package, for example `@storybook/addons`.

```bash
bun add @storybook/addons
```

### What is the expected behavior?

Storybook Addons package is installed successfully, enabled by a successful GET request to:

`https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/@storybook%2Faddons`

Please note the `storybook%2Faddons` forward slash is URL encoded.

### What do you see instead?

Storybook Addons package is **not** installed successfully.

GET request to:

`https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/@storybook/addons`

... results in a `400 Bad Request`

Please note the `storybook/addons` forward slash is not URL encoded.

After `bun install` all non-scoped packages install successfully, and all scoped packages are listed:

```bash
...
error: @storybook/addon-a11y@^6.5.16 failed to resolve
error: @storybook/addon-essentials@^6.5.16 failed to resolve
error: @storybook/addons@^6.5.16 failed to resolve
error: @storybook/components@^6.5.16 failed to resolve
error: @storybook/react@^6.5.16 failed to resolve
error: @storybook/theming@^6.5.16 failed to resolve
...
```

### Additional information

I think that this issue is being discussed in the comments of #643, and it may improve clarity having a dedicated issue.

While I am using AWS Code Artifact, #643 suggests it is not limited to this artifact repository.

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #5076 

Supersedes https://github.com/oven-sh/bun/pull/5484

### How did you verify your code works?

Updated a test. We also need to add integration tests for Artifactory, Azure Artifacts, and more of those, but this PR doesn't do that.

### CODE REVIEW

File: src/install/install.zig [hunk 1]
```diff
@@ -252,9 +252,22 @@ const NetworkTask = struct {
         warn_on_error: bool,
     ) !void {
         this.url_buf = blk: {
+
+            // Not all registries support scoped package names when fetching the manifest.
+            // registry.npmjs.org supports both "@storybook%2Faddons" and "@storybook/addons"
+            // Other registries like AWS codeartifact only support the former.
+            // "npm" CLI requests the the manifest with the encoded name.
```
Comment (beeb) [inline src/install/install.zig]: Typo (double "the")

Comment (Jarred-Sumner) [reply src/install/install.zig]: thanks

**Comment by beeb** [comment]
Thanks for the quick fix! This will enable evaluation of Bun at my workplace, I'm super excited.
