### PR TITLE
Fixes #12045

### LINKED ISSUE #12045: Crash when creating / setting up error handling for websockets
### How can we reproduce the crash?

1. Download this file:
```js
import { WebSocket } from 'ws'
const ws = new WebSocket('ws://localhost:8080')
ws.on('error', (error) => {
    console.error('WebSocket error:', error)
})
```
2. Run `bun install ws` in the folder with the file.
3. Run `bun run [fileName]`
4. Enjoy!

### Relevant log output

```shell
$ bun run crash.js
============================================================
Bun v1.1.15 (b23ba1fe) Windows x64
Args: "C:\Users\jack\AppData\Roaming\npm\node_modules\bun\bin\bun.exe" "run" "crash.js"
Features: jsc WebSocket 
Builtins: "bun:main" "node:string_decoder" "node:util/types" "ws" 
Elapsed: 96ms | User: 31ms | Sys: 31ms
RSS: 120.41MB | Peak: 120.41MB | Commit: 0.17GB | Faults: 29631

panic(main thread): attempt to use null value
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.15/wr1b23ba1fAiggggQ+0loJ62sqJ2vmu9C+vk5sB______A0eNpLLClJzS0oUSjJVygtTlXIK83JUShLzClNBQB82AmI
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on windows x86_64 [RunCommand]

**panic**: attempt to use null value

- [`ConsoleObject.zig:3126`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/ConsoleObject.zig#L3126>): `format`
- [`ConsoleObject.zig:798`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/ConsoleObject.zig#L798>): `format2`
- `??`
- [`utility:762`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.39.33519/include/utility#L762>): `std::exchange`
- *6 unknown/js code*

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #12045
Fixes https://github.com/oven-sh/bun/issues/11095

### How did you verify your code works?

There is a test

### CODE REVIEW

File: src/bun.js/bindings/webcore/WebSocket.cpp [hunk 1]
```diff
@@ -30,6 +30,8 @@
  */
 
 #include "config.h"
+#include "EventInit.h"
```
Comment (dylan-conway) [inline src/bun.js/bindings/webcore/WebSocket.cpp]: I don't think these are needed

**Review by dylan-conway — APPROVED** [review]
