### PR TITLE
fix(install): lockfile printing bugfix

### LINKED ISSUE #11535: Running `bun bun.lockb` crashes on certain repo's
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

I'm trying to figure out why my `bun bun.lockb` command crashes on certain repo's because this is causing an error when using nx, because they read the contents of the file for determening change detection. 

Thread on nx's github:  https://github.com/nrwl/nx/issues/26053
Example package.json that doesn't work: https://gist.github.com/cskiwi/0791fbd77c3845327ec37f6e2222f912

### What is the expected behavior?

That the  `bun bun.lockb` would always have an output

### What do you see instead?

```
he "nx/js/dependencies-and-lockfile" plugin threw an error while creating nodes from bun.lockb:
    Error: Command failed: bun <redacted>\bun.lockb
    ============================================================
    Bun v1.1.12 (43f0913c) Windows x64
    Args: "bun" "<redacted>\bun.lockb"
    Elapsed: 5ms | User: 0ms | Sys: 0ms
    RSS: 23.47MB | Peak: 23.47MB | Commit: 62.63MB | Faults: 5881
    
    panic(main thread): Internal assertion failure
    oh no: Bun has crashed. This indicates a bug in Bun, not your code.

    To send a redacted crash report to Bun's team,
    please file a GitHub issue using the link below:

     https://bun.report/1.1.12/wa143f0913AAghg+L+3pzIwi67F+8vC2mn1Fw7r1Fmty2Fqi4BiiJow6y+CA0eNrzzCtJLcpLzFFILC5OLSrJzM9TSEvMzCktSgUAiSkKPg


        at genericNodeError (node:internal/errors:983:15)
        at wrappedFn (node:internal/errors:537:14)
        at checkExecSyncError (node:child_process:889:11)
        at execSync (node:child_process:961:15)
        at Array.exports.createNodes (<redacted>\node_modules\nx\src\plugins\js\index.js:40:44)
        at <redacted>\node_modules\nx\src\project-graph\plugins\utils.js:49:54
        at Array.map (<anonymous>)
        at runCreateNodesInParallel (<redacted>\node_modules\nx\src\project-graph\plugins\utils.js:47:34)
        at LoadedNxPlugin.createNodes (<redacted>\node_modules\nx\src\project-graph\plugins\internal-api.js:23:74)
        at createProjectConfigurations (<redacted>\node_modules\nx\src\project-graph\utils\project-configuration-utils.js:253:17
```
### Additional information

This doesn't seem to happen on linux, but does on windows and most likely on mac (the user in thread did get some different errors, but might be related)

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
fixes two things:
- frees the correct pointer after printing lockfile in yarn format
  - fixes #11535 
- if there's a duplicate optional dependency, ensures the sorted dependencies remain sorted

### How did you verify your code works?
Added a test installing a package with a duplicate optional dependency. Previously `bun bun.lockb` would print multiple sections for `dependencies` because one normal dependency was swapped with the duplicate optional.

### CODE REVIEW

File: src/install/lockfile.zig [hunk 1]
```diff
@@ -3470,9 +3471,17 @@ pub const Package = extern struct {
                 list: for (keys, version_strings, 0..) |key, version_string_, i| {
                     // Duplicate peer & dev dependencies are promoted to whichever appeared first
                     // In practice, npm validates this so it shouldn't happen
-                    if (comptime group.behavior.isPeer() or group.behavior.isDev()) {
-                        for (dependencies[0..total_dependencies_count]) |dependency| {
-                            if (dependency.name_hash == key.hash) continue :list;
+                    var duplicate_at: ?usize = null;
+                    if (comptime group.behavior.isPeer() or group.behavior.isDev() or group.behavior.isOptional()) {
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig:3475]: I think we only need this check if it isOptional right? Because the inner for loop only breaks if isOptional

Comment (dylan-conway) [reply src/install/lockfile.zig:3475]: We want peer and dev dependencies to enter the loop as well, because they will hit `continue :list;`. It would probably be more clear like `if (!group.behavior.isNormal()) { ... }`
