### PR TITLE
fix: make node:crypto Hash.copy work correctly

### LINKED ISSUE #2651: node crypto Hash.copy is incorrect
node docs https://nodejs.org/api/crypto.html#hashcopyoptions

image

this implementation is definitely not correct. though they describe something that isn't easy for us to implement in a single line. we need a "deep copy of the internal state of the current Hash object" which this doesn't do at all. just returns a new copy with the same settings, and it's not even a hash object.

### PR DESCRIPTION
**Pull request by silversquirl**
This commit will also:
- add a CryptoHasher.copy function
- make CryptoHasher.digest reset the hasher so it can be reused

Resolves #2651

### CODE REVIEW

**Review by Jarred-Sumner — APPROVED** [review]
LGTM

Note there will be some unrelated test failures (mostly bundler stuff that hasn't been fixed)

Let's merge after CI runs

File: packages/bun-types/bun.d.ts [hunk 1]
```diff
@@ -2204,7 +2204,12 @@ declare module "bun" {
     update(input: StringOrBuffer, inputEncoding?: CryptoEncoding): CryptoHasher;
 
     /**
-     * Finalize the hash
```
Comment (Jarred-Sumner) [inline packages/bun-types/bun.d.ts:2207]: nice catch
