### PR TITLE
Fixes #11677

### LINKED ISSUE #11677: Segfault when passing empty string toContainKeys matcher
### How can we reproduce the crash?

````tsx
test.only('keymatcher segfault', () => {
  // Issue is the empty string argument
  expect({}).toContainKeys(['']);
});
````

Similar to earlier issue https://github.com/oven-sh/bun/issues/9118

### Relevant log output

_No response_

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [TestCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::Unicode::convertReplacingInvalidSequences`
- `??`
- [`array_list.zig:859`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/array_list.zig#L859>): `ExpectPrototype__toContainKeys`
- [`ZigGeneratedClasses.cpp:14372`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/build/codegen/ZigGeneratedClasses.cpp#L14372>): `WebCore::ExpectPrototype__toHaveBeenNthCalledWithCallback`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `llint_op_call_varargs_wide16`
- *3 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `llint_relativePCBase`

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #11677 

Speculative fix for a crash when copying headers

I don't think we ever need to call `link`

### CODE REVIEW

**Comment by birkskyum** [comment]
Latest commit on main looks like this:

```sh
[Subprocess] updateHasPendingActivity() true - true
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/routing.js) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/routing.js) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/routing.js])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/utils.js) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/utils.js) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/utils.js])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/routing.js) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/routing.js) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/@solidjs/router/dist/routing.js])
[napi] napi_get_value_bool
[napi] napi_create_promise
[napi] napi_create_string_utf8: napi_rs_async_work
[napi] napi_create_async_work
[napi] napi_queue_async_work
[Loop] ref 1000 + 1 = 1001
[napi] napi_get_value_bool
[napi] napi_create_promise
[napi] napi_create_string_utf8: napi_rs_async_work
[napi] napi_create_async_work
[napi] napi_queue_async_work
[Loop] ref 1001 + 1 = 1002
[FileReader] onPull(16384) = pending
[napi] napi_resolve_deferred
[napi] napi_delete_async_work
[Loop] sub 10 - 1 = 9
[napi] napi_resolve_deferred
[napi] napi_delete_async_work
[Loop] sub 9 - 1 = 8
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/dist/server.js) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/dist/server.js) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/dist/server.js])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/dist/package.json) = -1
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/package.json) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/package.json) = 38
[SYS] fstat(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/package.json]) = 0
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/package.json], 1331) = 1315 (0.011ms)
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/package.json], 16) = 0 (0.002ms)
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/solid-js/store/package.json])
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/package.json) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/package.json])
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/package.json) = 38
[SYS] fstat(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/package.json]) = 0
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/package.json], 158102) = 158086 (0.016ms)
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/package.json], 16) = 0 (0.002ms)
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/package.json])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/index.mjs) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/index.mjs) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/date-fns/index.mjs])
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json])
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json) = 38
[SYS] fstat(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json]) = 0
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json], 3581) = 3565 (0.003ms)
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json], 16) = 0 (0.002ms)
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/lib/marked.esm.js) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/lib/marked.esm.js) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/lib/marked.esm.js])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/lib/package.json) = -1
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json) = 38
[SYS] fstat(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json]) = 0
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json], 3581) = 3565 (0.003ms)
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json], 16) = 0 (0.001ms)
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/marked/package.json])
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/package.json) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/package.json])
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/package.json) = 38
[SYS] fstat(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/package.json]) = 0
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/package.json], 4056) = 4040 (0.003ms)
[SYS] read(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/package.json], 16) = 0 (0.001ms)
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/package.json])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/dist/index.mjs) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/dist/index.mjs) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/dist/index.mjs])
[SYS] stat(/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/drivers/fs-lite.mjs) = 0
[SYS] openat(-2, /Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/drivers/fs-lite.mjs) = 38
[SYS] close(38[/Users/admin/repos/bun-kitchensink/nodtes/node_modules/unstorage/drivers/fs-lite.mjs])
[h3] [unhandled] 1 | export default "native";
    ^
error: Unexpected end of JSON input
      at json (native:1:1)
      at asyncFunctionResume (:1:11)
      at promiseReactionJobWithoutPromiseUnwrapAsyncContext (:1:11)
      at promiseReactionJob (:1:11)
      at native:1:1

1 | export default "native";
    ^
SyntaxError: Unexpected end of JSON input
      at json (native:1:1)
      at asyncFunctionResume (:1:11)
      at promiseReactionJobWithoutPromiseUnwrapAsyncContext (:1:11)
      at promiseReactionJob (:1:11)
      at native:1:1


```

File: src/bun.js/modules/NodeModuleModule.h [hunk 1]
```diff
@@ -528,7 +528,7 @@ DEFINE_NATIVE_MODULE(NodeModule) {
 
   auto prototype = constructEmptyObject(globalObject, globalObject->objectPrototype(), 1);
   prototype->putDirectCustomAccessor(
-    vm, JSC::Identifier::fromString(vm, "require"_s),
+    vm, WebCore::clientData(vm)->builtinNames().requirePublicName(),
```
Comment (dylan-conway) [inline src/bun.js/modules/NodeModuleModule.h:531]: I think we should also do this in `CommonJSModuleRecord.cpp` in `evaluateCommonJSModuleOnce`

**Review by cirospaciari — APPROVED** [review]
