### PR TITLE
use `options.fd` if provided for `fs.Read/WriteStream`

### LINKED ISSUE #3099: @clack/prompts module is not working
### What version of Bun is running?

0.6.4

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

`bun i @clack/prompts`

Create `index.js` file :
```
import { text } from '@clack/prompts';
await text({
	message: "What is your best JS runtime ?"
})
```

`bun index.js`


### What is the expected behavior?

We should see a prompt in our CLI.

### What do you see instead?


```
4 | `&&(s&&n&&(e+=N(s)),C&&(e+=j(C)))}return e};function P(t,u,F){return String(t).normalize().replace(/\r\n/g,`
5 | `).split(`
6 | `).map(e=>uD(e,u,F)).join(`
7 | `)}function FD(t,u){if(t===u)return;const F=t.split(`
8 | `),e=u.split(`
9 | `),s=[];for(let C=0;C<Math.max(F.length,e.length);C++)F[C]!==e[C]&&s.push(C);return s}const R=Symbol("clack:cancel");function eD(t){return t===R}function g(t,u){t.isTTY&&t.setRawMode(u)}const V=new Map([["k","up"],["j","down"],["h","left"],["l","right"]]),tD=new Set(["up","down","left","right","space","enter"]);class h{constructor({render:u,input:F=k,output:e=y,...s},C=!0){this._track=!1,this._cursor=0,this.state="initial",this.error="",this.subscribers=new Map,this._prevFrame="",this.opts=s,this.onKeypress=this.onKeypress.bind(this),this.close=this.close.bind(this),this.render=this.render.bind(this),this._render=u.bind(this),this._track=C,this.input=F,this.output=e}prompt(){const u=new O(0);return u._write=(F,e,s)=>{this._track&&(this.value=this.rl.line.replace(/\t/g,""),this._cursor=this.rl.cursor,this.emit("value",this.value)),s()},this.input.pipe(u),this.rl=S.createInterface({input:this.input,output:u,tabSize:2,prompt:"",escapeCodeTimeout:50}),S.emitKeypressEvents(this.input,this.rl),this.rl.prompt(),this.opts.initialValue!==void 0&&this._track&&this.rl.write(this.opts.initialValue),this.input.on("keypress",this.onKeypress),g(this.input,!0),this.output.on("resize",this.render),this.render(),new Promise((F,e)=>{this.once("submit",()=>{this.output.write(x.show),this.output.off("resize",this.render),g(this.input,!1),F(this.value)}),this.once("cancel",()=>{this.output.write(x.show),this.output.off("resize",this.render),g(this.input,!1),F(R)})})}on(u,F){const e=this.subscribers.get(u)??[];e.push({cb:F}),this.subscribers.set(u,e)}once(u,F){const e=this.subscribers.get(u)??[];e.push({cb:F,once:!0}),this.subscribers.set(u,e)}emit(u,...F){const e=this.subscribers.get(u)??[],s=[];for(const C of e)C.cb(...F),C.once&&s.push(()=>e.splice(e.indexOf(C),1));for(const C of s)C()}unsubscribe(){this.subscribers.clear()}onKeypress(u,F){if(this.state==="error"&&(this.state="active"),F?.name&&!this._track&&V.has(F.name)&&this.emit("cursor",V.get(F.name)),F?.name&&tD.has(F.name)&&this.emit("cursor",F.name),u&&(u.toLowerCase()==="y"||u.toLowerCase()==="n")&&this.emit("confirm",u.toLowerCase()==="y"),u&&this.emit("key",u.toLowerCase()),F?.name==="return"){if(this.opts.validate){const e=this.opts.validate(this.value);e&&(this.error=e,this.state="error",this.rl.write(this.value))}this.state!=="error"&&(this.state="submit")}u===""&&(this.state="cancel"),(this.state==="submit"||this.state==="cancel")&&this.emit("finalize"),this.render(),(this.state==="submit"||this.state==="cancel")&&this.close()}close(){this.input.unpipe(),this.input.removeListener("keypress",this.onKeypress),this.output.write(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ^
error: Not implemented yet
      at prompt (/Users/zouloux/Documents/local/lab/bun-clack/node_modules/@clack/core/dist/index.mjs:9:692)
      at /Users/zouloux/Documents/local/lab/bun-clack/index.js:3:6
```
      

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?

Allows `fd` to be used when creating `fs.ReadStream` and `fs.WriteStream`. Also includes a fix for `@clack/prompts`.

fixes #3099 

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

added tests.

### CODE REVIEW

File: src/js/node/fs.js [hunk 1]
```diff
@@ -772,12 +785,9 @@ WriteStream = (function (InternalWriteStream) {
           (start === undefined || start === 0) &&
           fs.write === defaultWriteStreamOptions.fs.write &&
           fs.close === defaultWriteStreamOptions.fs.close;
-      } else {
-        tempThis.fd = fd;
-        tempThis[writeStreamPathFastPathSymbol] = false;
       }
 
-      if (!tempThis.fd) {
+      if (tempThis.fd === null || tempThis.fd === undefined) {
```
Comment (Jarred-Sumner) [inline src/js/node/fs.js]: `== null`

File: src/js/node/tty.js [hunk 2]
```diff
@@ -4,7 +4,9 @@ function ReadStream(fd) {
   if (!(this instanceof ReadStream)) return new ReadStream(fd);
   if (fd >> 0 !== fd || fd < 0) throw new RangeError("fd must be a positive integer");
 
-  const stream = require("node:fs").ReadStream.call(this, `/dev/fd/${fd}`);
+  const stream = require("node:fs").ReadStream.call(this, "", {
```
Comment (Jarred-Sumner) [inline src/js/node/tty.js:7]: empty string?

File: src/js/node/fs.js [hunk 3]
```diff
@@ -416,7 +417,13 @@ ReadStream = (function (InternalReadStream) {
 
       // This is kinda hacky but we create a temporary object to assign props that we will later pull into the `this` context after we call super
       var tempThis = {};
-      if (typeof pathOrFd === "string") {
+      if (fd !== null) {
+        if (typeof options.fd !== "number") {
```
Comment (Jarred-Sumner) [inline src/js/node/fs.js]:
```suggestion
        if (typeof fd !== "number") {
```

File: src/js/node/fs.js [hunk 4]
```diff
@@ -416,7 +417,13 @@ ReadStream = (function (InternalReadStream) {
...
+          throw new TypeError("Expected options.fd to be a number");
+        }
+        tempThis.fd = tempThis[readStreamPathOrFdSymbol] = options.fd;
```
Comment (Jarred-Sumner) [inline src/js/node/fs.js]:
```suggestion
        tempThis.fd = tempThis[readStreamPathOrFdSymbol] = fd;
```

File: src/js/node/fs.js [hunk 5]
```diff
@@ -416,7 +417,13 @@ ReadStream = (function (InternalReadStream) {
 
       // This is kinda hacky but we create a temporary object to assign props that we will later pull into the `this` context after we call super
       var tempThis = {};
-      if (typeof pathOrFd === "string") {
+      if (fd !== null) {
```
Comment (Jarred-Sumner) [inline src/js/node/fs.js]: `!= null`?

**Comment by Jarred-Sumner** [comment]
Thank you
