### PR TITLE
fix(shell): handle cwd paths with non ascii characters

### LINKED ISSUE #10398: Error during bun install on Windows [bunsh: No such file or directory]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### Install Bun using this command

`powershell -c "irm bun.sh/install.ps1|iex"`

#### Try bootstraping t4-app

`bun create t4-app@2.4.1`

image

### What is the expected behavior?

Command execution should end successfully with no errors

### What do you see instead?

image

### Additional information

Some info from t4-app discord channel 
image

### LINKED ISSUE #11324: "bun run dev" not run
### How can we reproduce the crash?

bun create vue@latest
bun install
bun run dev

### JavaScript/TypeScript code that reproduces the crash?

```shell
{
  "name": "test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "typescript": "^5.2.2",
    "vite": "^5.2.0",
    "vue-tsc": "^2.0.6"
  }
}
```

### Relevant log output

```shell
bun run dev
$ vite
error: Failed due to error: bunsh: No such file or directory:
```

### Stack Trace (bun.report)

 bun run dev
$ vite
error: Failed due to error: bunsh: No such file or directory:

### LINKED ISSUE #11802: bun install & bun run unexpected behavior on Windows caused by special characters such as öäü...
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

When you run _bun install_ in a project where the path contains a special character like in my case **ö** every time bun should run a script you receive the following error message: **bunsh: No such file or directory:**. 

Example path: D:\Projects\Websites\ö\landing-page
Working example path: D:\Projects\Websites\oe\landing-page
landing-page is the project root with the package.json

### What is the expected behavior?

Expected is that bun install and bun run works the same for paths containing special characters

### What do you see instead?

_No response_

### Additional information

_No response_

### LINKED ISSUE #11852: Creating a project with vite, bun is giving me problems to install the packages, how I can
### How can we reproduce the crash?

I am using vite to create a project with Vuejs, as development environment I am using Bun but when I install the packages with the command "bun install" I get the following error:

bun install v1.1.13 (bd6a6051)
  ⚙️  esbuild [1/1] error: Failed due to error: bunsh: No such file or directory:

error: postinstall script from "esbuild" exited with 1

I am using bun version 1.1.13 for windows and I am using powershell to execute my commands, is there any way to solve the problem to install the packages using Bun?

I used the command "pnpm install" and I was able to successfully install the packages without problems, but I don't understand why using the bun package manager gives me problems, here I share a screenshot.

any solution for this issue?
2024-06-13_14h03_05

### Relevant log output

```shell
➜ bun install
bun install v1.1.13 (bd6a6051)
  ⚙️  esbuild [1/1] error: Failed due to error: bunsh: No such file or directory:

error: postinstall script from "esbuild" exited with 1
```

### Stack Trace (bun.report)

➜ bun install
bun install v1.1.13 (bd6a6051)
  ⚙️  esbuild [1/1] error: Failed due to error: bunsh: No such file or directory:

error: postinstall script from "esbuild" exited with 1

### LINKED ISSUE #11891: bunsh: No such file or directory:
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

win10 22H2 x

### What steps can reproduce the bug?

两个一样的项目，一个项目包含中文路径，执行脚本指令，就会找不到环境，如果直接执行 bun run vite 则是可以的
如果没有包含中文路径，则一切正常
Two identical projects, one with a Chinese path, cannot find the environment when executing script commands. However, if you directly execute bun run vite, it works fine. If there is no Chinese path, everything works normally.

### What is the expected behavior?

我希望项目路径包含中文，可以正常执行脚本指令
I hope the project path can include Chinese characters and still execute script commands normally.

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
`getcwd` can return non ascii characters if they are in the current working directory path. This switches to `GetCurrentDirectoryW` on windows and converts it to utf8. libuv expects utf8 input.

fixes error like: 
```
error: bunsh: No such file or directory
```

fixes #11891 
fixes #11852 
fixes #11324 
fixes #11802 
fixes #10398 

### How did you verify your code works?
added a test

### CODE REVIEW

File: src/sys.zig [hunk 1]
```diff
@@ -345,18 +345,23 @@ pub fn Maybe(comptime ReturnTypeT: type) type {
...
-        Result.errnoSys(0, .getcwd).?;
+    return switch (getcwdZ(buf)) {
+        .err => |err| Result{ .err = err },
+        .result => |cwd| Result{ .result = cwd },
+    };
 }
 
 pub fn getcwdZ(buf: *bun.PathBuffer) Maybe([:0]const u8) {
     const Result = Maybe([:0]const u8);
     buf[0] = 0;
```
Comment (dylan-conway) [inline src/sys.zig:356]: is this necessary?

Comment (Jarred-Sumner) [reply src/sys.zig:356]: I don't think so, but it does ensure that even if it returns an empty string, the buffer is zero sentineled
