### PR TITLE
Fix crash when `napi_register_module_v1` returns `nullptr`

### LINKED ISSUE #16766: import duckdb crashs bun
### How can we reproduce the crash?

bun repl
> import {Database} from 'duckdb'; //"duckdb": "^1.1.3",

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.2.0 ([`b0c5a76`](<https://github.com/oven-sh/bun/tree/b0c5a7655dac9040655a22754c5eab91046e923b>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/b0c5a7655dac9040655a22754c5eab91046e923b/ld-temp.o#L0>): `llint_op_call_ignore_result`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/b0c5a7655dac9040655a22754c5eab91046e923b/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/b0c5a7655dac9040655a22754c5eab91046e923b/ld-temp.o#L0>): `llint_call_javascript`
- [`Interpreter.cpp:1278`](<https://github.com/oven-sh/bun/blob/b0c5a7655dac9040655a22754c5eab91046e923b//webkitbuild/vendor/WebKit/Source/JavaScriptCore/interpreter/Interpreter.cpp#L1278>): `JSC::Interpreter::executeCall`
- [`CallData.cpp:57`](<https://github.com/oven-sh/bun/blob/b0c5a7655dac9040655a22754c5eab91046e923b//webkitbuild/vendor/WebKit/Source/JavaScriptCore/runtime/CallData.cpp#L57>): `JSC::profiledCall`
- [`CommonJSModuleRecord.cpp:203`](<https://github.com/oven-sh/bun/blob/b0c5a7655dac9040655a22754c5eab91046e923b/src/bun.js/bindings/CommonJSModuleRecord.cpp#L203>): `Bun::evaluateCommonJSModuleOnce`

Features: process\_dlopen, Bun.stderr, Bun.stdin, Bun.stdout, WebSocket, bunfig, dotenv, http\_server, jsc, transpiler\_cache, tsconfig, tsconfig

### PR DESCRIPTION
**Pull request by 190n**
### What does this PR do?

Ensures that if `napi_register_module_v1` returns `nullptr`, we use the `exports` object as the return value of `require()`. This matches Node.js behavior.

Fixes #16766

### How did you verify your code works?

- [x] I included a test for the new code, or existing tests cover it
- [x] I ran my tests locally and they pass (`bun-debug test test-file-name.test`)

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 3:09 PM PT - Jan 27th, 2025</sup></div>

@190n, your commit 42bf4fc8fd666a241cdfe57ce1b6641443beba6c is building: [`#10661`](https://buildkite.com/bun/bun/builds/10661)

File: src/bun.js/bindings/BunProcess.cpp [hunk 1]
```diff
@@ -438,6 +438,12 @@ JSC_DEFINE_HOST_FUNCTION(Process_functionDlopen, (JSC::JSGlobalObject * globalOb
 
     EncodedJSValue exportsValue = JSC::JSValue::encode(exports);
     JSC::JSValue resultValue = JSValue::decode(napi_register_module_v1(globalObject, exportsValue));
+    // If a module returns `nullptr` (cast to a napi_value) from its register function, we should
+    // use the `exports` value (which may have had properties added to it) as the return value of
+    // `require()`.
+    if (resultValue.isEmpty()) {
+        resultValue = exports;
+    }
```
Comment (paperclover) [inline src/bun.js/bindings/BunProcess.cpp:447]: i feel like we should also `RETURN_IF_EXCEPTION`, or more specifically move the one on line 466 here, then add a second `RETURN_IF_EXCEPTION` after line 462 `ASSERT(success)`

**Review by paperclover — CHANGES_REQUESTED** [review]

File: src/bun.js/bindings/BunProcess.cpp (hunk 1 above)
Comment (190n) [reply src/bun.js/bindings/BunProcess.cpp:447]: done

**Review by paperclover — APPROVED** [review]
