### PR TITLE
Fix error when null/undefined is passed to stdio in spawn/spawnSync

### LINKED ISSUE #8095: bun 1.0.22 breaks child_process spawn() / spawnSync() - Invalid stdio option "null"
### What version of Bun is running?

1.0.22

### What platform is your computer?

Linux 5.15.0-67-generic x86_64 x86_64 - ubuntu 22.04

### What steps can reproduce the bug?

-

### What is the expected behavior?

-

### What do you see instead?

```js
@yusham:00-cup/bun-play> cat ./subprocess.js 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ./subprocess.js
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ import cp from 'child_process';
   2   │ 
   3   │ 
   4   │ cp.spawnSync('ls', ['-lagh'], {stdio: [null, 'inherit', null]})
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@yusham:00-cup/bun-play> bun ./subprocess.js 
1 | import cp from 'child_process';
2 | 
3 | 
4 | cp.spawnSync('ls', ['-lagh'], {stdio: [null, 'inherit', null]})
                        ^
error: Invalid stdio option "null"
      at node:child_process:357:47
      at map (:1:21)
      at node:child_process:173:47
      at /data/www/00-cup/bun-play/subprocess.js:4:1
@yusham:00-cup/bun-play> 
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Electroid**
### What does this PR do?

Fixes #8095 

- Fixed `spawn/Sync({ stdio: [null/undefined] })` being an error
- Fixed `spawn/Sync().stdout/error` being undefined instead of null (match Node.js)
- Fixed `spawn().stdio` incorrectly being an object, instead of an array

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Added regression tests.

### CODE REVIEW

File: src/js/node/child_process.js [hunk 1]
```diff
@@ -1327,16 +1331,22 @@ const nodeToBunLookup = {
   ipc: "ipc",
 };
 
-function nodeToBun(item) {
+function nodeToBun(item, index) {
+  // If not defined, use the default.
+  // For stdin/stdout/stderr, it's pipe. For others, it's ignore.
+  if (item === undefined || item === null) {
```
Comment (Jarred-Sumner) [inline src/js/node/child_process.js]:
```suggestion
  if (item == null) {
```

**Comment by Jarred-Sumner** [comment]
I think we could also allow `null` or `undefined` in the Bun.spawn implementation itself fwiw

**Comment by Electroid** [comment]
> I think we could also allow `null` or `undefined` in the Bun.spawn implementation itself fwiw

I noticed there was a bug with this, but didn't get to it. Looks like `null` to `Bun.spawn` is not ignoring, but using the default instead.
