### PR TITLE
Several bug fixes

### LINKED ISSUE #874: Creating Request from existing Request
### Version

0.1.5

### Platform

Darwin XXX-MBP.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Run code:
```ts
console.log(new Request(new Request('https://example.com'), {}).url)
//                                                          ⬆️ if removes this arg, then it works!  
```
And got this result:
```
❯ bun test-bun.ts
[object Request]
```

### How often does it reproduce? Is there a required condition?

Always, just run the same code I provided.

### What is the expected behavior?

It should be the URL of the existing request object: (Running on Chrome / Safari / node 18)
```
console.log(new Request(new Request('https://example.com')).url)
> https://example.com/
```

### What do you see instead?

```
❯ bun test-bun.ts
[object Request]
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
Fixes a crash on code like this:

```js
 expect(() => { throw Symbol("toString can throw"); }).toThrow()`
```

Fixes #874

Fixes merging behavior with `new Request(req1, req2)`

### CODE REVIEW

**Comment by dylan-conway** [comment]
`globals.test.js` needs an update too, `Request()` line 8

File: src/bun.js/webcore/response.zig [hunk 1]
```diff
@@ -731,7 +739,13 @@ pub const Fetch = struct {
 
             const fetch_error = JSC.SystemError{
                 .code = ZigString.init(@errorName(this.result.fail)),
-                .message = ZigString.init("fetch() failed"),
+                .message = switch (this.result.fail) {
+                    error.ConnectionClosed => ZigString.init("The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()"),
+                    error.FailedToOpenSocket => ZigString.init("Was there a typo in the url or port?"),
+                    error.TooManyRedirects => ZigString.init("The response redirected too many times. For more information, pass `verbose: true` in the second argument to fetch()"),
+                    error.ConnectionRefused => ZigString.init("Unable to connect. Is the computer able to access the url?"),
```
Comment (rehevkor5) [inline src/bun.js/webcore/response.zig:746]: The "Is the computer able to access the url?" part is awkward/strange/unusual, especially from the perspective of a web service. The client might get this error and not know what computer you're referring to, or how to determine whether it can "access the url" (whatever that means).

If the error is connection refused, I think the error text should be "Connection refused."
