### PR TITLE
Fix crash when FFI pointers are encoded as ints

### LINKED ISSUE #18750: Bun crash on read of FFI char ** output
### How can we reproduce the crash?

This crash happens on every bun version since 1.1.21 (1.1.20 and lower is working fine).

The crash is caused by new CString(ptr) where ptr is an element from an array of pointer serving as a char ** out parameter of a c++ FFI function.

Inside the c++ code the char ** is filled using the c_str() method of a std:string stored in a class that is not garbage collected until way after the crash (proof being that everything works in bun 1.1.20).

In bun 1.1.20 the pointer inside the array look like 102412420687320 and the pointer of the actual array is of a similar 131254905405664 but when using a newer version like bun 1.2.8, the pointer causing the crash look very different (ex: 611222776) while the array pointer is of the usual format (ex: 128783570977072).

### Relevant log output

```shell
Bun v1.2.8 (adab0f64) Linux x64
Linux Kernel v6.12.10 | glibc v2.41
CPU: sse42 popcnt avx avx2 avx512
Args: "bun" "./test/script/processAlarms.ts"
Features: Bun.stderr(2) Bun.stdout(2) fetch jsc transpiler_cache(6) tsconfig(3) tsconfig_paths 
Builtins: "bun:ffi" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:domain" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:net" "node:os" "node:path" "node:process" "node:querystring" "node:stream" "node:timers" "node:tls" "node:tty" "node:url" "node:util" "node:zlib" "node:dgram" "node:cluster" 
Elapsed: 495ms | User: 380ms | Sys: 43ms
RSS: 1.06GB | Peak: 132.46MB | Commit: 1.06GB | Faults: 3

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.2.8 ([`adab0f6`](<https://github.com/oven-sh/bun/tree/adab0f64f97c9240026df715006b7a0c42658069>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`FFIObject.zig:2`](<https://github.com/oven-sh/bun/blob/adab0f64f97c9240026df715006b7a0c42658069/src/bun.js/api/FFIObject.zig#L2>): `bun.js.bindings.bindings.toJSHostFunction__struct_1222670.function`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/adab0f64f97c9240026df715006b7a0c42658069/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/adab0f64f97c9240026df715006b7a0c42658069/ld-temp.o#L0>): `llint_op_construct`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/adab0f64f97c9240026df715006b7a0c42658069/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/adab0f64f97c9240026df715006b7a0c42658069/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/adab0f64f97c9240026df715006b7a0c42658069/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/adab0f64f97c9240026df715006b7a0c42658069/ld-temp.o#L0>): `llint_op_call_ignore_result`

Features: tsconfig, tsconfig\_paths, Bun.stderr, Bun.stdout, fetch, jsc

### PR DESCRIPTION
**Pull request by 190n**
### What does this PR do?

We used to always try reading pointers as doubles. This breaks if you have a pointer that is int32 encoded. Now we permit either numeric encoding.

Fixes #18750

I also cleaned up some JSValue bindings that were near the fix.

### How did you verify your code works?

There is a test.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 2:02 PM PT - Jun 12th, 2025</sup></div>

@190n, your commit 770461f9bdecb5248a57582f1c64f1019bdc2de3 is building: [`#18567`](https://buildkite.com/bun/bun/builds/18567)

File: src/bun.js/bindings/JSValue.zig [hunk 1]
```diff
@@ -2008,46 +2004,37 @@ pub const JSValue = enum(i64) {
...
-        return jsNumber(@as(f64, @floatFromInt(@as(usize, @bitCast(@as(usize, addr))))));
+    /// Encodes addr as a double. Resulting value can be passed to asPtrAddress.
+    pub fn fromPtrAddress(addr: usize) JSValue {
+        return jsDoubleNumber(@floatFromInt(addr));
     }
 
+    /// Interprets a numeric JSValue as a pointer address. Use on values returned by fromPtrAddress.
     pub fn asPtrAddress(this: JSValue) usize {
-        return @as(usize, @bitCast(@as(usize, @intFromFloat(this.asDouble()))));
+        return @intFromFloat(this.asNumber());
```
Comment (190n) [inline src/bun.js/bindings/JSValue.zig:2038]: changing `asDouble` to `asNumber` is the actual fix

**Review by cirospaciari — APPROVED** [review]
