### PR TITLE
CSS fix bug with merging style rules, fix unnecessary backslash, more tests

### LINKED ISSUE #16572: The bundler adds a backslash after each escape sequence in css strings.
### What version of Bun is running?

1.1.45+196621f25

### What platform is your computer?

Linux 6.12.9_1 x86_64 unknown

### What steps can reproduce the bug?

```css
/* repro.css */
.foo {
    content: "\2b";
}
```

Run `bun build --experimental-css repro.css`.

### What is the expected behavior?

Output should be
```css
/* repro.css */
.foo {
  content: "+";
}
```

### What do you see instead?

Output is
```css
/* repro.css */
.foo {
  content: "+\\";
}
```

### Additional information

_No response_

### LINKED ISSUE #16596: css parsing is merging two unrelated flex class selectors in one
### What version of Bun is running?

1.2.0+b0c5a7655

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

This is regarding bundling with `index.html` file as entry point. Create a styles.css with below content which is linked in `index.html`.

```css
.flexrow {
	flex-direction: row;
}

.flexcol {
	flex-direction: column;
}

.hello {
	flex-wrap: wrap;
}

.world {
	flex-wrap: nowrap;
}
```

Run build - 

```sh
bun build ./index.html --outdir=dist
```

### What is the expected behavior?

The generated build file should have the same css as defined.

### What do you see instead?

The generated style file in the dist folder has the below content which is not correct.

```css
.flexrow, .flexcol {
  flex-direction: row;
}

.hello, .world {
  flex-wrap: wrap;
}
```

### PR DESCRIPTION
**Pull request by zackradisic**
### What does this PR do?

Fixes #16572
Fixes #16596

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 6:09 PM PT - Jan 22nd, 2025</sup></div>

@zackradisic, your commit 3c0767608d96e95c1ee6ac3e4585e875ccfab1f7 is building: [`#10363`](https://buildkite.com/bun/bun/builds/10363)

File: src/css/properties/flex.zig [hunk 1]
```diff
@@ -397,390 +422,423 @@ pub const FlexLinePack = enum {
...
+            }
+        }
+
+        this.singleProperty("flex-grow", bun.take(&grow), "flex-positive", null, dest, context, "flex_grow");
+        this.singleProperty("flex-shrink", bun.take(&shrink), "flex-negative", null, dest, context, "flex_shrink");
+        this.singleProperty("flex-basis", bun.take(&basis), "flex-preferred-size", null, dest, context, "flex_basis");
+        this.singleProperty("order", bun.take(&order), "flex-order", .{ BoxOrdinalGroup, "box-ordinal-group" }, dest, context, "order");
+    }
+
+    fn fromStandard(val: anytype) ?FlexWrap {
```
Comment (Jarred-Sumner) [inline src/css/properties/flex.zig]: can we delete this dead code (it would've failed to compile if it was used)

Comment (Jarred-Sumner) [reply src/css/properties/flex.zig]: you marked this as resolved and then didn't delete it

Comment (zackradisic) [reply src/css/properties/flex.zig]: sorry forgot 2 push
