### PR TITLE
Don't crash when server.fetch() is called on a server without a fetch() handler

### LINKED ISSUE #18077: Segfault when calling Server#fetch with `.routes`
### How can we reproduce the crash?

I'm trying to write tests using `server.fetch(request)`. The server file only has this:

```ts
export const server = Bun.serve({
  routes: {
    "/": () => Response.json({ ok: true }),
  },

  port: process.env.PORT ?? 3000,
});
```

This segmentation fault happens when calling `server.fetch(request)`.

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.2.5 ([`013fddd`](<https://github.com/oven-sh/bun/tree/013fdddc6ed18bc849614ccb37a296fa0f69a5db>)) on macos aarch64 [TestCommand]

Segmentation fault at address 0x00000000

- *1 unknown/js code*
- `DebugHTTPSServerPrototype__doFetch`
- `DebugHTTPSServerPrototype__doFetch`
- `WebCore::DebugHTTPServerPrototype__fetchCallback`
- *1 unknown/js code*
- `jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__666_callHelper__dispatch_LowLevelInterpreter64_asm_2535`
- `jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__666_callHelper__dispatch_LowLevelInterpreter64_asm_2535`
- `jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__684_callHelper__dispatch_LowLevelInterpreter64_asm_2535`
- `llint_call_javascript`
- `JSC::Interpreter::executeCall`

Features: tsconfig, tsconfig\_paths, http\_server, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6324551853/">BUN-D2G</a></strong></sub>

### PR DESCRIPTION
**Pull request by pfgithub**
### What does this PR do?

Fix #18077

I would expect server.fetch() to support routes, but this at least prevents it from crashing when routes aren't specified.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 9:06 PM PT - Mar 12th, 2025</sup></div>

@pfgithub, your commit b6f3f3af27d648b068626994b11fab7cef05d486 is building: [`#13196`](https://buildkite.com/bun/bun/builds/13196)

**Review by cirospaciari — APPROVED** [review]

File: src/bun.js/api/server.zig [hunk 1]
```diff
@@ -8081,6 +8081,10 @@ pub fn NewServer(comptime NamespaceType: type, comptime ssl_enabled_: bool, comp
 
             var request = Request.new(existing_request);
 
+            if (this.config.onRequest == .zero) {
```
Comment (cirospaciari) [inline src/bun.js/api/server.zig]: var request = Request.new(existing_request); is leaking

**Review by cirospaciari — CHANGES_REQUESTED** [review]

**Review by cirospaciari — APPROVED** [review]
