### PR TITLE
resolve duplicate npm dependencies correctly

### LINKED ISSUE #1952: bun install crashes on 1st run with no cache
### What version of Bun is running?

0.5.3

### What platform is your computer?

Linux 5.15.0-2.52.3.el9uek.aarch64 aarch64 aarch64

### What steps can reproduce the bug?

When running `bun i` with no cache and lock file for the first time it crashes, running the command again works fine though.

`logs`
```
[opc@ashburn-1 test]$ rm -rf node_modules bun.lockb
[opc@ashburn-1 test]$ rm -rf /home/opc/.bun/install/cache
[opc@ashburn-1 test]$ bun i

error: ansi-regex@^5.0.1 failed to resolve
error: is-descriptor@^0.1.0 failed to resolve
error: locate-path@^3.0.0 failed to resolve
error: at-least-node@^1.0.0 failed to resolve
error: graceful-fs@^4.2.0 failed to resolve
error: jsonfile@^6.0.1 failed to resolve
error: universalify@^1.0.0 failed to resolve
error: lru-cache@^6.0.0 failed to resolve
```

`package.json`
```json
{
  "name": "name",
  "version": "1.0.0",
  "license": "unlicensed",
  "scripts": {
  },
  "dependencies": {
    "@bugsnag/expo": "^45.1.1",
    "@bugsnag/plugin-expo-eas-sourcemaps": "^45.1.0",
    "@motify/interactions": "^0.17.1",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/netinfo": "9.3.0",
    "@react-native-masked-view/masked-view": "^0.2.7",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@rematch/core": "^2.2.0",
    "@rematch/persist": "^2.1.2",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "@types/d3-shape": "^3.0.2",
    "@types/phone-formatter": "^0.0.2",
    "@types/set-interval-async": "^1.0.0",
    "apisauce": "^2.1.5",
    "axios": "^0.27.2",
    "d3-shape": "^3.1.0",
    "dayjs": "^1.11.5",
    "easy-peasy": "5.0.4",
    "expo": "~46.0.9",
    "expo-application": "~4.2.2",
    "expo-asset": "~8.6.1",
    "expo-blur": "~11.2.0",
    "expo-constants": "~13.2.3",
    "expo-crypto": "~11.0.0",
    "expo-dev-client": "~1.1.1",
    "expo-device": "~4.3.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-linear-gradient": "~11.4.0",
    "expo-linking": "~3.2.2",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-system-ui": "~1.3.0",
    "expo-updates": "~0.14.3",
    "expo-web-browser": "~11.0.0",
    "husky": "4.3.8",
    "mitt": "^3.0.0",
    "moti": "^0.18.0",
    "node-emoji": "^1.11.0",
    "onesignal-expo-plugin": "^1.0.2",
    "phone-formatter": "^0.0.2",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-hook-form": "^7.30.0",
    "react-native": "0.69.5",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-customizable-toast": "^0.1.7",
    "react-native-dotenv": "^3.3.1",
    "react-native-email-link": "^1.13.1",
    "react-native-fast-image": "^8.5.11",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-haptic-feedback": "^1.14.0",
    "react-native-iconly": "neo773/react-native-iconly",
    "react-native-interactable-reanimated": "^0.0.15",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-magic-modal": "^0.2.9",
    "react-native-onesignal": "^4.3.11",
    "react-native-portalize": "^1.0.7",
    "react-native-purchases": "^5.0.1",
    "react-native-reanimated": "^2.9.1",
    "react-native-recaptcha-that-works": "^1.3.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-skeleton-placeholder": "^5.0.0",
    "react-native-svg": "^13.0.0",
    "react-native-svg-legacy": "^12.5.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "react-query": "^3.38.1",
    "react-redux": "^8.0.2",
    "reconnecting-websocket": "^4.4.0",
    "rn-id-blurview": "^1.2.2",
    "set-interval-async": "^2.0.3",
    "tailwind-bootstrap-grid": "^5.0.1",
    "tailwind-rn": "^4.2.0",
    "true": "^0.0.4",
    "web-encoding": "^1.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@tailwindcss/typography": "^0.5.2",
    "@types/node-emoji": "^1.8.1",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "concurrently": "^7.1.0",
    "patch-package": "^6.5.1",
    "postcss": "^8.4.13",
    "react-test-renderer": "17.0.2",
    "tailwindcss": "^3.0.24",
    "typescript": "^4.6.3"
  },
  "private": true
}
```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alexlamsl**
fixes #1952

### CODE REVIEW

File: src/install/lockfile.zig [hunk 1]
```diff
@@ -1599,48 +1582,18 @@ pub fn getOrPutID(this: *Lockfile, id: PackageID, name_hash: PackageNameHash) !v
         this.unique_packages.unset(id);
 
         switch (index.*) {
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig:1584]: This dereferences the pointer

File: src/install/lockfile.zig [hunk 2]
```diff
@@ -1599,48 +1582,18 @@ pub fn getOrPutID(this: *Lockfile, id: PackageID, name_hash: PackageNameHash) !v
...
-                    new_ids[i + ids.len] = invalid_package_id - 1;
-                }
-
-                // stage1 compiler doesn't like this
-                new_ids[new_ids.len - 1] = invalid_package_id;
-                var new_ids_sentinel = new_ids.ptr[0 .. new_ids.len - 1 :invalid_package_id];
-                index.* = .{
-                    .PackageIDMultiple = new_ids_sentinel,
-                };
+            .PackageIDMultiple => |*ids| {
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]: and this references the deferenced pointer

this will only set `len` in the stack copy, not the one inside the array

instead, we will need to use std.meta.activeTag(entry) and reference by foo.PacakgeIDMultiple

Comment (alexlamsl) [reply src/install/lockfile.zig]: Fixed in https://github.com/oven-sh/bun/pull/1970/commits/8043296c3a64b568dce865d392927d630c03c0d5

**Comment by Jarred-Sumner** [comment]
Can you think of a way for us to write tests against this? Maybe the fake registry could return multiple versions of the same package?

**Comment by alexlamsl** [comment]
I think we'll need to upgrade `dummyRegistry` a little to make more complex test cases &minus; will take a look into it.
