### PR TITLE
hmr stability fixes

### LINKED ISSUE #17632: "__require is not defined" error
### What version of Bun is running?

1.2.3

### What platform is your computer?

macos

### What steps can reproduce the bug?

I can't get a great repo because I am running this at work and the stacktrace doesn't point at a particularly problematic file.

### What is the expected behavior?

No error.

### What do you see instead?

I tried to use the new bun dev server with `bun index.html`, but I see this error:

```
frontend ReferenceError: __require is not defined
      at e (http://localhost:3000/_bun/client/index-000000002ee2e723.js:51667:18)
      at http://localhost:3000/_bun/client/index-000000002ee2e723.js:51671:8
      at http://localhost:3000/_bun/client/index-000000002ee2e723.js:51629:26
      at node_modules/localforage/dist/localforage.js (http://localhost:3000/_bun/client/index-000000002ee2e723.js:51645:7)
      at node_modules/@sentry/integrations/esm/offline.js (http://localhost:3000/_bun/client/index-000000002ee2e723.js:51541:39)
      at async node_modules/@sentry/integrations/esm/index.js (http://localhost:3000/_bun/client/index-000000002ee2e723.js:50983:27)
```

None of the three files listed have a symbol named `__require`, so I'm stumped. 

### Additional information

_No response_

### LINKED ISSUE #17649: error: error: Failed to load bundled module 'runtime'. This is not a dynamic import...
### What version of Bun is running?

1.2.3+8c4d3ff80

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

Calling `bun run index.ts` on the index.ts below with the other 2 files.
**index.ts**
```typescript
import App from './index.html';
Bun.serve({
    port: 3000,
    development: true,
    routes: {
        "/": App
    }
})
```
**my-component.ts**
```typescript
import { LitElement } from "lit";
import { customElement } from "lit/decorators/custom-element.js";
import { html } from "lit/static-html.js";

@customElement('hello-world')
export class HelloWorld extends LitElement {

    private friend = 'Max';

  render() {
    return html`
        <input @change=${(value: string) => {this.friend = value}} placeholder=${this.friend}></input>
        <p>Hello, ${this.friend}!</p>`;
  }
}
```
**index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Lit-HTML App</title>
</head>
<body>
    <div id="hello-world"></div>
  <script type="module" src="./src/my-component.ts"></script>
</body>
</html> 
```

### What is the expected behavior?

No Runtime Error.

### What do you see instead?

❯ bun run index.ts
Bundled page in 59ms: index.html
frontend error: Failed to load bundled module 'runtime'. This is not a dynamic import, and therefore is a bug in Bun's bundler.
      at src/my-component.ts
      at index.html
      at Bun HMR Runtime
      at Bun HMR Runtime
    from browser tab http://localhost:3000/

### Additional information

_No response_

### LINKED ISSUE #17813: invalid js emitted when minifying comma expression
### What version of Bun is running?

1.2.5-canary.32+11979f69e

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

```sh
git clone git@github.com:porsager/postgres.git
cd postgres
bun run test/index.js
```

### What is the expected behavior?

Tests should run

### What do you see instead?

```
# Unhandled error between tests
-------------------------------
70 |       ? console.error('⛔️', x.name + ' at line', x.line, 'cleanup failed', '\n', util.inspect(x.cleanup))
71 |       : console.error('⛔️', x.name + ' at line', x.line, x.failed
72 |         ? 'failed'
73 |         : 'never finished', x.error ? '\n' + util.inspect(x.error) : ''
74 |       );
75 |   });
     ^
SyntaxError: Unexpected token ','
      at <parse> (/<redacted>/postgres/tests/test.js:75:1)
```

### Additional information

Transpiled output (`bun build --no-bundle`). Adding `// @bun` to the top of this and running it does not produce the same parser error.
```js
import util from "util";
let done = 0;
let only = false;
let ignored = 0;
let failed = false;
let promise = Promise.resolve();
const tests = {}, ignore = {};
export const nt = () => ignored++;
export const ot = (...rest) => (only = true, test(true, ...rest));
export const t = (...rest) => test(false, ...rest);
t.timeout = 5;
async function test(o, name, options, fn) {
  typeof options !== "object" && (fn = options, options = {});
  const line = new Error().stack.split(`
`)[3].match(":([0-9]+):")[1];
  await 1;
  if (only && !o)
    return;
  tests[line] = { fn, line, name };
  promise = promise.then(() => Promise.race([
    new Promise((resolve, reject) => fn.timer = setTimeout(() => reject("Timed out"), (options.timeout || t.timeout) * 1000)),
    failed ? (ignored++, ignore) : fn()
  ])).then(async (x) => {
    clearTimeout(fn.timer);
    if (x === ignore)
      return;
    if (!Array.isArray(x))
      throw new Error("Test should return result array");
    const [expected, got] = await Promise.all(x);
    if (expected !== got) {
      failed = true;
      throw new Error(util.inspect(expected) + " != " + util.inspect(got));
    }
    tests[line].succeeded = true;
    process.stdout.write("✅");
  }).catch((err) => {
    tests[line].failed = failed = true;
    tests[line].error = err instanceof Error ? err : new Error(util.inspect(err));
  }).then(() => {
    ++done === Object.keys(tests).length && exit();
  });
}
function exit() {
  let success = true;
  Object.values(tests).every((x) => {
    if (x.succeeded)
      return true;
    success = false;
    x.cleanup ? console.error("⛔️", x.name + " at line", x.line, "cleanup failed", `
`, util.inspect(x.cleanup)) : console.error("⛔️", x.name + " at line", x.line, x.failed ? "failed" : "never finished", x.error ? `
` + util.inspect(x.error) : "");
  });
  only ? console.error("⚠️", "Not all tests were run") : ignored ? console.error("⚠️", ignored, "ignored test" + (ignored === 1 ? "" : "s", `
`)) : success ? console.log("\uD83C\uDF89") : console.error("⚠️", "Not good");
  !process.exitCode && (!success || only || ignored) && (process.exitCode = 1);
}
```

### LINKED ISSUE #17816: requiring ES module with exported `__esModule = undefined` throws error
### What version of Bun is running?

1.2.2+c1708ea6a

### What platform is your computer?

Linux 6.12.12 x86_64 unknown

### What steps can reproduce the bug?

```sh
[me@thonkpad-nix:/tmp/a]$ echo 'export let __esModule' >module.mjs

[me@thonkpad-nix:/tmp/a]$ bun -e 'require("./module.mjs")'
1 | require("./module.mjs")
    ^
TypeError: Attempted to assign to readonly property.
      at /tmp/a/[eval]:1:1

Bun v1.2.2 (Linux x64)

```

### What is the expected behavior?

It should return the ES module namespace `Module { __esModule: undefined }` like Node.

### What do you see instead?

`TypeError: Attempted to assign to readonly property`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

BUN-10878 - assertion failure: watch invalid file path
BUN-10771 - Fixes #17632, Fixes #17649
BUN-10834 - stop watching node modules in dev mode
BUN-10832 - empty file fix
BUN-10696 - `Reloaded in {}ms` would sometimes print a nonsensical value. See https://github.com/oven-sh/bun/issues/17752#issuecomment-2689612645
BUN-10694 - Handle deleting files
- inline `undefined` for `import.meta.hot` outside of dev mode. 
- Fixes #17816
- Fixes #17813

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 11:08 PM PT - Feb 27th, 2025</sup></div>

@paperclover, your commit ba5b374b075d7d203d538505074faa54ff0b07f2 is building: [`#12483`](https://buildkite.com/bun/bun/builds/12483)

File: src/js_ast.zig [hunk 1]
```diff
@@ -1567,6 +1567,20 @@ pub const E = struct {
...
+        /// emits `exports` or `module.exports` depending on `commonjs_named_exports_deoptimized`
+        module_exports,
+        /// `import.meta.hot`
+        hot,
+        /// `import.meta.hot.accept`
+        hot_accept,
+        /// Converted from `hot_accept` to this in js_parser.zig when it is
+        /// passed strings. Printed as `import.meta.hot.acceptSpecifiers`
+        hot_accept_visited,
+        /// Prints the resolved specifier string for a resolved specifier.
```
Comment (Jarred-Sumner) [inline src/js_ast.zig]:
```suggestion
        /// Prints the resolved specifier string for an import record
```

File: .vscode/settings.json [hunk 2]
```diff
@@ -46,7 +46,7 @@
   },
 
   // lldb
-  "lldb.launch.initCommands": ["command source ${workspaceFolder}/.lldbinit"],
+  // "lldb.launch.initCommands": ["command source ${workspaceFolder}/.lldbinit"],
   "lldb.verboseLogging": false,
```
Comment (paperclover) [inline .vscode/settings.json]: clo dont comment this out for everyone please
