### PR TITLE
Redact secrets in `bunfig.toml` and `npmrc` logs

### LINKED ISSUE #14444: bun install prints npmrc registry authentication credentials when npmrc options cant be parsed
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 23.6.0 arm64 arm
This also happens on Linux / amd64

### What steps can reproduce the bug?

running `bun install` prints npm registry authentication credentials when an .npmrc has registry options without an associated registry definition.

.npmrc example (redacted):
```
always-auth=true
registry=https://registry.********.***/*********/api/npm/npm-virtual/
//registry.********.***/*********/api/npm/npm-virtual/:_auth=${{inputs.npm_token}}
//legacy_registry.**.***/*********/api/npm/**************-npm-virtual/:_auth=${{inputs.npm_token}}
//legacy_registry.**.***/*********/**************/api/npm/**************-npm/:_auth=${{inputs.npm_token}}
```

Our .npmrc exists this way to support when a legacy registry needs to be used.

### What is the expected behavior?

1. Redact the auth values when warning/errors are printed
2. Parse the aforementioned configuration file without throwing a warning

### What do you see instead?

Bun prints a warning with the auth value when `bun install` is executed:
```
4 | pi/npm/***********-npm-virtual/:_auth=SUPER_SECRET_TOKEN
                                                                                    ^
warn: The following .npmrc registry option was not applied:

  //legacy_registry.*****.***/***********/api/npm/********-npm-virtual/:_auth=***

Because we couldn't find the registry: legacy_registry.*****.***/*********/api/npm/**********-npm-virtual/.
   at /home/user/.npmrc:4:81
```

### Additional information

_No response_

### LINKED ISSUE #14867: Bun will print private package token if set it ~/.npmrc
### What version of Bun is running?

1.1.31

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```sh
# put a private package token in your global npmrc file
echo "//npm.pkg.github.com/:_authToken=<your_token>" >> ~/.npmrc

# the add any package (or run bun install)
bun add typescript

# Bun will then print the `<your_token>` as part of the error message
```

### What is the expected behavior?

Bun should not print secrets unexpectedly.

### What do you see instead?

 ```
1 | //npm.pkg.github.com/:_authToken=<your_token>
                                     ^
warn: The following .npmrc registry option was not applied:

  //npm.pkg.github.com/:_authToken=<your_token>

Because we couldn't find the registry: npm.pkg.github.com/.
   at /Users/jack/.npmrc:1:34
bun add v1.1.31 (e448c4cc)

installed typescript@5.6.3 with binaries:
 - tsc
 - tsserver

[6.00ms] done
```

This is a bug because `<your_token>` is a private token that may have considerable access (i.e. if it's a github package registry token, it could have access to a lot of your github account, it would be bad practice but it's easy to do).

If you're in a public space, or screen sharing you would not expect to have this command print a secret, hopefully you notice and cancel the token quickly.

### Additional information

Related issue: https://github.com/oven-sh/bun/issues/14433 (I opened a separate issue because printing credentials is a security risk, cause is the same, effect is very different - it's easy to merge issues if you prefer)
Issue introduced here (I think): https://github.com/oven-sh/bun/pull/13990

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Replaces secrets with `*` when logging errors and warnings for `bunfig.toml` and `npmrc` files.

Special keywords searched for: _auth, _authToken, email, _password, token. Additionally UUIDs, `npm_` prefixed tokens, and passwords in urls are replaced.

Screenshot 2024-10-30 at 5 25 02 PM

closes #14867 
closes #14444 

### How did you verify your code works?
Added tests for keywords and edgecases

### CODE REVIEW

**Comment by robobun** [comment]
@dylan-conway, your commit 05abd98bd7ec18c7c829d5eb0b953e2b8793ef1f is building: [`#5473`](https://buildkite.com/bun/bun/builds/5473)

File: src/string_immutable.zig [hunk 1]
```diff
@@ -217,9 +214,8 @@ pub fn isNPMPackageName(target: string) bool {
     return !scoped or slash_index > 0 and slash_index + 1 < target.len;
 }
 
-pub fn startsWithUUID(str: string) bool {
-    const uuid_len = 36;
-    if (str.len < uuid_len) return false;
+pub fn isUUID(str: string) bool {
+    bun.assertWithLocation(str.len == 36, @src());
```
Comment (nektro) [inline src/string_immutable.zig]:
```suggestion
    if (str.len != 36) return false;
```

File: src/string_immutable.zig [hunk 2]
```diff
@@ -257,6 +253,12 @@ pub fn startsWithUUID(str: string) bool {
     return true;
 }
 
+pub fn startsWithUUID(str: string) bool {
+    const uuid_len = 36;
+    if (str.len < uuid_len) return false;
+    return isUUID(str[0..uuid_len]);
```
Comment (nektro) [inline src/string_immutable.zig]:
```suggestion
    const uuid_len = 36;
    return isUUID(str[0..@min(str.len, uuid_len)]);
```

**Review by nektro — APPROVED** [review]
