### PR TITLE
[install] operator on root package of workspaces

### LINKED ISSUE #2592: `bun install` inside a workspace package needs to use the workspace's root lockfile instead of creating a new one
If you run `bun install` or `bun add` inside a workspace member's package, it currently creates a new lockfile and installs into the workspace member's node_modules folder. 

This is incorrect:
1) npm doesn't do it
2) It is not the intended behavior of workspaces. This causes packages to reinstall unnecessarily and potentially differing versions to exist.

Workspace member package:
```json
{
  "name": "workspace-pkg",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "^0.5.0"
  },
  "dependencies": {
    "react": "^18.2.0"
  }
}
```

Workspace root package:
```json
{
  "name": "repo",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "^0.5.0"
  },
  "workspaces": [
    "workspace-pkg"
  ]
}

```

Running `bun install` inside a workspace member package:
```zig
❯ bun install # inside workspace member
bun install v0.5.9 (f3ab445c)
 + bun-types@0.5.8
 + react@18.2.0

 4 packages installed [3.00ms]
```

It installs into the workspace member's node_modules folder (instead of the workspace root):
```bash
/tmp/repo/workspace-pkg
❯ ls node_modules/
bun-types/  js-tokens/  loose-envify/  react/
```

It also doesn't clean up the workspace member's node_modules folder. 

If you run `bun install` in a workspace root, now there are two installs of `react` and the workspace member's node_modules folder will always have precedence over the workspace root's node_modules folder.

### PR DESCRIPTION
**Pull request by alexlamsl**
fixes #2592

### CODE REVIEW

File: src/install/install.zig [hunk 1]
```diff
@@ -4970,49 +4970,107 @@ pub const PackageManager = struct {
...
+                        Output.prettyErrorln("Error {s} accessing {s}", .{ @errorName(err), this_cwd });
                         Output.flush();
                         return err;
                     };
-
-                    break :brk std.fs.cwd().openFileZ("package.json", .{ .mode = .read_write }) catch {
-                        this_cwd = parent;
-                        continue :outer;
+                    defer dir.close();
+                    break :child dir.openFileZ("package.json", .{ .mode = .read_write }) catch {
```
Comment (Jarred-Sumner) [inline src/install/install.zig:4992]: This will make `bun install` a little slower due to opening and closing many directories

I wonder if we could instead use absolute paths?

Comment (Jarred-Sumner) [reply src/install/install.zig:4992]: it might be fine though, i'm assuming `chdir` is cheaper than opening directories since we will later need to resolve relative to the directory

File: src/install/install.zig [hunk 2]
```diff
@@ -4970,49 +4970,107 @@ pub const PackageManager = struct {
...
+                var path_buf: [bun.MAX_PATH_BYTES]u8 = undefined;
+                const json_path = try bun.getFdPath(json_file.handle, &path_buf);
+                const json_source = logger.Source.initPathString(
+                    json_path,
+                    json_buf[0..json_len],
+                );
+                initializeStore();
+                const json = try json_parser.ParseJSONUTF8(&json_source, ctx.log, ctx.allocator);
+                if (json.asProperty("workspaces")) |prop| {
+                    var workspace_names = bun.StringArrayHashMap(string).init(ctx.allocator);
```
Comment (Jarred-Sumner) [inline src/install/install.zig]:
```zig
var workspace_names = bun.StringMap.init(ctx.allocator, true);
defer workspace_names.deinit();
```

File: src/install/install.zig [hunk 3]
```diff
@@ -6296,10 +6348,8 @@ pub const PackageManager = struct {
     var cwd_buf: [bun.MAX_PATH_BYTES]u8 = undefined;
     var package_json_cwd_buf: [bun.MAX_PATH_BYTES]u8 = undefined;
 
-    pub inline fn install(
-        ctx: Command.Context,
-    ) !void {
-        var manager = PackageManager.initMaybeInstall(ctx, null, &install_params, true) catch |err| {
+    pub inline fn install(ctx: Command.Context) !void {
```
Comment (Jarred-Sumner) [inline src/install/install.zig:6346]: If you do `bun install react` inside a workspace package does it add to the workspace package's package.json?

File: src/install/install.zig (hunk 1 above)
Comment (alexlamsl) [reply src/install/install.zig:4992]: I thought about that, but the directory opening checks for things like access rights, so combining the two calls would lose some handling logic &minus; though I'm not sure if it is worth the trouble to maintain prior behaviour? 🤔

File: src/install/install.zig (hunk 2 above)
Comment (alexlamsl) [reply src/install/install.zig]: You mean that [one from six lines below](https://github.com/oven-sh/bun/pull/2834/files#diff-2d4db027e059280840de7dfe46dda1752467e66c1c3014369ed701b026cd06fcR5032)? 🤔

File: src/install/install.zig (hunk 1 above)
Comment (Jarred-Sumner) [reply src/install/install.zig:4992]: yeah sounds good, its probably fine

File: src/install/install.zig (hunk 2 above)
Comment (Jarred-Sumner) [reply src/install/install.zig]: no i meant we could remove the code for iterating through .values() and .keys() to free them and re-use an existing abstraction `StringMap` for this to do that for us

File: src/install/install.zig (hunk 3 above)
Comment (alexlamsl) [reply src/install/install.zig:6346]: With this PR it adds it to the root package.

Comment (Jarred-Sumner) [reply src/install/install.zig:6346]: `bun install` should install the root workspace package
`bun install react` should:
1) Add `react` as a dependency to the workspace package's package
2) Install the workspace package's dependencies and the root package's dependencies (all workspace package's dependencies is fine for now though since IIRC it works that way currently and we can fix that later)

File: src/install/install.zig (hunk 2 above)
Comment (alexlamsl) [reply src/install/install.zig]: Ah okay &minus; will upgrade the one within `Package.parseWithJSON()` too then.

Comment (alexlamsl) [reply src/install/install.zig]: Done in https://github.com/oven-sh/bun/pull/2834/commits/28c24d8b5b412b57f7f00228c98dc46bdede16f7

File: src/install/install.zig (hunk 3 above)
Comment (alexlamsl) [reply src/install/install.zig:6346]: Done in https://github.com/oven-sh/bun/pull/2834/commits/28c24d8b5b412b57f7f00228c98dc46bdede16f7

File: test/cli/install/bun-add.test.ts [hunk 4]
```diff
@@ -1351,3 +1351,61 @@ it("should add dependency without duplication (GitHub)", async () => {
   );
   await access(join(package_dir, "bun.lockb"));
 });
+
+it("should add dependencies to workspaces directly", async () => {
```
Comment (Jarred-Sumner) [inline test/cli/install/bun-add.test.ts:1355]: this test is kind of confusing to me

basically it should be the equivalent of

```
bun add foo
jq package.json .dependencies.react  # should now appear
cat node_modules/react/package.json # should fail unless the workspace already had a conflicting version installed
cd ../
cat package.json # should be unmodified
```

Comment (alexlamsl) [reply test/cli/install/bun-add.test.ts:1355]: Oops, got distracted and ended up with a half-baked test &minus; will fix.

Comment (alexlamsl) [reply test/cli/install/bun-add.test.ts:1355]: Done in https://github.com/oven-sh/bun/pull/2834/commits/92f7fd35a5127f9386e08b32da2f7c5f69acfcd9

**Review by Jarred-Sumner — APPROVED** [review]
Thank you

**Comment by mciparelli** [comment]
@Jarred-Sumner is there a release with this fix yet?
