### PR TITLE
fix error message in bun.serve

### LINKED ISSUE #4555: Unintuitive error on invalid tls configuration
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```js
Bun.serve({
  fetch(req, server) {
    return undefined;
  },
  tls: {
    key: Bun.file('./key.pm'),
    cert: Bun.file('./cert.pem')
  }
});
```

### What is the expected behavior?

I expected either an error for the BunFile not existing or for the tls configuration being wrong since I had a typo: `key.pm` instead of the correct `key.pem`

### What do you see instead?
```js
1 | Bun.serve({
  fetch(req, server) {
    return;
  },
  tls: {
    key: Bun.file("./key.pm"),
    cert: Bun.file("./cert.pem")
  }
});
   ^
TypeError: Expected fetch() to be a function
 code: "ERR_INVALID_ARG_TYPE"

index.ts:1:0
```
### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Fixes #4555

This is one example why using `JSC.C.ExceptionRef` is a horrible idea. We should not be using these at any point in Bun.

This error in particular has caused many users a lot of confusion because a faulty error was printed.

The real error happens during SSLConfig.inJS (this should be named fromJS)

image

but the exception ref is not set since BunFile does not use exception refs, it uses the real exception system JSC provides.

so the null check fails, we fall down to this getter
image

the getter fails because we have an exception, and so on until `fetch`

image

the getter here fails, and we override the already thrown error with another error.

I've changed this to check for an exception, but that is a band-aid solution that only fixes this case.

We now print the actual first error.
image

To make this harder to hit I've also moved the check after the fetch error to make it impossible to hit the error in this way.

I would add an assertion to ensure we dont double-throw elsewhere but it seems this would make other tests fail (should be investigated one day)

### CODE REVIEW

File: src/bun.js/bindings/bindings.cpp [hunk 1]
```diff
@@ -5351,3 +5351,8 @@ extern "C" EncodedJSValue ExpectStatic__getPrototype(JSC::JSGlobalObject* global
 {
     return JSValue::encode(reinterpret_cast<Zig::GlobalObject*>(globalObject)->JSExpectStaticPrototype());
 }
+
+extern "C" bool JSGlobalObject__hasException(JSC::JSGlobalObject* globalObject)
+{
+    return DECLARE_CATCH_SCOPE(globalObject->vm()).exception() != 0;
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/bindings.cpp:5357]: this leaks memory i'm pretty sure

Comment (Jarred-Sumner) [reply src/bun.js/bindings/bindings.cpp:5357]: it does not leak memory
