### PR TITLE
dev server: rewrite HMRModule, support sync esm + hot.accept

### LINKED ISSUE #17633: error: Cannot load ES module synchronously
### What version of Bun is running?

1.2.3

### What platform is your computer?

macOS

### What steps can reproduce the bug?

Install moment + moment-timezone

```
    "moment": "^2.30.1",
    "moment-timezone": "^0.5.45",
```

Import `moment-timezone`

```
import moment from 'moment-timezone';
```

Use bun's new frontend dev server:

```
bun index.html
```

### What is the expected behavior?

It works.

### What do you see instead?

```
Runtime Error
error: Cannot load ES module synchronously
at http://localhost:3000/_bun/client/index-00000000564cb2fb.js:65774:41
at node_modules/moment-timezone/moment-timezone.js in http://localhost:3000/_bun/client/index-00000000564cb2fb.js:65780:7
at node_modules/moment-timezone/index.js in http://localhost:3000/_bun/client/index-00000000564cb2fb.js:64909:43
```

### Additional information

_No response_

### LINKED ISSUE #17863: Bun development server crashes when importing HeroUI
### What version of Bun is running?

Bun v1.2.4 (fd9a5ea6) macOS Silicon

### What platform is your computer?

macOS v15.3 Silicon

### What steps can reproduce the bug?

`bun src/index.html` crashes when I include HeroUI's `<HeroUIProvider>` in my `index.tsx`'s returned html.

```
➜ http://localhost:3000/

Press h + Enter to show shortcuts
============================================================
Bun v1.2.4 (fd9a5ea6) macOS Silicon
macOS v15.3
Args: "bun" "src/index.html"
Features: Bun.stderr(2) Bun.stdin(2) Bun.stdout(2) bunfig http_server jsc dev_server tsconfig process_dlopen 
Builtins: "bun:jsc" "node:assert" "node:buffer" "node:constants" "node:crypto" "node:fs" "node:fs/promises" "node:module" "node:os" "node:path" "node:perf_hooks" "node:process" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:v8" 
Elapsed: 1388ms | User: 693ms | Sys: 528ms
RSS: 0.33GB | Peak: 0.33GB | Commit: 1.07GB | Faults: 106

panic: Unexpected tag in printStmt: .s_lazy_export
Crashed while printing /Users/marcos/Documents/GitHub/leetcow/bombtimer.dev/node_modules/@heroui/shared-icons/dist/chunk-V2PVPQWW.mjs
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.2.4/Ma1fd9a5eakIukg0Bukxt1Cmk3uJ+mnwJuwimK+7lwBm929H__A0eNoLzUutKEhNLklNUShJTFfIzFMoKMrMKwkuyS2xUtArjs9JrKqMT60oyC8qAQBkpRB5

oh no: multiple threads are crashing
panic: Unexpected tag in printStmt: .s_lazy_export
Crashed while printing /Users/marcos/Documents/GitHub/leetcow/bombtimer.dev/node_modules/@heroui/shared-icons/dist/chunk-GQGYXTXM.mjs
 https://bun.report/1.2.4/Ma1fd9a5eakIukg0Bukxt1Cmk3uJ+mnwJuwimK+7lwBm929H__A0eNoLzUutKEhNLklNUShJTFfIzFMoKMrMKwkuyS2xUtArjs9JrKqMT60oyC8qAQBkpRB5

oh no: multiple threads are crashing
panic: Unexpected tag in printStmt: .s_lazy_export
Crashed while printing /Users/marcos/Documents/GitHub/leetcow/bombtimer.dev/node_modules/@heroui/theme/dist/chunk-WQEDQHKX.mjs
 [1]    76707 trace trap  bun src/index.html
```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

Stack trace:

Bun v1.2.4 ([`fd9a5ea`](<https://github.com/oven-sh/bun/tree/fd9a5ea668e9ffce5fd5f25a7cfd2d45f0eaa85b>)) on macos aarch64 [AutoCommand]

**panic**: Unexpected tag in printStmt: .s_lazy_export

- `js_printer.NewPrinter`
- `js_printer.NewPrinter`
- `bundler.bundle_v2.LinkerContext.printCodeForFileInChunkJS`
- `bundler.bundle_v2.LinkerContext.generateCompileResultForJSChunk`
- `Thread.PosixThreadImpl.spawn__anon_350893.Instance.entryFn`

Features: tsconfig, tsconfig\_paths, process\_dlopen, Bun.stderr, Bun.stdout, bunfig, dotenv, http\_server, jsc, dev\_server

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6334562244/">BUN-DAV</a></strong></sub>

### LINKED ISSUE #17900: HMR unnecessarily reloads CSS bundle on every SQLite database update
### What version of Bun is running?

1.4 & 1.2.5-canary.59 (99d85be5)

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

I have a sqlite database file that lives at the root directory of my project. While using `--hot`, I noticed that every time the sqlite database file updates, the HMR server triggers a CSS bundle reload. This is evident in both the dev server stdout and the HMR websocket messages in the browser.

The database file **_isn't_** "imported" in my code via an import statement; it's accessed using the `Database` constructor (i.e. `new Datebase('path/to/db.sqlite')`).

Repro:

I have a repo so you can easily verify the issue:

- Clone https://github.com/iitzkube/bun-hmr-bug
- Run `bun run dev`
- Open the localhost url in browser (_to kick off the bundler_)
- Spam click "Update SQLite Database" (_this will perform an INSERT/UPDATE query_) 
- Watch the devserver stdout and/or the HMR websocket messages in the browser.

https://github.com/user-attachments/assets/9ec4db10-3974-415a-8f32-fb0b334fdaae

P.S. 

I noticed a similar behavior whenever a new file is created in root directory of the project, which could be related to the issue described above.

You can test this by running the following command in the root directory of the project (after you have started the server and opened the app in the browser)

```sh
touch file_$(date +%H%M%S)
```

### What is the expected behavior?

Bun dev server should not reload the CSS bundle when the SQLite database file updates.

### LINKED ISSUE #17965: "Require is not defined" using import.meta.main with HMR
### What version of Bun is running?

1.2.5-canary.94+1d32e78cf

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

With this `index.html`:

```html
<!doctype html>
<title>Bug</title>
<script type="module" src="script.js"></script>
```

and this `script.js`:

```js
console.log('yes')
if (import.meta.main) console.log('hi')
```

run `bun index.html`. Open it in a browser and you'll see 'yes' correctly output to the console. Now edit `script.js`, for example to change the text in one of the strings, save and the page will try to HMR. You'll get the following error:

```
ReferenceError: require is not defined
```

Only way to recover is to restart `bun index.html` and everything works fine (until you change the script again).

### What is the expected behavior?

It should work, as it does if I run `vite` in the folder.

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
- BUN-10772: Fixes #17633
- BUN-10824: Support `import.meta.hot.accept`
- Fixes #17863
- Fixes #17965
- Fixes #17900

It may fix the following issues, but the tickets (as of writing) do not provide full reproductions.

- #17896
- #17613

This rewrites most of hmr-module.ts as well as an overhaul to HMR's bundling format. You can now `require("./esm")` just like `bun build` and `bun run` support. But if there is a top-level `await`, an error is raised.

CleanShot 2025-03-05 at 18 10 23@2x

Since I had to rewrite all of the code, now was a perfect time to support `import.meta.hot.accept`

```ts
// self-accepting
import.meta.hot.accept();
import.meta.hot.accept((newExports) => {});

// accept changes from other modules
import * as foo from "./foo";
export let stateful = getStateful(foo);
import.meta.hot.accept("./foo", (newFoo) => {
  stateful.foo = newFoo;
});
```

Unlike Vite, we patch inter-module dependencies automatically, making use of this function much simpler. Maybe we disable this for self-accepting modules that pass a callback.

To make the HMR easier to use and have more "just work" moments, Bun will very aggressively DCE the import.meta.hot object in production. Most simple HMR code doesn't have to be gated behind `if (import.meta.hot)`. So the most basics like the above examples can be put at top level.

`import.meta.hot.data` will inline to `{}` in production, which allows us to
simplify the existing React template very greatly. **This change was not actually
made to the template** so that it is more clear of the two states.

```diff
-if (import.meta.hot) {
   // With hot module reloading, `import.meta.hot.data` is persisted.
+  // In production, this line minifies to `const root = createRoot(elem);`
   const root = (import.meta.hot.data.root ??= createRoot(elem));
   root.render(app);
-} else {
-  // The hot module reloading API is not available in production.
-  createRoot(elem).render(app);
-}
```

This comment details a bit about the new module format.

```
/// The conversion logic is completely different for format .internal_bake_dev
/// For CommonJS, all statements are copied `inside_wrapper_suffix` and this returns.
///
/// For ESM, this function populates all three lists:
/// 1. outside_wrapper_prefix: all import statements, unmodified.
/// 2. inside_wrapper_prefix: a var decl line and a call to `module.retrieve`
/// 3. inside_wrapper_suffix: all non-import statements
///
/// The imports are rewritten at print time to fit the packed array format
/// that the HMR runtime can decode. This encoding is low on JS objects and
/// indentation.
///
/// 1 ┃ "module/esm": [ [
///   ┃   'module_1', 1, "add",
///   ┃   'module_2', 2, "mul", "div",
///   ┃   'module_3', 0, // bare or import star
///     ], [ "default" ], [], (hmr) => {
/// 2 ┃   var [module_1, module_2, module_3] = hmr.imports;
///   ┃   hmr.onUpdate = [
///   ┃     (module) => (module_1 = module),
///   ┃     (module) => (module_2 = module),
///   ┃     (module) => (module_3 = module),
///   ┃   ];
///
/// 3 ┃   console.log("my module", module_1.add(1, module_2.mul(2, 3));
///   ┃   module.exports = {
///   ┃     default: module_3.something(module_2.div),
///   ┃   };
///     }, false ],
///        ----- "is the module async?"
```

`input_graph` is renamed to `unloadedModuleRegistry` and is now of this type:

```ts
declare const unloadedModuleRegistry: Record<string, UnloadedModule>;
declare type UnloadedModule = UnloadedESM | UnloadedCommonJS;
declare type UnloadedESM = [
  deps: EncodedDependencyArray,
  exportKeys: string[],
  starImports: Id[],
  load: (mod: import("./hmr-module").HMRModule) => Promise<void>,
  isAsync: boolean
];
declare type EncodedDependencyArray = (string | number)[];
declare type UnloadedCommonJS = (
  hmr: import("./hmr-module").HMRModule,
  module: import("./hmr-module").HMRModule["cjs"]
) => any;
declare type CommonJSModule = {
  id: Id;
  exports: any;
  require: (id: Id) => any;
};
```

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 3:48 PM PT - Mar 6th, 2025</sup></div>

@paperclover, your commit 147905743b0bfa058ef82752db1fa2a8d04db2e5 is building: [`#12775`](https://buildkite.com/bun/bun/builds/12775)

File: src/js_printer.zig [hunk 1]
```diff
@@ -1164,14 +1165,17 @@ fn NewPrinter(
...
+                p.printNewline();
 
-            p.indent();
-            p.printBlockBody(stmts);
-            p.unindent();
-            p.needs_semicolon = false;
+                p.indent();
+                p.printBlockBody(stmts);
+                p.unindent();
+                p.needs_semicolon = false;
```
Comment (dylan-conway) [inline src/js_printer.zig]: `p.needs_semicolon = false;` should be unconditional right?

Comment (paperclover) [reply src/js_printer.zig]: correct. this can be moved outside since printIndent/addSourceMapping/print do not load this value
