### PR TITLE
Fixes `node:http` and `node:stream` so `ytdl-core` works.

### LINKED ISSUE #3336: ytld-core: segmentation fault (core dumped)
### What version of Bun is running?

0.6.1 (also tested on canary, same problem)

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Paste the following code snippet into a new file:
```js
import ytdl from 'ytdl-core';
const info = await ytdl.getInfo('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
console.log(info);
```

Run your file using `bun start`

### What is the expected behavior?

Expected behavior is information about the video provided in a JSON format printed in the console.

### What do you see instead?

A segmentation fault error.
`[1]    27760 segmentation fault (core dumped)  bun run tst.js`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
Fixes #3336 
```ts
import ytdl from "ytdl-core";
const info = await ytdl.getInfo("https://www.youtube.com/watch?v=dQw4w9WgXcQ");
console.log(info);
```

This fixes a lot of subtle things in bun:

- In JSReadableState, check if `highWaterMark` is a number. Would segfault if exists but not an integer number.
- Cleanup `node:http`
- `node:https`'s `request` and `get` will set the protocol to https properly now.
- reading a body with `request`/`get` now uses a `ReadableStream` under the hood, as the old implementation didn't seem to work properly (might be a bug relating to `Readable.fromWeb`). this approach is simpler and also would be a little faster.
- Add types for `readMany`
- Fix a crash with `createServer` and you abort a request in a specific way.
- Fix `emitClose` being false by default in some cases, causing `"close"` not be emitted.

### CODE REVIEW

File: src/js/node/http.ts [hunk 1]
```diff
@@ -649,52 +652,43 @@ export class IncomingMessage extends Readable {
...
       }
 
-      // this can be closed by the time we get here if enough data was synchronously available
-      this.#bodyStream &&
-        this.#bodyStream.on("end", () => {
-          this.#closeBodyStream();
-        });
-    } else {
-      // this.#bodyStream.read(size);
+      (async () => {
```
Comment (Jarred-Sumner) [inline src/js/node/http.ts]: we should move this to an internal function so that we avoid creating a new function each time read is called

Comment (Jarred-Sumner) [reply src/js/node/http.ts]: `#consumeReader(reader) { ...` or something

File: src/js/node/http.ts [hunk 2]
```diff
@@ -649,52 +652,43 @@ export class IncomingMessage extends Readable {
...
+        while (true) {
+          var { done, value, size } = await reader.readMany();
```
Comment (Jarred-Sumner) [inline src/js/node/http.ts]: I think we might need to handle `reader.closed` or one of those states

**Comment by paperclover** [comment]
could be merged, however if a request cancels halfway through, the "error" event is never emitted, and neither is end or close.

i'm not sure if there's a great way to pick up on this. abortsignal? cancel? need to check that zig actually has this done right

File: src/js/node/http.ts [hunk 3]
```diff
@@ -483,8 +483,8 @@ export class Server extends EventEmitter {
       if (tls) {
         this.serverName = tls.serverName || host || "localhost";
       }
-      this.#server = Bun.serve({
-        tls,
+      this.#server = Bun.serve<any>({
+        // tls,
```
Comment (Jarred-Sumner) [inline src/js/node/http.ts]: Won’t this break TLS?

File: src/js/node/http.ts [hunk 4]
```diff
@@ -649,64 +652,51 @@ export class IncomingMessage extends Readable {
...
+  async #consumeStream(reader: ReadableStreamDefaultReader) {
+    while (true) {
+      var { done, value } = await reader.readMany();
+      if (this.#aborted) return;
+      if (done) {
+        this.push(null);
+        this.destroy();
+        break;
+      }
+      for (var v of value) {
```
Comment (Jarred-Sumner) [inline src/js/node/http.ts:641]: This does ignore backpressure on the stream but it’s probably okay for now

File: src/js/node/http.ts [hunk 5]
```diff
@@ -649,64 +652,51 @@ export class IncomingMessage extends Readable {
...
 
-      // this can be closed by the time we get here if enough data was synchronously available
-      this.#bodyStream &&
-        this.#bodyStream.on("end", () => {
-          this.#closeBodyStream();
-        });
-    } else {
-      // this.#bodyStream.read(size);
+      this.#consumeStream(reader);
+
```
Comment (Jarred-Sumner) [inline src/js/node/http.ts]: Shouldn’t this be assigned before consuming? The stream can start sending chunks synchronously which push() can then cause events to be emitted which could make this re-entrant and cause unexpected behavior?

File: src/js/node/http.ts [hunk 6]
```diff
@@ -649,64 +652,51 @@ export class IncomingMessage extends Readable {
...
+      this.#bodyStream = reader;
     }
   }
 
   get aborted() {
     return this.#aborted;
   }
 
-  abort() {
```
Comment (Jarred-Sumner) [inline src/js/node/http.ts:653]: Is this not a public function in node?

File: src/js/node/http.ts (hunk 3 above)
Comment (paperclover) [reply src/js/node/http.ts]: oh i meant to ask you about this but the types dont define tls as a valid property here. i forgot to properly map it to the top level properties that do exist.

unless we support this but untyped, i didnt check.

File: src/js/node/http.ts [hunk 7]
```diff
@@ -1328,8 +1320,8 @@ export class ClientRequest extends OutgoingMessage {
       } else {
         protocol = defaultAgent.protocol || "http:";
       }
-      this.#protocol = protocol;
     }
+    this.#protocol = protocol;
```
Comment (Jarred-Sumner) [inline src/js/node/http.ts:1299]: Can you verify that redirects from https -> http and https -> http still work? I don’t know if we have a test for that.

File: src/js/node/https.ts [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+  Server,
+  METHODS,
+  STATUS_CODES,
+  createServer,
+  ServerResponse,
+  IncomingMessage,
+  request,
+  get,
+  maxHeaderSize,
+  // validateHeaderName,
```
Comment (Jarred-Sumner) [inline src/js/node/https.ts]: We should add these validate functions because it’ll break code to not have them and they’re small

File: src/js/node/http.ts (hunk 3 above)
Comment (Jarred-Sumner) [reply src/js/node/http.ts]: The types are not the source of truth. Node.js behavior is the source of truth.

File: src/js/node/http.ts (hunk 6 above)
Comment (paperclover) [reply src/js/node/http.ts:653]: its not but i should double check both cases you can get this class in node
