### PR TITLE
Fix confirm is never true in windows

### LINKED ISSUE #10643: confirm() is never true on Windows
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Ran into same thing I reported previously on Linux... https://github.com/oven-sh/bun/issues/5985

### What is the expected behavior?

returns true for `y`

### What do you see instead?

is always false, regardless of value

### Additional information

It does work (was fixed) on Linux

### PR DESCRIPTION
**Pull request by rcaselles**
### What does this PR do?
It fixes confirm dialog was always false in bundows

### How did you verify your code works?
With the new test added

this fixes #10643

### CODE REVIEW

File: src/bun.js/webcore.zig [hunk 1]
```diff
@@ -121,7 +121,7 @@ fn confirm(globalObject: *JSC.JSGlobalObject, callframe: *JSC.CallFrame) callcon
     // *  Not relevant in a server context.
 
     switch (first_byte) {
-        '\n' => return .false,
+        '\n', '\r' => return .false,
```
Comment (paperclover) [inline src/bun.js/webcore.zig]: when this \r is read, we should ignore it and read the next character.

i think this would cause a bug if you called confirm twice and press return

**Review by paperclover — CHANGES_REQUESTED** [review]
nice, can you double check my note.

File: src/bun.js/webcore.zig (hunk 1 above)
Comment (rcaselles) [reply src/bun.js/webcore.zig]: Changed

**Comment by rcaselles** [comment]
Done! Please check now

**Review by paperclover — APPROVED** [review]
