### PR TITLE
fix(install): fix false positive "lockfile is frozen" when using `bun install --production`

### LINKED ISSUE #5792: error: lockfile had changes, but lockfile is frozen
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I am using below command inside a docker image and it is failing with error - error: lockfile had changes, but lockfile is frozen
`bun install --production`

- Initially everything was working as expected
- I updated one of the packages
- and after that tried to build the docker image again.

I am using bun as a package manager.

node version - 18.16.0the 

### What is the expected behavior?

should install packages without any issues.

### What do you see instead?

```
 => ERROR [stage-1 6/8] RUN bun install --production                                                                                                                                                          0.2s 
------                                                                                                                                                                                                             
 > [stage-1 6/8] RUN bun install --production:                                                                                                                                                                     
0.209 bun install v1.0.2 (37edd5a6)                                                                                                                                                                                
0.211 error: lockfile had changes, but lockfile is frozen                                                                                                                                                          
------                                                                                                                                                                                                             
Dockerfile:24
--------------------
  22 |     COPY package.json bun.lockb .env.dev firebase-dev-admin.json ./
  23 |     RUN npm install -g bun
  24 | >>> RUN bun install --production
  25 |     
  26 |     # cleanup 
--------------------
ERROR: failed to solve: process "/bin/sh -c bun install --production" did not complete successfully: exit code: 1
```

### Additional information

I tried using `frozen-lockfile` flag as well, with no help

```
 => ERROR [stage-1 6/8] RUN bun install --production --frozen-lockfile                                                                                                                                        0.3s 
------                                                                                                                                                                                                             
 > [stage-1 6/8] RUN bun install --production --frozen-lockfile:                                                                                                                                                   
0.241 bun install v1.0.2 (37edd5a6)                                                                                                                                                                                
0.243 error: lockfile had changes, but lockfile is frozen                                                                                                                                                          
------                                                                                                                                                                                                             
Dockerfile:24
--------------------
  22 |     COPY package.json bun.lockb .env.dev firebase-dev-admin.json ./
  23 |     RUN npm install -g bun
  24 | >>> RUN bun install --production --frozen-lockfile
  25 |     
  26 |     # cleanup 
--------------------
ERROR: failed to solve: process "/bin/sh -c bun install --production --frozen-lockfile" did not complete successfully: exit code: 1
```

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

- Fixes https://github.com/oven-sh/bun/issues/5792
- Fix debug assertion failure in `bun install --production`
- Adds a little more logs in `bun install --verbose`

### How did you verify your code works?

Manually

### CODE REVIEW

File: src/install/install.zig [hunk 1]
```diff
@@ -8410,12 +8410,14 @@ pub const PackageManager = struct {
         ctx: Command.Context,
         comptime log_level: PackageManager.Options.LogLevel,
     ) !PackageInstall.Summary {
-        var lockfile = this.lockfile;
+        const original_lockfile = this.lockfile;
+        defer this.lockfile = original_lockfile;
```
Comment (dylan-conway) [inline src/install/install.zig:8414]: is this needed? We want `PackageManager` to use the lockfile before `clean()` for printing the summary?

Comment (Jarred-Sumner) [reply src/install/install.zig:8414]: The lockfile stored on `this` must be the expected instance, or else either git dependencies could fail or it will attempt to install dev dependencies

File: src/install/install.zig [hunk 2]
```diff
@@ -8410,12 +8410,14 @@ pub const PackageManager = struct {
...
         if (!this.options.local_package_features.dev_dependencies) {
-            lockfile = try lockfile.maybeCloneFilteringRootPackages(
+            this.lockfile = try this.lockfile.maybeCloneFilteringRootPackages(
                 this.options.local_package_features,
                 this.options.enable.exact_versions,
             );
+            this.lockfile = this.lockfile;
```
Comment (dylan-conway) [inline src/install/install.zig]: this can be removed

**Review by dylan-conway — APPROVED** [review]
Looks good

File: src/install/install.zig (hunk 2 above)
Comment (Jarred-Sumner) [reply src/install/install.zig]:
```suggestion

```
