### PR TITLE
fix: `reflect-metadata` import order

### LINKED ISSUE #4677: Reflect-metadata doesn't work for tsyringe
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

- Create a simple app with bun init
- add reflect-metadata and tsyringe to dependencies
- modify index.ts like this
```
// index.ts
import 'reflect-metadata'
import { container, singleton } from 'tsyringe'

@singleton()
class A {
  constructor() {
    console.log('A')
  }
}

container.resolve(A)
```
- modify package.json like this
```
{
  "name": "simplest",
  "module": "index.ts",
  "type": "module",
  "scripts": {
    "start": "bun ./index.ts"
  },
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "reflect-metadata": "^0.1.13",
    "tsyringe": "^4.8.0"
  }
}
```
- modify tsconfig like this
```
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "bundler",
    "moduleDetection": "force",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "composite": true,
    "strict": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "types": [
      "bun-types" // add Bun global
    ]
  }
}
```
- run `bun start`

### What is the expected behavior?

It should print `A` to the console.

### What do you see instead?

```
$ bun ./index.ts
1 | "use strict";
2 | Object.defineProperty(exports, "__esModule", { value: true });
3 | const tslib_1 = require("tslib");
4 | if (typeof Reflect === "undefined" || !Reflect.getMetadata) {
5 |     throw new Error(`tsyringe requires a reflect polyfill. Please add 'import "reflect-metadata"' to the top of your entry point.`);
              ^
error: tsyringe requires a reflect polyfill. Please add 'import "reflect-metadata"' to the top of your entry point.
      at /home/cm/Programming/bun/simplest/node_modules/tsyringe/dist/cjs/index.js:5:10
      at globalThis (/home/cm/Programming/bun/simplest/node_modules/tsyringe/dist/cjs/index.js:15:126)
error: script "start" exited with code 1 (SIGHUP)
```

### Additional information

When I use 
`const { container, singleton } = await import('tsyringe')` instead of direct import. It works.

### PR DESCRIPTION
**Pull request by DonIsaac**
Fixes module resolution and importing with these changes:
- record when imported modules declare themselvesas `"type": "commonjs"`
- `"type": "commonjs"` is now used as a hint by the transpiler to treat code being parsed as CJS (and to add a CJS wrapper function around it)
- when asynchronously importing a cjs module (e.g. from an ESM module), those CJS modules now get transpiled and loaded synchronously

### What was happening?
Tl;Dr, `reflect-metadata` was being treated as ESM and imports to it were resolving after `tsyringe` imports.

### How did you verify your code works?
I wrote a test

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 4:50 PM PT - Mar 11th, 2025</sup></div>

@DonIsaac, your commit 79f0cf5f6919a07a67378a2c117f9d903b8f8865 is building: [`#13040`](https://buildkite.com/bun/bun/builds/13040)

**Comment by DonIsaac** [comment]
update: we've decided to go with the hacky approach that doesn't force sync transpilation of cjs modules. Only `reflect-metadata` will be transpiled synchronously

File: src/bun.js/module_loader.zig [hunk 1]
```diff
@@ -1929,22 +1942,18 @@ pub const ModuleLoader = struct {
...
-
-                        if (actual_package_json.module_type == .esm) {
-                            break :brk ResolvedSource.Tag.package_json_type_module;
-                        }
-                    }
-
-                    break :brk ResolvedSource.Tag.javascript;
+                const tag: ResolvedSource.Tag = switch (loader) {
+                    .json, .jsonc => .json_for_object_loader,
+                    .js, .jsx, .ts, .tsx => if (parse_result.source.path.isFile()) brk: {
```
Comment (Jarred-Sumner) [inline src/bun.js/module_loader.zig]: The `isFile` isn't necessary 
```suggestion
                    .js, .jsx, .ts, .tsx => brk: {
```

File: src/fs.zig [hunk 2]
```diff
@@ -1907,7 +1920,7 @@ pub const Path = struct {
         return Path{
             .pretty = text,
             .text = text,
-            .namespace = "file",
+            .namespace = determineNamespace(text),
```
Comment (Jarred-Sumner) [inline src/fs.zig]: Path.init is called extremely frequently everywhere in the codebase. We should be cautious of adding any more work in here.

Are we sure this is needed? For example, the `getLoaderAndVirtualSource` method knows when the path is a `blob:` and could instead create the Path with the `blob` namespace set instead of doing the duplicate check.

File: src/fs.zig [hunk 3]
```diff
@@ -1916,7 +1929,7 @@ pub const Path = struct {
         return Path{
             .pretty = pretty,
             .text = text,
-            .namespace = "file",
+            .namespace = determineNamespace(text),
```
Comment (Jarred-Sumner) [inline src/fs.zig]: Ditto

File: src/fs.zig [hunk 4]
```diff
@@ -1950,6 +1963,32 @@ pub const Path = struct {
...
+        if (text.len > url_namespace_prefix_len and text[url_namespace_prefix_len] == ':') {
+            const maybe_namespace = text[0..url_namespace_prefix_len];
+            if (eql(maybe_namespace, "data:")) {
+                namespace = ns_dataurl;
+            } else if (eql(maybe_namespace, "blob:")) {
+                namespace = ns_blob;
+            }
+        }
+
+        // FIXME: this invariant is broken in many places
```
Comment (Jarred-Sumner) [inline src/fs.zig]: Not broken, the invariant is incorrect. `text` is not always an absolute path, like when an import_record.path.text  is not resolved yet. Can you delete this comment and/or add a comment mentioning that `text` is not always an absolute path?

File: src/options.zig [hunk 5]
```diff
@@ -970,6 +971,8 @@ const LoaderResult = struct {
     path: Fs.Path,
     is_main: bool,
     specifier: string,
+    package_json: ?*const PackageJSON,
+    // module_type: ModuleType,
```
Comment (Jarred-Sumner) [inline src/options.zig]: Can you delete the commented out argument?

File: src/options.zig [hunk 6]
```diff
@@ -1035,12 +1038,22 @@ pub fn getLoaderAndVirtualSource(
 
     const is_main = strings.eqlLong(specifier, jsc_vm.main, true);
 
+    const dir = path.name.dir;
+    const package_json: ?*const PackageJSON = if (path.isFile() and dir.len > 0 and std.fs.path.isAbsolute(dir))
```
Comment (Jarred-Sumner) [inline src/options.zig]: Why are we copying dir to a local variable and then using `path.name.dir` directly below?

File: src/fs.zig [hunk 7]
```diff
@@ -1950,6 +1963,32 @@ pub const Path = struct {
         };
     }
 
+    fn determineNamespace(text: string) string {
+        const eql = bun.strings.eqlComptime;
```
Comment (Jarred-Sumner) [inline src/fs.zig]: This does make it harder to cmd + f for all usages of strings.eqlComptime.

File: src/transpiler.zig [hunk 8]
```diff
@@ -992,6 +992,8 @@ pub const Transpiler = struct {
 
         dont_bundle_twice: bool = false,
         allow_commonjs: bool = false,
+        /// `"type"` from `package.json`
```
Comment (Jarred-Sumner) [inline src/transpiler.zig]:
```suggestion
        /// `"type"` from `package.json`. Used to make sure the parser defaults to CommonJS or ESM based on what the package.json says, when it doesn't otherwise know from reading the source code.
```

**Review by Jarred-Sumner — COMMENTED** [review]
A few questions

File: src/resolver/resolver.zig [hunk 9]
```diff
@@ -2612,6 +2613,7 @@ pub const Resolver = struct {
         return try r.dirInfoCachedMaybeLog(path, false, true);
     }
 
+    /// Like `readDirInfo`, but returns `null` instead of throwing an error.
```
Comment (Jarred-Sumner) [inline src/resolver/resolver.zig:2617]: Was this comment helpful for you? The lack of a `!` and the name communicate this information as well

Comment (DonIsaac) [reply src/resolver/resolver.zig:2617]: It makes finding related methods easier when hovering over usages in my editor

File: src/fs.zig (hunk 7 above)
Comment (DonIsaac) [reply src/fs.zig]: Why? It will take them right here.

**Comment by DonIsaac** [comment]
Changes to `Fs.Path` have been moved to #18168

**Comment by thereis** [comment]
LGTM!

File: src/codegen/bundle-modules.ts [hunk 10]
```diff
@@ -380,12 +381,19 @@ namespace InternalModuleRegistryConstants {
...
+    .join("\n")}
 }
 }`,
   );
 }
 
+/**
+ * IDs with bits set past this offset are used for builtin modules.
+ */
+const BUILTIN = 9;
```
Comment (paperclover) [inline src/codegen/bundle-modules.ts]: this variable is not used. it is also incorrect, and the comment is not as helpful as the one that already exists.

tags 0 ... 511 (1 << 9 - 1) are tags. after that, the tags translate to InternalModuleRegistry ids

```
    // Built in modules are loaded through InternalModuleRegistry by numerical ID.
    // In this enum are represented as `(1 << 9) & id`
```

File: src/options.zig [hunk 11]
```diff
@@ -1036,12 +1039,23 @@ pub fn getLoaderAndVirtualSource(
 
     const is_main = strings.eqlLong(specifier, jsc_vm.main, true);
 
+    const dir = path.name.dir;
+    // NOTE: we cannot trust `path.isFile()` since it's not always correct
+    const package_json: ?*const PackageJSON = if (std.fs.path.isAbsolute(dir))
```
Comment (paperclover) [inline src/options.zig]: should this also check path.isFile() so that it doesn't apply to virtual namespaces that happen to have file-like paths?

File: src/bun.js/module_loader.zig [hunk 12]
```diff
@@ -2288,27 +2300,68 @@ pub const ModuleLoader = struct {
...
+                    // doesn't record them.
+                    if (pkg_name) |pkg_name_| {
+                        inline for (always_sync_modules) |always_sync_specifier| {
+                            if (bun.strings.eqlComptime(pkg_name_, always_sync_specifier)) {
+                                break :transpile_async;
+                            }
+                        }
+                    }
+
+                    // TODO: check if the resolved source must be transpiled synchronously
```
Comment (paperclover) [inline src/bun.js/module_loader.zig:2356]: what happens when we dont check

**Review by paperclover — COMMENTED** [review]
some questions

File: src/options.zig (hunk 11 above)
Comment (DonIsaac) [reply src/options.zig]: `path.isFile` almost always lies; I don't think this is worth it.

File: src/codegen/bundle-modules.ts (hunk 10 above)
Comment (DonIsaac) [reply src/codegen/bundle-modules.ts]: Its usage got clobbered by a merge conflict; i'll remove it

File: src/bun.js/module_loader.zig (hunk 12 above)
Comment (DonIsaac) [reply src/bun.js/module_loader.zig:2356]: What happens is the bug this PR is "fixing". We're currently restricting the solution to `reflect-metadata` for performance reasons, but this problems exists more generally. We need to know if the resolved source is CJS and/or requires sync loading. `"type": "commonjs"` is useful but insufficient.
