### PR TITLE
Fixes #14411

### LINKED ISSUE #14411: Failed to load config from vite.static.config.ts (Bun 1.1.30)
### What version of Bun is running?

v1.1.30 (using the bun action for github actions) 

### What platform is your computer?

ubuntu-22.04 - github actions runner

### What steps can reproduce the bug?

I received this error:
```
bun run build:service_name
bun run build:src:service_name -- id=$id && bun run build:copy:service_name -- id=$id
bunx --bun vite build --config vite.static.config.ts -- env=service_name id=1939
failed to load config from /home/runner/work/repo/repo/dir/vite.static.config.ts
error during build:
Error: config must export or return an object.
    at <anonymous> (/home/runner/work/repo/repo/dir/node_modules/vite/dist/node/chunks/dep-52909643.js:66187:[23](https://github.com/org/repo/actions/runs/11235/job/312355#step:5:24))
    at processTicksAndRejections (:7:39)
error: script "build:src:service_name" exited with code 1
error: script "build:service_name" exited with code 1
```

The build is failing currently

### What is the expected behavior?

```
vite v4.5.2 building for production...
transforming...
✓ 1 modules transformed.
vite v4.5.2 building for production...
transforming...
```

### What do you see instead?

_No response_

### Additional information

It was working in the previous version - v1.1.29

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #14411

### How did you verify your code works?

Manually tested. We should really add a few integration tests for Vite.

### CODE REVIEW

**Comment by robobun** [comment]
@Jarred-Sumner, your commit 67114974dc79b055046db18258a838aafd670f9b is building: [`#5084`](https://buildkite.com/bun/bun/builds/5084)

File: src/js/builtins/Module.ts [hunk 1]
```diff
@@ -76,6 +76,17 @@ export function overridableRequire(this: CommonJSModuleRecord, id: string) {
...
     if (esm?.evaluated && (esm.state ?? 0) >= $ModuleReady) {
       const namespace = Loader.getModuleNamespaceObject(esm!.module);
+      // In Bun, when __esModule is not defined, it's a CustomAccessor on the prototype.
+      // Various libraries expect __esModule to be set when using ESM from require().
+      // We don't want to always inject the __esModule export into every module,
+      // And creating an Object wrapper causes the actual exports to not be own properties.
+      // So instead of either of those, we make it so that the __esModule property can be set at runtime.
+      // It only supports "true" and undefined. Anything non-truthy is treated as undefined.
+      // https://github.com/oven-sh/bun/issues/14411
+      if (namespace.__esModule === undefined) {
```
Comment (Jarred-Sumner) [inline src/js/builtins/Module.ts:86]: cc @nicolo-ribaudo incase you find this interesting
