### PR TITLE
require.resolve with `paths` option

### LINKED ISSUE #4511: `require.resolve()` does not respect `paths` option
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Given 2 files

- `/a.js`
```js
console.log(require.resolve('./b.js', { paths: [__dirname + '/folder'] }));
```

- `/folder/b.js`
```js
// ...
```

Execute `bun /a.js`

### What is the expected behavior?

Output:

```
/folder/b.js
```

### What do you see instead?

Bun crash and output:

```
error: Cannot find module "./b.js" from "/a.js"
```

### Additional information

We are using the `paths` option heavily in our codebase, so this issue is blocking our Bun integration, but luckily this seems to be the only issue at the moment. :)

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Fixes #4511

Unrelated on this PR i'm removing tests incorrectly marked as passing (test/js/node/test/parallel/test-*-strip-types.js). As well as simplifying some of the code of DevServer.WatcherAtomics; this one doesn't change behavior, it's just a silly trick you can do.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 8:23 PM PT - Apr 7th, 2025</sup></div>

@paperclover, your commit a65740d3ea7341b9bcd10bf840aa2cd76b012dab is building: [`#14633`](https://buildkite.com/bun/bun/builds/14633)

File: src/bake/DevServer.zig [hunk 1]
```diff
@@ -6417,7 +6414,7 @@ const WatcherAtomics = struct {
     fn watcherAcquireEvent(state: *WatcherAtomics) *HotReloadEvent {
         state.watcher_has_event.lock();
 
-        var ev: *HotReloadEvent = &state.events[state.current].aligned;
+        var ev: *HotReloadEvent = &state.events[state.current];
         switch (ev.contention_indicator.swap(1, .seq_cst)) {
```
Comment (Jarred-Sumner) [inline src/bake/DevServer.zig:6418]: i bet this doesn't actually work thread safely

File: src/bun.js/modules/NodeModuleModule.cpp [hunk 2]
```diff
@@ -472,16 +474,23 @@ JSC_DEFINE_HOST_FUNCTION(jsFunctionResolveLookupPaths,
...
         if (parent.paths) {
+            auto array = JSC::constructArray(globalObject, (ArrayAllocationProfile*)nullptr, nullptr, 0);
             auto len = parent.paths->length();
             for (size_t i = 0; i < len; i++) {
                 auto path = parent.paths->getIndex(globalObject, i);
                 array->push(globalObject, path);
             }
+            RELEASE_AND_RETURN(scope, array);
+        } else if (parent.pathsArrayLazy && parent.filename) {
+            auto filenameValue = parent.filename->value(globalObject);
```
Comment (paperclover) [inline src/bun.js/modules/NodeModuleModule.cpp:486]: muissing wexcceptioon check

File: src/bun.js/modules/NodeModuleModule.cpp [hunk 3]
```diff
@@ -472,16 +474,23 @@ JSC_DEFINE_HOST_FUNCTION(jsFunctionResolveLookupPaths,
...
+            auto filename = Bun::toString(filenameValue);
+            auto paths = JSValue::decode(Resolver__nodeModulePathsJSValue(filename, globalObject, true));
+            RELEASE_AND_RETURN(scope, paths);
+        } else {
+            auto array = JSC::constructArray(globalObject, (ArrayAllocationProfile*)nullptr, nullptr, 0);
```
Comment (paperclover) [inline src/bun.js/modules/NodeModuleModule.cpp]:
```suggestion
            auto array = JSC::constructEmmptyArray(globalObject, nullptr);
```
