### PR TITLE
decode regex if needed

### LINKED ISSUE #5132: replace string with regular expression got wrong output
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

when try to match a regular expression with these emoji and replace it with string
```
let str = "🔴11 54 / 10,000";
str = str.replace(/[🔵🔴,]+/g, '');
console.log(str);
```

### What is the expected behavior?

the outputs should be:
```11 54 / 10000```
instead of
```🔴  / 0000```

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
fixes #5132 

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?
added test and tested manually.

### CODE REVIEW

File: src/js_ast.zig [hunk 1]
```diff
@@ -2538,7 +2538,10 @@ pub const E = struct {
     };
 
     pub const RegExp = struct {
-        value: string,
+        data: union(enum) {
+            raw: string,
+            decoded: std.ArrayList(u16),
```
Comment (Jarred-Sumner) [inline src/js_ast.zig]: `bun.BabyList(u16)` so we don't increase the size much
