### PR TITLE
node fs compat pr #2

### LINKED ISSUE #8246: [win][fs] There is no support of long paths
### What version of Bun is running?

1.0.23

### What platform is your computer?

Window 10

### What steps can reproduce the bug?

```js
import fs from "node:fs/promises";


const filePathAbs = "C:\\VeryLongName00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\\Again00000000000000000000000000000000\\[twitter] SpaceX—2024.01.17—1747633689276608977—GEDXkT3WUAAWxF3.jpg";
console.log(filePathAbs.length);
console.log(await fs.stat(filePathAbs));
```

### What is the expected behavior?

```
315
Stats {
  ...
  size: 1182629,
  ...
}
```

### What do you see instead?

```
315
ENOENT: No such file or directory
   errno: -4058
 syscall: "stat"
```

### Additional information

BTW, 8.3 file path is supported:
```js
const filePath83 = "C:\\VERYLO~1\\AGAIN0~1\\[twitter] SpaceX—2024.01.17—1747633689276608977—GEDXkT3WUAAWxF3.jpg";
console.log(filePath83.length); // 88
console.log(await fs.stat(filePath83)); // Stats { ... }
```

---

Rel:
- https://github.com/oven-sh/bun/issues/8836

---

https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#skip-normalization

> Unless the path starts exactly with `\\?\` _(note the use of the canonical backslash)_, it is normalized.
>
> Why would you want to skip normalization? There are three major reasons:
> 1. To get access to paths that are normally unavailable but are legal. A file or directory called `hidden.`, for example, is impossible to access in any other way.
> 2. To improve performance by skipping normalization if you've already normalized.
> 3. **To skip the `MAX_PATH` check for path length to allow for paths that are greater than 259 characters.**

### LINKED ISSUE #8255: [win][fs] Crash on reading (`fs.readFile`) 2 GB file+ (`reached unreachable code`)
### What version of Bun is running?

1.0.23

### What platform is your computer?

Window 10

### What steps can reproduce the bug?

```js
import fs from "node:fs/promises";

try {
    const largeFilePath = "...";
    const file = await fs.readFile(largeFilePath);
    console.log(file.length);
} catch (e) {
    console.error(e);
    console.log("Okay, I will use stream approach");
}
```

### What is the expected behavior?

Node.js:
```
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (4545459987) is greater than 2 GiB
    at new NodeError (node:internal/errors:405:5)
    at readFileHandle (node:internal/fs/promises:497:11)
    at async file:///C:/Downloads/bun-windows-x64/x.mjs:4:18 {
  code: 'ERR_FS_FILE_TOO_LARGE'
}
Okay, I will use stream approach
```

### What do you see instead?

Bun:
```
uh-oh: reached unreachable code
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.23-canary.14 (52894121) Windows x64
AutoCommand:
Elapsed: 679ms | User: 500ms | Sys: 859ms
RSS: 4.64GB | Peak: 4.64GB | Commit: 4.71GB | Faults: 1134829
----- bun meta -----

0   00007FF6C47351E8
1   ???
2   ???
3   ???
4   ???
5   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 7368 panic: reached unreachable code
???:?:?: 0x7ff6c3ba4677 in ??? (???)
???:?:?: 0x7ff6c3802443 in ??? (???)
???:?:?: 0x7ff8940a7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ff895f626b0 in ??? (ntdll.dll)
```

### Additional information

It should just throw `RangeError`, instead of an application's crash.
Rel: https://github.com/oven-sh/bun/issues/8254

### PR DESCRIPTION
**Pull request by paperclover**
fixes #8246 
fixes #8255

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 2:58 PM PT - Jan 15th, 2025</sup></div>

@paperclover, your commit 35d8caf744522d6bc4a8c34dc8b41e7ab3264217 is building: [`#9683`](https://buildkite.com/bun/bun/builds/9683)

File: src/bun.js/api/BunObject.zig [hunk 1]
```diff
@@ -3634,7 +3635,8 @@ pub const FFIObject = struct {
                 return err;
             },
             .slice => |slice| {
-                return WebCore.Encoder.toString(slice.ptr, slice.len, globalThis, .utf8);
+                var str = bun.String.createUTF8(slice);
+                return str.toJS(globalThis);
```
Comment (Jarred-Sumner) [inline src/bun.js/api/BunObject.zig]:
```suggestion
                return bun.String.createUTF8ForJS(globalThis, slice);
```
