### PR TITLE
fix(test): test.failing when tests use a done callback

### LINKED ISSUE #18928: test: `it.failing` fails when error is passed to done callback
### What version of Bun is running?

1.2.10-canary.10+06e0c876f

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

```ts
// test succeeds, as expected
it.failing("throwing with done() callback", done => {
    throw new Error("error");
});
// test fails, but it should pass
it.failing("passing error to done()", done => {
    done(new Error("error"));
});
```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DonIsaac**
### What does this PR do?
Fixes #18928

`test.failing` should pass when tests using `done()` pass it an error or throw.

I've also fixed the type definitions for `test.failing` so that it optionally takes `TestOptions` as the 3rd parameter.

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?
I've added test cases

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 1:49 PM PT - Apr 10th, 2025</sup></div>

@DonIsaac, your commit 35fb247a6a6acf5b1ebd84ab4576534e8b944f8e is building: [`#14782`](https://buildkite.com/bun/bun/builds/14782)

File: src/bun.js/test/jest.zig [hunk 1]
```diff
@@ -633,22 +633,23 @@ pub const TestScope = struct {
 
         if (JSC.getFunctionData(function)) |data| {
             var task = bun.cast(*TestRunnerTask, data);
+            const current_test = task.describe.tests.items[task.describe.current_test_id];
+            const is_failing = current_test.tag == .fail;
```
Comment (paperclover) [inline src/bun.js/test/jest.zig:637]: nit, would name this like 'test_expects_failure' to avoid confusion with if the test itself failed or not (stored in test_succeeded)

**Review by paperclover — APPROVED** [review]

**Review by dylan-conway — APPROVED** [review]
