### PR TITLE
fix(bundler): bundling invalid html / export star as / react refresh fixes

### LINKED ISSUE #17554: dev server: assertion failure when bundling invalid html file
### How can we reproduce the crash?

Here's my files:
<details><summary>index.ts</summary>
<p>

```ts
import app from './public/app.html';
Bun.serve({
  routes: {
    '/': app,
    '/login': app,
    '/onboarding': app,
  },
  development: true,
});
```
</p>
</details>

<details><summary>app.html</summary>
<p>

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <link rel="stylesheet" href="../src/app/styles.css" />
  </head>
  <body>
    <div id="root" />
    <script type="module" src="../src/app/index.tsx" />
  </body>
</html>
```
</p>
</details>

<details><summary>index.tsx</summary>
<p>

```tsx
import ReactDOM from 'react-dom/client';
document.addEventListener('DOMContentLoaded', () => {
  const rootElement = document.getElementById('root');

  if (!rootElement) {
    return null;
  }

  const root = ReactDOM.createRoot(rootElement);
  root.render(
    <StrictMode>
      <div>Hello</div>
    </StrictMode>
  );
});

```
</p>
</details>

Let me know if I can provide more information to help mitigate the issue

### Relevant log output

```shell
Bun v1.2.3 (8c4d3ff8) macOS Silicon
macOS v15.2
Args: "" "" "" ""
Features: Bun.stderr(2) Bun.stdout(2) bunfig(2) dotenv(2) http_server jsc dev_server tsconfig tsconfig_paths process_dlopen 
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:constants" "node:crypto" "node:fs" "node:fs/promises" "node:module" "node:os" "node:path" "node:perf_hooks" "node:process" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:v8" 
Elapsed: 582ms | User: 198ms | Sys: 39ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 1.07GB | Faults: 102

panic(main thread): Segmentation fault at address 0x3F681FFFFE0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.2.3/Mr18c4d3ffsIq0g0B_24/mRmj+jQ22mgNu380Ku4uzL+y0lHm/8nFms7hiB2mi0EA2s/Bhiggg+D

/opt/homebrew/bin/bash: line 1: 67644 Trace/BPT trap: 5       bun -b run index.ts
```

### Stack Trace (bun.report)

Bun v1.2.3 ([`8c4d3ff`](<https://github.com/oven-sh/bun/tree/8c4d3ff801843916eb7e1c8d153c9d1109af41ba>)) on macos aarch64 [RunCommand]

Segmentation fault at address 0x45275FFFFE0

- *1 unknown/js code*
- `bake.DevServer.onHtmlRequestWithBundle`
- `bake.DevServer.finalizeBundle`
- `bundler.bundle_v2.BundleV2.onAfterDecrementScanCounter`
- `bun.js.event_loop.ManagedTask.New`
- `bun.js.event_loop.EventLoop.tickQueueWithCount__anon_517689`
- `bun.js.event_loop.EventLoop.tick`
- `bun.js.javascript.OpaqueWrap__anon_33711__struct_239516.callback`
- `JSC__VM__holdAPILock`
- `bun_js.Run.boot`

Features: transpiler\_cache, tsconfig, tsconfig\_paths, process\_dlopen, Bun.stderr, Bun.stdin, Bun.stdout, bunfig, dotenv, http\_server, jsc, dev\_server

### LINKED ISSUE #17564: Unexpected error with frontend dev server and react 19 app
### What version of Bun is running?

1.2.3+8c4d3ff80

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

I don't have a minimal reproducer, but one example is [this app](https://github.com/russellmcc/bilinear-audio), from the root of that repo run `bun web/reverb/index.html`

### What is the expected behavior?

No errors, web app runs

### What do you see instead?

```
frontend error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
      at createFiberFromTypeAndProps (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:13350:28)
      at createFiberFromElement (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:13364:14)
      at reconcileChildFibersImpl (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:5238:31)
      at /Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:5415:33
      at reconcileChildren (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:7738:13)
      at beginWork (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:9951:13)
      at runWithFiberInDEV (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:543:16)
      at performUnitOfWork (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:15044:22)
      at workLoopSync (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:14870:41)
      at renderRootSync (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:14850:11)
      at performWorkOnRoot (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:14384:44)
      at performWorkOnRootViaSchedulerTask (/Users/russruss/proj/bilinear-audio/node_modules/react-dom/cjs/react-dom-client.development.js:15931:7)
      at performWorkUntilDeadline (/Users/russruss/proj/bilinear-audio/node_modules/scheduler/cjs/scheduler.development.js:44:48)
    from browser tab http://localhost:3000/
```

### Additional information

I'm very excited about the frontend dev server functionality and would love to replace vite as my dev server!  The app is working well with vite.

### LINKED ISSUE #17566: bun dev error when bundling redux-persist dependency in a react app
### What version of Bun is running?

1.2.3

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

Hi and thanks for this amazing tool. I got through several errors when trying to bun ./index.html long awaited HMR serve feature, like bun not being able to transpile(?) some ts code correctly, for example:  
```tsx
    const hookState =
      <U = Scope.Descriptor,>(transform?: (v: Scope.Descriptor) => U) =>
      () => {
        const state = useContext(context)
        return useMemo(() => (transform || identity)(state), [state]) as U
      }
```

which I could fix by replacing it with:  
```tsx
      function hookState<U = Scope.Descriptor>(transform?: (v: Scope.Descriptor) => U) {
        return () => {
          const state = useContext(context)
          return useMemo(() => (transform || identity)(state), [state]) as U
        }
      }
```
and others, and at the end got bug, that is not on my end, which is possibly related to how bun interprets some package code, specifically `redux-persist`.  
I have assembled a reproduction repo:  
https://github.com/xblurx/bun-redux-persist-repro  

to reproduce you should run `bun ./src/index.html` and see the browser.

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
Fixes #17554
Fixes #17564
Fixes #17566

the invalid html caused a crash because the dev server did not know where to inject script and style tags. this removes the body tag code since i decided to inject everything into head

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 2:04 PM PT - Feb 25th, 2025</sup></div>

@paperclover, your commit af8fb2d0832154e155b78e2e35647d4132b70843 is building: [`#12235`](https://buildkite.com/bun/bun/builds/12235)

File: src/HTMLScanner.zig [hunk 1]
```diff
@@ -269,21 +269,6 @@ pub fn HTMLProcessor(comptime T: type, comptime visit_head_and_body: bool) type
                     null,
                     null,
                 );
-
-                const body_selector = try lol.HTMLSelector.parse("body");
```
Comment (DonIsaac) [inline src/HTMLScanner.zig:273]: What happens if
```html
<!-- valid html w/ script in body tag -->
<html>
  <body>
  <script src="./foo/bar.ts"></script>
  </body>
</html>
```

Comment (paperclover) [reply src/HTMLScanner.zig:273]: In dev mode:

`GET /` will return
```
<!-- valid html w/ script in body tag -->
<html>
  <body>
  </body>
</html>
<script type="module" crossorigin src="/_bun/client/index-00000000000000000.js"></script>
```

perhaps the body logic should be added for fallback so that the injection location can be, in order:

- `head`
- `body`
- `html`
- the end of the file

Comment (DonIsaac) [reply src/HTMLScanner.zig:273]: Are there already tests covering this behavior? If not, can we add them?

Comment (paperclover) [reply src/HTMLScanner.zig:273]: yes
