### PR TITLE
fix: execArgv sometimes could include user args

### LINKED ISSUE #11673: process.execArgv may incorrectly include user options
### What version of Bun is running?

1.1.12

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Bun is sometimes duplicating all the script options into `process.execArgv`.

`process.execArgv` should only include options for the node application itself. Options coming after the script name are for the script being run and should not appear in `process.execArgv`. 

https://nodejs.org/api/process.html#processexecargv

> The `process.execArgv` property returns the set of Node.js-specific command-line options passed when the Node.js process was launched. These options do not appear in the array returned by the [process.argv](https://nodejs.org/api/process.html#processargv) property, and do not include the Node.js executable, the name of the script, or any options following the script name. These options are useful in order to spawn child processes with the same execution environment as the parent.The process.execArgv property returns the set of Node.js-specific command-line options passed when the Node.js process was launched. These options do not appear in the array returned by the [process.argv](https://nodejs.org/api/process.html#processargv) property, and do not include the Node.js executable, the name of the script, or any options following the script name. These options are useful in order to spawn child processes with the same execution environment as the parent.

Example program:
```js
console.log({ argv: process.argv, execArgv: process.execArgv });
```

### What is the expected behavior?

```console
% bun run args.js -a -b -c    
{
  argv: [ "/opt/homebrew/Cellar/bun/1.1.12/bin/bun", "/Users/john/Documents/Sandpits/commander/issues/2205/args.js",
    "-a", "-b", "-c"
  ],
  execArgv: [],
}


% bun run args.js foo -a -b -c
{
  argv: [ "/opt/homebrew/Cellar/bun/1.1.12/bin/bun", "/Users/john/Documents/Sandpits/commander/issues/2205/args.js",
    "foo", "-a", "-b", "-c"
  ],
  execArgv: [],
}
```

### What do you see instead?

Depending on the mixture of script arguments, the script options may incorrectly appear in `process.execArgv`.

```console
% bun run args.js -a -b -c    
{
  argv: [ "/opt/homebrew/Cellar/bun/1.1.12/bin/bun", "/Users/john/Documents/Sandpits/commander/issues/2205/args.js",
    "-a", "-b", "-c"
  ],
  execArgv: [],
}


% bun run args.js foo -a -b -c
{
  argv: [ "/opt/homebrew/Cellar/bun/1.1.12/bin/bun", "/Users/john/Documents/Sandpits/commander/issues/2205/args.js",
    "foo", "-a", "-b", "-c"
  ],
  execArgv: [ "-a", "-b", "-c" ],
}
```

### Additional information

I am reporting this because of an issue opened against Commander by a Bun user. When they upgraded Commander, their program broke because Commander has added auto-detection support for the node mode options like `-e` and `--print`. The auto-detection misfires because the script `-e` option is also appearing in `process.execArgv`.

- https://github.com/tj/commander.js/issues/2205
- https://github.com/tj/commander.js/pull/2164

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Fixes #11673 (this issue is a good write up)

### CODE REVIEW

File: src/bun.js/node/types.zig [hunk 1]
```diff
@@ -4903,32 +4904,62 @@ pub const Process = struct {
...
+        defer args.deinit();
+
+        var seen_run = false;
+        var prev: ?[]const u8 = null;
 
-        for (bun.argv[@min(bun.argv.len, offset)..]) |arg| {
-            if (arg.len == 0)
+        // we re-parse the process argv to extract execArgv, since this is a very uncommon operation
+        // it isn't worth doing this as a part of the CLI
+        for (bun.argv[1..]) |arg| {
```
Comment (Jarred-Sumner) [inline src/bun.js/node/types.zig]:
```suggestion
        for (bun.argv[@min(bun.argv.len, 1)..]) |arg| {
```

Comment (paperclover) [reply src/bun.js/node/types.zig]: is it possible to start the runtime with *zero* arguments?

Comment (Jarred-Sumner) [reply src/bun.js/node/types.zig]: it should be possible, yes
