### PR TITLE
Fixed: radians rewritten to degrees without converting

### LINKED ISSUE #19619: radians rewritten to degrees without converting
### What version of Bun is running?

1.2.13+64ed68c9e

### What platform is your computer?

Darwin 24.4.0 arm64 arm

### What steps can reproduce the bug?

Create a CSS file containing radians, e.g.:

```css
/* bun.css */
.bun {
    transform: rotate(1rad);
}
```

Build it: `bun build bun.css`

### What is the expected behavior?

The amount `1rad` should be passed through unmodified (or perhaps converted to degrees, but that would be imprecise and result in more characters)

### What do you see instead?

`1rad` is rewritten to `1deg`, which is not the same value (a radian is around 57 degrees):

```css
/* bun.css */
.bun {
  transform: rotate(1deg);
}
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by 39ali**
### What does this PR do?

Fixes #19619

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

If JavaScript/TypeScript modules or builtins changed:

- [ ] I included a test for the new code, or existing tests cover it
- [x] I ran my tests locally and they pass (`bun-debug test test-file-name.test`)

### CODE REVIEW

**Comment by RiskyMH** [comment]
Can you make a test so this doesn't regress in the future :)

**Comment by 39ali** [comment]
@RiskyMH  done!

File: src/css/values/angle.zig [hunk 1]
```diff
@@ -82,17 +82,7 @@ pub const Angle = union(Tag) {
...
-            .rad => |val| brk: {
-                const deg = this.toDegrees();
-
-                // We print 5 digits of precision by default.
-                // Switch to degrees if there are an even number of them.
-                if (css.fract(std.math.round(deg * 100000.0)) == 0) {
-                    break :brk .{ val, "deg" };
-                } else {
-                    break :brk .{ val, "rad" };
-                }
```
Comment (190n) [inline src/css/values/angle.zig]: would it work if instead we kept this logic but changed `.{ val, "deg" }` to `.{ deg, "deg" }`? that way we can transpile something like `0.52359878rad` to `30deg` which seems to be the intent of this if/else

Comment (39ali) [reply src/css/values/angle.zig]: i decided to convert rad to deg only if it's length(char length) is smaller to minimize precision error and file size, 
 because in cases where `1rad` it'll get converted to `57.30deg` which is longer and less accurate , and if `0.52359878rad` the results will be `30deg`, a solution that will kinda accommodates both

Comment (39ali) [reply src/css/values/angle.zig]: @190n wdut?

Comment (190n) [reply src/css/values/angle.zig]: > in cases where 1rad it'll get converted to 57.30deg which is longer and less accurate
> if 0.52359878rad the results will be 30deg

Wouldn't the original logic (`css.fract(std.math.round(deg * 100000.0)) == 0`) have accomplished both of these results, too? Since it's checking the precision of the converted degrees value not the original radians.

I'd prefer to keep the fix for this tightly scoped, and then if we want to make broader changes to how we decide which unit to print the result in we can apply those in more places on a followup PR.

@zackradisic any thoughts?

File: test/js/bun/css/css.test.ts [hunk 2]
```diff
@@ -6939,6 +6939,10 @@ describe("css tests", () => {
     minify_test(".foo { transform: scale3d(1, 2, 1)", ".foo{transform:scaleY(2)}");
     minify_test(".foo { transform: scale3d(1, 1, 2)", ".foo{transform:scaleZ(2)}");
     minify_test(".foo { transform: scale3d(2, 2, 1)", ".foo{transform:scale(2)}");
+    minify_test(".foo { transform: rotate(20rad)", ".foo{transform:rotate(20rad)}");
+    minify_test(".foo { transform: rotateX(20rad)", ".foo{transform:rotateX(20rad)}");
+    minify_test(".foo { transform: rotateY(20rad)", ".foo{transform:rotateY(20rad)}");
+    minify_test(".foo { transform: rotateZ(20rad)", ".foo{transform:rotate(20rad)}");
```
Comment (190n) [inline test/js/bun/css/css.test.ts:6945]: We should also test cases where the rounding logic has an effect (like 0.017453293 rad -> 1 deg)

File: src/css/values/angle.zig (hunk 1 above)
Comment (39ali) [reply src/css/values/angle.zig]: > Wouldn't the original logic (`css.fract(std.math.round(deg * 100000.0)) == 0`) have accomplished both of these results, too? Since it's checking the precision of the converted degrees value not the original radians.

@190n  no, take 1rad for example -> 57.29578deg -> css.fract(5729578)=0 so it'll take the deg instead of the 1rad, the logic doesn't make sense here, so without a change it'll almost always take the deg

File: test/js/bun/css/css.test.ts (hunk 2 above)
Comment (39ali) [reply test/js/bun/css/css.test.ts:6945]: done !
