### PR TITLE
fix #3716

### LINKED ISSUE #3716: Bun.env truncates .env string values containing `#` when run as an npm script
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

Create a directory containing
.env
```
TEST_VAR='ABC#DEF'
```

reproFile.js
```
console.log(Bun.env.TEST_VAR);
```

package.json
```
{
  "name": "bun-env-bug-repro",
  "scripts": {
    "reproScript": "bun run reproFile.js"
  }
}
```

cd into new directory
run `bun run reproFile.js` - the terminal output is correct `ABC#DEF`
run `bun reproScript` - the terminal output is incorrect `ABC` (truncates `#` and rest of string)

### What is the expected behavior?

The output of `bun reproScript` and `bun run reproFile.js` is `ABC#DEF` in both cases

### What do you see instead?

`bun run reproFile.js` outputs `ABC#DEF`
`bun reproScript` outputs `ABC` and truncates the `#` and the rest of the string

### Additional information

The same bug appears if the reproFile is `.ts`
`bun run reproScript` has the same bug as just `bun reproScript`

Not sure whether that's any help

### PR DESCRIPTION
**Pull request by dylan-conway**
fixes #3716

### CODE REVIEW

File: src/env_loader.zig [hunk 1]
```diff
@@ -329,13 +329,24 @@ pub const Loader = struct {
...
-        // This is a little weird because it's evidently stored line-by-line
-        var source = logger.Source.initPathString("process.env", "");
-
         this.map.map.ensureTotalCapacity(std.os.environ.len) catch unreachable;
-        for (std.os.environ) |env| {
-            source.contents = bun.span(env);
-            Parser.parse(&source, this.allocator, this.map, true, true);
+        for (std.os.environ) |_env| {
+            var env = bun.span(_env);
+            if (strings.indexOfChar(env, '=')) |i| {
```
Comment (Jarred-Sumner) [inline src/env_loader.zig:335]: wonder what happens if an env key has an `=` in it

Comment (Jarred-Sumner) [reply src/env_loader.zig:335]: according to Stack Overflow, this is correct

https://stackoverflow.com/questions/41109789/is-the-equals-sign-character-allowed-in-the-value-of-an-environment-value-in
