### PR TITLE
windows: changes to install/upgrade/uninstallation process

### LINKED ISSUE #8919: windows release blocker: make sure `bun upgrade` upgrades `bunx`
putting this todo item publicly so others are aware.

right now i think `bun upgrade` doesn't upgrade the `bunx.exe` hard link. this is simply [incorrect](https://www.merriam-webster.com/dictionary/incorrect) behavior.

i handle this in `install.ps1`

```ps1
# delete bunx if it exists already. this happens if you re-install
# we don't want to hit an "already exists" error.
Remove-Item "${BunBin}\bunx.exe" -ErrorAction SilentlyContinue
Remove-Item "${BunBin}\bunx.cmd" -ErrorAction SilentlyContinue

try {
  $null = New-Item -ItemType HardLink -Path "${BunBin}\bunx.exe" -Target "${BunBin}\bun.exe" -Force
} catch {
  Write-Warning "Could not create a hard link for bunx, falling back to a cmd script`n"
  Set-Content -Path "${BunBin}\bunx.cmd" -Value "@%~dp0bun.exe x %*"
}
```

this logic has to be ported to zig for bun upgrade

### LINKED ISSUE #9006: add an option to install.ps1 to prevent updating path + update path through registry
See https://github.com/prefix-dev/pixi/pull/692

See https://discord.com/channels/876711213126520882/1149339379446325248/1209328330604683304

### PR DESCRIPTION
**Pull request by paperclover**
Fixes #8919

- Do not expand env vars. Fixes #9006
- Add an Uninstall script. This also adds it into the "Add and Remove Programs" menu.
- Rewrite the bunx hardlink every installation
- Other cleanup steps

Supersedes #8877

### CODE REVIEW

File: src/cli/shell_completions.zig [hunk 1]
```diff
@@ -37,6 +38,8 @@ pub const Shell = enum {
             return Shell.zsh;
         } else if (strings.eqlComptime(basename, "fish")) {
             return Shell.fish;
+        } else if (strings.eqlComptime(basename, "pwsh") or strings.eqlComptime(basename, "powershell")) {
+            return Shell.fish;
```
Comment (Jarred-Sumner) [inline src/cli/shell_completions.zig]: Shell.powershell

File: src/cli/install.ps1 [hunk 2]
```diff
@@ -1,35 +1,95 @@
...
+  Write-Output "Bun for Windows is only available for x86 64-bit Windows.`n"
+  exit 1
+}
+
+# This corresponds to .win10_rs5 in build.zig
+$MinBuild = 17763;
+$MinBuildName = "Windows 10 1809"
+$WinVer = [System.Environment]::OSVersion.Version
+if ($WinVer.Major -lt 10 -or ($WinVer.Major -eq 10 -and $WinVer.Build -lt $MinBuild)) {
+  Write-Warning "Bun requires at $($MinBuildName) or newer.`n`nThe install will still continue but it may not work.`n"
```
Comment (RiskyMH) [inline src/cli/install.ps1]: The `$($MinBuildName)` seems a little overkill, I think it should be just `$MinBuildName` or instead place the `Windows 10 1809` text there (as its the only usage).

**Comment by Jarred-Sumner** [comment]
does not compile on windows
