### PR TITLE
bustDirCache on FileSystemRouter.reload & fix of dir_cache keys in windows 

### LINKED ISSUE #4522: FileSystemRouter reload method not working
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

Hello !

I'm trying to used FIleSystemRouter with watch function from fs but when i renamed, moved, deleted a file in the watched directory, the router keep the last route state (same routes, no change)

i tried many thing, like removing watch function and create a setInterval and reload router and console the router, but still same

i prepared for you a little zip containing minimal reproduction code

repro:
   add a new page in pages directory and remove it after

[FileSystemRouter_issue.zip](https://github.com/oven-sh/bun/files/12538806/FileSystemRouter_issue.zip)

thank you ! 

### What is the expected behavior?

refreshing the router instance to see the new discovered routes

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Kapsonfire**
### What does this PR do?

When the structure of the routes directory for the FileSystemRouter changes, the reload function cant load it, because readDirInfo is cached. So I changed the code to recursively bust the dirCache.

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [X] Code changes

### How did you verify your code works?

I dont know how to write tests for this. Ive tested it locally.

Fixes #4522

### CODE REVIEW

File: src/bun.js/api/filesystem_router.zig [hunk 1]
```diff
@@ -211,6 +211,38 @@ pub const FileSystemRouter = struct {
...
+            return;
+        };
+
+        if (root_dir_info) |dir| {
+            if (dir.getEntriesConst()) |entries| {
+                var iter = entries.data.iterator();
+                outer: while (iter.next()) |entry_ptr| {
+                    const entry = entry_ptr.value_ptr.*;
+
+                    if (entry.base()[0] == '.') {
```
Comment (paperclover) [inline src/bun.js/api/filesystem_router.zig:216]: this should also ignore `node_modules`, see `router.zig`'s `banned_dirs`

**Review by paperclover — CHANGES_REQUESTED** [review]
nice. at a glance this looks reasonable, but you should add a test case to cover changing directories

**Comment by Jarred-Sumner** [comment]
Can’t we bump the version number and then we don’t need to eagerly call bustDirCache?

File: src/bun.js/api/filesystem_router.zig (hunk 1 above)
Comment (Kapsonfire) [reply src/bun.js/api/filesystem_router.zig:216]: Done! I've exported the banned_dirs from router.zig and using it in the filesystemrouter

Comment (Kapsonfire) [reply src/bun.js/api/filesystem_router.zig:216]: Also there's a test included now

**Review by paperclover — APPROVED** [review]

**Comment by Kapsonfire-DE** [comment]
The key generation for dir_caches had a bug on windows.
Trailing slashes were removed but it was hardcoded to "/" - since Windows uses "\\" the bustDirCache function in Windows did not work properly. I've changed it by moving the hardcoded to a constant defined before. the constant is set on comptime. 
\\ for windows
else
/

File: src/allocators.zig [hunk 2]
```diff
@@ -469,6 +469,11 @@ pub fn BSSMap(comptime ValueType: type, comptime count: anytype, comptime store_
         const Self = @This();
         const Overflow = OverflowList(ValueType, count / 4);
 
+        const TRAILING_SLASH_CHAR = if (Environment.isWindows)
```
Comment (paperclover) [inline src/allocators.zig]: instead of this, can't `std.fs.path.sep_str` can be used?

(additionally, this variable should be lowercase, but for this situation it should just be removed)

**Review by paperclover — CHANGES_REQUESTED** [review]
will run tests but one nitpick

File: src/allocators.zig (hunk 2 above)
Comment (Kapsonfire) [reply src/allocators.zig]: you are right - replaced it
