### PR TITLE
fix(runtime): remove env variable limit

### LINKED ISSUE #6694: Bun.env limited to 768?
### What version of Bun is running?

v1.0.7

### What platform is your computer?

Linux 5.10.196-183.736.amzn2.x86_64

### What steps can reproduce the bug?

Load up a lot of environment variables. In my case, I'm running this in a oven/bun docker image inside of a large K8s cluster. This K8s cluster is populating lots of environment variables.

```sh
echo "console.log(Object.keys(Bun.env).length)" > test.ts
bun run test.ts
# -> 768
env | wc -l
# -> 952
```

### What is the expected behavior?

I expect Bun.env to see the same env variables
I mainly noticed it because of the 4 env variables I was having k8s assign to my pod, only 1 of them was recognized inside Bun, but all 4 were in the `env | grep MY_ENV` command.

### What do you see instead?

Bun doesn't seem to load past 768 Env vars. Perhaps on of my variables is breaking the parsing somehow, but 768 does seem like a somewhat round number (3 * 256)

### Additional information

https://discord.com/channels/876711213126520882/1166504028771987556/1166504028771987556

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Previously, we had a 768 env var limit, only because it wasn't super clear how to get the data from zig to c++. Using pointers to the zig bytes, this is done using the minimal amount of pointer work and only one string copy per key.

Fixes #6694

### CODE REVIEW

File: src/bun.js/api/bun.zig [hunk 1]
```diff
@@ -4414,8 +4414,16 @@ pub const FFIObject = struct {
 /// Also, you can't iterate over process.env normally since it only exists at build-time otherwise
 // This is aliased to Bun.env
 pub const EnvironmentVariables = struct {
-    pub export fn Bun__getEnvNames(globalObject: *JSC.JSGlobalObject, names: [*]ZigString, max: usize) usize {
-        return getEnvNames(globalObject, names[0..max]);
```
Comment (dylan-conway) [inline src/bun.js/api/bun.zig:4418]: `getEnvNames` function should be deleted

**Review by dylan-conway — APPROVED** [review]
LGTM
