### PR TITLE
Fixes #12039

### LINKED ISSUE #12039: Bun panic caused by Segmentation fault.
### How can we reproduce the crash?

Hi, 
I want to report bun panic while using zero width joiner (zwd), you can reproduce this bug by running the following code. 

```javascript 
class C {
    W_‍_J;
  }
var c = new C();
```

### Relevant log output

```shell
============================================================
Bun v1.1.15 (b23ba1fe) macOS x64
Args: "bun" "run" "bug.js"
Features: jsc 
Builtins: "bun:main" 
Elapsed: 7880ms | User: 4159ms | Sys: 3255ms
RSS: 5.27GB | Peak: 5.27GB | Commit: 14.00GB | Faults: 0

panic(main thread): Segmentation fault at address 0x10001
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on macos x86_64 [RunCommand]

Segmentation fault at address 0x00010001

- *2 unknown/js code*
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.Parser._parse__anon_347685`
- `src.cache.JavaScript.parse`
- `src.bundler.Bundler.parseMaybeReturnFileOnlyAllowSharedBuffer__anon_313038`
- `src.bundler.Bundler.parseMaybeReturnFileOnly__anon_305623`

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #12039

### How did you verify your code works?

There is a test

### CODE REVIEW

File: src/js_lexer/identifier.zig [hunk 1]
```diff
@@ -108,6 +109,8 @@ pub const JumpTable = struct {
             'A'...'Z', 'a'...'z', '0'...'9', '$', '_' => true,
             else => if (codepoint < 128)
                 return false
+            else if (codepoint == 0x200C or codepoint == 0x200D)
```
Comment (dylan-conway) [inline src/js_lexer/identifier.zig:112]: This also applies for `isIdentifierStart` i think

File: test/regression/issue/012039.test.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+test("#12039 ZWJ", async () => {
+  const code = /*js*/ `
+export default class {
+  W‍;
+}
+`;
+  expect(() => new Bun.Transpiler().transformSync(code)).not.toThrow();
+});
+
+test("#12039 ZWNJ", async () => {
```
Comment (dylan-conway) [inline test/regression/issue/012039.test.ts:13]: and we should have a test for starting with 2805

File: src/js_lexer/identifier.zig (hunk 1 above)
Comment (Jarred-Sumner) [reply src/js_lexer/identifier.zig:112]: Only identifier continue

**Review by dylan-conway — APPROVED** [review]
