### PR TITLE
ensure `.bin` folder is created before linking binaries

### LINKED ISSUE #7161: `error: linking uuid: FileNotFound` on bun install
### What version of Bun is running?

1.0.12+85c997513

### What platform is your computer?

Amazon Linux 2.4 x86 (Codebuild)

### What steps can reproduce the bug?

I was not able to reproduce this issue locally.

Create a bun project and install any of the following packages:
- json5
- uuid
- jsesc
- js-yaml
- regjsparser
- semver
- which

Run an AWS codebuild instance to build the project that executes: `bun install`

### What is the expected behavior?

Bun will install the packages without error

### What do you see instead?

```

1518 packages installed [51.38s]
--
152 |  
153 | error: linking json5: FileNotFound
154 |  
155 | error: linking jsesc: FileNotFound
156 |  
157 | error: linking js-yaml: FileNotFound
158 |  
159 | error: linking regjsparser: FileNotFound
160 |  
161 | error: linking semver: FileNotFound
162 |  
163 | error: linking resolve: FileNotFound
164 |  
165 | error: linking uuid: FileNotFound
166 |  
167 | error: linking json5: FileNotFound
168 |  
169 | error: linking which: FileNotFound
170 |  
171 | error: linking jsesc: FileNotFound
172 |  
173 | error: linking rollup: FileNotFound


```

### Additional information

I don't believe this issue is specific to codebuild itself but I don't know which environment could replicate it. I was also trying to rollback bun as I had no issues with it up until this point but somehow it's now failing with these errors and there seems to be no way to rollback or install a specific version.

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
fixes #7161 

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?
added and modified tests

### CODE REVIEW

File: src/install/bin.zig [hunk 1]
```diff
@@ -352,8 +357,31 @@ pub const Bin = extern struct {
...
+                            };
+                        } else {
+                            root_dir.makeDirZ(".bin") catch |err| {
+                                this.err = err;
+                                return;
+                            };
+                        }
+
+                        if (comptime Environment.isPosix) {
+                            Bin.Linker.umask = C.umask(0);
```
Comment (Jarred-Sumner) [inline src/install/bin.zig:375]: We should only run this once.

**Review by Jarred-Sumner — APPROVED** [review]
