### PR TITLE
.npmrc follow up

### LINKED ISSUE #12332: Bun install failed with `.npmrc` (username/password)
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64 | Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

1. Write and publish a private NPM package on a registry (GCP artifact registry in my case)
2. Create another project with dependency from (1)
3. Create a `.npmrc` file to configure scoped registry (generated by `google-artifactregistry-auth` in my case)
4. Make sure the registry is authenticated using `username` and `_password`
5. Delete bun cache directory from local machine
6. Delete `node_modules`
7. Run `bun install`

_Normally, `google-artifactregistry-auth` will generate `_authToken`, but I take the `.npmrc` from GitHub Actions that `google-artifactregistry-auth` generated `username` and `_password` instead._

### What is the expected behavior?

Bun should be successfully installed everything

### What do you see instead?

```
error: GET https://asia-southeast1-npm.pkg.dev/<project-id>/<repo-name>/<pkg-name>/-/<pkg-name>-<version>.tgz - 403
```

### Additional information

- Originally occurred on Linux (GitHub Actions) using GCP Service Account login. But the same configuration (basic auth `_json_key_base64`) error on everything I tested (windows, docker WSL, github actions)
- Tried with NPM on Windows using same configuration -> working
- Tried with Yarn on Windows using same configuration -> working
- Tried with NPM on Docker WSL using same configuration -> working

Here is the `.npmrc`:
```
# Insert the following snippet into your project .npmrc
@my-org-private-pkgs:registry=https://asia-southeast1-npm.pkg.dev/gcp-project-id/my-org-private-pkgs/
//asia-southeast1-npm.pkg.dev/gcp-project-id/my-org-private-pkgs/:always-auth=true
# Insert the following snippet into your user .npmrc
//asia-southeast1-npm.pkg.dev/gcp-project-id/my-org-private-pkgs/:_password="<REDACTED -- BASE64(BASE64(SERVICE_ACCOUNT_JSON))>"
//asia-southeast1-npm.pkg.dev/gcp-project-id/my-org-private-pkgs/:username=_json_key_base64
//asia-southeast1-npm.pkg.dev/gcp-project-id/my-org-private-pkgs/:email=not.valid@email.com
```

You may notice the `email` field on the `.npmrc`, I have tried downloading using just Postman with basic auth, working ok

### LINKED ISSUE #12338: [Bun v1.1.18] .npmrc auth option support
### What is the problem this feature would solve?

In our company we use `.npmrc` like this:

```
@some-name:registry=http....
//.../repository/npm/:_auth=some__secret_key
```

And for now I have an error
image

EDIT:
I try to rewrite our `.npmrc` :

```
@some-name:registry=http://.../repository/npm/    <- this / at the end is VERY IMPORTANT
_auth=some__secret_key
```

And it works!

### What is the feature you are proposing to solve the problem?

Support for npmrc auth option.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by zackradisic**
### What does this PR do?

Fixes #12332
Fixes #12338

Fix unresolved comments from previous PR

### CODE REVIEW

File: src/ini.zig [hunk 1]
```diff
@@ -724,8 +726,43 @@ pub const ConfigIterator = struct {
...
+                    log.addErrorFmt(
+                        source,
+                        this.loc,
+                        allocator,
+                        "{s} is not valid base64",
+                        .{@tagName(this.optname)},
+                    ) catch bun.outOfMemory();
+                    return null;
+                }
+                std.debug.print("{s} = {s}\n", .{ @tagName(this.optname), slice[0..result.count] });
```
Comment (Jarred-Sumner) [inline src/ini.zig]: It's a little suspicious that there were no test failures because of this std.debug.print

File: src/ini.zig [hunk 2]
```diff
@@ -858,20 +893,17 @@ pub fn loadNpmrcFromFile(
...
-                err,
+                e,
                 ".npmrc",
             });
             Global.exit(1);
         },
-    }
-    const source = bun.logger.Source.initPathString(".npmrc", npmrc_contents.items[0..]);
+    };
+    defer allocator.free(source.contents);
```
Comment (dylan-conway) [inline src/ini.zig:907]: This will free contents before it's used by logger. Maybe move `printForLogLevel` to the bottom of this function?

File: src/ini.zig [hunk 3]
```diff
@@ -1142,23 +1192,50 @@ pub fn loadNpmrc(
...
+            source,
+            conf_item.loc,
+            allocator,
+            "invalid _auth value, expected it to decode to \\<username\\>:\\<password\\> but got an empty string",
+            .{},
+        ) catch bun.outOfMemory();
+        return;
+    }
+    const decode_len = bun.base64.decodeLen(conf_item.value);
+    var decoded = allocator.alloc(u8, decode_len) catch bun.outOfMemory();
```
Comment (dylan-conway) [inline src/ini.zig]: nit. this will make it harder to free the wrong pointer if this code is changed in the future
```suggestion
    const decoded = allocator.alloc(u8, decode_len) catch bun.outOfMemory();
```

File: src/ini.zig [hunk 4]
```diff
@@ -1142,23 +1192,50 @@ pub fn loadNpmrc(
...
+    const result = bun.base64.decode(decoded[0..], conf_item.value);
```
Comment (dylan-conway) [inline src/ini.zig:1226]: This base64 decode will always fail for `username:password` because it includes invalid character `:`. Will need to change this to find `colon_idx` first

**Review by dylan-conway — CHANGES_REQUESTED** [review]
Left a few comments. Main things are:
- split `username:password` so `:` isn't decoded
- free source contents after error printing

File: src/ini.zig (hunk 4 above)
Comment (zackradisic) [reply src/ini.zig:1226]: this is okay because its the entire string encoded in base64 (e.g. `btoa(username + ":" + password)`)

Comment (dylan-conway) [reply src/ini.zig:1226]: ah right, that makes sense

**Review by dylan-conway — APPROVED** [review]

**Comment by dylan-conway** [comment]
@zackradisic The test failure on windows in `bun-install-registry.test.ts` is real
