### PR TITLE
fix 16939

### LINKED ISSUE #16939: `Bun.file('háčky-čárky').stat()` fails with `ENOENT` error
### What version of Bun is running?

1.2.1+ce532901c

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

While `Bun.file('bořek.txt').exists()` works fine, `Bun.file('bořek.txt').stat()` fails with `ENOENT` error when file contains diacritics.

Reproduction here: https://github.com/ViliamKopecky/bun-file-stat-diacritics-bugreport

### What is the expected behavior?

`Bun.file().stat()` should work with diacritics in file names.

```txt
alice.txt exists true
alice.txt stat 5

bořek.txt exists true
bořek.txt stat 5
```

### What do you see instead?

```txt
alice.txt exists true
alice.txt stat 5

bořek.txt exists true
ENOENT: no such file or directory, stat 'boÅek.txt'
    path: "boÅek.txt",
 syscall: "stat",
   errno: -2,
    code: "ENOENT"


Bun v1.2.1 (macOS arm64)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Fixes using paths with unicode in `Bun.file().stat()` and `Bun.file().delete/unlink()`

Closes #16939

### How did you verify your code works?
Added a test for both functions.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 5:10 AM PT - Feb 2nd, 2025</sup></div>

@dylan-conway, your commit ac49fad1794667dcccdb18b18f6d4db46a2e1fc2 is building: [`#11016`](https://buildkite.com/bun/bun/builds/11016)

File: src/bun.js/webcore/blob.zig [hunk 1]
```diff
@@ -4750,15 +4755,23 @@ pub const Blob = struct {
...
         return switch (store.data) {
             .file => |*file| {
                 return switch (file.pathlike) {
-                    .path => |path_like| JSC.Node.Async.stat.create(globalThis, undefined, .{
-                        .path = .{ .encoded_slice = ZigString.init(path_like.slice()).toSliceClone(bun.default_allocator) },
-                    }, globalThis.bunVM()),
+                    .path => |path_like| {
+                        return JSC.Node.Async.stat.create(globalThis, undefined, .{
+                            .path = .{
+                                .encoded_slice = switch (path_like) {
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/blob.zig:4767]: maybe we can use path_like.toThreadSafe()? There's a method like that somewhere
