### PR TITLE
SQLite in Bun.sql

### LINKED ISSUE #18951: Export PostgresError class for type-safe error handling
### What is the problem this feature would solve?

When using Bun's PostgreSQL client, error handling is currently suboptimal because the `PostgresError` type is not exported. This makes it impossible to use `instanceof` checks for proper error handling and type narrowing.

Currently, when catching database errors, developers must rely on duck typing or property checking to determine if an error is PostgreSQL-specific. This approach is brittle, less type-safe, and requires extra boilerplate code that could be avoided with proper type exports.

```javascript
try {
  // Database operation
} catch (error) {
  // Cannot do: if (error instanceof PostgresError)
  
  // Must resort to property checking:
  if (typeof error === 'object' && 
      error !== null && 
      'code' in error && 
      'severity' in error) {
    // Handle as PostgreSQL error
  }
}
```

### What is the feature you are proposing to solve the problem?

Export the `PostgresError` class/type from the PostgreSQL client implementation to allow for proper error handling using `instanceof` checks.

This would enable clean, type-safe error handling:

```javascript
import { PostgresError } from 'bun'; // or wherever it would be exported from

try {
  // Database operation
} catch (error) {
  if (error instanceof PostgresError) {
    // Type-safe access to properties
    console.error(`Database error: ${error.code}`);
    
    // Handle specific error types
    if (error.code === '23505') {
      // Handle unique constraint violation
    }
  } else {
    // Handle other error types
  }
}
```

### What alternatives have you considered?

_No response_

### LINKED ISSUE #19701: SQLite adapter with `Bun.sql`
Bun has a built-in SQLite client with [`bun:sqlite`](https://bun.sh/docs/api/sqlite). We also want it to support using SQLite with the new `Bun.sql` APIs, which currently supports Postgres.

### PR DESCRIPTION
**Pull request by alii**
### What does this PR do?

Support sqlite in the Bun.sql API

Fixes #18951
Fixes #19701

### How did you verify your code works?

tests

### CODE REVIEW

**Comment by pxseu** [comment]
great stuff

File: src/bun.js/bindings/sqlite/JSSQLStatement.cpp [hunk 1]
```diff
@@ -1526,14 +1585,35 @@ JSC_DEFINE_HOST_FUNCTION(jsSQLStatementPrepareStatementFunction, (JSC::JSGlobalO
...
     if (
         // fast path: ascii latin1 string is utf8
         sqlString.is8Bit() && simdutf::validate_ascii(reinterpret_cast<const char*>(sqlString.span8().data()), sqlString.length())) {
-        rc = sqlite3_prepare_v3(db, reinterpret_cast<const char*>(sqlString.span8().data()), sqlString.length(), flags, &statement, nullptr);
+        const char* sqlData = reinterpret_cast<const char*>(sqlString.span8().data());
+        const char* sqlEnd = sqlData + sqlString.length();
+        rc = sqlite3_prepare_v3(db, sqlData, sqlString.length(), flags, &statement, &tail);
+
+        // Check if there are remaining statements
+        if (rc == SQLITE_OK && tail != nullptr && tail < sqlEnd) {
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/sqlite/JSSQLStatement.cpp]: By design, multiple statements in sqlite3_prepare_v3 is not supported. Should this code still be here?

File: src/bun.js/bindings/sqlite/JSSQLStatement.cpp [hunk 2]
```diff
@@ -1526,14 +1585,35 @@ JSC_DEFINE_HOST_FUNCTION(jsSQLStatementPrepareStatementFunction, (JSC::JSGlobalO
...
     } else {
         // slow path: utf16 or latin1 string with supplemental characters
         CString utf8 = sqlString.utf8();
-        rc = sqlite3_prepare_v3(db, utf8.data(), utf8.length(), flags, &statement, nullptr);
+        const char* sqlData = utf8.data();
+        const char* sqlEnd = sqlData + utf8.length();
+        rc = sqlite3_prepare_v3(db, sqlData, utf8.length(), flags, &statement, &tail);
+
+        // Check if there are remaining statements
+        if (rc == SQLITE_OK && tail != nullptr && tail < sqlEnd) {
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/sqlite/JSSQLStatement.cpp]: Here as well.

File: src/js/internal/sql/query.ts [hunk 3]
```diff
@@ -0,0 +1,330 @@
...
+Object.defineProperty(Query, Symbol.species, { value: PublicPromise });
+Object.defineProperty(Query, Symbol.toStringTag, { value: "Query" });
+
+enum SQLQueryResultMode {
+  objects = 0,
+  values = 1,
+  raw = 2,
+}
+
+enum SQLQueryFlags {
```
Comment (Jarred-Sumner) [inline src/js/internal/sql/query.ts]: Can you verify manually in the build/debug output that these get inlined into integer literals?

File: src/js/internal/sql/shared.ts [hunk 4]
```diff
@@ -0,0 +1,559 @@
...
+  if (!isOptionsOfAdapter(options, adapter)) {
+    throw new Error(`Expected adapter to be ${adapter}, but got '${options.adapter}'`);
+  }
+}
+
+function parseOptions(
+  stringOrUrlOrOptions: Bun.SQL.Options | string | URL | undefined,
+  definitelyOptionsButMaybeEmpty: Bun.SQL.Options,
+): Bun.SQL.__internal.DefinedOptions {
+  let [
```
Comment (Jarred-Sumner) [inline src/js/internal/sql/shared.ts]: let's avoid all these extra property accesses


```suggestion
  const env = Bun.env;
```

File: src/js/internal/sql/query.ts (hunk 3 above)
Comment (alii) [reply src/js/internal/sql/query.ts]: They do not since, but I had to remove the const since const enums aren't supported being passed around as a value. The internals generator doesn't like named exports but we might be able to adjust it to support inlining const enums only. I'll make sure to look into that before this merges.

File: src/js/internal/sql/sqlite.ts [hunk 5]
```diff
@@ -0,0 +1,611 @@
...
+      return "UPDATE";
+    case SQLCommand.whereIn:
+    case SQLCommand.where:
+      return "WHERE";
+    default:
+      return "";
+  }
+}
+
+function detectCommand(query: string): SQLCommand {
```
Comment (Jarred-Sumner) [inline src/js/internal/sql/sqlite.ts]: This causes it to duplicate the query string potentially multiple times.

Instead, we can loop until we have a space-like delimiter and then .slice() just that region?

File: src/js/internal/sql/sqlite.ts [hunk 6]
```diff
@@ -0,0 +1,611 @@
...
+        sql.trim().toUpperCase().includes("RETURNING") ||
+        command === "PRAGMA" ||
+        command === "WITH" ||
+        command === "EXPLAIN"
+      ) {
+        // SELECT queries must use prepared statements for results
+        const stmt = db.prepare(sql);
+        let result: unknown[] | undefined;
+
+        if (mode === SQLQueryResultMode.values) {
```
Comment (Jarred-Sumner) [inline src/js/internal/sql/sqlite.ts:341]: Replace the `...` with .$apply.

File: src/bun.js/bindings/sqlite/JSSQLStatement.cpp [hunk 7]
```diff
@@ -488,6 +491,60 @@ class JSSQLStatement : public JSC::JSDestructibleObject {
     void finishCreation(JSC::VM& vm);
 };
 
+static JSValue toJSAsBuffer(JSC::VM& vm, JSC::JSGlobalObject* globalObject, sqlite3_stmt* stmt, int i)
+{
+    auto scope = DECLARE_THROW_SCOPE(vm);
+
+    switch (sqlite3_column_type(stmt, i)) {
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/sqlite/JSSQLStatement.cpp:497]: can you double check this is the right one to use? the one that is the actual value and not the declaration type

File: src/bun.js/bindings/sqlite/JSSQLStatement.cpp (hunk 1 above)
Comment (alii) [reply src/bun.js/bindings/sqlite/JSSQLStatement.cpp]: it's no longer used, will remove.

File: src/js/internal/sql/errors.ts [hunk 8]
```diff
@@ -0,0 +1,140 @@
+class SQLError extends Error {
```
Comment (cirospaciari) [inline src/js/internal/sql/errors.ts]: extends SQLError

File: src/bun.js/bindings/BunObject.cpp [hunk 9]
```diff
@@ -303,6 +303,9 @@ static JSValue defaultBunSQLObject(VM& vm, JSObject* bunObject)
     auto scope = DECLARE_THROW_SCOPE(vm);
     auto* globalObject = defaultGlobalObject(bunObject->globalObject());
     JSValue sqlValue = globalObject->internalModuleRegistry()->requireId(globalObject, vm, InternalModuleRegistry::BunSql);
+#if BUN_DEBUG
+    if (scope.exception()) globalObject->reportUncaughtExceptionAtEventLoop(globalObject, scope.exception());
+#endif
```
Comment (dylan-conway) [inline src/bun.js/bindings/BunObject.cpp:312]: delete

File: src/bun.js/bindings/BunObject.cpp [hunk 10]
```diff
@@ -312,6 +315,9 @@ static JSValue constructBunSQLObject(VM& vm, JSObject* bunObject)
...
```
Comment (dylan-conway) [inline src/bun.js/bindings/BunObject.cpp:324]: delete

File: src/bun.js/bindings/BunObject.cpp (hunk 9 above)
Comment (dylan-conway) [reply src/bun.js/bindings/BunObject.cpp:312]: don't delete

File: src/bun.js/bindings/BunObject.cpp (hunk 10 above)
Comment (dylan-conway) [reply src/bun.js/bindings/BunObject.cpp:324]: don't delete

Comment (alii) [reply src/bun.js/bindings/BunObject.cpp:324]: 😹

File: src/bun.js/bindings/sqlite/JSSQLStatement.cpp (hunk 7 above)
Comment (alii) [reply src/bun.js/bindings/sqlite/JSSQLStatement.cpp:497]: it is the right one

File: src/js/internal/sql/query.ts (hunk 3 above)
Comment (alii) [reply src/js/internal/sql/query.ts]: They are inlined but the enum still exists (but is _unused_ in the file🤔)
CleanShot 2025-08-18 at 12 18 13@2x

File: src/js/internal/sql/errors.ts [hunk 11]
```diff
@@ -0,0 +1,95 @@
...
+  public readonly line: string | undefined;
+  public readonly routine: string | undefined;
+
+  constructor(message: string, options: PostgresErrorOptions) {
+    super(message);
+
+    this.name = "PostgresError";
+    this.code = options.code;
+
+    if (options.detail !== undefined) this.detail = options.detail;
```
Comment (Jarred-Sumner) [inline src/js/internal/sql/errors.ts:54]: Can these be destructured to avoid duplicate options property accesses

File: src/js/internal/sql/sqlite.ts [hunk 12]
```diff
@@ -0,0 +1,785 @@
...
+
+  private readonly sql: string;
+  private readonly values: unknown[];
+  private readonly parsedInfo: SQLParsedInfo;
+
+  public constructor(sql: string, values: unknown[]) {
+    this.sql = sql;
+    this.values = values;
+    // Parse the SQL query once when creating the handle
+    this.parsedInfo = parseSQLQuery(sql);
```
Comment (Jarred-Sumner) [inline src/js/internal/sql/sqlite.ts:308]: Can we avoid parsing the query multiple times?
