### PR TITLE
types: Rewrite to avoid conflicts and allow for doc generation

### LINKED ISSUE #358: <reference no-default-lib="true" /> in bun-types causes vscode to not recognize  lib.dom.d.ts types
when I add `bun-types` to `tsconfig.json` vscode is unable to recognize types from `lib.dom.d.ts` (`FormData`, `navigator`, etc.).

Removing `bun-types` from `tsconfig.json` brings back DOM types but I want but types so I tinkered around. I commented out this line specifically in `bun-types` and it seems to have solved the problem. Now I can have `bun-types` in `tsconfig.json` and I'm getting DOM types.

https://github.com/Jarred-Sumner/bun/blob/ee83e25120f8ff52fb44d83ac25b965c2cc2b062/packages/bun-types/types.d.ts#L5

### LINKED ISSUE #8761: `@types/bun` still conflicts with `@types/node`
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```
mkdir /tmp/bun-node-types && cd /tmp/bun-node-types
bun init --yes
bun add @types/node @types/bun typescript
echo "{}" > tsconfig.json # Remove `skipLibCheck`
bun x tsc
```

### What is the expected behavior?

TypeScript runs successfully.

### What do you see instead?

```
node_modules/typescript/lib/lib.dom.d.ts:8138:11 - error TS2430: Interface 'EventSource' incorrectly extends interface 'Bun.EventSource'.
  Types of property 'onerror' are incompatible.
    Type '(this: EventSource, ev: Event) => any' is not assignable to type '(this: Bun.EventSource, ev: Event) => any'.
      The 'this' types of each signature are incompatible.
        Type 'Bun.EventSource' is not assignable to type 'EventSource'.
          Types of property 'onmessage' are incompatible.
            Type '(this: Bun.EventSource, ev: Bun.MessageEvent<any>) => any' is not assignable to type '(this: EventSource, ev: MessageEvent<any>) => any'.
              Types of parameters 'ev' and 'ev' are incompatible.
                Type 'MessageEvent<any>' is not assignable to type 'Bun.MessageEvent<any>'.
                  Types of property 'ports' are incompatible.
                    Type 'readonly MessagePort[]' is not assignable to type 'readonly import("worker_threads").MessagePort[]'.
                      Type 'MessagePort' is missing the following properties from type 'MessagePort': ref, unref, addListener, emit, and 13 more.

8138 interface EventSource extends EventTarget {
               ~~~~~~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:15414:11 - error TS2430: Interface 'MessageEvent<T>' incorrectly extends interface 'Bun.MessageEvent<T>'.
  Types of property 'ports' are incompatible.
    Type 'readonly MessagePort[]' is not assignable to type 'readonly import("worker_threads").MessagePort[]'.

15414 interface MessageEvent<T = any> extends Event {
                ~~~~~~~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:25362:11 - error TS2430: Interface 'WebSocket' incorrectly extends interface 'import("/private/tmp/bun-node-types/node_modules/@types/ws/index").WebSocket'.
  Types of property 'binaryType' are incompatible.
    Type 'BinaryType' is not assignable to type '"arraybuffer" | "nodebuffer" | "fragments"'.
      Type '"blob"' is not assignable to type '"arraybuffer" | "nodebuffer" | "fragments"'.

25362 interface WebSocket extends EventTarget {
                ~~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/typescript/lib/lib.dom.d.ts:8138
```

### Additional information

Also see:

- https://github.com/oven-sh/bun/issues/358#issuecomment-1728344170
- https://github.com/oven-sh/bun/issues/463

This prevents me from using `@types/bun` in projects where `@types/node` is also needed. When I try to use `@types/bun` in [`cubing.js`](https://github.com/cubing/cubing.js), I get additional conflicts:

```
node_modules/@types/node/module.d.ts:283:13 - error TS2687: All declarations of 'dirname' must have identical modifiers.

283             dirname: string;
                ~~~~~~~

node_modules/@types/node/module.d.ts:289:13 - error TS2687: All declarations of 'filename' must have identical modifiers.

289             filename: string;
                ~~~~~~~~

node_modules/bun-types/types.d.ts:601:12 - error TS2687: All declarations of 'dirname' must have identical modifiers.

601   readonly dirname: string;
               ~~~~~~~

node_modules/bun-types/types.d.ts:604:12 - error TS2687: All declarations of 'filename' must have identical modifiers.

604   readonly filename: string;
               ~~~~~~~~

node_modules/bun-types/types.d.ts:1036:20 - error TS2694: Namespace 'WebSocket' has no exported member 'WebSocket'.

1036     : import("ws").WebSocket;
                        ~~~~~~~~~
```

### LINKED ISSUE #8765: Bun.stdin.stream() TypeScript type is not iteratable
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Write a program with the stdin example from the [Bun documentation](https://bun.sh/guides/process/stdin):

```typescript
for await (const chunk of Bun.stdin.stream()) {
  // chunk is Uint8Array
  // this converts it to text (assumes ASCII encoding)
  const chunkText = Buffer.from(chunk).toString();
  console.log(`Chunk: ${chunkText}`);
}
```

### What is the expected behavior?

No type errors should be reported.

### What do you see instead?

A type error:

```
Type 'ReadableStream<Uint8Array>' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.
```

### Additional information

Looks like ReadableStream isn't getting the async iterator from stream/web's definition (stream/web has it, lib/dom does not).

### LINKED ISSUE #12662: Headers has incomplete type definition
### What version of Bun is running?

1.1.20

### What platform is your computer?

_No response_

### What steps can reproduce the bug?

The [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) type in Bun doesn't show as an iterable (using for-of) and doesn't include other methods such as `entries()`. However, they do work as iterables at runtime

### What is the expected behavior?

Use the correct type for Headers as defined by the spec.

### What do you see instead?

_No response_

### Additional information

_No response_

### LINKED ISSUE #13167: fetch & Bun.serve tls type error
### What version of Bun is running?

1.1.22-canary.96+df33f2b2a

### What platform is your computer?

Linux 6.6.6-76060606-generic x86_64 x86_64

### What steps can reproduce the bug?

Create a new bun project using `bun init`

Copy and paste the fetch tls example from bun docs https://bun.sh/docs/api/fetch

```ts
await fetch("https://example.com", {
  tls: {
    key: Bun.file("/path/to/key.pem"),
    cert: Bun.file("/path/to/cert.pem"),
    // ca: [Bun.file("/path/to/ca.pem")],
  },
});
```

### What is the expected behavior?

Expected behavior is to have no type errors.

### What do you see instead?

Type error on tls:

```
No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'tls' does not exist in type 'RequestInit'.ts(2769)
lib.dom.d.ts(28327, 18): The last overload is declared here.
```

image

image

### Additional information

I believe this is an issue with DefinitelyTyped's bun types being behind in version. Looks like the last version merged with 1.1.17. Or possibly with the monorepo bun-types being incorrect.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bun
https://github.com/oven-sh/bun/tree/main/packages/bun-types

From the `node_modules/bun-types/globals.d.ts`
```ts
interface FetchRequestInit extends RequestInit {
  /**
	  * Log the raw HTTP request & response to stdout. This API may be
	  * removed in a future version of Bun without notice.
	  * This is a custom property that is not part of the Fetch API specification.
	  * It exists mostly as a debugging tool
	  */
  verbose?: boolean;
  /**
	  * Override http_proxy or HTTPS_PROXY
	  * This is a custom property that is not part of the Fetch API specification.
	  */
  proxy?: string;
  
  /**
	  * Override the default TLS options
	  */
  tls?: {
	  rejectUnauthorized?: boolean | undefined; // Defaults to true
	  checkServerIdentity?: any; // TODO: change `any` to `checkServerIdentity`
  };
}
```

As seen tls only has the two properties `rejectUnauthorized` and `checkServerIdentity`, and is missing `key`, `cert`, and `ca` .

### LINKED ISSUE #13599: Type error with `fetch` and `tls`-Option
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Linux 6.10.6-arch1-1 x86_64

### What steps can reproduce the bug?

- bun init .
- bun add @bun/types
- edit index.ts in vscode:
```ts
fetch("", {
    tls: { rejectUnauthorized: false }  // This will be highlighted by Typescript
})
```

You will get an error about the `tls` property:

```
Object literal may only specify known properties, and 'tls' does not exist in type 'RequestInit'.ts(2769)
```

### What is the expected behavior?

`RequestInit` type should allow the `tls` property.

### What do you see instead?

An error message and squiggly lines.
image

### Additional information

My testing shows that the error exists from 1.1.7 onward. With bun types to 1.1.6, things are fine.

### LINKED ISSUE #13669: `bun-types` marks instances of URL as constructor
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

```ts
const a = new URL("https://bun.sh");
const b = new a("https://bun.sh");
```

### What is the expected behavior?

(tsc and Visual Studio Code) should mark `new a` in line 2 as error

### What do you see instead?

It passes type checks using `@types/bun`, but bun can't run it:

```txt
$ bun run index.ts
1 | const a = new URL("https://bun.sh");
2 | const b = new a("https://bun.sh");
              ^
TypeError: URL is not a constructor (evaluating 'new a("https://bun.sh")')
      at /workspaces/try-bun/src/index.ts:2:11

Bun v1.1.26 (Linux x64 baseline)
```

### Additional information

_No response_

### LINKED ISSUE #13858: `parse` does not exist on URL
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

access the `parse` property of URL

### What is the expected behavior?

it's typed correctly something like the lib types:
```
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/URL/parse_static) */
    parse(url: string | URL, base?: string | URL): URL | null;
```

### What do you see instead?

```
<file name>:919:5 - error TS2339: Property 'parse' does not exist on type '{ new (url: string | URL, base?: string | URL | undefined): URL; prototype: URL; canParse(url: string | URL, base?: string | undefined): boolean; createObjectURL(obj: Blob | MediaSource): string; revokeObjectURL(url: string): void; }'.

919 URL.parse;
```

### Additional information

This function exists:
```
bun repl
Welcome to Bun v1.1.26
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> typeof URL.parse
'function'
> 
```

### LINKED ISSUE #14660: Type 'ReadableStream<any>' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.ts(2504)
### What is the type of issue?

Example code is not working

### What is the issue?

```typescript
const stream = new ReadableStream({
	start(controller) {
		controller.enqueue('hello')
		controller.enqueue('world')
		controller.close()
	},
})

//! Type 'ReadableStream<any>' must have a '[Symbol.asyncIterator]()' method
//! that returns an async iterator.ts(2504)
for await (const chunk of stream) { 
	console.log(chunk)
	// => "hello"
	// => "world"
}

```

maybe tsconfig.json is wrong?

```jsonc
// tsconfig.json
{
	"compilerOptions": {
		"target": "ESNext",
		"jsx": "react-jsx",
		// Enable latest features
		"lib": ["ESNext", "DOM"],
		"moduleDetection": "force",
		"module": "ESNext",

		// Bundler mode
		"moduleResolution": "bundler",
		"allowImportingTsExtensions": true,
		"allowJs": true,

		// Best practices
		"strict": true,
		"noFallthroughCasesInSwitch": true,

		"noPropertyAccessFromIndexSignature": true,
		// Some stricter flags
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noEmit": true,
		"verbatimModuleSyntax": true,
		"skipLibCheck": true
	}
}
```

### Where did you find it?

https://bun.sh/docs/api/streams

### LINKED ISSUE #14892: Bun types not supporting Typescript 5.7 TypedArrays now being generic over ArrayBufferLike
### What version of Bun is running?

1.1.32+fe8d0079e

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

1. Run a typecheck of the following code:

```ts
Buffer.from("foo").equals(Buffer.from("bar"))
```

### What is the expected behavior?

It should typecheck successfully and work.

### What do you see instead?

There is a type error:

```
Argument of type 'Buffer' is not assignable to parameter of type 'Uint8Array'.
  The types returned by 'entries()' are incompatible between these types.
    Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 9 more.ts(2345)
```

But the actual call works.

### Additional information

This feature was introduced in Typescript 5.7 beta:

https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#typedarrays-are-now-generic-over-arraybufferlike

I'm not sure what the policy is surrounding beta features from Typescript, but figure worth raising a bug just in case because the types are preventing making a call that is actually valid in the underlying platform. I can work around it by pinning a newer version of `@types/node`, not sure if that's the expected way to do things though.

### LINKED ISSUE #16044: Buffer type not compatible with BinaryLike
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Microsoft Windows NT 10.0.26100.0 x64

### What steps can reproduce the bug?

Image

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

Installing @types/node as well fixes this, but I don't think you're supposed to use it alongside @types/bun

### LINKED ISSUE #16537: `Error.isError` is implemented but type definition is missing
### What version of Bun is running?

1.1.45

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

[`Error.isError` was implemented in v. 1.1.39](https://bun.sh/blog/bun-v1.1.39#error-iserror)
[The `isError` method does not exist in the `ErrorConstructor` type](https://github.com/oven-sh/bun/blob/3128beed67a182ee11a5ea0ed31ddd2c729c14d3/packages/bun-types/globals.d.ts#L1524)

### What is the expected behavior?

The type definition should be present in `globals.d.ts` to avoid TypeScript warnings.

### What do you see instead?

`Property 'isError' does not exist on type 'ErrorConstructor'.ts(2339)`

### Additional information

_No response_

### LINKED ISSUE #16785: Missing properties in File type
### What version of Bun is running?

1.2.0+b0c5a7655

### What platform is your computer?

Microsoft Windows NT 10.0.26100.0 x64

### What steps can reproduce the bug?

- create a new file, check the `json` and `formData` property through a console log, you should see that they are defined but the types are missing.

### What is the expected behavior?

For `@bun/types` to contain those properties.

### What do you see instead?

No type for those properties.

### Additional information

I saw this bug when dealing a lib that has @types/node and it caused an error on typescript.

### LINKED ISSUE #17203: custom added features in `fetch` are not typed
### What version of Bun is running?

1.2.3-canary.50+14164920b

### What platform is your computer?

Linux 6.8.0-52-generic x86_64 x86_64 

### What steps can reproduce the bug?

```typescript
fetch("https://www.example.com", {
    proxy: "http://something",    
});

fetch("https://www.example.com", {
    unix: "test.sock",    
});
```

### What is the expected behavior?

_No response_

### What do you see instead?

None of the properties (including the rest: s3, tls, decompress, verbose) are typed and fetch inherits the type from `@types/node`.

### Additional information

_No response_

### LINKED ISSUE #17256: fetch is missing { proxy: ... } property
### What version of Bun is running?

1.2.2+c1708ea6a

### What platform is your computer?

Linux 6.8.0-52-generic aarch64 unknown

### What steps can reproduce the bug?

```
await Bun.fetch("https://example.com", {
	proxy: "anything", // this fails
})
```

package.json includes:
```
"devDependencies": {
		"@types/bun": "latest"
	},
```

### What is the expected behavior?

_No response_

### What do you see instead?

```
Object literal may only specify known properties, and 'proxy' does not exist in type 'RequestInit'.
```

### Additional information

_No response_

### LINKED ISSUE #17940: Async generator function not allowed in types for Response constructor
### What version of Bun is running?

1.2.4+fd9a5ea66

### What platform is your computer?

Linux 6.1.43 x86_64 unknown (CodeSandbox)

### What steps can reproduce the bug?

Run TypeScript type checks on [this example](https://bun.sh/guides/http/stream-iterator)

### What is the expected behavior?

No error. TypeScript typings should cover this use case.

### What do you see instead?

```
Argument of type '() => AsyncGenerator<"Hello, " | "world!" | Uint8Array<ArrayBuffer>, void, unknown>' is not assignable to parameter of type 'BodyInit'.
```

[Repro in CodeSandbox](https://codesandbox.io/p/devbox/youthful-worker-tw2r29?workspaceId=ws_WB9kpBETsjiRsWbtDHFqQZ) (requires signing in and possibly forking to see the error)

### Additional information

Using @types/bun version 1.2.4

### LINKED ISSUE #17980: Property `try` does not exist on type 'PromiseConstructor'.typescript(2339) @types/1.2.4
### What version of Bun is running?

1.2.4

### What platform is your computer?

_No response_

### What steps can reproduce the bug?

Promise.try(() => {
  console.log('1');
})

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### LINKED ISSUE #18458: types: Fix not returning anything during upgrade when specifying websockets and routes
> @alii I can confirm most of the issues have resolved with the latest 1.2.6 release, but the last issue I describe in my comment above still persists:
> 
> ```ts
> const server = Bun.serve({
> //                 ~~~~~
>   websocket: {
>     message() {},
>   },
>   routes: {
>     '/ws': (req) => {
>       if (server.upgrade(req)) {
>         return; // <- causes type error
>       }
>       return new Response('Upgrade failed', { status: 500 });
>     }
>   }
> });
> ```
> 
> ```
> Type '(req: BunRequest<"/ws">) => Response | undefined' is not assignable to type 'RouteHandler<"/ws">'.
>     Type 'Response | undefined' is not assignable to type 'Response | Promise<Response>'.
>         Type 'undefined' is not assignable to type 'Response | Promise<Response>'.
> ```
> 
> Both the [documentation](https://bun.sh/docs/api/websockets#start-a-websocket-server) and [unit tests](https://github.com/oven-sh/bun/blob/888a4fa51dcc60f1f049e5031ca5aaa04d7c56f5/test/js/bun/http/bun-server.test.ts#L1126) returns undefined without a response after upgrading a socket.  

 _Originally posted by @iitzkube in [#18314](https://github.com/oven-sh/bun/issues/18314#issuecomment-2750546212)_

### PR DESCRIPTION
**Pull request by alii**
### What does this PR do?

This PR rearranges all of bun-types to in a way that eliminates conflicts with Node.js AND lib.dom.d.ts, as well as declaring the `Bun` namespace and other symbols in a way we can generate documentation from.

Fixes #13599
Fixes #8761
Fixes #13167
Fixes #17203
Fixes #17256
Fixes #13858
Fixes #16044
Fixes #18458
Fixes #17980
Fixes #14660
Fixes #8765
Fixes #17940
Fixes #16785
Fixes #16537
Fixes #14892
Fixes #13669
Fixes #12662
Fixes #358

todo: 
- [x] rewrite the types
- [ ] ~~publish @oven/typescript-bun-lib-dom~~
- [ ] ~~figure out CI for autopatching dom..? (might not be necessary)~~
- [ ] ~~see if we can get BodyInit & HeadersInit to be declared inside of Bun types, not dom~~

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 12:33 PM PT - Mar 9th, 2025</sup></div>

@alii, your commit eeeab082ca5690dbfc109c678a4ed7ac0b375db7 is building: [`#12911`](https://buildkite.com/bun/bun/builds/12911)

**Comment by KilianB** [comment]
Bun supports a few methods like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toBase64 that are not part of the node types. Would this be a good time to include those as well?

**Comment by alii** [comment]
Hi @KilianB this is a JavaScript API, so it makes sense they don't exist in Node's types.

Ideally these ship with TypeScript's lib, but since they're so new it makes sense for us to include them Bun until they existing in TypeScript.

There is a PR which fixes this #18034, should merge soon.

**Comment by Jarred-Sumner** [comment]
@alii we can't merge this until the test pass

**Comment by alii** [comment]
@jarred-sumner it seems like the failing tests are unrelated to changes in this PR. How can we resolve?

**Comment by Jarred-Sumner** [comment]
They’re only failing in this branch. It’s likely related to the
tsconfig.json changes

File: packages/bun-types/bun.d.ts [hunk 1]
```diff
@@ -1644,7 +1644,7 @@ declare module "bun" {
    *   user: 'dbuser',
    *   password: 'secretpass',
    *   database: 'myapp',
-   *   idleTimeout: 30,
+   *   idleTimeout: 30000,
```
Comment (KilianB) [inline packages/bun-types/bun.d.ts]: This might have gotten reverted by mistake https://github.com/oven-sh/bun/pull/18234?

Comment (alii) [reply packages/bun-types/bun.d.ts:1647]: Thanks, nice spot😅

Comment (alii) [reply packages/bun-types/bun.d.ts]: Thanks, nice spot😅
