### PR TITLE
fix(node:http): match Node headers casing (lowercase only)

### LINKED ISSUE #2273: Fix the casing of node:http/https response headers
### What version of Bun is running?

0.5.8

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

Making a request through the node:http/https stack does not downcase the response headers that Node.js already does.

```javascript
async function sendRequest(url, headers, body, method) {
  const agent = new https.Agent({

  });

  const options = {
    agent,
    hostname: url.hostname,
    path: `${url.pathname}${url.search}`,
    port: url.port,
    method: method,
    headers: headers
  };

  return new Promise((resolve, reject) => {
    const request = https.request(url, options, (response) => {
      const res = {
        correlationId: response.headers["x-ms-correlation-request-id"],
        trackingId: response.headers["trackingid"],
        statusCode: response.statusCode,
        body: ""
      };

      response.on("data", (data) => {
        res.body += data;
      });

      response.on("end", () => {
        resolve(res);
      });
    });

    request.on("error", (err) => {
      reject(err);
    });

    request.write(body);
    request.end();
  });
}
```

### What is the expected behavior?

I would expect to be able to get the Tracking ID such as this using the full lower case:

```javascript
      const res = {
        correlationId: response.headers["x-ms-correlation-request-id"],
        trackingId: response.headers["trackingid"],
        statusCode: response.statusCode,
        body: ""
      };
```

Which would then print out like the following:

```bash
Tracking ID: efdb6e84-b4d9-4a6c-b8e0-c6823ade8713
```

### What do you see instead?

Bun does not normalize or lower case the headers, therefore, the field is undefined, so instead the field is returned as `TrackingId` and not `trackingid`.

```javascript
      const res = {
        correlationId: response.headers["x-ms-correlation-request-id"],
        trackingId: response.headers["trackingid"],
        statusCode: response.statusCode,
        body: ""
      };
```

Which would then print out like the following:

```bash
Tracking ID: undefined
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #2273

### CODE REVIEW

File: src/bun.js/bindings/webcore/JSFetchHeaders.cpp [hunk 1]
```diff
@@ -450,7 +450,7 @@ static inline JSC::EncodedJSValue jsFetchHeadersPrototypeFunction_toJSONBody(JSC
         for (auto it = vec.begin(); it != vec.end(); ++it) {
             auto& name = it->key;
             auto& value = it->value;
-            obj->putDirect(vm, Identifier::fromString(vm, name), jsString(vm, value), 0);
+            obj->putDirect(vm, Identifier::fromString(vm, name.convertToASCIILowercase()), jsString(vm, value), 0);
```
Comment (ThatOneBro) [inline src/bun.js/bindings/webcore/JSFetchHeaders.cpp]: I think this is right because we should only be allowing ASCII header names as mentioned in the RFC for both http/1.1 and http2
https://www.rfc-editor.org/rfc/rfc7540#section-1:~:text=Just%20as%20in%20HTTP/1.x%2C%20header%20field%20names%20are%20strings%20of%20ASCII%0A%20%20%20characters%20that%20are%20compared%20in%20a%20case%2Dinsensitive%20fashion

Comment (ThatOneBro) [reply src/bun.js/bindings/webcore/JSFetchHeaders.cpp]: Actually I think there should be a `WTFMove` here probably

**Comment by Jarred-Sumner** [comment]
Thank you
