### PR TITLE
fix(windows): make fs.symlink normalize forward slashes to backslashes

### LINKED ISSUE #8273: [win][fs] Symlink should use `\` as a path separator
### What version of Bun is running?

1.0.23

### What platform is your computer?

Window 10

### What steps can reproduce the bug?

```js
import fs from "node:fs/promises";

await fs.mkdir("files/2024", {recursive: true});
await fs.writeFile("files/2024/123.txt", "text");
await fs.symlink("files/2024/123.txt", "file-sym.txt");
console.log(await fs.readlink("file-sym.txt"));
```

### What is the expected behavior?

```
files\2024\123.txt
```

The symlink works in Explorer.

### What do you see instead?

```
files/2024/123.txt
```
The symlink does not work in Explorer and other programs.

### Additional information

Rel: https://github.com/oven-sh/bun/issues/8272

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Fixes #8273

`sliceZWithForcedCopy` now returns a (mutable) []u8 slice instead of a constant one, but only if you enable force copy.

### CODE REVIEW

File: src/bun.js/node/node_fs.zig [hunk 1]
```diff
@@ -5717,8 +5717,16 @@ pub const NodeFS = struct {
         var to_buf: [bun.MAX_PATH_BYTES]u8 = undefined;
 
         if (Environment.isWindows) {
+            const target: [:0]u8 = args.old_path.sliceZWithForceCopy(&this.sync_error_buf, true);
+            // UV does not normalize slashes in symlink targets, but Node does
+            // See https://github.com/oven-sh/bun/issues/8273
+            for (target) |*c| {
+                if (c.* == '/') {
```
Comment (Jarred-Sumner) [inline src/bun.js/node/node_fs.zig:5726]: i feel like there's a SIMD @Vector thing we can do here

but we can leave that as a TODO

Comment (paperclover) [reply src/bun.js/node/node_fs.zig:5726]: i'll add a todo

Comment (Jarred-Sumner) [reply src/bun.js/node/node_fs.zig:5726]: sliceWIthZForceCopyWithNormalizedSlashesOnWindows
