### PR TITLE
[WIP] feat(napi): add `napi-fatal-exception`

### LINKED ISSUE #2053: `nodejs-polars` fails on supported NAPI function
### What version of Bun is running?

0.5.6

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

The following script attempts to use the [`nodejs-polars`](https://www.npmjs.com/package/nodejs-polars) package, which is the official bindings (using napi-rs) to the [Polars](https://github.com/pola-rs/polars) dataframe library.

The following simple script attempts to create a dataframe:
```js
import pl from 'nodejs-polars';

const df = pl.DataFrame([
  { a: 1, b: 2 },
  { a: 4, b: 10 },
]);
console.log(df);
```

### What is the expected behavior?

Using Node:
```
❯ node test.js
shape: (2, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ f64 ┆ f64  │
╞═════╪══════╡
│ 1.0 ┆ 2.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 4.0 ┆ 10.0 │
└─────┴──────┘
```

### What do you see instead?

Using Bun:
```
❯ bun test.js
125 |                 try {
126 |                     if (localFileExisted) {
127 |                         nativeBinding = require('./nodejs-polars.darwin-arm64.node');
128 |                     }
129 |                     else {
130 |                         nativeBinding = require('nodejs-polars-darwin-arm64');
                            ^
TypeError: dlopen(/Users/luke/Developer/dataset/node_modules/nodejs-polars-darwin-arm64/nodejs-polars.darwin-arm64.node, 0x0001): symbol not found in flat namespace '_napi_fatal_exception'
      at /Users/luke/Developer/dataset/node_modules/nodejs-polars/bin/native-polars.js:130:24
      at /Users/luke/Developer/dataset/node_modules/nodejs-polars/bin/internals/polars_internal.js:6:27
      at /Users/luke/Developer/dataset/node_modules/nodejs-polars/bin/series/series.js:7:26
      at /Users/luke/Developer/dataset/node_modules/nodejs-polars/bin/index.js:24:15
      at /Users/luke/Developer/dataset/test.js:1:0
```

### Additional information

The [napi tracking issue](https://github.com/oven-sh/bun/issues/158) says `napi_fatal_exception` should be supported.

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #2053 , needs to be tested first

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
needs to be referenced in this function:

https://github.com/oven-sh/bun/blob/jarred/new-bundler/src/napi/napi.zig#L1440-L1446

then,  needs to be added to this list:

https://github.com/oven-sh/bun/blob/jarred/new-bundler/src/symbols.txt#L140

File: src/bun.js/bindings/napi.cpp [hunk 1]
```diff
@@ -967,6 +967,21 @@ extern "C" napi_status napi_get_and_clear_last_exception(napi_env env,
     return napi_ok;
 }
 
+extern "C" napi_status napi_fatal_exception(napi_env env,
+    napi_value err)
+{
+    auto globalObject = toJS(env);
+    JSC::JSValue value = JSC::JSValue::decode(reinterpret_cast<JSC::EncodedJSValue>(err));
+    JSC::JSObject* obj = value.getObject();
+    if (UNLIKELY(obj == nullptr || !obj->isErrorInstance())) {
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/napi.cpp:976]: There is a subtle difference between an exception and an error and I'm not sure this satisfies that

Comment (Jarred-Sumner) [reply src/bun.js/bindings/napi.cpp:976]: But I'm also not sure if the value passed here is expected to be a JSC::Exception

Comment (Jarred-Sumner) [reply src/bun.js/bindings/napi.cpp:976]: I think we can merge this since its better than the present state regardless
