### PR TITLE
[node:net] fix createConnection options passing

### LINKED ISSUE #3094: `net.createConnection(path)` param format not supported
### What version of Bun is running?

0.6.4

### What platform is your computer?

macOS

### What steps can reproduce the bug?

Not working

```
const socket = net.createConnection(sockname);
```

Working

```
const socket = net.createConnection({path: sockname});
```

https://nodejs.org/api/net.html#netcreateconnectionpath-connectlistener

---

As used here: https://github.com/facebook/watchman/blob/main/watchman/node/index.js#L114

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cirospaciari**
fix #3094

### CODE REVIEW

File: src/bun.js/net.exports.js [hunk 1]
```diff
@@ -531,18 +531,12 @@ const Socket = (function (InternalSocket) {
 );
 
 function createConnection(port, host, connectListener) {
-  if (typeof host == "function") {
-    connectListener = host;
-    host = undefined;
+  if (typeof port === "object") {
```
Comment (Jarred-Sumner) [inline src/bun.js/net.exports.js:534]: this should probably respect arguments.length but it's better than status quo

**Comment by Jarred-Sumner** [comment]
Thank you

also for fixing prettier
