### PR TITLE
fix: Resolve specifiers passed to `mock.module`

### LINKED ISSUE #7677: Module mocking not working as expected
### What version of Bun is running?

1.18.0

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

When using mock.module, I expect the function to be mocked, however nothing seems to happen.

**The function:**
```tsx
import { v4 } from "uuid";

export const getRandomNumber = () => {
  return v4();
};
```

**The test:**
```tsx
import { describe, expect, mock, test } from "bun:test";
import { getRandomNumber } from "./getRandomNumber";

describe("Given the getRandomFunction is called", () => {
  test("Then the length of the number should match 36", () => {
    const value = getRandomNumber();
    expect(value).toHaveLength(36);
  });

  test("Then the value should equal the mocked value", () => {
    mock.module("uuid", () => ({ v4: "mocked-uuid" }));
    const value = getRandomNumber();
    expect(value).toEqual("mocked-uuid");
  });
});
```

**Reproducible repo:**
https://github.com/jacobarvidsson/bun-mocking

### What is the expected behavior?

The test should pass.

### What do you see instead?

The module is never mocked and generates a new uuid every test run.

### Additional information
Screenshot 2023-12-15 at 10 21 45

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes https://github.com/oven-sh/bun/issues/7189
Fixes #7677 

Previously, mock.module would assume the specifier was already resolved.

For example: `mock.module("./foo", () => ({ bar: 42 }))` would only load successfully if `foo` lived in the path `./dir/foo` (i.e. it did not automatically infer the file extension or otherwise go through module resolution).

This was very confusing because, if you happened to mock a module before it was ever imported, then it would behave as expected because module resolution for mocks happens before the rest of the module resolution code.

### How did you verify your code works?

Updated tests which newly failed

### CODE REVIEW

File: src/bun.js/bindings/BunPlugin.cpp [hunk 1]
```diff
@@ -541,16 +542,30 @@ extern "C" EncodedJSValue JSMock__jsModuleMock(JSC::JSGlobalObject* lexicalGloba
         return {};
     }
 
-    if (specifier.startsWith("./"_s) || specifier.startsWith("../"_s) || specifier == "."_s) {
+    if (specifier.startsWith("file:"_s)) {
+        URL url = URL(URL(), specifier);
```
Comment (paperclover) [inline src/bun.js/bindings/BunPlugin.cpp]:
```
URL url(specifier)
if (!url.isValid()) {
  throw
}
```

File: src/bun.js/bindings/BunPlugin.cpp [hunk 2]
```diff
@@ -541,16 +542,30 @@ extern "C" EncodedJSValue JSMock__jsModuleMock(JSC::JSGlobalObject* lexicalGloba
...
+                    specifierString = specifierStr;
+                    specifier = specifierString->value(globalObject);
+                }
+            } else {
+                // If module resolution fails, we leave the specifier as-is
+                // You might not have the module installed in the first place
+            }
+
+            RETURN_IF_EXCEPTION(scope, {});
         }
```
Comment (paperclover) [inline src/bun.js/bindings/BunPlugin.cpp:592]:
```
else {
  // throw runtime exception, or RELEASE_ASSERT_NOT_REACHED()
}
```

i am surprised this is not a compiler warning

**Review by paperclover — CHANGES_REQUESTED** [review]
need to handle some edge cases i pointed out but also:

- `mock.module("./non-exist")` should now make a fake file "non-exist" exist that can be imported. similarly `mock.module('react')` should work without react installed

File: src/bun.js/bindings/BunPlugin.cpp (hunk 2 above)
Comment (paperclover) [reply src/bun.js/bindings/BunPlugin.cpp:592]: NVM

**Comment by Jarred-Sumner** [comment]
updated

File: src/bun.js/bindings/BunPlugin.cpp [hunk 3]
```diff
@@ -541,16 +542,45 @@ extern "C" EncodedJSValue JSMock__jsModuleMock(JSC::JSGlobalObject* lexicalGloba
         return {};
     }
 
-    if (specifier.startsWith("./"_s) || specifier.startsWith("../"_s) || specifier == "."_s) {
+    if (specifier.startsWith("file:"_s)) {
+        URL url = URL(URL(), specifier);
```
Comment (paperclover) [inline src/bun.js/bindings/BunPlugin.cpp]: this is still an issue as this can be an invalid file url, and calling `fileSystemPath()` will not valid.

`specifier` is taken as `specifierString` which is taken from `callframe->argument(0)` which can be any string

File: src/bun.js/bindings/BunPlugin.cpp [hunk 4]
```diff
@@ -738,6 +768,26 @@ EncodedJSValue BunPlugin::OnLoad::run(JSC::JSGlobalObject* globalObject, BunStri
...
+std::optional<String> BunPlugin::OnLoad::resolveVirtualModule(const String& path, const String& from)
+{
+    ASSERT(virtualModules);
+
+    if (this->mustDoExpensiveRelativeLookup) {
+        String joinedPath = path;
+
+        if (path.startsWith("./"_s) || path.startsWith("../"_s) || path.startsWith("."_s)) {
+            auto url = WTF::URL::fileURLWithFileSystemPath(from);
+            if (url.isValid()) {
```
Comment (paperclover) [inline src/bun.js/bindings/BunPlugin.cpp]: is this ever false? (if so, it should be added as an assertion failure in WebKit)

File: src/bun.js/bindings/BunPlugin.cpp [hunk 5]
```diff
@@ -738,6 +768,26 @@ EncodedJSValue BunPlugin::OnLoad::run(JSC::JSGlobalObject* globalObject, BunStri
...
 }
 
+std::optional<String> BunPlugin::OnLoad::resolveVirtualModule(const String& path, const String& from)
+{
+    ASSERT(virtualModules);
+
+    if (this->mustDoExpensiveRelativeLookup) {
+        String joinedPath = path;
+
+        if (path.startsWith("./"_s) || path.startsWith("../"_s) || path.startsWith("."_s)) {
```
Comment (paperclover) [inline src/bun.js/bindings/BunPlugin.cpp]: i don't think `path.startsWith(".")` is correct. Is this supposed to be `path == "."_s`. if not, then this entire condition boils down to `if(path.startsWith("."_s))`

File: src/bun.js/bindings/ImportMetaObject.cpp [hunk 6]
```diff
@@ -277,49 +286,52 @@ extern "C" JSC::EncodedJSValue functionImportMeta__resolveSync(JSC::JSGlobalObje
     return result;
 }
 
-extern "C" JSC::EncodedJSValue functionImportMeta__resolveSyncPrivate(JSC::JSGlobalObject* globalObject, JSC::CallFrame* callFrame)
+extern "C" JSC::EncodedJSValue functionImportMeta__resolveSyncPrivate(JSC::JSGlobalObject* lexicalGlobalObject, JSC::CallFrame* callFrame)
```
Comment (paperclover) [inline src/bun.js/bindings/ImportMetaObject.cpp:289]: good renaming

**Review by paperclover — CHANGES_REQUESTED** [review]
notes are mostly due to me spending so much time looking at how `WTF::URL` works, but very minor things.

i assume this code does work

File: src/bun.js/bindings/BunPlugin.cpp (hunk 5 above)
Comment (Jarred-Sumner) [reply src/bun.js/bindings/BunPlugin.cpp]: It should be `./` || `..` because you could theoretically import files prefixed with `.`
