### PR TITLE
Fix prisma generate by emitting readable event on EoF

### LINKED ISSUE #5320: Bun doesn't run prisma generate or prisma migrate inside docker containers or WSL
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

# Docker:
```dockerfile
FROM oven/bun AS builder

WORKDIR /tmp/app

COPY package.json .
COPY bun.lockb .

RUN bun install

COPY src ./src
COPY tsconfig.json .

# This would be the optimal solution but it doesn't work, so I'm gonna use a hack here until I figure out how to fix it
#   RUN bunx prisma:generate
#   COPY prisma/schema.prisma ./prisma/schema.prisma
COPY node_modules/.prisma ./node_modules/.prisma

RUN bun run build

FROM oven/bun AS runner

ARG DEFAULT_DATABASE_URL= "file:./deploy.db"
ENV DATABASE_URL=$DEFAULT_DATABASE_URL

WORKDIR /app

COPY --from=builder /tmp/app/package.json /app/package.json
COPY --from=builder /tmp/app/bun.lockb /app/bun.lockb
RUN bun install -p

# Refer to the comment above
#   COPY --from=builder /tmp/app/prisma/schema.prisma ./prisma/schema.prisma
#   RUN bun run prisma:generate
COPY --from=builder /tmp/app/node_modules/.prisma /app/node_modules/.prisma

#   These commands aren't working either. The prisma:migrate has to be done in the external machine
#   RUN bun add prisma
#   RUN bun run prisma:migrate

COPY --from=builder /tmp/app/build /app/build

CMD ["bun", "start"]
```

# WSL:

Install WSL normally...
```powershell
wsl --install
```

Make bun installation inside Ubuntu.

Try to follow this exact guide: https://bun.sh/guides/ecosystem/prisma

### What is the expected behavior?

Prisma installs normally

### What do you see instead?

This, download never finishes:
```bash
root@7fa00e64baa1:/app# bun run prisma:deploy
$ bunx prisma migrate deploy
Downloading Prisma engines for Node-API for debian-openssl-1.1.x [===                 ] 15%root@7fa00e64baa1:/app#
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by camero2734**
### What does this PR do?
Fixes #5320

The main reason (there's currently two) that `bunx prisma generate` fails is because of the `getHash` method that listens for the `readable` event on a `ReadStream`:
```ts
// Prisma calls this in its ensureBinariesExist method that's called before every CLI command
// ../fetch-engine/src/getHash.ts
var import_crypto2 = __toESM(require("crypto"));
var import_fs13 = __toESM(require("fs"));
function getHash(filePath) {
  const hash = import_crypto2.default.createHash("sha256");
  const input = import_fs13.default.createReadStream(filePath);
  return new Promise((resolve3) => {
    input.on("readable", () => {
      const data = input.read();
      if (data) {
        hash.update(data);
      } else {
        resolve3(hash.digest("hex"));
      }
    });
  });
}
```

There's a bug in Bun where this event is not called for EoF (i.e. where `read` returns `null`).

As such, the `else` statement is never called, and ends up causing the whole program to exit silently.

-------

This seems to be broken due to a reason related to #4409. We have:
```cpp
// src/bun.js/bindings/JSReadableHelper.cpp
EncodedJSValue emitReadable(JSGlobalObject* lexicalGlobalObject, JSObject* stream, JSReadableState* state)
{
    VM& vm = lexicalGlobalObject->vm();

    state->setBool(JSReadableState::needReadable, false);
    if (!state->getBool(JSReadableState::emittedReadable)) {
        state->setBool(JSReadableState::emittedReadable, true);
        Zig::GlobalObject* globalObject = reinterpret_cast<Zig::GlobalObject*>(lexicalGlobalObject);
        // This is the issue
        globalObject->queueMicrotask(JSValue(globalObject->emitReadableNextTickFunction()), JSValue(stream), JSValue(state), JSValue {}, JSValue {});
    }
    return JSValue::encode(jsUndefined());
}
```

From some testing, it seems this microtask only gets run _after_ the stream has been `destroyed`, at which point the event is not allowed to be emitted anymore.

Similar to #4409, it seems this needs to be called via `process.nextTick` instead so that things run in the correct order.

To fix this, I moved the `onEofChunk` method into JS (`src/js/node/stream.js`) so that I could schedule it with `process.nextTick` instead. With this change, all expected `readable` events are emitted/received, and this fixes prisma CLI commands (almost).

(P.S. Maybe there's a way to add to the `nextTick` queue from C++, but I couldn't find a straightforward way of doing it, so that's why I moved things back to JS)

### How did you verify your code works?
I added a test to `test/js/node/stream/node-stream.test.js`. It times out in previous versions of bun, but passes with these changes.

I also tested Prisma in a docker container. `bun-patched` is a bun binary built in release mode with these changes.

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM debian:bullseye-slim

# Disable the runtime transpiler cache by default inside Docker containers.
# On ephemeral containers, the cache is not useful
ARG BUN_RUNTIME_TRANSPILER_CACHE_PATH=0
ENV BUN_RUNTIME_TRANSPILER_CACHE_PATH=${BUN_RUNTIME_TRANSPILER_CACHE_PATH}

COPY ./bun-patched /usr/local/bin/bun

RUN groupadd bun \
      --gid 1000 \
    && useradd bun \
      --uid 1000 \
      --gid bun \
      --shell /bin/sh \
      --create-home \
    && ln -s /usr/local/bin/bun /usr/local/bin/bunx \
    && which bun \
    && which bunx \
    && bun --version

WORKDIR /home/bun/app

COPY --link package.json bun.lockb ./

RUN bun install

COPY . .

RUN sed -i '1s/node/bun/' ./node_modules/prisma/build/index.js
RUN bunx prisma generate && echo "Exited" && sleep 1000
# ^ Prints the expected prisma generate success message
```

</details>

<details>
<summary>Relevant output</summary>

```
#13 [8/9] RUN sed -i '1s/node/bun/' ./node_modules/prisma/build/index.js
#13 DONE 0.2s

#14 [9/9] RUN bunx prisma generate && echo "Exited" && sleep 1000
#14 0.912 Prisma schema loaded from prisma/schema.prisma
#14 1.250
#14 1.250 ✔ Generated Prisma Client (v5.10.2) to ./node_modules/@prisma/client in 41ms
#14 1.250
#14 1.250 Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
#14 1.250 ```
#14 1.250 import { PrismaClient } from '@prisma/client'
#14 1.250 const prisma = new PrismaClient()
#14 1.250 ```
#14 1.250 or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
#14 1.250 ```
#14 1.250 import { PrismaClient } from '@prisma/client/edge'
#14 1.250 const prisma = new PrismaClient()
#14 1.250 ```
#14 1.250
#14 1.250 See other ways of importing Prisma Client: http://pris.ly/d/importing-client
#14 1.250
#14 1.250 ┌─────────────────────────────────────────────────────────────┐
#14 1.250 │  Deploying your app to serverless or edge functions?        │
#14 1.250 │  Try Prisma Accelerate for connection pooling and caching.  │
#14 1.250 │  https://pris.ly/cli/accelerate                             │
#14 1.250 └─────────────────────────────────────────────────────────────┘
#14 1.250
#14 1.429 Exited
```

</details>

### Further issues
There's still one issue with running `bunx prisma` that this PR does not address. It seems `bunx` does not resolve symlinks correctly. The "executable" (`node_modules/.bin/prisma`) is a symlink to a js file (`node_modules/prisma/build/index.js`) that makes this check:
```ts
if (eval("require.main === module")) {
   // ... actually run
}
```

but this does not return true due to the symlink. I checked `Bun.main` and it returns `node_modules/.bin/prisma`, when I believe it should resolve to the symlinked path (`node_modules/prisma/build/index.js`).  Since these don't match, it fails.

It's still possible to "manually" invoke the CLI without node now though, via:
```bash
bun run --bun ./node_modules/prisma/build/index.js generate
```

which gets around the symlink issue. For whatever reason, it also seems that:
```bash
# Replace #!/usr/bin/env node with #!/usr/bin/env bun
RUN sed -i '1s/node/bun/' ./node_modules/prisma/build/index.js
RUN bunx prisma generate
```

works as well, although I'm not sure why. Perhaps the symlink is only an issue when bun is running in `node` mode.

Without doing one of the two things above, `bunx prisma` commands will still silently fail (though for a different reason)

### CODE REVIEW

File: src/js/node/stream.js [hunk 1]
```diff
@@ -2624,6 +2627,24 @@ var require_readable = __commonJS({
       $debug("about to maybereadmore");
       maybeReadMore(stream, state);
     }
+    function onEofChunk(stream, state) {
```
Comment (Jarred-Sumner) [inline src/js/node/stream.js:2630]: In JS, property accesses are slower than variable declarations - so lets only do these once

```suggestion
    function onEofChunk(stream, state) {
     if (state.ended) return;
     const decoder = state.decoder;
      if (decoder) {
        const chunk = decoder.end();
        const chunkLength = chunk?.length;
        if (chunkLength) {
          state.buffer.push(chunk);
          state.length += state.objectMode ? 1 : chunkLength;
        }
      }
      state.ended = true;
      if (state.sync) {
        emitReadable(stream, state);
      } else {
        state.needReadable = false;
        state.emittedReadable = true;
        _emitReadable(stream, state);
      }
    }
```

**Comment by Jarred-Sumner** [comment]
This is great. We really appreciate your PRs. I have one nitpick

**Comment by Jarred-Sumner** [comment]
> There's still one issue with running bunx prisma that this PR does not address. It seems bunx does not resolve symlinks correctly. The "executable" (node_modules/.bin/prisma) is a symlink to a js file (node_modules/prisma/build/index.js) that makes this check:

Addressed in #9105

**Comment by camero2734** [comment]
> > There's still one issue with running bunx prisma that this PR does not address. It seems bunx does not resolve symlinks correctly. The "executable" (node_modules/.bin/prisma) is a symlink to a js file (node_modules/prisma/build/index.js) that makes this check:
> 
> Addressed in #9105 

Awesome!
