### PR TITLE
fix(install): free correct pointer in `bun patch --commit`

### LINKED ISSUE #16047: Crash when creating patch
### How can we reproduce the crash?

_No response_

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.42-canary ([`18ac7f9`](<https://github.com/oven-sh/bun/tree/18ac7f9509b16c3b1f8e98cebd18a6474c97bed7>)) on macos aarch64 [PatchCommand]

Segmentation fault at address 0x4000000000000B0

- *1 unknown/js code*
- `src.http.HTTPThread.processEvents`
- `Thread.PosixThreadImpl.spawn__anon_177490.Instance.entryFn`

Features: dotenv, spawn

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6184687002/">BUN-AGC</a></strong></sub>

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Ensures the pointer for `lockfile.buffer.trees` is known by the allocator.

fixes #16047

### How did you verify your code works?
Manually

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 11:33 AM PT - Dec 30th, 2024</sup></div>

@dylan-conway, your commit af1c439bc6bc475b9788948c8fe5235a8c7393e6 is building: [`#8670`](https://buildkite.com/bun/bun/builds/8670)

File: src/install/lockfile.zig [hunk 1]
```diff
@@ -733,7 +741,17 @@ pub const Tree = struct {
                 this.queue.deinit();
                 this.sort_buf.deinit(this.allocator);
 
-                return dependency_ids;
+                // take over the `builder.list` pointer for only trees
+                if (@intFromPtr(trees.ptr) != @intFromPtr(list_ptr)) {
+                    var new: [*]Tree = @ptrCast(list_ptr);
+                    bun.copy(Tree, new[0..trees.len], trees);
```
Comment (dylan-conway) [inline src/install/lockfile.zig:747]: We can use this memory because the other field `.dependencies` was already appended to another list and won't be used again
