### PR TITLE
dev server: fix some small css bugs

### LINKED ISSUE #17622: Bun.serve() HMR: CSS reference not found after change
### What version of Bun is running?

1.2.3

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

1. Create a basic Bun.serve() setup in `index.ts`:
```ts
import { serve } from "bun";
import Frontend from "./frontend/index.html";

serve({
  port: 3000,
  routes: {
    "/*": Frontend,
  },
});
```
2. Include a stylesheet in the HTML:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <div id="root">Hey!</div>
    <script type="module" src="./index.ts"></script>
  </body>
</html>
```
3. Run `bun run index.ts`, it works as expected.
4. Change some text in the HTML file, **the CSS file is not found anymore**.

```
error: Failed to resolve dynamic import 'frontend/styles.css'. With Bun's DevServer, all imports must be statically known at build time so that the bundler can trace everything.
at async http://localhost:3000/_bun/client/index-00000000c27d04ce.js:10:7017
```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
- BUN-10761 - Fixes #17622
- Fix CSS and HTML import before create bugs.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 4:27 PM PT - Mar 3rd, 2025</sup></div>

@paperclover, your commit 1f8df109e4268d0217d3d6b9162a5d2a883698d9 is building: [`#12617`](https://buildkite.com/bun/bun/builds/12617)

File: src/bake/DevServer.zig [hunk 1]
```diff
@@ -5072,25 +5076,52 @@ const DirectoryWatchStore = struct {
...
+                    bun.strings.startsWith(specifier, "../"))) return;
+
+                break :specifier_to_use specifier;
+            },
+
+            // Imports in HTML and CSS can resolve to relative paths.
+            .html, .css => if (bun.path.Platform.auto.isSeparator(specifier[0]))
+                specifier[1..]
+            else
+                specifier,
```
Comment (dylan-conway) [inline src/bake/DevServer.zig]: Is this for removing the root? if so, this needs to handle windows drives

Comment (paperclover) [reply src/bake/DevServer.zig]: no. it is pairing code to HTMLScanner.zig
```
fn createImportRecord(this: *HTMLScanner, input_path: []const u8, kind: ImportKind) !void {
    // In HTML, sometimes people do /src/index.js
    // In that case, we don't want to use the absolute filesystem path, we want to use the path relative to the project root
    const path_to_use = if (input_path.len > 1 and input_path[0] == '/')
        bun.path.joinAbsString(bun.fs.FileSystem.instance.top_level_dir, &[_][]const u8{input_path[1..]}, .auto)
```
but what i have is wrong in my file. it should always only check '/' and never '\'

File: src/bake/DevServer.zig [hunk 2]
```diff
@@ -5099,7 +5129,7 @@ const DirectoryWatchStore = struct {
             .server, .ssr => (try dev.server_graph.insertEmpty(import_source, .unknown)).key,
         };
 
-        store.insert(dir, owned_file_path, specifier) catch |err| switch (err) {
+        store.insert(dir, owned_file_path, specifier_to_use) catch |err| switch (err) {
```
Comment (Jarred-Sumner) [inline src/bake/DevServer.zig]: I still think it sketchy we don't use absolute or normalized paths exclusively

Comment (paperclover) [reply src/bake/DevServer.zig]: this comment doesn't make sense, `specifier` is this is a unresolved specifier. though bringing this up does reveal that the new variable can be eliminated entirely.
