### PR TITLE
fix(spawn): memory leak in `"pipe"`d stdout/stderr

### LINKED ISSUE #18265: Memory leak in `Bun.spawn` with subprocess polling
### What version of Bun is running?

1.2.6-canary.74+74768449b

### What platform is your computer?

Linux 6.1.62 x86_64 / Darwin 24.3.0 arm64

### What steps can reproduce the bug?

I have been noticing an unusual increase in memory usage with my app and after days of debugging I was able to narrow it down to `Bun.spawn` being the culprit.

The app polls a short-lived subprocess twice every second and reads its output. The subprocess is very small and quick (the output is ~600 bytes and execution time is ~30ms). Over an extended period of time (~12 hours), the RSS grows significantly, exceeding 1GB. The heap stats stay relatively stable although very slowly trending upwards. 

This is unexpected for a lightweight polling operation and suggests that subprocess handles, output buffers, or event listeners are not being properly cleaned up, preventing garbage collection. I started monitoring `process.memoryUsage()` and here's the readings I got on two different instances:

Image

Image

---

### Repro steps:

> [!NOTE]
> I added a detailed repro script [here](https://github.com/oven-sh/bun/issues/18265#issuecomment-2731824956) and shared the memory readings from it [here](https://github.com/oven-sh/bun/issues/18265#issuecomment-2734439071). 

To further validate this, I kept this snippet bellow running overnight:

```ts
async function spawn() {
  // mimicking a small subprocess with minimal stdout output (not actual process i'm spawning)
  const proc = Bun.spawn(['sed', '20q', '/etc/passwd'], {
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  // In my app, I'm consuming the stdout stream output but I didn't do it in this test
  // to rule that out so I'm just waiting for the process to exit
  // const output = await Bun.readableStreamToText(proc.stdout);
  await proc.exited;
}

while (true) {
  console.clear();
  console.log(`RSS: ${process.memoryUsage().rss / 1024 / 1024} MB`);
  await spawn();
  await Bun.sleep(1000);
}
```

And here's the readings I got after 12 hours:

```
RSS: 701.03125 MB
```

You can also play around the with sleep duration and see how the memory grows, although it might not happen immediately as you can see in the graphs above. You might want to keep it running for few hours or overnight (in which it would be helpful to log the max RSS too).

I understand RSS is not necessarily an indication of memory leaks, but even when I look the overall memory consumption of my app process from the host system, I see that it reaches around 1.5GB after a while, even for this small repro above.

### What is the expected behavior?

Memory usage should stabilize over time.

I ran the repro snippet above with node v23.8.0 using `child_process.spawn` side by side with Bun (which btw Bun did use waaaaaaay less heap) for the same duration, and this is the reading I got:

```
RSS: 92.53125 MB
```

### What do you see instead?

Memory grows unbounded to over 1GB

### Additional information

If this is not a "memory leak" in the classical sense, could you please me help understand what it is and why I don't get similar RSS readings with other runtimes?

### PR DESCRIPTION
**Pull request by DonIsaac**
### What does this PR do?
Closes #18265

Fixes a memory leak in `Bun.spawn` when `stdout` or `stderr` were set to `"pipe"`.

When spawned, we were creating a `Readable` with a buffered reader. When reading completes, that `.pipe` readable gets converted into a `.buffer` readable. `.buffer` variants were ignored in `Readable.finalize`, causing the leak.

### How did you verify your code works?
Ive added a test

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 7:47 PM PT - Mar 19th, 2025</sup></div>

@DonIsaac, your commit bb720e07d72d067faf8c73406a17b68c05db496e is building: [`#13558`](https://buildkite.com/bun/bun/builds/13558)

File: src/bun.js/api/bun/subprocess.zig [hunk 1]
```diff
@@ -502,14 +511,18 @@ const Readable = union(enum) {
...
                 defer this.* = .{ .closed = {} };
 
-                if (buffer.len == 0) {
+                if (buffer.length() == 0) {
                     return JSC.WebCore.ReadableStream.empty(globalThis);
                 }
 
-                const blob = JSC.WebCore.Blob.init(buffer, bun.default_allocator, globalThis);
+                const own = buffer.takeSlice(bun.default_allocator) catch {
+                    globalThis.throwOutOfMemory() catch return .zero;
```
Comment (DonIsaac) [inline src/bun.js/api/bun/subprocess.zig:522]: IMO `toJS()` should be returning a `bun.JSError` but ¯\_(ツ)_/¯

File: src/bun.js/api/bun/subprocess.zig [hunk 2]
```diff
@@ -502,14 +511,18 @@ const Readable = union(enum) {
...
+                    unreachable;
```
Comment (paperclover) [inline src/bun.js/api/bun/subprocess.zig]: this line can be removed; `globalThis.throwOutOfMemory()` always returns an error and the catch expression is `noreturn`, so this unreachable is not analyzed.

please avoid using unreachable anywhere unless it is actually semantically analyzed but not possible to reach.

File: src/bun.js/api/bun/subprocess.zig [hunk 3]
```diff
@@ -376,12 +376,18 @@ const Readable = union(enum) {
...
     ignore: void,
     closed: void,
-    buffer: []u8,
+    /// Eventually we will implement Readables created from blobs and array buffers.
+    /// When we do that, `buffer` will be borrowed from those objects.
+    ///
+    /// When a buffered `pipe` finishes reading from its file descriptor,
+    /// the owning `Readable` will be convered into this variant and the pipe's
+    /// buffer will be taken as an owned `CowString`.
+    buffer: CowString,
```
Comment (paperclover) [inline src/bun.js/api/bun/subprocess.zig:385]: this string is always owned? if so, then `CowString` is the wrong abstraction for this field

**Review by paperclover — CHANGES_REQUESTED** [review]

File: src/bun.js/api/bun/subprocess.zig (hunk 2 above)
Comment (DonIsaac) [reply src/bun.js/api/bun/subprocess.zig]: I can't ignore the return, the Zig compiler won't let me.
```zig
_ = globalThis.throwOutOfMemory();
```

File: src/bun.js/api/bun/subprocess.zig (hunk 3 above)
Comment (DonIsaac) [reply src/bun.js/api/bun/subprocess.zig:385]: It is for now, but it won't be in the future. There's no overhead incurred by using `CowString`; it's still 2 bytes

File: src/bun.js/api/bun/subprocess.zig [hunk 4]
```diff
@@ -311,7 +311,7 @@ pub fn onCloseIO(this: *Subprocess, kind: StdioKind) void {
             switch (out.*) {
```
Comment (iitzkube) [inline src/bun.js/api/bun/subprocess.zig:311]: Hi @DonIsaac - thank you for the quick fix! 🙂

just a small question, in the PR description you said:

> If proc.stdout or proc.stderr were never accessed, they were never freed

I'm a little confused, could you please clarify this part? Does it apply in the JS land? In my case, I was actually reading from stdout via `Bun.readableStreamToText(proc.stdout)`. I posted an updated repro script yesterday that reads from stdout https://github.com/oven-sh/bun/issues/18265#issuecomment-2735170059

fwiw, as part of me debugging this I also tried consuming stdout an async iterator paired with `TextDecoder.decode(chunk)`, as well as `new Response(proc.stdout).text()`. All of these accessed stdout and resulted in the memory leak.

Comment (DonIsaac) [reply src/bun.js/api/bun/subprocess.zig:311]: Yeah good catch; whether or not it's being accessed isn't actually affecting things. We simply weren't freeing `.buffer` readers in any case. Thanks for bringing this to my attention.

**Comment by Jarred-Sumner** [comment]
did you base this off of reading the code or off of measuring RSS in a release build after repeatedly spawning? i'm moderately confident the only case where `buffer` is used on posix is either when using passing a Blob/Response as stdin, or in spawnSync when "pipe" is passed - and the bug report was for Bun.spawn

https://github.com/oven-sh/bun/blob/main/src/bun.js/api/bun/spawn/stdio.zig#L199

**Comment by DonIsaac** [comment]
> did you base this off of reading the code or off of measuring RSS in a release build after repeatedly spawning? i'm moderately confident the only case where `buffer` is used on posix is either when using passing a Blob/Response as stdin, or in spawnSync when "pipe" is passed - and the bug report was for Bun.spawn
> 
> [`main`/src/bun.js/api/bun/spawn/stdio.zig#L199](https://github.com/oven-sh/bun/blob/main/src/bun.js/api/bun/spawn/stdio.zig?rgh-link-date=2025-03-20T03%3A53%3A04Z#L199)

Reading the code, step-through debugging, and using Instruments. This leak isn't visible via heap snapshots since `HeapAnalyzer` only visits JSCell edges and does not take native properties in to account.
image

**Comment by Jarred-Sumner** [comment]
> only visits JSCell edges and does not take native properties in to account.

It does! that is what all these `memoryCost` functions do.
- `pub fn memoryCost(this: *const Readable) usize {`
- `pub fn memoryCost(this: *const Source) usize {`
- `pub fn memoryCost(this: *const This) usize {`
- `pub fn memoryCost(this: *const PipeReader) usize {`
- `pub fn memoryCost(this: *const Writable) usize {`
- `pub fn memoryCost(this: *const Subprocess) usize {`

**Comment by DonIsaac** [comment]
@Jarred-Sumner  Update: `JSFooClass::analyzeHeap`, which is the function used by `HeapAnalyzer` to generate heap snapshots, never calls `memoryCost`
image

**Comment by Jarred-Sumner** [comment]
> never calls memoryCost

are you sure

```c++
size_t JSSubprocess::memoryCost(void* ptr) {
  return ptr ? Subprocess__memoryCost(ptr) : 0;
}

void JSSubprocess::analyzeHeap(JSCell* cell, HeapAnalyzer& analyzer)
{
    auto* thisObject = jsCast<JSSubprocess*>(cell);
    if (void* wrapped = thisObject->wrapped()) {
        analyzer.setWrappedObjectForCell(cell, wrapped);
    }

    Base::analyzeHeap(cell, analyzer);
    auto& vm = thisObject->vm();

    
if (JSValue m_stdoutValue = thisObject->m_stdout.get()) {
  if (m_stdoutValue.isCell()) {
    const Identifier& id = Identifier::fromString(vm, "readable"_s);
    analyzer.analyzePropertyNameEdge(cell, m_stdoutValue.asCell(), id.impl());
  }
}
  
if (JSValue m_stderrValue = thisObject->m_stderr.get()) {
  if (m_stderrValue.isCell()) {
    const Identifier& id = Identifier::fromString(vm, "stderr"_s);
    analyzer.analyzePropertyNameEdge(cell, m_stderrValue.asCell(), id.impl());
  }
}
  
if (JSValue m_stdinValue = thisObject->m_stdin.get()) {
  if (m_stdinValue.isCell()) {
    const Identifier& id = Identifier::fromString(vm, "stdin"_s);
    analyzer.analyzePropertyNameEdge(cell, m_stdinValue.asCell(), id.impl());
  }
}
  
if (JSValue m_stdoutValue = thisObject->m_stdout.get()) {
  if (m_stdoutValue.isCell()) {
    const Identifier& id = Identifier::fromString(vm, "stdout"_s);
    analyzer.analyzePropertyNameEdge(cell, m_stdoutValue.asCell(), id.impl());
  }
}
  
if (JSValue m_stdinValue = thisObject->m_stdin.get()) {
  if (m_stdinValue.isCell()) {
    const Identifier& id = Identifier::fromString(vm, "writable"_s);
    analyzer.analyzePropertyNameEdge(cell, m_stdinValue.asCell(), id.impl());
  }
}
}
```

**Comment by Jarred-Sumner** [comment]
hm that is interesting

File: src/bun.js/api/bun/subprocess.zig (hunk 2 above)
Comment (pfgithub) [reply src/bun.js/api/bun/subprocess.zig]: it's the 'unreachable' line that can be removed (or changed to 'comptime unreachable')

**Comment by DonIsaac** [comment]
Only the cached `JSValue`s put directly on the `this` object from getters are appearing in snapshots
image

**Comment by DonIsaac** [comment]
Just saw those; not sure why they're not appearing then. Maybe its a bug when we create the snapshot JSON?

**Comment by paperclover** [comment]
this should have a leak test before merging

File: .clangd [hunk 5]
```diff
@@ -2,7 +2,7 @@ Index:
   Background: Skip # Disable slow background indexing of these files.
 
 CompileFlags:
-  CompilationDatabase: build/debug
+  CompilationDatabase: build/debug-local
```
Comment (Jarred-Sumner) [inline .clangd]:
```suggestion
  CompilationDatabase: build/debug
```

File: .vscode/launch.json [hunk 6]
```diff
@@ -151,7 +151,7 @@
       "type": "lldb",
       "request": "launch",
       "name": "bun run [file]",
-      "program": "${workspaceFolder}/build/debug/bun-debug",
+      "program": "${workspaceFolder}/build/debug-local/bun-debug",
```
Comment (Jarred-Sumner) [inline .vscode/launch.json]:
```suggestion
      "program": "${workspaceFolder}/build/debug/bun-debug",
```

File: .vscode/settings.json [hunk 7]
```diff
@@ -2,7 +2,7 @@
   // Editor
   "editor.tabSize": 2,
   "editor.insertSpaces": true,
-  "editor.formatOnSave": true,
+  "editor.formatOnSave": false,
```
Comment (Jarred-Sumner) [inline .vscode/settings.json]:
```suggestion
  "editor.formatOnSave": true,
```

File: build.zig [hunk 8]
```diff
@@ -196,7 +196,7 @@ pub fn build(b: *Build) !void {
 
     const codegen_path = b.pathFromRoot(
         b.option([]const u8, "codegen_path", "Set the generated code directory") orelse
-            "build/debug/codegen",
+            "build/debug-local/codegen",
```
Comment (Jarred-Sumner) [inline build.zig]:
```suggestion
            "build/debug/codegen",
```

File: cmake/targets/BuildBun.cmake [hunk 9]
```diff
@@ -590,6 +590,7 @@ register_command(
       -Doptimize=${ZIG_OPTIMIZE}
       -Dcpu=${ZIG_CPU}
       -Denable_logs=$<IF:$<BOOL:${ENABLE_LOGS}>,true,false>
+      -Denable_asan=$<IF:$<BOOL:${ENABLE_ASAN}>,true,false>
```
Comment (Jarred-Sumner) [inline cmake/targets/BuildBun.cmake]:
```suggestion

```

File: spawn-leak.ts [hunk 10]
```diff
@@ -0,0 +1,47 @@
+async function spawn() {
```
Comment (Jarred-Sumner) [inline spawn-leak.ts]: this should go in test/js/bun/...

File: test/js/bun/http/serve-body-leak.test.ts [hunk 11]
```diff
@@ -155,13 +155,13 @@ async function calculateMemoryLeak(fn: (url: URL) => Promise<void>, url: URL) {
...
 for (const test_info of [
-  ["#10265 should not leak memory when ignoring the body", callIgnore, false, 64],
+  // ["#10265 should not leak memory when ignoring the body", callIgnore, false, 64],
   ["should not leak memory when buffering the body", callBuffering, false, 64],
-  ["should not leak memory when buffering a JSON body", callJSONBuffering, false, 64],
-  ["should not leak memory when buffering the body and accessing req.body", callBufferingBodyGetter, false, 64],
-  ["should not leak memory when streaming the body", callStreaming, isFlaky && isLinux, 64],
-  ["should not leak memory when streaming the body incompletely", callIncompleteStreaming, false, 64],
-  ["should not leak memory when streaming the body and echoing it back", callStreamingEcho, false, 64],
+  // ["should not leak memory when buffering a JSON body", callJSONBuffering, false, 64],
```
Comment (Jarred-Sumner) [inline test/js/bun/http/serve-body-leak.test.ts]: these should all be uncommented

File: src/js/builtins.d.ts [hunk 12]
```diff
@@ -1,4 +1,4 @@
-/// <reference types="../../build/debug/codegen/generated.d.ts" />
+/// <reference types="../../build/debug-local/codegen/generated.d.ts" />
```
Comment (Jarred-Sumner) [inline src/js/builtins.d.ts]:
```suggestion
/// <reference types="../../build/debug/codegen/generated.d.ts" />
```

File: test/js/bun/spawn/spawn-pipe-leak.test.ts [hunk 13]
```diff
@@ -0,0 +1,77 @@
...
+                stdout: "pipe", // We pipe stdout but never read from it
+                stderr: "ignore",
+                stdin: "ignore",
+              });
+
+              // Only await the exit, don't read any data
+              await process.exited;
+
+              // Don't return anything to help GC
+              Bun.gc(true);
```
Comment (Jarred-Sumner) [inline test/js/bun/spawn/spawn-pipe-leak.test.ts]: gc(true) here makes it unnecessarily slow

File: test/js/bun/spawn/spawn-pipe-leak.test.ts [hunk 14]
```diff
@@ -0,0 +1,77 @@
...
+    // Run the test
+    await testSpawnMemoryLeak(10, 5);
+    // Check memory after the test
+    const memAfter = process.memoryUsage();
+
+    log("Memory leak test completed");
+    log(`Final memory usage: ${Math.round(process.memoryUsage.rss() / 1024 / 1024)} MB`);
+    log(`Memory difference: ${Math.round((process.memoryUsage.rss() - memBefore.rss) / 1024 / 1024)} MB`);
+
+    // should not have grown more than 25%
```
Comment (Jarred-Sumner) [inline test/js/bun/spawn/spawn-pipe-leak.test.ts]: 25% is probably too aggro. I suggest a fixed size. It should not double.

File: test/js/bun/spawn/spawn-pipe-leak.test.ts [hunk 15]
```diff
@@ -0,0 +1,77 @@
...
+    const delta = memAfter.rss - memBefore.rss;
+    expect(delta / memBefore.rss).toBeLessThan(0.25);
+  }, 20_000);
```
Comment (Jarred-Sumner) [inline test/js/bun/spawn/spawn-pipe-leak.test.ts]: 20s is really long. I bet we can make this test useful and < 5s

Comment (DonIsaac) [reply test/js/bun/spawn/spawn-pipe-leak.test.ts]: Test runs in ~7s, but setting the limit high should help avoid flakiness

File: test/js/bun/spawn/spawn-pipe-leak.test.ts (hunk 14 above)
Comment (DonIsaac) [reply test/js/bun/spawn/spawn-pipe-leak.test.ts]: Comparing after warmup should account for memory allocated by compiled executables. Right now it only grows by 9mb. I'll increase it to 50%; 2x is likely to hide real leaks

File: test/js/bun/spawn/spawn-pipe-leak.test.ts (hunk 15 above)
Comment (DonIsaac) [reply test/js/bun/spawn/spawn-pipe-leak.test.ts]: update: after removing `Bun.gc` calls, this tests takes ~3s

**Comment by iitzkube** [comment]
I'm afraid this did not fix memory leak unfortunately...

I've been testing [`1.2.6-canary.97+f1cd5abfa`](https://github.com/oven-sh/bun/commit/f1cd5abfaa1dc303de889ffe554db14907858a09) (which includes this PR commit) for the last couple of hours both in Docker and macOS and I'm still seeing an increase in RSS and memory usage in general.

```sh
$ bun --revision
1.2.6-canary.97+f1cd5abfa
```

Here's how it's been performing side by side with `1.2.5+013fdddc6` (latest) with stdout pipe'd for ~1h30m (each in separate Docker container):

| `stdout-pipe-1.2.5` | `stdout-pipe-1.2.6-canary.97+f1cd5abfa` |
|--------|--------|
| Screenshot 2025-03-20 at 10 00 43 PM | Screenshot 2025-03-20 at 10 00 49 PM |

_btw, i ran the test twice and noticed the memory usage in the newer version is slightly higher by a few MBs (same script, docker image, etc.) but maybe it's just random / other factors are involved, idk._

<details>
<summary><code>docker stats</code> log for the <code>stdout-pipe-1.2.6-canary.97+f1cd5abfa</code> container</summary>
<p>

```
                      CPU     MEM USAGE / LIMIT     NET I/O         BLOCK I/O
2025-03-20 20:12:17   1.96%   43.3MiB / 3.886GiB    66kB / 56.1kB   137MB / 8.19kB
2025-03-20 20:22:20   1.72%   76.68MiB / 3.886GiB   133kB / 114kB   270MB / 20.5kB
2025-03-20 20:27:22   2.56%   52.74MiB / 3.886GiB   166kB / 142kB   317MB / 24.6kB
2025-03-20 20:42:26   1.82%   57.6MiB / 3.886GiB    265kB / 228kB   417MB / 24.6kB
2025-03-20 21:07:34   2.30%   69.15MiB / 3.886GiB   430kB / 371kB   660MB / 24.6kB
2025-03-20 21:22:39   1.71%   74.61MiB / 3.886GiB   529kB / 456kB   754MB / 24.6kB
2025-03-20 21:37:44   2.12%   84.63MiB / 3.886GiB   627kB / 542kB   867MB / 24.6kB
2025-03-20 21:42:45   2.29%   107.3MiB / 3.886GiB   661kB / 571kB   934MB / 24.6kB
2025-03-20 21:52:48   2.04%   115.1MiB / 3.886GiB   726kB / 628kB   1.03GB / 28.7kB
2025-03-20 22:07:53   2.48%   114.5MiB / 3.886GiB   825kB / 714kB   1.15GB / 32.8kB
```

</p>
</details> 

Similarly, I had the canary version running the stdout pipe script on macOS for the same duration and this is the Memory Usage I see in Activity Monitor right now:

Screenshot 2025-03-20 at 10 39 33 PM


---

No issues with `1.2.6-canary.97+f1cd5abfa` when all stdio is ignored:

Screenshot 2025-03-20 at 10 31 40 PM


<details><summary><code>docker stats</code> log for the <code>stdout-ignore-1.2.6-canary.97+f1cd5abfa</code></summary>
<p>

```
                      CPU     MEM USAGE / LIMIT     NET I/O         BLOCK I/O
2025-03-20 20:32:43   0.64%   15.99MiB / 3.886GiB   1.52kB / 646B   1.28MB / 8.19kB
2025-03-20 20:47:47   1.01%   13.96MiB / 3.886GiB   100kB / 84.5k   37.1MB / 8.19kB
2025-03-20 20:52:49   0.96%   14.27MiB / 3.886GiB   133kB / 112kB   42.5MB / 8.19kB
2025-03-20 21:12:55   0.71%   14.55MiB / 3.886GiB   265kB / 225kB   62MB / 8.19kB
2025-03-20 21:33:01   0.87%   14.45MiB / 3.886GiB   397kB / 336kB   114MB / 8.19kB
2025-03-20 21:38:03   0.47%   17.73MiB / 3.886GiB   430kB / 364kB   122MB / 8.19kB
2025-03-20 21:53:08   0.89%   17.94MiB / 3.886GiB   529kB / 448kB   161MB / 8.19kB
2025-03-20 22:03:11   0.69%   16.88MiB / 3.886GiB   595kB / 504kB   172MB / 24.6kB
2025-03-20 22:08:12   0.66%   17.71MiB / 3.886GiB   628kB / 532kB   182MB / 24.6kB
2025-03-20 22:23:17   0.57%   18.43MiB / 3.886GiB   727kB / 616kB   261MB / 1.88MB
```
</p>
</details> 

---

<details><summary>Expand for test script I've been running</summary>
<p>


```ts
const BUN_REVISION = Bun.version + '-' + Bun.revision.slice(0, 7);

const spawn = async (...args: string[]) => {
  const proc = Bun.spawn([...args], {
    stdio: ['ignore', 'pipe', 'ignore'],
  });
  const output = await Bun.readableStreamToText(proc.stdout);
  const lines = output.split('\n');
  for (let i = 0; i < lines.length; i++) {
    if (i === lines.length - 1) {
      return true;
    }
  }
  return false;
};

const toMB = (bytes: number) => `${(bytes / 1024 ** 2).toFixed(1)} MB`;

let min = 0;
let max = 0;
let initial = 0;

while (true) {
  await spawn('sed', '50q', '/etc/passwd');
  await spawn('sed', '10q', '/etc/passwd');

  if (!initial) {
    min = max = initial = process.memoryUsage().rss;
    continue;
  }

  console.clear();

  const { rss, heapUsed, heapTotal } = process.memoryUsage();

  min = Math.min(min, rss);
  max = Math.max(max, rss);

  console.log('        Pid', process.pid);
  console.log('   Revision', BUN_REVISION);
  console.log('  Heap Used', toMB(heapUsed));
  console.log(' Heap Total', toMB(heapTotal));
  console.log('Current RSS', toMB(rss));
  console.log('    Min RSS', toMB(min));
  console.log('    Max RSS', toMB(max));

  await Bun.sleep(1000);
}
```

</p>
</details> 

</p>
</details>
