### PR TITLE
Merge import.meta.require and require to be the same thing

### LINKED ISSUE #3724: Vite dev is failing on 0.7
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

` bun --bun vite dev
`
returns 
`failed to load config from /Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/vite.config.ts
error when starting dev server:
Error: config must export or return an object.
    at <anonymous> (/Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:66014:15)
error: "vite" exited with code 1 (SIGHUP)
`

this is the vite config `import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react-swc'
import {posix} from "path";

const config = defineConfig({
    plugins: [react()],
    build: {
        outDir: "build",
    },
    server: {
        port: 3000,

    },
    resolve: {
        alias: [
            {find: "@/src", replacement: posix.resolve("/", "src")},
            {find: "src", replacement: posix.resolve("/", "/src")}
        ]
    },
})

export default config`

### What is the expected behavior?

Vite dev runs 

### What do you see instead?

import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react-swc'
import {posix} from "path";

const config = defineConfig({
    plugins: [react()],
    build: {
        outDir: "build",
    },
    server: {
        port: 3000,

    },
    resolve: {
        alias: [
            {find: "@/src", replacement: posix.resolve("/", "src")},
            {find: "src", replacement: posix.resolve("/", "/src")}
        ]
    },
})

export default config

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
We used to implement `require` twice. once for `import.meta.require` and then once in the actual `require` implementation. This is just old code from before the CJS rewrite.

`import.meta.require` and `createRequire` now create an empty `JSCommonJSModule` and return it's `require` function.

Fixes #3724, because the old require implementation would not append `__esModule` to certain case.

### CODE REVIEW

File: src/bun.js/bindings/CommonJSModuleRecord.cpp [hunk 1]
```diff
@@ -969,4 +938,40 @@ std::optional<JSC::SourceCode> createCommonJSModule(
...
+        moduleObject,
+        ArgList(), 1, jsString(vm, String("require"_s)));
+
+    JSFunction* resolveFunction = JSC::JSBoundFunction::create(vm,
+        globalObject,
+        globalObject->requireResolveFunctionUnbound(),
+        moduleObject,
+        ArgList(), 1, jsString(vm, String("require"_s)));
+
+    requireFunction->putDirect(vm, builtinNames.resolvePublicName(), resolveFunction, 0);
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/CommonJSModuleRecord.cpp]: PropertyAttribute::Function | 0

**Comment by Jarred-Sumner** [comment]
Looks like this breaks plugins because plugins for "real" CommonJS aren't actually implemented yet (that's why plugins + svelte tests are failing) 

I think that will need to be addressed before this PR can move forward.
