### PR TITLE
devserver: fix cases where source maps would not remap

### LINKED ISSUE #17559: stack traces of hot reloading payloads do not remap for the overlay
### What version of Bun is running?

1.2.3+8c4d3ff80

### What platform is your computer?

Darwin 24.3.0 x86_64 i386

### What steps can reproduce the bug?

I'm not sure how reproducible it is, without cloning my entire project, but the problem seems some what generic. I'll include the source for the file I was working on either way:

```jsx
import { produce } from 'immer';
import React, { PropsWithChildren, useEffect, useState } from 'react';

import { AppStateProvider, initialAppState } from '../contexts/AppState';

import { processWebsocketMessage } from './handler';
import { useWebsocket, WebsocketMessage } from './useWebsocket';

type Props = PropsWithChildren;

export const SocketProvider = ({ children }: Props): React.JSX.Element => {
    const [appState, setAppState] = useState(initialAppState());

    useEffect(() => {
        return useWebsocket({
            socketId: 'main-socket',
            path: '/api/v1/ui/socket',
            onConnect: () => setAppState(value => produce(value, draft => {
                draft.meta.socketConnected = new Date();
            })),
            onClose: () => setAppState(value => produce(value, draft => {
                draft.meta.socketConnected = false;
            })),
            onMessage: (message: WebsocketMessage): void => {
                processWebsocketMessage(message, setAppState);
            }
        });
    }, []);

    return <AppStateProvider value={appState}>
        {children}
    </AppStateProvider>
}
```

I then added the following code between line 12 and 14 (don't mind me doing dumb stuff), which obviously yielded an error:

```javascript
console.log(process.env.TEST);
```

Image

### What is the expected behavior?

The browser should show the error to be `ReferenceError: process is not defined` (that it does correctly), pointing to line 14 (the line with the `console.log`) in the source code view in the error dialog.

### What do you see instead?

At first it shows the error to be coming from somewhere deep in React (I think), and when I save the file again, it shows it originating in the right file, but the wrong line/symbol, which is confusing.

At first:
Image

<details>
<summary>Text from the screenshot</summary>
Runtime Error
ReferenceError: process is not defined
        callComponent["react-stack-bottom-frame"].bind(callComponent),
      callRender = {
        "react-stack-bottom-frame": function (instance) {
          var wasRendering = isRendering;
          isRendering = !0;
at eval in eval at 117 http://localhost:3000/_bun/client/index-00000000122f82b0.js:9:6459, <anonymous>:19:19
at react-stack-bottom-frame in node_modules/react-dom/cjs/react-dom-client.development.js:22437:9
at renderWithHooks in node_modules/react-dom/cjs/react-dom-client.development.js:5769:22
at updateFunctionComponent in node_modules/react-dom/cjs/react-dom-client.development.js:8034:7
at beginWork in node_modules/react-dom/cjs/react-dom-client.development.js:9711:26
at runWithFiberInDEV in node_modules/react-dom/cjs/react-dom-client.development.js:551:14
at performUnitOfWork in node_modules/react-dom/cjs/react-dom-client.development.js:15066:45
at workLoopSync in node_modules/react-dom/cjs/react-dom-client.development.js:14877:7
at renderRootSync in node_modules/react-dom/cjs/react-dom-client.development.js:14854:42
at performWorkOnRoot in node_modules/react-dom/cjs/react-dom-client.development.js:14399:21
</details>

After saving again:
Image

<details>
<summary>Text from the screenshot</summary>
Runtime Error
ReferenceError: process is not defined
            socketId: 'main-socket',
            path: '/api/v1/ui/socket',
            onConnect: () => setAppState(value => produce(value, draft => {
                draft.meta.socketConnected = new Date();
            })),
at src/frontend/app/js/socket/SocketProvider.tsx:21:13
at react-stack-bottom-frame in node_modules/react-dom/cjs/react-dom-client.development.js:22437:9
at renderWithHooks in node_modules/react-dom/cjs/react-dom-client.development.js:5769:22
at updateFunctionComponent in node_modules/react-dom/cjs/react-dom-client.development.js:8034:7
at beginWork in node_modules/react-dom/cjs/react-dom-client.development.js:9711:26
at runWithFiberInDEV in node_modules/react-dom/cjs/react-dom-client.development.js:551:14
at performUnitOfWork in node_modules/react-dom/cjs/react-dom-client.development.js:15066:45
at workLoopSync in node_modules/react-dom/cjs/react-dom-client.development.js:14877:7
at renderRootSync in node_modules/react-dom/cjs/react-dom-client.development.js:14854:42
at performWorkOnRoot in node_modules/react-dom/cjs/react-dom-client.development.js:14399:21
</details>

### Additional information

This is a **very** minor issue, the dev server is absolutely amazing, 100% love it. This particular issue isn't bothering me much, just figured you'd want to know.

### PR DESCRIPTION
**Pull request by paperclover**
`eval` for hot-loaded chunks cause many problems relating to source maps. To make user's code more reliable. since this tests code that depends on different browser quicks, including how it applies CORS rules, i haven't yet written a test. it seems a good target for this test would involve puppeteer.

note that the ES module registry is avoided on purpose.

Fixes #17559

Now that correct logic for knowing the reachable JS files exists on the client, this opens up the work to implement proper ref-counting of these on the server. That followup will fix memory buildup problems.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 3:56 PM PT - Apr 25th, 2025</sup></div>

@paperclover, your commit 8ac8e13abf3b640ef9cbfa8ed036bdaa621a97fa is building: [`#15643`](https://buildkite.com/bun/bun/builds/15643)

File: src/bake/client/stack-trace.ts [hunk 1]
```diff
@@ -6,14 +6,39 @@ export interface Frame {
...
+ * unreachable, the oldest blobs will get freed.
+ */
+const gcSize = 1024 * 1024 * 2; // 2MB
+
 /**
  * Modern port of the error-stack-parser library
  * https://github.com/stacktracejs/error-stack-parser/blob/9f33c224b5d7b607755eb277f9d51fcdb7287e24/error-stack-parser.js
  */
 export function parseStackTrace(error: Error | any): null | Frame[] {
+  console.log({stack:error.stack});
```
Comment (Jarred-Sumner) [inline src/bake/client/stack-trace.ts]: did you mean to keep the console log in there?

File: src/bun.js/bindings/BunString.cpp [hunk 2]
```diff
@@ -467,6 +467,17 @@ extern "C" BunString URL__getFileURLString(BunString* filePath)
...
 
+extern "C" size_t URL__originLength(BunString* str)
+{
+    WTF::String string = str->toWTFString();
+    if (!string)
+        return 0;
+    WTF::URL url(string);
+    if (!url.isValid())
+        return 0;
+    return url.pathStart();
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/BunString.cpp:478]: If the URL contains non-ascii characters or gets puny decoded, this will return a UTF-16 byte length instead of a UTF-8 byte length

rihgt?

Comment (paperclover) [reply src/bun.js/bindings/BunString.cpp:478]: true

Comment (paperclover) [reply src/bun.js/bindings/BunString.cpp:478]: the new version of this function only operates on ascii

File: src/bun.js/bindings/BunString.cpp [hunk 3]
```diff
@@ -467,6 +467,17 @@ extern "C" BunString URL__getFileURLString(BunString* filePath)
     return Bun::toStringRef(WTF::URL::fileURLWithFileSystemPath(filePath->toWTFString()).stringWithoutFragmentIdentifier());
 }
 
+extern "C" size_t URL__originLength(const char* latin1_slice, size_t len)
+{
+    WTF::String string = WTF::StringView(latin1_slice, len, true).toString();
```
Comment (dylan-conway) [inline src/bun.js/bindings/BunString.cpp:472]:
```suggestion
    WTF::String string = WTF::String({ latin1_slice, len, true });
```

File: src/bun.js/bindings/URL.zig [hunk 4]
```diff
@@ -108,6 +108,19 @@ pub const URL = opaque {
...
         return URL__pathname(url);
     }
+
+    extern fn URL__originLength(latin1_slice: [*]const u8, len: usize) u32;
+    pub fn originFromSlice(slice: []const u8) ?[]const u8 {
+        JSC.markBinding(@src());
+        // a valid URL will not have ascii in the origin.
+        const first_non_ascii = bun.strings.firstNonASCII(slice) orelse slice.len;
+        const len = URL__originLength(
+            slice[0..first_non_ascii].ptr,
```
Comment (dylan-conway) [inline src/bun.js/bindings/URL.zig:118]: ~~the pointer stays the same. do we need to use `firstNonAscii`?~~

nevermind, used in second argument

File: src/bake/client/stack-trace.ts [hunk 5]
```diff
@@ -96,5 +120,44 @@ function extractLocation(urlLike: string) {
...
+      // Delete old blobs
+      let acc = 0;
+      for (let i = 0; i < gcBlobs.length; i++) {
+        acc += gcBlobs[i].size;
+        if (acc > gcSize) {
+          acc -= gcBlobs[i].size;
+          URL.revokeObjectURL(gcBlobs[i].url);
+          gcBlobs.splice(i, 1);
+          i--;
+        }
```
[the remark this answers is not in the document]
Comment (e3dio) [reply src/bake/client/stack-trace.ts:159]: Almost helpful but it missed the `i--` so the code was ok

[the remark this answers is not in the document]
Comment (paperclover) [reply src/bake/client/stack-trace.ts:159]: this ai review is actually "correct" but not for the reason it states. the reason the loop must be backwards is so that entries towards the end are prioritized. right now it would actually delete `value` immediately since it is at the end of the list.

i only caught that while writing a comment explaining why the loop iteration had to be forwards
