### PR TITLE
WebKit Upgrade

### LINKED ISSUE #19557: Segmentation fault at address 0x0
### How can we reproduce the crash?

I encountered a segmentation fault in a bigger closed-source project and tried to strip away as much as possible while preserving the crash until I got the following snippet. I am aware that the code in the snippet makes no sense but any seemingly uncorrelated change changes the the error.
```js
async function initializeFileImporter() {
  for (let i = 1; i <= 500; i++) {
    const fetchResult = await fetch(
      "https://wallpapers.com/images/hd/cute-funny-cat-pictures-h7zabmrk0t67e4bd.jpg"
    );
    await fetchResult.blob();
  }
}

async function main() {
  const importer = async () => ({});
  const addToLog = console.log;

  const data = { ids: undefined };
  if (data.ids !== undefined) {
    addToLog(await importer().catch((error: any) => ({ error })));
  } else {
    await initializeFileImporter();
    addToLog({ message: `initialized importer` });
  }
}

main();
```

Note that replacing `({error})` in line 16 by `null` yields the following error which is not a crash but also seems to be unintentional:
```
14 |   const data = { ids: undefined };
15 |   if (data.ids !== undefined) {
16 |     addToLog(await importer().catch((error: any) => null));
17 |   } else {
18 |     await initializeFileImporter();
19 |     addToLog({ message: `initialized importer` });
         ^
TypeError: addToLog is not a function. (In 'addToLog({ message: "initialized importer" })', 'addToLog' is 6.633171186320096e-299)
      at main (/home/lars/Dokumente/cloned/frontend/scripts/import/run.ts:19:5)

Bun v1.2.13-canary.29+de487713e (Linux x64)
```
With different but similar versions of the code the following errors could be created:
```
TypeError: addToLog is not a function. (In 'addToLog(...)', 'addToLog' is 8.637371750472184e-309)
TypeError: addToLog is not a function. (In 'addToLog(...)', 'addToLog' is an instance of Object)
TypeError: addToLog is not a function. (In 'addToLog(...)', 'addToLog' is undefined)
```

The crash could also be confirmed on Bun v1.2.4 (macOS arm64)

### Relevant log output

```shell
============================================================
Bun Canary v1.2.13-canary.29 (de487713) Linux x64
Linux Kernel v6.8.0 | glibc v2.35
CPU: sse42 popcnt avx avx2 avx512
Args: "bun" "./scripts/import/run.ts"
Features: dotenv(6) fetch(500) jsc tsconfig 
Builtins: "bun:main" 
Elapsed: 7354ms | User: 572ms | Sys: 897ms
RSS: 0.02ZB | Peak: 75.66MB | Commit: 0.02ZB | Faults: 0

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.2.13/la2de48771EgwkQk61jqE+xyQ___07248Dwumm/E4m91oFiyv+uF098nhDA2AA

Ungültiger Maschinenbefehl (Speicherabzug geschrieben)
```

### Stack Trace (bun.report)

Bun v1.2.13-canary ([`de48771`](<https://github.com/oven-sh/bun/tree/de487713ed48e8b170c7014534864aa61de212a2>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/de487713ed48e8b170c7014534864aa61de212a2/ld-temp.o#L0>): `llint_call_javascript`
- [`Interpreter.cpp:1322`](<https://github.com/oven-sh/bun/blob/de487713ed48e8b170c7014534864aa61de212a2//webkitbuild/vendor/WebKit/Source/JavaScriptCore/interpreter/Interpreter.cpp#L1322>): `JSC::Interpreter::executeCall`
- [`CallData.cpp:57`](<https://github.com/oven-sh/bun/blob/de487713ed48e8b170c7014534864aa61de212a2//webkitbuild/vendor/WebKit/Source/JavaScriptCore/runtime/CallData.cpp#L57>): `JSC::runJSMicrotask`
- [`VM.cpp:1357`](<https://github.com/oven-sh/bun/blob/de487713ed48e8b170c7014534864aa61de212a2//webkitbuild/vendor/WebKit/Source/JavaScriptCore/runtime/VM.cpp#L1357>): `JSC::VM::drainMicrotasks`
- [`event_loop.zig:940`](<https://github.com/oven-sh/bun/blob/de487713ed48e8b170c7014534864aa61de212a2/src/bun.js/event_loop.zig#L940>): `bun.js.event_loop.EventLoop.tickQueueWithCount__anon_512314`

Features: transpiler\_cache, tsconfig, dotenv, fetch, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6595934356/">BUN-J54</a></strong></sub>

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

- Replace all `LIKELY` with `[[likely]]`
- Replace all `UNLIKELY` with `[[unlikely]]`
- Discard two clang warnings
- Includes `<limits>` to fix PureNaN.h compile errors
- Fixes our definition of JSType to match WebKit adding `DisposableStack`
- Fixes out-of-bounds detection in Buffer BigInt methods and adds test
- Fixes crashes due to an uninitialized `ErrorableResolvedSource`

Fixes #19557

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 11:11 PM PT - May 21st, 2025</sup></div>

@Jarred-Sumner, your commit a2cb251f9d00e3ce0088e006ee81309d0ab664b5 is building: [`#17104`](https://buildkite.com/bun/bun/builds/17104)

File: src/bun.js/bindings/JSValue.zig [hunk 1]
```diff
@@ -98,33 +98,34 @@ pub const JSValue = enum(i64) {
...
-        Set = 76,
-        WeakMap = 77,
-        WeakSet = 78,
-        WebAssemblyModule = 79,
-        WebAssemblyInstance = 80,
-        WebAssemblyGCObject = 81,
-        StringObject = 82,
-        DerivedStringObject = 83,
-        InternalFieldTuple = 84,
+        DisposableStack = 58,
```
Comment (190n) [inline src/bun.js/bindings/JSValue.zig:101]: we should get translate-c to do this
