### PR TITLE
fix: crash in `Bun.inspect.table`

### LINKED ISSUE #18230: Crash in Bun.inspect.table()
### How can we reproduce the crash?

`Bun.inspect.table(null)` works
`Bun.inspect.table(undefined)` works
`Bun.inspect.table([])` works
`Bun.inspect.table({})` works
`Bun.inspect.table('')` crashes

### Relevant log output

```shell
============================================================
Bun v1.2.2 (c1708ea6) macOS Silicon
macOS v15.3.2
Args: "bun" "psql.js" "describe" "test" "table"
Features: jsc 
Builtins: "bun:main" "node:fs" "node:util/types" 
Elapsed: 15ms | User: 11ms | Sys: 5ms
RSS: 29.36MB | Peak: 29.36MB | Commit: 1.07GB | Faults: 84

panic(main thread): Segmentation fault at address 0x6
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.2.2 ([`c1708ea`](<https://github.com/oven-sh/bun/tree/c1708ea6ab529a4c747a8282a24d125dc20b0a63>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x00000006

- *1 unknown/js code*
- `Bun__JSPropertyIterator__create`
- `src.bun.js.bindings.bindings.toJSHostFunction__struct_142603.function`
- *1 unknown/js code*
- `jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__666_callHelper__dispatch_LowLevelInterpreter64_asm_2538`
- `jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__666_callHelper__dispatch_LowLevelInterpreter64_asm_2538`
- `jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__684_callHelper__dispatch_LowLevelInterpreter64_asm_2538`
- `jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__684_callHelper__dispatch_LowLevelInterpreter64_asm_2538`
- `llint_call_javascript`
- `JSC::Interpreter::executeCall`

Features: Bun.stdin, fetch, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6405426453/">BUN-EA5</a></strong></sub>

### PR DESCRIPTION
**Pull request by DonIsaac**
### What does this PR do?
Fixes #18230

### How did you verify your code works?
I added tests

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 12:17 PM PT - Mar 17th, 2025</sup></div>

@DonIsaac, your commit cd8ecc2fe0b25498f6c5513c60a993a0ab6c4a9f is building: [`#13398`](https://buildkite.com/bun/bun/builds/13398)

File: src/bun.js/bindings/JSValue.zig [hunk 1]
```diff
@@ -1559,10 +1569,26 @@ pub const JSValue = enum(i64) {
...
+    /// For values that are already objects, this is effectively a reinterpret
+    /// cast.
     pub fn toObject(this: JSValue, globalThis: *JSGlobalObject) *JSObject {
         return cppFn("toObject", .{ this, globalThis });
     }
 
+    /// Statically cast a value to a JSObject.
+    ///
+    /// Returns _null_ for non-objects. Use `toObject` to runtime-cast them instead.
+    pub fn asObject(this: JSValue) ?*JSObject {
```
Comment (Jarred-Sumner) [inline src/bun.js/bindings/JSValue.zig]: This is a bit backwards. `getObject` should be optional, and `asObject` should assert. That's how JSC does it in their methods.

Comment (DonIsaac) [reply src/bun.js/bindings/JSValue.zig:1583]: I agree it's backwards, but that's how `JSC` has named it.

File: src/bun.js/bindings/JSPropertyIterator.zig [hunk 2]
```diff
@@ -21,38 +14,58 @@ pub fn JSPropertyIterator(comptime options: JSPropertyIteratorOptions) type {
...
         pub fn deinit(this: *@This()) void {
-            if (this.impl) |impl| {
-                Bun__JSPropertyIterator__deinit(impl);
-            }
+            if (this.impl) |impl| impl.deinit();
             this.* = undefined;
         }
 
+        /// `object` should be a `JSC::JSObject`. Non-objects will be runtime converted.
         pub fn init(globalObject: *JSC.JSGlobalObject, object: JSC.JSValue) bun.JSError!@This() {
```
Comment (dylan-conway) [inline src/bun.js/bindings/JSPropertyIterator.zig:38]:
```suggestion
        pub fn init(globalObject: *JSC.JSGlobalObject, object: *JSC.JSObject) bun.JSError!@This() {
```
This will allow us to avoid the exception. Most changes needed to make this work look like:
```diff
- if (!value.isObject()) {
+ const obj = value.getObject() orelse {
    global.throw(...);
}
```
}

**Review by dylan-conway — CHANGES_REQUESTED** [review]
Just one suggestion. It will involve changing each `.init` callsite slightly, but is a good change to make. Looks like this will catch a couple potential crashes

File: src/bun.js/bindings/JSPropertyIterator.zig (hunk 2 above)
Comment (DonIsaac) [reply src/bun.js/bindings/JSPropertyIterator.zig:38]: I'll make this change in a follow-up PR.

**Review by dylan-conway — APPROVED** [review]
