### PR TITLE
fix(resolver): allow builtins to be imported via subpath imports

### LINKED ISSUE #4972: bunx --bun astro dev not working
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 588c084220b1 5.15.0-1040-oracle #46-Ubuntu SMP Fri Jul 14 21:47:21 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### What steps can reproduce the bug?

Hi, I use bun x create a astro project, but use bunx --bun astro dev  output error.

like this:
截屏2023-09-12 00 23 00

截屏2023-09-12 00 25 07

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

Fixes #4972 
Fixes https://github.com/oven-sh/bun/issues/7488

### CODE REVIEW

File: src/resolver/resolver.zig [hunk 1]
```diff
@@ -2881,14 +2888,23 @@ pub const Resolver = struct {
 
         const esm_resolution = esmodule.resolveImports(import_path, imports_map.root);
 
-        if (esm_resolution.status == .PackageResolve)
+        if (esm_resolution.status == .PackageResolve) {
+            if (JSC.HardcodedModule.Aliases.get(esm_resolution.path, .bun)) |builtin| {
```
Comment (Jarred-Sumner) [inline src/resolver/resolver.zig]: This needs to only apply when using Bun. This would do weird things in the browser
