### PR TITLE
fix(install): `peer/dev/optional = false` lockfile fix

### LINKED ISSUE #5571: Support bun install --omit=dev
### What is the problem this feature would solve?

NPM advised us to use: `npm install --omit=dev`, and bun only has `--production` / `-p` flags.

Please, also introduce the `--omit` flag with Bun.

### What is the feature you are proposing to solve the problem?

Compatibility with node/npm. For a better drop-in replacement without regression impact.

### What alternatives have you considered?

Running: `bun install --omit=dev` .. but I don't think it works, it doesn't give an error either? Looking at the options: `bun install --help` doesn't show the `--omit` flag option.

Tested with bun v1.0.2.

### LINKED ISSUE #15107: Bun keep install devDependencies on project
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I am currently build an npm package with bun.
However when i do install. It will install `extraneous` dependencies.

if i do `bun i` it will install me all dependencies, even the devDependencies.
But if i do `npm i` it will install me only dependencies, NOT devDependencies.

Here is my package.json.

```json
{
    "name": "litojs",
    "version": "0.0.1",
    "main": "src/index.ts",
    "type": "module",
    "exports": {
        ".": "./src/index.ts"
    },
    "scripts": {
        "lint": "bunx eslint ./src"
    },
    "devDependencies": {
        "@types/bun": "latest",
        "@eslint/js": "^9.14.0",
        "@types/eslint__js": "^8.42.3",
        "eslint": "^9.14.0",
        "eslint-plugin-simple-import-sort": "^12.1.1",
        "typescript-eslint": "^8.13.0"
    },
    "peerDependencies": {
        "typescript": "^5.6.3"
    },
    "dependencies": {
        "chalk": "^5.3.0"
    }
}
```

### What is the expected behavior?

The expected behaviour is only Install Dependencies, without devDependencies.

### What do you see instead?

This is when i do install using `bun`.
Image

This is when i do install using `npm`.
Image

### Additional information

_No response_

### LINKED ISSUE #15858: `bun install --save-text-lockfile` generates incompatible `bun.lock`
### What version of Bun is running?

1.1.40+b5b51004e

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### Bug Report
I am trying to to migrate from `bun.lockb` to `bun.lock` without changing the exact dependencies.
`bun install --save-text-lockfile` produces a `bun.lock` file that seems incompatible with subsequent `--frozen-lockfile` operations, leading to errors.

### Steps to Reproduce:
1. Create a repository with attached files:
- [package.json](https://github.com/user-attachments/files/18189555/package.json)
- [bun.lockb.zip](https://github.com/user-attachments/files/18189559/bun.lockb.zip)
    - unzip to `bun.lock`
2. Run `bun install --frozen-lockfile`.
- Expected: No changes, installation proceeds using bun.lockb.
- Actual: As expected.
3. Run `bun install --save-text-lockfile`.
- Expected: A `bun.lock` is created without issues.
- Actual: Both `bun.lock` and `bun.lockb` exist.
4. Delete `bun.lockb` to keep only the text lock file.
5. Run `bun install --frozen-lockfile` again.
- Expected: Install completes successfully using the bun.lock without any changes.
- Actual: Encounter the following error:
```
bun install v1.1.40 (b5b51004)
472 |     "@jest/core": ["@jest/core@29.7.0", "", { "dependencies": { "@jest/console": "^2
          ^
error: Unable to resolve dependencies for package
    at bun.lock:472:5
InvalidPackageInfo: failed to parse lockfile: 'bun.lock'

warn: Ignoring lockfile
error: lockfile had changes, but lockfile is frozen
```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Ensures the dependency tree saved to the lockfile includes dependencies that are disabled through configuration. This fixes bugs where your lockfile would fail to load due to it being unresolvable.

fixes #15858

Also fixes a crash caused by the lockfile containing an invalid url.

Implements `bun install --omit <dependency type>` for `dev`, `peer`, and `optional`.

closes #5571 

Adds support for `omit` and `include` in `.npmrc`.

closes #15107

Fixes inconsistent total package install count in progress. Now it will report total number of package copies instead of unique packages.

fixes (unconfirmed) #15598 

Fixes an infinite loop caused by disabling optional dependencies and installing with a populated cache.

### How did you verify your code works?
Added a test for invalid url bug, --omit, and valid text lockfiles after disabling dependency groups.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 11:33 PM PT - Dec 18th, 2024</sup></div>

@dylan-conway, your commit a3cfda77606f878263f2247d25ed042860e3c9bf is building: [`#8216`](https://buildkite.com/bun/bun/builds/8216)

File: src/install/lockfile.zig [hunk 1]
```diff
@@ -652,82 +660,98 @@ pub const Tree = struct {
...
+
+            /// Flatten the multi-dimensional ArrayList of package IDs into a single easily serializable array
+            pub fn clean(this: *@This()) OOM!DependencyIDList {
+                const end = @as(Id, @truncate(this.list.len));
+                var i: Id = 0;
+                var total: u32 = 0;
+                const trees = this.list.items(.tree);
+                const dependencies = this.list.items(.dependencies);
+
+                while (i < end) : (i += 1) {
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]:
```suggestion
                for (trees[i..end]) |*tree| {
```

File: src/install/lockfile.zig [hunk 2]
```diff
@@ -779,21 +807,48 @@ pub const Tree = struct {
...
+                if (builder.lockfile.isPackageDisabled(
+                    dep_id,
+                    switch (pkg_resolutions[parent_pkg_id].tag) {
+                        .root, .workspace, .folder => builder.manager.options.local_package_features,
+                        else => builder.manager.options.remote_package_features,
+                    },
+                    &pkg_metas[pkg_id],
+                )) {
+                    if (log_level.isVerbose()) {
+                        const meta = pkg_metas[pkg_id];
```
Comment (Jarred-Sumner) [inline src/install/lockfile.zig]:
```suggestion
                        const meta = &pkg_metas[pkg_id];
```

**Review by Jarred-Sumner — APPROVED** [review]
