### PR TITLE
[PKG-513, ENG-19757] `bun install`: fix non-ascii edge case and simplify task lifetimes

### LINKED ISSUE #21243: bun failed to link package: next@15.4.2
### What version of Bun is running?

1.2.19+aad3abead

### What platform is your computer?

win11 x64

### What steps can reproduce the bug?

```
bun install next@15.4.2
```

```
bun add v1.2.19 (aad3abea)
  🔍 Resolving... ENOENT: No such file or directory: failed to link package: next@15.4.2 (copyfile)

installed next@15.4.2 with binaries:
 - next

Failed to install 1 package
```

It prompts that the link failed and the project cannot use next~ 

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

node v22.17.0
npm 11.4.2
bun v1.2.19 (aad3abea)

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?

Replaces the preallocated_tasks HiveArray with a fixed-size tasks array allocated per install, and renames the tasks queue to task_queue for clarity. Tasks are now initialized up front and referenced by entry_id, simplifying task lifecycle management and reducing dynamic allocation overhead.

---

Fixes a bug in handling non-ascii directory paths in `Bun.which` on windows.

fixes #21243

---

Fixes a string UAF when importing a module with a non-latin1 file path

### How did you verify your code works?
Added a test for both path bugs.

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 12:37 PM PT - Jul 23rd, 2025</sup></div>

@dylan-conway, your commit 723eee8a22141259c9dc2ce006baa7c04c578d4a is building: [`#21292`](https://buildkite.com/bun/bun/builds/21292)

File: src/bun.js/VirtualMachine.zig [hunk 1]
```diff
@@ -1555,11 +1555,11 @@ fn _resolve(
         return;
     } else if (strings.hasPrefixComptime(specifier, js_ast.Macro.namespaceWithColon)) {
         ret.result = null;
-        ret.path = specifier;
+        ret.path = try bun.default_allocator.dupe(u8, specifier);
```
Comment (dylan-conway) [inline src/bun.js/VirtualMachine.zig:1558]: these are allocated now because the caller of this function frees `specifier` at the end of the function if it's allocated. non-ascii triggers the bug because we need to allocate for the convertion to utf8

**Review by pfgithub — APPROVED** [review]
