### PR TITLE
attempt to fix debugger

### LINKED ISSUE #15439: Debugging Not Working After Upgrade to 1.1.37
### What version of Bun is running?

1.1.37+8ca0eb831

### What platform is your computer?

Linux 6.8.0-49-generic x86_64 x86_64

### What steps can reproduce the bug?

console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");

Set breakpoints on lines 1 to 4.
Run the debugger.

### What is the expected behavior?

The breakpoint only stops at line 1.

### What do you see instead?

The breakpoints do not trigger, and the program simply continues running without stopping.

Debugger attached.
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Debugger detached.

### Additional information

In version 1.1.36, breakpoints are triggered, but as reported previously, the breakpoint incorrectly stops at line 2 instead of line 1.
After upgrading to 1.1.37, the breakpoints no longer work at all — the program just runs without stopping.
The expected behavior is for the breakpoint to trigger on line 1.

https://github.com/oven-sh/bun/issues/15131

### PR DESCRIPTION
**Pull request by RiskyMH**
2 different fixes:
1. make vscode debugger work by removing `BUN_INSPECT_CONNECT_TO` condition to not wait forever (as extension always sets it, bun doesnt wait enough usually)
2. reverts some changes in `BunDebugger.cpp` so it works in debug.bun.sh again (it seems to still work for vscode)

fixes #15439
fixes maybe #15715

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 8:37 PM PT - Dec 15th, 2024</sup></div>

@RiskyMH, your commit de4fb985a1d41fee18233f9219bbb4b1c96feeea is building: [`#8026`](https://buildkite.com/bun/bun/builds/8026)

File: src/bun.js/bindings/BunDebugger.cpp [hunk 1]
```diff
@@ -120,10 +124,10 @@ class BunInspectorConnection : public Inspector::FrontendChannel {
...
         }
 
-        if (waitingForConnection) {
-            waitingForConnection = false;
-            Debugger__didConnect();
-        }
+        // if (waitingForConnection) {
+        // waitingForConnection = false;
+        // Debugger__didConnect();
+        // }
```
Comment (RiskyMH) [inline src/bun.js/bindings/BunDebugger.cpp]: I'm still not sure about the importance of this, so left them in for review and then can remove once its determined to work well.

**Comment by Jarred-Sumner** [comment]
The second thing that defaults it to .shortly should be reverted. We can remove the commented out code though
