### PR TITLE
Fixes #4876

### LINKED ISSUE #4876: res.json() throw JSON Parse error
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

run below code with bun will throw `SyntaxError: JSON Parse error: Unrecognized token ''`

```
const res = await fetch("https://www.1823.gov.hk/common/ical/en.json");
const data = await res.json();
console.log(data);
```

### What is the expected behavior?

log the response json

### What do you see instead?

`SyntaxError: JSON Parse error: Unrecognized token ''`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

Fixes #4876 

### How did you verify your code works?

There are tests

### CODE REVIEW

File: src/js/builtins/ReadableStreamInternals.ts [hunk 1]
```diff
@@ -1070,11 +1070,15 @@ export function createTextStream(highWaterMark) {
       }
 
       if (hasString && !hasBuffer) {
+        if (rope.charCodeAt(0) === 0xfeff) {
+          rope = rope.slice(1);
+        }
+
         return rope;
```
Comment (akx) [inline src/js/builtins/ReadableStreamInternals.ts:1077]: Should this just call `withoutUTF8BOM`?

File: src/js/builtins/ReadableStreamInternals.ts [hunk 2]
```diff
@@ -1089,12 +1093,16 @@ export function createTextStream(highWaterMark) {
       }
       array.length = 0;
       if (rope.length > 0) {
+        if (rope.charCodeAt(0) === 0xfeff) {
+          rope = rope.slice(1);
+        }
```
Comment (akx) [inline src/js/builtins/ReadableStreamInternals.ts:1098]: Ditto, could also be a `withoutUTF8BOM` call?

File: src/js/builtins/ReadableStreamInternals.ts (hunk 1 above)
Comment (TheDirigible) [reply src/js/builtins/ReadableStreamInternals.ts:1077]: But then the source would be readable.  This fix doesn't even have a comment explaining what it's doing.
