### PR TITLE
Bun.redis getex all arguments

### LINKED ISSUE #21905: Redis `getex` method signature is wrong
### What version of Bun is running?

1.2.13+64ed68c9e

### What platform is your computer?

Darwin 24.6.0 arm64 arm

### What steps can reproduce the bug?

```typescript
import { redis } from "bun";

// This should work according to Redis GETEX specification
await redis.getex("mykey", "EX", 60);

// But TypeScript shows error and runtime fails because parameters are missing
// Current signature only accepts: getex(key: KeyLike)
// Expected signature should be: getex(key: KeyLike, "EX" | "PX" | "EXAT" | "PXAT" | "PERSIST", value?: number)
```

The current `getex` method in `packages/bun-types/redis.d.ts` is missing all expiration parameters that are core to the GETEX command.

### What is the expected behavior?

The `getex` method should accept expiration parameters according to Redis GETEX specification:

```typescript
redis.getex("key", "EX", 60)     // Set expiration in seconds
redis.getex("key", "PX", 60000)  // Set expiration in milliseconds  
redis.getex("key", "PERSIST")    // Remove expiration
```

### What do you see instead?

_No response_

### Additional information

Either the JSDoc comment "optionally set its expiration" is misleading, or the method signature is incomplete. The Redis GETEX command's main purpose is to get a value AND modify expiration atomically, but current implementation only allows GET without expiration control.

Reference: https://redis.io/docs/latest/commands/getex/

### PR DESCRIPTION
**Pull request by alii**
### What does this PR do?

Fix #21905

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 4:07 PM PT - Aug 15th, 2025</sup></div>

@alii, your commit 889a7e08cd9c5febcfb2cb9de6997b3b80f21ba1 is building: [`#23134`](https://buildkite.com/bun/bun/builds/23134)

File: src/bun.js/api/bun/subprocess/ResourceUsage.zig [hunk 1]
```diff
@@ -63,11 +63,10 @@ pub fn getContextSwitches(this: *ResourceUsage, globalObject: *JSGlobalObject) J
...
 pub fn finalize(this: *ResourceUsage) callconv(.C) void {
-    bun.default_allocator.destroy(this);
+    bun.destroy(this);
 }
 
 const bun = @import("bun");
-const default_allocator = bun.default_allocator;
 const Rusage = bun.spawn.Rusage;
 
 const jsc = bun.jsc;
```
Comment (RiskyMH) [inline src/bun.js/api/bun/subprocess/ResourceUsage.zig:72]: was this a related change?

Comment (alii) [reply src/bun.js/api/bun/subprocess/ResourceUsage.zig:72]: Yeah, was causing ASAN issues. happened in the recent subprocess splitup and only happens on macos. surprised it wasnt ran into already in other places

File: src/valkey/js_valkey_functions.zig [hunk 2]
```diff
@@ -582,7 +582,7 @@ pub const bitcount = compile.@"(key: RedisKey)"("bitcount", "BITCOUNT", "key").c
 pub const dump = compile.@"(key: RedisKey)"("dump", "DUMP", "key").call;
 pub const expiretime = compile.@"(key: RedisKey)"("expiretime", "EXPIRETIME", "key").call;
 pub const getdel = compile.@"(key: RedisKey)"("getdel", "GETDEL", "key").call;
-pub const getex = compile.@"(key: RedisKey)"("getex", "GETEX", "key").call;
+pub const getex = compile.@"(...strings: string[])"("getex", "GETEX").call;
```
Comment (RiskyMH) [inline src/valkey/js_valkey_functions.zig:585]: i wonder the perf difference of this, also does it handle no/less params passed well?

Comment (alii) [reply src/valkey/js_valkey_functions.zig:585]: true we should check

Comment (Jarred-Sumner) [reply src/valkey/js_valkey_functions.zig:585]: it'll be the same
