### PR TITLE
rm unused PackageJSON.hash field

### LINKED ISSUE #9020: packages with names over 1024 crash the resolver
### What version of Bun is running?

_No response_

### What platform is your computer?

_No response_

### What steps can reproduce the bug?

`bun run boo`

[package.json](https://github.com/oven-sh/bun/files/14352427/package.json)

### What is the expected behavior?

to not crash

### What do you see instead?

```
thread 2355986 panic: reached unreachable code
/Users/dave/code/bun/.cache/zig/lib/std/debug.zig:342:14: 0x100329abf in assert (bun-zig)
    if (!ok) unreachable; // assertion failure
             ^
/Users/dave/code/bun/src/bun.zig:364:60: 0x1003844a3 in copy__anon_46322 (bun-zig)
    if (comptime Environment.allow_assert) std.debug.assert(dest.len >= src.len);
                                                           ^
/Users/dave/code/bun/src/resolver/package_json.zig:64:17: 0x100be4faf in generateHash (bun-zig)
        bun.copy(u8, &hashy, package_json.name);
                ^
/Users/dave/code/bun/src/resolver/package_json.zig:1022:42: 0x1007727af in parse__anon_87999 (bun-zig)
                package_json.generateHash();
```
image

### Additional information

issue found by @ryanccn, thanks for this reproduction

### PR DESCRIPTION
**Pull request by hudon**
### What does this PR do?

fix #9020 

generating package_json.hash uses a fixed buffer size which causes a crash when the package name is too long.
The hash value is never used though, so this patch removes the field altogether.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I ran `bun run boo` with the `package.json` file provided in #9020  and again with the same file after truncating the name to a legal size and ensured no crash.

### CODE REVIEW

**Review by dylan-conway — CHANGES_REQUESTED** [review]
Seems like the `PackageJSON.hash` field isn't used anywhere. Could you actually delete this code (`generateHash`, `isAppPackage`, `generate_hash` enum, ...)?

File: src/cli/run_command.zig [hunk 1]
```diff
@@ -1611,6 +1611,7 @@ pub const RunCommand = struct {
         }
 
         if (log_errors) {
+            ctx.log.print(Output.errorWriter()) catch {};
```
Comment (hudon) [inline src/cli/run_command.zig]: this is unrelated but wdyt should I keep it? otherwise any logged errors will never get seen right?

Comment (dylan-conway) [reply src/cli/run_command.zig]: It does seem correct to have this here, but it needs a test to ensure it works. I don't know a situation where it would print an error since this is the branch for failing to find the module. If you know one could you add a test? Otherwise let's delete it.

**Review by dylan-conway — APPROVED** [review]
Looks good, will merge after CI finishes
