### PR TITLE
Bun gets a new bundler

### LINKED ISSUE #74: SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries
Hello!
I'm hitting the following while trying bun on an existing nextjs project. Any suggestions on how to debug?
```
bun
[0.12ms] "node_modules.bun" - 1933 modules, 130 packages
[0.03ms] ".env.development"
[3.00ms] Bun!! v0.0.52


  Link: http://localhost:3001


[0.06ms] "node_modules.server.bun" - 1938 modules, 131 packages
[0.00ms] ".env.development"
[91.62ms] Next.js ready! (powered by Bun)
75 |         console.error(err);
76 |     });
77 |     addEventListener("fetch", async (event) => {
78 |       var route = Bun.match(event);
79 |
80 |       const PageNamespace = await import(route.filePath);
                                      ^
 SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries.
      at (anonymous) (http://localhost:3001/blob:node_modules.server.bun:80:34)
```

### LINKED ISSUE #421: `ReferenceError` on a bundle made by `rollup`
I made a [bundle](https://github.com/putoutjs/bundle) of 🐊[Putout](https://github.com/coderaiser/putout) that works on `node.js` and `deno`, but when I run with bun, I have an error:

```js
coderaiser@localcmd:~/putout-bundle$ bun bundle/putout.js
58736 | 		        .build("expression")
58737 | 		        .field("expression", def("Expression"));
58738 | 		}
58739 | 		exports.default = default_1;
58740 | 		module.exports = exports["default"];
58741 | } (jsx, jsx.exports));
      ^
 ReferenceError: Can't find variable: jsx
      at requireJsx (/Users/coderaiser/putout-bundle/bundle/putout.js:58741:3)
      at /Users/coderaiser/putout-bundle/bundle/putout.js:59884:43
      at requireMain (/Users/coderaiser/putout-bundle/bundle/putout.js:59920:42)
      at /Users/coderaiser/putout-bundle/bundle/putout.js:76015:34
      at /Users/coderaiser/putout-bundle/bundle/putout.js:76073:6
```

When I extracted this function into a file `jsx.js`:

```js
var jsx = {exports: {}};

var hasRequiredJsx;

function requireJsx () {
	if (hasRequiredJsx) return jsx.exports;
	hasRequiredJsx = 1;
	(function (module, exports) {
		Object.defineProperty(exports, "__esModule", { value: true });
		var tslib_1 = require$$0$8;
		var es_proposals_1 = (0, tslib_1.__importDefault)(requireEsProposals());
		var types_1 = (0, tslib_1.__importDefault)(requireTypes());
		var shared_1 = (0, tslib_1.__importDefault)(requireShared());
		function default_1(fork) {
		    fork.use(es_proposals_1.default);
		    var types = fork.use(types_1.default);
		    var def = types.Type.def;
		    var or = types.Type.or;
		    var defaults = fork.use(shared_1.default).defaults;
		    def("JSXAttribute")
		        .bases("Node")
		        .build("name", "value")
		        .field("name", or(def("JSXIdentifier"), def("JSXNamespacedName")))
		        .field("value", or(def("Literal"), // attr="value"
		    def("JSXExpressionContainer"), // attr={value}
		    def("JSXElement"), // attr=<div />
		    def("JSXFragment"), // attr=<></>
		    null // attr= or just attr
		    ), defaults["null"]);
		    def("JSXIdentifier")
		        .bases("Identifier")
		        .build("name")
		        .field("name", String);
		    def("JSXNamespacedName")
		        .bases("Node")
		        .build("namespace", "name")
		        .field("namespace", def("JSXIdentifier"))
		        .field("name", def("JSXIdentifier"));
		    def("JSXMemberExpression")
		        .bases("MemberExpression")
		        .build("object", "property")
		        .field("object", or(def("JSXIdentifier"), def("JSXMemberExpression")))
		        .field("property", def("JSXIdentifier"))
		        .field("computed", Boolean, defaults.false);
		    var JSXElementName = or(def("JSXIdentifier"), def("JSXNamespacedName"), def("JSXMemberExpression"));
		    def("JSXSpreadAttribute")
		        .bases("Node")
		        .build("argument")
		        .field("argument", def("Expression"));
		    var JSXAttributes = [or(def("JSXAttribute"), def("JSXSpreadAttribute"))];
		    def("JSXExpressionContainer")
		        .bases("Expression")
		        .build("expression")
		        .field("expression", or(def("Expression"), def("JSXEmptyExpression")));
		    var JSXChildren = [or(def("JSXText"), def("JSXExpressionContainer"), def("JSXSpreadChild"), def("JSXElement"), def("JSXFragment"), def("Literal") // Legacy: Esprima should return JSXText instead.
		        )];
		    def("JSXElement")
		        .bases("Expression")
		        .build("openingElement", "closingElement", "children")
		        .field("openingElement", def("JSXOpeningElement"))
		        .field("closingElement", or(def("JSXClosingElement"), null), defaults["null"])
		        .field("children", JSXChildren, defaults.emptyArray)
		        .field("name", JSXElementName, function () {
		        // Little-known fact: the `this` object inside a default function
		        // is none other than the partially-built object itself, and any
		        // fields initialized directly from builder function arguments
		        // (like openingElement, closingElement, and children) are
		        // guaranteed to be available.
		        return this.openingElement.name;
		    }, true) // hidden from traversal
		        .field("selfClosing", Boolean, function () {
		        return this.openingElement.selfClosing;
		    }, true) // hidden from traversal
		        .field("attributes", JSXAttributes, function () {
		        return this.openingElement.attributes;
		    }, true); // hidden from traversal
		    def("JSXOpeningElement")
		        .bases("Node")
		        .build("name", "attributes", "selfClosing")
		        .field("name", JSXElementName)
		        .field("attributes", JSXAttributes, defaults.emptyArray)
		        .field("selfClosing", Boolean, defaults["false"]);
		    def("JSXClosingElement")
		        .bases("Node")
		        .build("name")
		        .field("name", JSXElementName);
		    def("JSXFragment")
		        .bases("Expression")
		        .build("openingFragment", "closingFragment", "children")
		        .field("openingFragment", def("JSXOpeningFragment"))
		        .field("closingFragment", def("JSXClosingFragment"))
		        .field("children", JSXChildren, defaults.emptyArray);
		    def("JSXOpeningFragment")
		        .bases("Node")
		        .build();
		    def("JSXClosingFragment")
		        .bases("Node")
		        .build();
		    def("JSXText")
		        .bases("Literal")
		        .build("value", "raw")
		        .field("value", String)
		        .field("raw", String, function () {
		        return this.value;
		    });
		    def("JSXEmptyExpression")
		        .bases("Node")
		        .build();
		    def("JSXSpreadChild")
		        .bases("Node")
		        .build("expression")
		        .field("expression", def("Expression"));
		}
		exports.default = default_1;
		module.exports = exports["default"];
} (jsx, jsx.exports));
	return jsx.exports;
}
```

And run with `bun jsx.js` everything works fine, so maybe the reason is TO MANY VARIABLES in global scope, or something like this.

### LINKED ISSUE #875: SyntaxError when using Material-UI (@mui) components (includes emotion)
### Version

0.1.5

### Platform

Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Create a new bun project using react template
```bash
bun create react
cd react
bun add @mui/material @emotion/react @emotion/styled
```
Update `src/App.jsx` (use `@mui/material/Button` component):
```jsx
import Button from "@mui/material/Button";

function App() {
  return (
    <Button variant="contained">Mui Button</Button>
  );
}

export default App;
``` 
Start the `bun` server and open the browser
```bash
bun dev
open http://localhost:3000
```
Open dev tools and look for the following error:
```
Uncaught SyntaxError: Export 'jsx' is not defined in module
```
error1

### How often does it reproduce? Is there a required condition?

_No response_

### What is the expected behavior?

Material-UI button element without console errors:
button

### What do you see instead?

SyntaxError in the console

### Additional information

There is a reported bug for the same issue on the discord channel but I couldn't find a related GitHub issue.

### LINKED ISSUE #1032: Cannot access 'default' before initialization
### Version

0.1.7

### Platform

macOS 12.5.0 (Apple Silicon)

### What steps will reproduce the bug?

1. `bun create react my-app`
2. `bun a @nextui-org/react` 
3. Add import from package `import { NextUIProvider } from '@nextui-org/react'` to index
4. Run `bun dev` and observe error.

### How often does it reproduce? Is there a required condition?

100% of the time that `NextUIProvider` is imported. Running this is a node environment works.

### What is the expected behavior?

Package import works as expected without error

### What do you see instead?

**Cannot access 'default' before initialization**
In `lr` – node_modules.bun:7:7023
```bun
`+d.line_text.trim()),a=a.trimRight()+`
 `+u,o(a.trim())}console.groupEnd()}verbose=!1;handleError=t=>{O.error("Websocket error",t.error),this.reconnect===0&&this.debouncedReconnect()};handleBuildSuccess(t,o){let a=Ke(t),v=this.builds.get(a.id)||-1/0;if(v>a.from_timestamp+4){this.verbose&&O.debug(`Ignoring outdated update for "${a.module_path}".
  Expected: >=`,v,`
   Received:`,a.from_timestamp);return}var u=t.data.byteOffset+t.index+a.blob_length<=t.data.buffer.byteLength?new Uint8Array(t.data.buffer,t.data.byteOffset+t.index,a.blob_length):He||=new Uint8Array(0);if(a.loader===I.css)return f.clear(),this.needsConsoleClear&&(console.clear(),this.needsConsoleClear=!1),this.loaders.css.handleBuildSuccess(u,a,o);let d=a.id,p=this.indexOfModuleId(d);if(p===-1){this.verbose&&O.debug("Skipping reload for unknown module id:",d);return}if(this.verbose){var _=w.dependencies.modules[p].file_path;_.startsWith(this.cwd)&&(_=_.substring(this.cwd.length)),O.debug("Preparing to reload",_)}var E=t.index+a.blob_length,R=0;E>t.data.length&&E>4&&(E=t.data.length-4),E>4&&t.data.length>=E+4&&(new Uint8Array(this.hashBuffer.buffer).set(t.data.subarray(E,E+4)),R=this.hashBuffer[0]);var x=new S(a.id,p,a,u,1,R||0);u=null,x.timings.notify=o-a.from_timestamp,f.clear(),x.run().then(([P,D])=>{var W=P.file_path;W.startsWith(this.cwd)&&(W=W.substring(this.cwd.length)),this.needsConsoleClear&&(console.clear(),this.needsConsoleClear=!1),O.log(`[${e(D.total)}ms] Reloaded`,W)},P=>{if(!(typeof P=="object"&&P&&P instanceof L)){O.error("Hot Module Reload failed!",P);debugger}})}performFullReload(){typeof location<"u"&&(this.socket.readyState===this.socket.OPEN&&(this.reconnect=1,this.socket.close()),location.reload())}handleFileChangeNotification(t,o,a){let v=Je(t),u="";switch(v.loader){case I.css:{u=this.loaders.css.filePath(v);break}case I.js:case I.jsx:case I.tsx:case I.ts:case I.json:{let d=w.dependencies.graph.subarray(0,w.dependencies.graph_used).indexOf(v.id);d>-1&&(u=w.dependencies.modules[d].file_path);break}default:return}return this.handleFileChangeNotificationBase(o,v,u,a)}handleFileChangeNotificationBase(t,o,a,v){if(!(a&&a.length>0)){this.verbose&&O.debug("Unknown module changed, skipping");return}if((this.builds.get(o.id)||-1/0)>t){O.debug(`Received stale update for ${a}`);return}let d=2;switch(o.loader){case I.css:{this.builds.set(o.id,t),o.id=this.loaders.css.bundleId(),this.builds.set(o.id,t),d=1;break}case I.js:case I.jsx:case I.json:case I.ts:case I.tsx:{switch(this.javascriptReloader){case J.disable:break;case J.fast_refresh:{this.builds.set(o.id,t),d=1;break}case J.live:{d=0;break}}break}}switch(d){case 1:{v&&!this.buildCommandBufWithFilePath&&(this.buildCommandBufWithFilePath=new Uint8Array(4096+256));let p=v?this.buildCommandBufWithFilePath:this.buildCommandBuf;if(p[0]=v?ge.build_with_file_path:ge.build,this.buildCommandUArray[0]=t,p.set(this.buildCommandUArrayEight,1),this.buildCommandUArray[0]=o.id,p.set(this.buildCommandUArrayEight,5),v){se||(se=new TextEncoder),this.buildCommandUArray[0]=a.length,p.set(this.buildCommandUArrayEight,9);let _=se.encodeInto(a,p.subarray(13));this.socket.send(this.buildCommandBufWithFilePath.subarray(0,13+_.written))}else this.socket.send(this.buildCommandBuf);this.verbose&&O.debug(`Requesting update for ${a}`);break}case 0:{this.performFullReload();break}}}buildCommandBuf=new Uint8Array(9);buildCommandUArray=new Uint32Array(1);buildCommandUArrayEight=new Uint8Array(this.buildCommandUArray.buffer);hashBuffer=new Uint32Array(1);buildCommandBufWithFilePath;handleOpen=t=>{globalThis.clearTimeout(this.nextReconnectAttempt),setTimeout(()=>{this.socket&&this.socket.readyState==this.socket.OPEN&&(globalThis.clearTimeout(this.nextReconnectAttempt),this.reconnectDelay=16)},16)};handleMessage=t=>{let o=new Uint8Array(t.data),a=new te(o),v=$e(a),u=new te(o.subarray(a.index));switch(v.kind){case K.build_fail:{this.handleBuildFailure(u,v.timestamp);break}case K.build_success:{this.handleBuildSuccess(u,v.timestamp);break}case K.resolve_file:{let{id:_}=ze(u),E=this.builds.get(_)||0;if(E==0&&S.VERBOSE){O.debug(`Unknown module? ${_}`);return}let R=w.dependencies.graph.subarray(0,w.dependencies.graph_used).indexOf(_);var d="",p=I.js;if(R>-1)d=w.dependencies.modules[R].file_path;else{let x=this.loaders.css.findCSSLinkTag(_);x&&x.file.length&&(d=x.file)}if(!d||d.length===0){S.VERBOSE&&O.debug(`Unknown module? ${_}`);return}switch(d.substring(d.lastIndexOf("."))){case".css":{p=I.css;break}case".mjs":case".cjs":case".js":{p=I.js;break}case".json":{p=I.json;break}case".cts":case".mts":case".ts":{p=I.ts;break}case".tsx":{p=I.tsx;break}case".jsx":{p=I.jsx;break}default:{p=I.file;break}}this.handleFileChangeNotificationBase(E,{id:_,loader:p},d,!0);break}case K.file_change_notification:{this.handleFileChangeNotification(u,v.timestamp,!1);break}case K.file_change_notification_with_hint:{this.handleFileChangeNotification(u,v.timestamp,!0);break}case K.welcome:{let _=performance.now();this.hasWelcomed=!0;let E=De(u);switch(this.epoch=E.epoch,this.javascriptReloader=E.javascriptReloader,this.cwd=E.cwd,this.assetPrefixPath=E.assetPrefix,this.javascriptReloader){case J.fast_refresh:{O.log("HMR connected in",e(_-Q),"ms");break}case J.live:{O.log("Live reload connected in",e(_-Q),"ms");break}default:{O.log("Bun connected in",e(_-Q),"ms");break}}Q=_,this.epoch||O.warn("Internal HMR error");break}}};disableReconnect=!1;handleClose=t=>{this.reconnect!==0||this.disableReconnect||this.debouncedReconnect()}}let U=0;class L extends Error{constructor(t){super(t)}}class S{module_id=0;module_index=0;build;hash=0;timings={notify:0,decode:0,import:0,callbacks:0,total:0,start:0};static VERBOSE=!1;bytes;reloader;constructor(t,o,a,v,u,d){this.module_id=t,this.module_index=o,this.build=a,this.bytes=v,this.reloader=u,this.hash=d}async run(){U++;let t;try{t=await this._run()}finally{U--}return t}async _run(){let t=U,o=performance.now(),a=w.dependencies,v=w.dependencies.graph_used;var u=w.dependencies.modules.length>this.module_index&&w.dependencies.modules[this.module_index];w.dependencies=a.fork(this.module_index);var d="";let p=this.build.module_path.length>0&&this.build.module_path[0]==="/"?this.build.module_path.substring(1):this.build.module_path,_=this.hash>0&&this.build.module_path.length>0?`
//# sourceMappingURL=${globalThis.location.origin}/${p}.map?b=${this.hash.toString(16)}`:"";try{let P=new Blob(_.length>0?[this.bytes,_]:[this.bytes],{type:"text/javascript"});d=URL.createObjectURL(P),w.dependencies.blobToID.set(d,this.module_id),await import(d),this.bytes=null,URL.revokeObjectURL(d),this.timings.import=performance.now()-o}catch(P){throw w.dependencies=a,URL.revokeObjectURL(d),this.bytes=null,"__BunRenderHMRError"in globalThis&&globalThis.__BunRenderHMRError(P,u.file_path,u.id),u=null,P}w.dependencies.graph_used===this.module_index&&(w.dependencies.graph_used=v),d="",this.bytes=null,S.VERBOSE&&O.debug("Re-imported",w.dependencies.modules[this.module_index].file_path,"in",e(this.timings.import),". Running callbacks");let E=performance.now(),R=u?new Set(u.additional_updaters):new Set;try{switch(this.reloader){case 1:{let P=!1,D=u&&u.previousVersion&&u.previousVersion.id===u.id&&u.hasSameExports(u.previousVersion);var x=w.dependencies.modules[this.module_index];u&&u._update!==x._update&&(D?(u.previousVersion&&(x.previousVersion=u.previousVersion),x.additional_updaters=R):(u.boundUpdate||=u.update.bind(u),x.additional_updaters?x.additional_updaters.add(u.boundUpdate):x.additional_updaters=new Set([u.boundUpdate]),x.previousVersion=u));let W=Math.min(this.module_index+1,w.dependencies.graph_used);for(let Z=0;Z<=W;Z++){let l=w.dependencies.modules[Z];if(!l)continue;let n=!1;l.exports.__hmrDisable||(typeof l.dispose=="function"&&(l.dispose(),n=!0),typeof l.accept=="function"&&(l.accept(),n=!0),l.isRefreshBoundary&&(P=!0),n||l.update())}if(U===t&&P)c.RefreshRuntime.performReactRefresh(),D&&(u.previousVersion=null);else if(U===t)c.performFullRefresh();else return Promise.reject(new L(`Expected pendingUpdateCount: ${t} but received: ${U}`));break}}}catch(P){throw w.dependencies=a,w.dependencies.modules[this.module_index].additional_updaters=R,P}return this.timings.callbacks=performance.now()-E,S.VERBOSE&&O.debug("Ran callbacks",w.dependencies.modules[this.module_index].file_path,"in",e(this.timings.callbacks),"ms"),a=null,this.timings.total=this.timings.import+this.timings.callbacks+this.timings.notify,Promise.resolve([w.dependencies.modules[this.module_index],this.timings])}}class C{modules;graph;graph_used=0;blobToID=new Map;getModuleByBlobURL(t){let o=this.blobToID.get(t);return Number.isFinite(o)&&this.getModuleByID(o)}getFilePathFromBlob(t){let o=this.getModuleByBlobURL(t);if(!o)return null;let a=o.file_path;return a.startsWith(g.client.cwd)&&(a=a.substring(g.client.cwd.length)),a}getModuleByID(t){let o=this.graph.indexOf(t);return o>-1?this.modules[o]:null}loadDefaults(){this.modules=new Array(32),this.graph=new Uint32Array(32),this.graph_used=0}static loadWithDefaults(){let t=new C;return t.loadDefaults(),t}fork(t){let o=new C;return o.modules=this.modules.slice(),o.graph_used=t,o.graph=this.graph.slice(),o}}class w{constructor(t,o){if(this.id=t,this.file_path=o,Object.defineProperty(this,"name",{get(){return this.file_path},configurable:!1,enumerable:!1}),w.dependencies||(w.dependencies=w._dependencies),this.graph_index=w.dependencies.graph_used++,w.dependencies.graph.length<=this.graph_index){let a=new Uint32Array(w.dependencies.graph.length*4);a.set(w.dependencies.graph),w.dependencies.graph=a,w.dependencies.modules.length=a.length}w.dependencies.modules[this.graph_index]=this,w.dependencies.graph[this.graph_index]=this.id}previousVersion=null;hasSameExports(t){let o=Object.keys(this.exports),a=Object.keys(t.exports);if(o.length!==a.length)return!1;for(let v=0;v<o.length;v++)if(o[v]!==a[v])return!1;return!0}#e;get _update(){return this.#e}set _update(t){this.#e=t;var o=_e.get(this.file_path)}boundUpdate;update(){var t=_e.get(this.id);if(t?.length)for(let o of t)o(this.exports);this._update(this.exports)}static _dependencies=C.loadWithDefaults();exportAll(t){for(let o in t)this._exports[o]=t[o],Object.defineProperty(this.exports,o,{get:this._exports[o],configurable:!0,enumerable:!0})}static dependencies;file_path;_load=function(){};id=0;graph_index=0;_exports={};exports={}}class j extends w{constructor(t,o,a){super(t,o),this.refreshRuntimeBaseID=(this.file_path.length>7?this.id.toString(36):this.file_path)+"/",c.RefreshRuntime=c.RefreshRuntime||a,c.hasInjectedFastRefresh||(a.injectIntoGlobalHook(globalThis),c.hasInjectedFastRefresh=!0)}refreshRuntimeBaseID;isRefreshBoundary=!1;$r_(t,o){c.RefreshRuntime.register(t,this.refreshRuntimeBaseID+o)}$r(t){!c.RefreshRuntime.isLikelyComponentType(t)||this.$r_(t,t.name||t.displayName)}exportAll(t){super.exportAll(t);var o=!1,a=!0;for(let v in t){if(v==="__esModule")continue;o=!0;let u=t[v]();if(u&&typeof u=="function"&&!("name"in u)&&Object.isExtensible(u)){let d={get(){return v},enumerable:!1,configurable:!0};try{Object.defineProperties(u,{name:d,displayName:d})}catch{}}if(!c.RefreshRuntime.isLikelyComponentType(u)){a=!1;continue}this.$r_(u,v)}this.isRefreshBoundary=o&&a}loaded(t){this._update=t}}O={debug(...k){console.debug(...k)},error(...k){console.error(...k)},log(...k){console.log(...k)},warn(...k){console.warn(...k)}},Ye=w,Ze=j,Qe=g,Xe=Y,"document"in globalThis&&document.addEventListener("onimportcss",g.onCSSImport,{passive:!0}),globalThis.__BUN=g,globalThis.__BUN_ERROR=f}var se,me,Q,He,_e,O;var be,er,rr;{let e;(S=>(S[S.entry_point=0]="entry_point",S[S.stmt=1]="stmt",S[S.require=2]="require",S[S.dynamic=3]="dynamic",S[S.require_resolve=4]="require_resolve",S[S.at=5]="at",S[S.at_conditional=6]="at_conditional",S[S.url=7]="url"))(e||={});class r extends Error{constructor(c){super(c.message),this.name=c.name,this.data=c}data;get position(){return this.data.position}get[Symbol.toStringTag](){return`${this.name}: ${this.message}`}}class i extends r{constructor(c){super(c),this.name=c.name,this.data=c}data;get importKind(){return this.data.importKind}get specifier(){return this.data.specifier||""}}er=i,be=r,rr=e}var ft=Symbol.for,nr=Object.create,Lr=Object.getOwnPropertyDescriptors,H=Object.defineProperty,Or=Object.getPrototypeOf,ar=Object.prototype.hasOwnProperty,Pr=Object.getOwnPropertyNames,Tr=Object.getOwnPropertyDescriptor,or=e=>H(e,"__esModule",{value:!0,configurable:!0}),Cr=(e,r,i)=>{for(let s in i)ar.call(e,s)||H(e,s,{get:()=>r()[i[s]],enumerable:!0,configurable:!0});return e},qr=e=>ur(or(H(e!=null?nr(Or(e)):{},"default",e&&e.__esModule&&"default"in e?{get:()=>e.default,enumerable:!0,configurable:!0}:{value:e,enumerable:!0,configurable:!0})),e),tr=Symbol.for("CommonJSTransformed"),Se=Symbol.for("CommonJS"),ke=(e,r)=>{var i,s=!1;let c=function(){if(s)return i.exports;s=!0,e((i={exports:{}},i),i.exports);let f=typeof i.exports;return(f==="object"||f==="function")&&!i.exports[tr]&&Object.isExtensible(i.exports)&&(Object.defineProperty(i.exports,tr,{value:!0,enumerable:!1,configurable:!1}),"default"in i.exports||Object.defineProperty(i.exports,"default",{get(){return i.exports},set(A){if(A!==i.exports)return i.exports=A,!0},enumerable:!1,configurable:!0})),i.exports};return c[Se]=!0,c},Fr=ke,lr=e=>e!=null&&typeof e=="object"&&(e.default&&e.default[Se]||e[Se]),sr=e=>lr(e)?e.default():e;sr.d=e=>e;var Nr=ke,jr=(e,r)=>(Object.defineProperty(e,"name",{value:r,enumerable:!1,configurable:!0}),e),Vr=(e,r)=>{for(var i in r)H(e,i,{get:r[i],enumerable:!0,configurable:!0,set:s=>r[i]=()=>s})},Wr=(e,r)=>{for(var i in r)H(e,i,{get:()=>r[i],set:s=>r[i]=s,enumerable:!0,configurable:!0})},$r=(e,r)=>{H(e,"default",{get:()=>r,set:i=>r=i,enumerable:!0,configurable:!0})},ur=(e,r,i)=>{if(r&&typeof r=="object"||typeof r=="function")for(let s of Pr(r))!ar.call(e,s)&&s!=="default"&&H(e,s,{get:()=>r[s],configurable:!0,enumerable:!(i=Tr(r,s))||i.enumerable});return e};function ir(e){for(let r in e)return!0;return!1}function Dr(e,r){var i=nr(r,Lr(e));for(let s in r)i[s]===void 0&&(i[s]=r[s]);return i}var Jr=(e,r)=>ir(r)?ir(e)?Dr(e,r):r:e;var fr=qe(dr());var Pe={};Te(Pe,{_getMountedRootCount:()=>rt,collectCustomHooksForSignature:()=>vr,createSignatureFunctionForTransform:()=>tt,findAffectedHostInstances:()=>Xr,getFamilyByID:()=>Zr,getFamilyByType:()=>Qr,hasUnrecoverableErrors:()=>et,injectIntoGlobalHook:()=>br,isLikelyComponentType:()=>it,performReactRefresh:()=>Yr,register:()=>Ue,setSignature:()=>ve});var Ie="for"in Symbol?Symbol.for("react.forward_ref"):60112,Re="for"in Symbol?Symbol.for("react.memo"):60115,Le=typeof WeakMap=="function"?WeakMap:Map,Ee=new Map,Ae=new Le,b=new Le,Me=new Le,ue=[],de=new Map,ce=new Map,G=new Set,X=new Set,ie=typeof WeakMap=="function"?new WeakMap:null,fe=!1;function he(e){if(e.fullKey!==null)return e.fullKey;let r=e.ownKey,i;try{i=e.getCustomHooks()}catch{return e.forceReset=!0,e.fullKey=r,r}for(let s=0;s<i.length;s++){let c=i[s];if(typeof c!="function")return e.forceReset=!0,e.fullKey=r,r;let B=b.get(c);if(B===void 0)continue;let f=he(B);B.forceReset&&(e.forceReset=!0),r+=`
/*                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ^ happend here                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
---
`+f}return e.fullKey=r,r}function Kr(e,r){let i=b.get(e),s=b.get(r);return i===void 0&&s===void 0?!0:!(i===void 0||s===void 0||he(i)!==he(s)||s.forceReset)}function cr(e){return e.prototype&&e.prototype.isReactComponent}function Gr(e,r){return cr(e)||cr(r)?!1:!!Kr(e,r)}function zr(e){return Me.get(e)}function Hr(e){let r=new Map;return e.forEach((i,s)=>{r.set(s,i)}),r}function hr(e){let r=new Set;return e.forEach(i=>{r.add(i)}),r}function Oe(e,r){try{return e[r]}catch{return}}function Yr(){if(ue.length===0||fe)return null;fe=!0;try{let e=new Set,r=new Set,i=ue;ue=[],i.forEach(U=>{let[L,S]=U,C=L.current;Me.set(C,L),Me.set(S,L),L.current=S,Gr(C,S)?r.add(L):e.add(L)});let s={updatedFamilies:r,staleFamilies:e};de.forEach(U=>{U.setRefreshHandler(zr)});let c=!1,B=null,f=hr(X),A=hr(G),g=Hr(ce);if(f.forEach(U=>{let L=g.get(U);if(L===void 0)throw new Error("Could not find helpers for a root. This is a bug in React Refresh.");if(X.has(U),ie===null||!ie.has(U))return;let S=ie.get(U);try{L.scheduleRoot(U,S)}catch(C){c||(c=!0,B=C)}}),A.forEach(U=>{let L=g.get(U);if(L===void 0)throw new Error("Could not find helpers for a root. This is a bug in React Refresh.");G.has(U);try{L.scheduleRefresh(U,s)}catch(S){c||(c=!0,B=S)}}),c)throw B;return s}finally{fe=!1}}function Ue(e,r){if(e===null||typeof e!="function"&&typeof e!="object"||Ae.has(e))return;let i=Ee.get(r);if(i===void 0?(i={current:e},Ee.set(r,i)):ue.push([i,e]),Ae.set(e,i),typeof e=="object"&&e!==null)switch(Oe(e,"$$typeof")){case Ie:Ue(e.render,r+"$render");break;case Re:Ue(e.type,r+"$type");break}}function ve(e,r){let i=arguments.length>2&&arguments[2]!==void 0?arguments[2]:!1,s=arguments.length>3?arguments[3]:void 0;if(b.has(e)||b.set(e,{forceReset:i,ownKey:r,fullKey:null,getCustomHooks:s||(()=>[])}),typeof e=="object"&&e!==null)switch(Oe(e,"$$typeof")){case Ie:ve(e.render,r,i,s);break;case Re:ve(e.type,r,i,s);break}}function vr(e){let r=b.get(e);r!==void 0&&he(r)}function Zr(e){return Ee.get(e)}function Qr(e){return Ae.get(e)}function Xr(e){let r=new Set;return G.forEach(i=>{let s=ce.get(i);if(s===void 0)throw new Error("Could not find helpers for a root. This is a bug in React Refresh.");s.findHostInstancesForRefresh(i,e).forEach(c=>{r.add(c)})}),r}function br(e){let r=e.__REACT_DEVTOOLS_GLOBAL_HOOK__;if(r===void 0){let B=0;e.__REACT_DEVTOOLS_GLOBAL_HOOK__=r={renderers:new Map,supportsFiber:!0,inject(f){return B++},onScheduleFiberRoot(f,A,g){},onCommitFiberRoot(f,A,g,U){},onCommitFiberUnmount(){}}}if(r.isDisabled){console.warn("Something has shimmed the React DevTools global hook (__REACT_DEVTOOLS_GLOBAL_HOOK__). Fast Refresh is not compatible with this shim and will be disabled.");return}let i=r.inject;r.inject=function(B){let f=i.apply(this,arguments);return typeof B.scheduleRefresh=="function"&&typeof B.setRefreshHandler=="function"&&de.set(f,B),f},r.renderers.forEach((B,f)=>{typeof B.scheduleRefresh=="function"&&typeof B.setRefreshHandler=="function"&&de.set(f,B)});let s=r.onCommitFiberRoot,c=r.onScheduleFiberRoot||(()=>{});r.onScheduleFiberRoot=function(B,f,A){return fe||(X.delete(f),ie!==null&&ie.set(f,A)),c.apply(this,arguments)},r.onCommitFiberRoot=function(B,f,A,g){let U=de.get(B);if(U!==void 0){ce.set(f,U);let L=f.current,S=L.alternate;if(S!==null){let C=S.memoizedState!=null&&S.memoizedState.element!=null&&G.has(f),w=L.memoizedState!=null&&L.memoizedState.element!=null;!C&&w?(G.add(f),X.delete(f)):C&&w||(C&&!w?(G.delete(f),g?X.add(f):ce.delete(f)):!C&&!w&&g&&X.add(f))}else G.add(f)}return s.apply(this,arguments)}}function et(){return!1}function rt(){return G.size}function tt(){let e,r,i=!1;return function(s,c,B,f){if(typeof c=="string")return e||(e=s,r=typeof f=="function"),s!=null&&(typeof s=="function"||typeof s=="object")&&ve(s,c,B,f),s;!i&&r&&(i=!0,vr(e))}}function it(e){switch(typeof e){case"function":{if(e.prototype!=null){if(e.prototype.isReactComponent)return!0;let i=Object.getOwnPropertyNames(e.prototype);if(i.length>1||i[0]!=="constructor"||e.prototype.__proto__!==Object.prototype)return!1}let r=e.name||e.displayName;return typeof r=="string"&&/^[A-Z]/.test(r)}case"object":{if(e!=null)switch(Oe(e,"$$typeof")){case Ie:case Re:return!0;default:return!1}return!1}default:return!1}}globalThis.process||={env:{},cwd(){return"/bun-fake-dir/"}};return kr(nt);})();
// ---
```
Stack trace:
```js

  `lr` node_modules.bun:7:7023
  `sr` node_modules.bun:7:7060
  λ()  node_modules/@nextui-org/react/esm/textarea/textarea.js:9:21
```
Info:
  > bun v0.1.7
  > macOS 12.5.0 (Apple Silicon)
  > User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36
  > Pathname: /


### Additional information

Repo for repro: https://github.com/hellsan631/mycraft2

### LINKED ISSUE #1169: Bundling source and deps into top-level js
### What is the problem this feature will solve?

I'm missing how to achieve simple bundler functionality.  Looks like most of the machinery is there, or maybe this is just a doc bug.  GH docs seem to indicate bundling is possible "While you could use bun's bundler & transpiler separately to build for browsers or node".

I asked around on discord and wasn't clear how.  

### What is the feature you are proposing to solve the problem?

I'd like to specify an entry point and and output bundle name so that I can load it into a host index.html.
```
# index.jsx
import React from 'react'
import {render} from 'react-dom'
function App() { return <h1>Hello Whirled!</h1> }
render(<App/>)
```
```
> bun bun --entry=src/index.jsx --out=bun-bundle.js
```
and have this operate as a top-level modules in HTML:
```
<script type="module" src="./bun-bundle.js"></script>
```
And have that index.jsx evaluated such that the render is called and you see **Hello Whirled!** in a static serving env.

### What alternatives have you considered?

Currently, bun bun and the exported code is only the modules
```
bun bun src/index.jsx && ./node_modules.bun > public/node_modules.js
```
But then that means I need to bundle my jsx with a different tool and usually huge set of deps and that I'm looking to get rid of by using bun.

Great project so far!

### LINKED ISSUE #1270: `Unexpected keyword "export"`, when importing Sentry
### Version

v0.1.13 (canary e94e6d8d)

### Platform

Linux spiffytop 5.19.8-1-default #1 SMP PREEMPT_DYNAMIC Thu Sep 8 10:26:47 UTC 2022 (0330383) x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

sentry-test.js
```js
import Sentry from '@sentry/node';
console.log(Sentry);
```

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

Successful import

### What do you see instead?

```
$ bun run sentry-test.js
[0.05ms] ".env"
1 | export { _asyncNullishCoalesce } from './_asyncNullishCoalesce.js';
2 | export { _asyncOptionalChain } from './_asyncOptionalChain.js';
3 | export { _asyncOptionalChainDelete } from './_asyncOptionalChainDelete.js';
4 | export { _createNamedExportFrom } from './_createNamedExportFrom.js';
   ^
TypeError: Unexpected keyword 'export' while parsing module "/home/spiffytech/Documents/bootspoon/impermalink/node_modules/@sentry/utils/esm/buildPolyfills/_createNamedExportFrom.js"
      at /home/spiffytech/Documents/bootspoon/impermalink/node_modules/@sentry/utils/esm/buildPolyfills/index.js:4:0
      at /home/spiffytech/Documents/bootspoon/impermalink/node_modules/@sentry/utils/esm/index.js:5:0
      at /home/spiffytech/Documents/bootspoon/impermalink/node_modules/@sentry/core/esm/integrations/index.js:1:0
```

### Additional information
Jarred's remarks from Discord:

> There's a few reasons why this module wouldn't work but it is interesting that this is happening at the top-level of this file
>
> bun hasn't implemented the module for async local storage
>
> which Sentry likely depends on
>
> this particular bug though looks like it did an esm -> cjs transform but for some reason there was leftover export statements
>
> this is the kind of code that breaks the most in bun's transpiler right now -- other transpilers 

```
$ cat /home/spiffytech/Documents/bootspoon/impermalink/node_modules/@sentry/utils/esm/buildPolyfills/_createNamedExportFrom.js
/**
 * Copy a property from the given object into `exports`, under the given name.
 *
 * Adapted from Sucrase (https://github.com/alangpierce/sucrase)
 *
 * @param obj The object containing the property to copy.
 * @param localName The name under which to export the property
 * @param importedName The name under which the property lives in `obj`
 */
function _createNamedExportFrom(obj, localName, importedName) {
  exports[localName] = obj[importedName];
}

// Sucrase version:
// function _createNamedExportFrom(obj, localName, importedName) {
//   Object.defineProperty(exports, localName, {enumerable: true, get: () => obj[importedName]});
// }

export { _createNamedExportFrom };
//# sourceMappingURL=_createNamedExportFrom.js.map
```

### LINKED ISSUE #1724: Transpiler must rename symbols banned in strict mode
Examples:
- `interface`
- `public`

This currently breaks `serve` when used with `bunx`

```zig
❯ bunx --bun serve
341 | 		break;
342 | 	}
343 |
344 | 	if (entry) {
345 | 		const {public} = config;
346 | 		config.public = path.relative(cwd, (public ? path.resolve(entry, public) : entry));
     ^
SyntaxError: Cannot use abbreviated destructuring syntax for reserved name 'public' in strict mode.
      at /usr/lib/node_modules/serve/bin/serve.js:346:2
```

Since bun only supports ESM & strict mode, this is necessary to do.

### LINKED ISSUE #2221: bun bundler segmentation fault
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 6.1.12-artix1-1 x86_64 unknown

### What steps can reproduce the bug?

Create empty project, install any library - svelte in this case

Create index.ts
```ts
import * as svelte from "svelte";

// i know this is is not the right syntax
export svelte;
```
run `bun bun index.ts`

### What is the expected behavior?

Error message

### What do you see instead?

segmentation fault

### Additional information

_No response_

### LINKED ISSUE #2244: Bun's bundler is stuck when trying to load node_modules.bun
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 6.1.12-artix1-1 x86_64 unknown

### What steps can reproduce the bug?

Just run `bun bun` in latest canary release, it will get stuck
But `node_modules.bun` must exist

### What is the expected behavior?

Bundle dependencies

### What do you see instead?

Nothing, it's stuck

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
## What is this?

This implements a new JavaScript bundler designed for production bundling targeting browsers & Bun's runtime. It's mostly based on esbuild's implementation. It outputs ESM and supports code-splitting. Unlike bun's current bundler, this bundles the entire app (not just node_modules), which makes it suitable for production. It also fixes many issues with CommonJS <> ESM interop and some transpiler edgecases due to (previously) lack of correct symbol renaming.

This PR is still very much a work-in-progress. It is far enough along to produce bundled output, but not far enough along yet for actual usage or benchmarking.

#### Breaking changes

This PR deprecates the current version of `bun bun` and replaces it with this new bundler. We may also rename `bun bun` to `bun bundle` or `bun build` (not decided yet). **`node_modules.bun` files will no longer be generated**. To smooth the transition, we will alias `bun bun` to the new command for at least one minor version.

### Important missing features

Large missing features:
- [ ] Source Maps
- [ ] JavaScript API
- [x] React Server Components

Bun's runtime specifically:
- [ ] Expose JavaScript API
- [ ] Read `// @bun`, to prevent bundling in the runtime twice
- [ ] Inline `import.meta` object
- [ ] Enable bundling by default in the JavaScript runtime

Must TODO before merging:
- [x] Port esbuild's tests
- [ ] Free memory when building from JS API (right now it leaks)
- [ ] Source Maps
- [ ] More granular parallelization than chunks. 
- [ ] Event loop integration with JS
- [ ] Incremental mode suitable for development
- [ ] IIFE output format

Fixes https://github.com/oven-sh/bun/issues/1968 Fixes https://github.com/oven-sh/bun/issues/1961 Fixes #1032 Fixes #74 Fixes #1724 Fixes #1270 Fixes #875 (more correctly) Fixes #2244 Fixes #2221 Fixes #1169 Fixes #421 (more correctly)

### CODE REVIEW

File: src/runtime.js [hunk 1]
```diff
@@ -7,56 +8,101 @@ var __hasOwnProp = Object.prototype.hasOwnProperty;
...
+      __defProp(to, key, {
+        get: () => mod[key],
+        enumerable: true,
+      });
+
+  return to;
+};
+
+/* @__PURE__ */
+var moduleCache = new /* @__PURE__ */ WeakMap();
```
Comment (kzc) [inline src/runtime.js]: The pure annotations above are in the wrong place. They must directly precede a function call or `new`.

```sh
$ echo '/*@__PURE__*/ var obj = new /*@__PURE__*/ FooBar();' | uglify-js --toplevel -bmc
new FooBar();

$ echo '/*@__PURE__*/ var obj = new /*@__PURE__*/ FooBar();' | rollup --silent
new  FooBar();

$ echo '/*@__PURE__*/ var obj = new /*@__PURE__*/ FooBar();' | esbuild --bundle --minify
(()=>{var o=new FooBar;})();
```

```sh
$ echo 'var obj = /*@__PURE__*/ new FooBar();' | uglify-js --toplevel -bmc

$ echo 'var obj = /*@__PURE__*/ new FooBar();' | rollup --silent

$ echo 'var obj = /*@__PURE__*/ new FooBar();' | esbuild --bundle --minify
(()=>{})();
```

Side question: Any way `bun` could accept javascript input from stdin?

/cc @alexlamsl

Comment (alexlamsl) [reply src/runtime.js]: > Any way `bun` could accept javascript input from stdin?

I'd certainly vote for that &minus; makes hand-testing of cross-platform compatibility a _lot_ easier :nerd_face:

Will look into that during my next spare cycles...

**Comment by Jarred-Sumner** [comment]
I'm about to merge this. It's not actually ready yet, but there shouldn't be breaking changes to the runtime in this code. Just breaking changes to `bun bun`.
