### PR TITLE
Fixes #7736

### LINKED ISSUE #7736: Large maps that are equal aren't comparing equal
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```ts
//
// NOTE:
// - At <= 912 elements, the test always passes
// - At > 912 elements, the test starts failing significantly more (though not _always_)
//
const MAP_SIZE = 913;

function* genpairs() {
  for (let i = 0; i < MAP_SIZE; i++) {
    yield ["k" + i, 1] as const;
  }
}

test("bug", () => {
  const x = new Map(genpairs());
  const y = new Map(genpairs());
  expect(x).toEqual(y);
});
```

### What is the expected behavior?

No matter how large the maps are that are being compared, I'd expect this statement to not fail as long as their contents are equal.

### What do you see instead?

The test starts failing most of the time when comparing maps larger than 912 elements.

### Additional information

Here is a repo with a clean/minimal replication:

https://github.com/nvie/clean-project/tree/map-equals-bug (not `main` branch)

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

- Fixes #7736
- Makes `expect(map1).toEqual(map2)` something like 50x faster

### How did you verify your code works?

Regression tests

### CODE REVIEW

File: src/bun.js/bindings/bindings.cpp [hunk 1]
```diff
@@ -524,8 +533,59 @@ bool Bun__deepEquals(JSC__JSGlobalObject* globalObject, JSValue v1, JSValue v2,
...
+                    if (bucket2ptr && (*bucket2ptr)->deleted()) {
+                        bucket2ptr = nullptr;
+                    }
+
+                    if (!bucket2ptr) {
+                        auto findDeepEqualKey = [&]() -> bool {
+                            auto* bucket = set2->head();
+                            while (bucket) {
+                                if (!bucket->deleted()) {
+                                    auto key2 = bucket->key();
```
Comment (dylan-conway) [inline src/bun.js/bindings/bindings.cpp:557]: RETURN_IF_EXCEPTION(*scope, false);

**Review by dylan-conway — APPROVED** [review]
