### PR TITLE
Fix copying UTF-16 -> UTF-8 sometimes causing invalid UTF-8 bytes

### LINKED ISSUE #20564: Incorrect `console.log()` output for long UTF-8 string
### What version of Bun is running?

1.2.17+282dda62c

### What platform is your computer?

Linux 6.6.87.2-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Step 1. Create a file named `test.js`:

```js
// test.js
const text = Array(10000).fill('肉醬意大利粉').join('\n')
console.log(text)
```

Step 2. Run the following command in a bash shell:

```bash
bun test.js | sed "/肉醬意大利粉/d; ="
```

Step 2 (Alternative). Run the following command:

```bash
bun test.js > test.out
```

Match the regex `^(?!肉醬意大利粉)` in the file `test.out`.

### What is the expected behavior?

The command should print nothing.

<details>
<summary>Rationale</summary>

The `sed` command will match the line with the regex "肉醬意大利粉". If matched, nothing will be printed. Otherwise, the line number as well as the content will be printed.

</details>

### What do you see instead?

Extra bytes are printed on Line 3450 and Line 6899, respectively.

```
3450
肉�醬意大利粉
6899
肉醬�意大利粉
```

### Additional information

The bug is reproducible on two other platforms:

- an Ubuntu server (`Linux 5.15.0-140-generic x86_64 x86_64`)
- a Windows PC (`Microsoft Windows NT 10.0.22631.0 x64`)

I also tested on Node v22.15.0, which printed all lines correctly.

The following script also printed all lines correctly. So this bug is probably only related to the `console.log()` method.

```js
// test.js
const text = Array(10000).fill('肉醬意大利粉').join('\n')
// console.log(text)
text.split('\n').forEach((line) => console.log(line))
```

The following script also printed all lines correctly.

```js
// test.js
// const text = Array(10000).fill('肉醬意大利粉').join('\n')
const text = Array(10000).fill('the quick brown fox jumps over the lazy dog').join('\n')
console.log(text)
```

### PR DESCRIPTION
**Pull request by zackradisic**
### Problem

The `copyUTF16IntoUTF8WithBuffer` function converts UTF-16 strings into UTF-8 and writes them to a provided buffer.

This function had a `allow_partial_write` parameter. If enabled and the function encountered a codepoint whose UTF-8 bytelength could not fit in the output buffer, it would write only the bytes that could fit.

For example, if the function encountered a codepoint whose UTF-8 bytelength was 3 bytes, but the remaining buffer had only 1 byte left, it would do:

```
// write the first byte of the 3 byte encoding
remaining[0] = @as(u8, @truncate(0xE0 | (replacement.code_point >> 12)));
```

This is actually what a node Buffer does if you write a unicode codepoint whose bytelength is longer than the buffer, and is the reason this parameter exists.

The issue is that `allow_partial_write` is a confusing name. This function _already_ does "partial" writes, in the sense that it will write as many codepoints to the buffer that can fit. What this parameter _really_ should be called is `allow_truncated_utf8_sequence` or something of the sort to signal that it's allowing incomplete utf-8 sequences to be written to the output.

This confusion led to this parameter being enabled in places it should absolutely not be, for example when formatting a string for console.log (see #20564)

### Solution

Renamed the parameter and the `copyUTF16IntoUTF8WithBuffer` and `copyUTF16IntoUTF8` functions have it disabled by default. You can use `copyUTF16IntoUTF8WithBufferImpl` and `copyUTF16IntoUTF8Impl` to manually enable it.

Fixes #20564 

and possibly many many more

### CODE REVIEW

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
The Node buffer tests show this is not quite correct. We should probably keep the behavior for Buffer, and not use it elsewhere.

File: src/baby_list.zig [hunk 1]
```diff
@@ -389,7 +389,7 @@ pub fn BabyList(comptime Type: type) type {
                     const orig_len = list_.items.len;
 
                     const slice_ = list_.items.ptr[orig_len..list_.capacity];
-                    const result = strings.copyUTF16IntoUTF8WithBuffer(slice_, []const u16, remain, trimmed, out_len, true);
+                    const result = strings.copyUTF16IntoUTF8WithBuffer(slice_, []const u16, remain, trimmed, out_len);
```
Comment (Jarred-Sumner) [inline src/baby_list.zig]: Is this a breaking change?

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
The risk of subtle breaking changes with no test coverage is high in this PR. Can we instead keep the status quo behavior in all call sites we're not 100% confident should be updated, and leave a FIXME comment?

File: src/bun.js/webcore/Sink.zig [hunk 2]
```diff
@@ -79,7 +79,7 @@ pub const UTF8Fallback = struct {
 
         if (stack_size >= str.len * 2) {
             var buf: [stack_size]u8 = undefined;
-            const copied = bun.strings.copyUTF16IntoUTF8(&buf, []const u16, str, true);
```
Comment (zackradisic) [inline src/bun.js/webcore/Sink.zig:82]: We should keep partial writes here

File: src/install/PackageInstall.zig [hunk 3]
```diff
@@ -1317,7 +1317,7 @@ pub const PackageInstall = struct {
                 _ = node_fs_for_package_installer.mkdirRecursiveOSPathImpl(void, {}, fullpath, 0, false);
             }
 
-            const res = strings.copyUTF16IntoUTF8(dest_buf[0..], []const u16, wbuf[0..i], true);
+            const res = strings.copyUTF16IntoUTF8(dest_buf[0..], []const u16, wbuf[0..i]);
```
Comment (zackradisic) [inline src/install/PackageInstall.zig:1320]: We should keep partial writes here

File: src/http/websocket_client.zig [hunk 4]
```diff
@@ -1228,7 +1228,7 @@ const Copy = union(enum) {
         switch (this) {
             .utf16 => |utf16| {
                 header.len = WebsocketHeader.packLength(content_byte_len);
-                const encode_into_result = strings.copyUTF16IntoUTF8(to_mask, []const u16, utf16, true);
+                const encode_into_result = strings.copyUTF16IntoUTF8(to_mask, []const u16, utf16);
```
Comment (zackradisic) [inline src/http/websocket_client.zig]: We should keep partial writes here

File: src/string/MutableString.zig [hunk 5]
```diff
@@ -393,7 +392,6 @@ pub const BufferedWriter = struct {
                 this.remain()[0 .. bytes.len * 2],
                 []const u16,
                 bytes,
-                true,
```
Comment (zackradisic) [inline src/string/MutableString.zig:396]: This should match text encoder and so not do partial writes

Comment (zackradisic) [reply src/string/MutableString.zig:396]: Also we should check how textencoder in nodejs and what it does

Comment (zackradisic) [reply src/string/MutableString.zig:396]: TextEncoder in nodejs will write nothing if there isn't enough space

**Comment by zackradisic** [comment]
Alright so I have restored original behavior to pretty much all codepaths. Now the places that have changed are:

1. `formatUTF16TypeWithPathOptions` in `fmt.zig`, as this was causing the causing `console.log(...)` to write invalid UTF-8 bytes. You never want to write invalid UTF-8 in this formatting function.
2. The code in `TextEncoder.zig`, the `TextEncoder__encode16` ensures that there is enough space in the buffer and the `TextEncoder__encodeInto16` function is for `TextEncoder.encodeInto(...)` whose [behavior is to stop without writing the codepoint if there is not enough space](https://encoding.spec.whatwg.org/#dom-textencoder-encodeinto).
3. Also `MutableString.zig` as it is supposed to behave exactly as `TextEncoder` according to the comment in the file
