### PR TITLE
Fix fd offset handling in ReadStream

### LINKED ISSUE #9907: `fs.createReadStream` and `fs.createWriteStream` from `fd` behaviour differs from Node
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

```js
const fs = require('fs');
const path = require('path');
const os = require('os');

const tempFile = path.join(os.tmpdir(), 'temp.txt');
fs.open(tempFile, 'w+', (err, fd) => {
  if (err) {
    console.error('Error opening file:', err);
    return;
  }

  const writeStream = fs.createWriteStream('', { fd: fd });
  const readStream = fs.createReadStream('', { fd: fd, start: 0 });

  readStream.on('data', (chunk) => {
    console.log('Got chunk', chunk.toString())
  });

  const data = 'Hello, World!';
  writeStream.write(data, (err) => {
    if (err) {
      console.error('Error writing to file:', err);
      writeStream.close(() => { });
      return;
    }

    console.log('Data written to file.');
  });
});
```

### What is the expected behavior?

```
~/projects/bun-fd-repro
❯ node test.js
Data written to file.
Got chunk Hello, World!
```

### What do you see instead?

```
~/projects/bun-fd-repro
❯ bun test.js
Data written to file.
```

### Additional information

Originally ran into this bug bumping Bun while testing https://github.com/replit/ruspty

### PR DESCRIPTION
**Pull request by gvilums**
### What does this PR do?
Fixes #9907

### How did you verify your code works?
Added a test

### CODE REVIEW

File: src/io/PipeReader.zig [hunk 1]
```diff
@@ -948,6 +981,7 @@ pub const WindowsBufferedReader = struct {
 
         is_paused: bool = true,
         has_inflight_read: bool = false,
+        use_pread: bool = false,
```
Comment (Jarred-Sumner) [inline src/io/PipeReader.zig:984]: 8 bits -> 9 bits 😢

Comment (Jarred-Sumner) [reply src/io/PipeReader.zig:984]: idk what to do about that, seems fine

Comment (gvilums) [reply src/io/PipeReader.zig:984]: because the entire struct is 8-byte aligned this doesn't matter anyway

File: src/bun.js/webcore/streams.zig [hunk 2]
```diff
@@ -348,6 +348,37 @@ pub const ReadableStream = struct {
...
+                            .blob = store,
+                        },
+                    },
+                });
+                store.ref();
+
+                return reader.toReadableStream(globalThis);
+            },
+            else => {
+                return .zero;
```
Comment (Jarred-Sumner) [inline src/bun.js/webcore/streams.zig:378]: This will cause a crash at runtime if it ever is reached.

```suggestion
                globalThis.throw("Expected FileBlob", .{});
                return .zero;
```

**Review by Jarred-Sumner — APPROVED** [review]
LGTM

One comment
