### PR TITLE
revert 84c91bf7e16f5cf2f629d8d38124d1967755f247

### LINKED ISSUE #5542: TextDecoder doesn't implement "stream" option
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

```js
const decoder = new TextDecoder('utf-8');
const first = decoder.decode(new Uint8Array([226, 153]), { stream: true });
const second = decoder.decode(new Uint8Array([165]), { stream: true });
console.log({first, second});
```

### What is the expected behavior?

`first` should be an empty string and `second` should return a `♥` string

### What do you see instead?

Both `first` and `second` are populated with incorrect values

### Additional information

_No response_

### LINKED ISSUE #5648: Add TextDecoderStream and TextEncoderStream
`TextDecoderStream` and `TextEncoderStream` are missing

### PR DESCRIPTION
**Pull request by dylan-conway**
### What does this PR do?
Reverts 84c91bf7e16f5cf2f629d8d38124d1967755f247, bringing back `TextEncoderStream` and `TextDecoderStream`.

Also changes `TextEncoderStream` to use `simdutf` when possible.

closes #5648 
closes #5542 

### How did you verify your code works?
existing tests

### CODE REVIEW

**Comment by robobun** [comment]
@dylan-conway, your commit e3570c762f64fbca6822d6a29a516904f8d33244 is building: [`#1654`](https://buildkite.com/bun/bun/builds/1654)

File: test/harness.ts [hunk 1]
```diff
@@ -1174,6 +1174,17 @@ export function isMacOSVersionAtLeast(minVersion: number): boolean {
   return parseFloat(macOSVersion) >= minVersion;
 }
 
+export function readableStreamFromArray(array) {
+  return new ReadableStream({
+    start(controller) {
```
Comment (Jarred-Sumner) [inline test/harness.ts]:
```suggestion
    pull(controller) {
```
