### PR TITLE
fix(bundler): fix part liveness calculation

### LINKED ISSUE #9037: Ts code not working after bun build
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

```
bun build index.ts --target=bun --outfile index.js 
bun run index.js
```

1. Run pushSSHPublicKey:

```js
import {
  EC2InstanceConnectClient,
  SendSSHPublicKeyCommand,
} from "@aws-sdk/client-ec2-instance-connect";

const { AWS_REGION, INSTANCE_ID, BASTION_USER, AVAILABILITY_ZONE } =
  process.env;

const pushSSHPublicKey = async (publicKey: string) => {
  const client = new EC2InstanceConnectClient({ region: AWS_REGION });

  const command = new SendSSHPublicKeyCommand({
    InstanceId: INSTANCE_ID,
    InstanceOSUser: BASTION_USER,
    SSHPublicKey: publicKey,
    AvailabilityZone: AVAILABILITY_ZONE,
  });

  try {
    await client.send(command);

    console.log("SSH public key successfully pushed to the instance.");
    return true;
  } catch (error) {
    console.error("Failed to push SSH public key:", error);
    return false;
  }
};

export { pushSSHPublicKey };
```

.env of:
```
AWS_REGION=us-west-2 (is my case, but probably not relevant)
INSTANCE_ID (can't share)
BASTION_USER (can't share)
AVAILABILITY_ZONE (can't share)
AWS_PROFILE=xxxx (This is important, if this is not defined, it works as expected), I am using AWS identity center on my profile
```

.aws/config contents:
```
[default]
sso_account_id = (can't share)
sso_region = (can't share)
sso_start_url=(can't share)
sso_role_name = (can't share)
region = us-west-2
[profile (can't share)]
sso_session = (can't share)
sso_account_id = (can't share)
sso_role_name = (can't share)
[sso-session (can't share)]
sso_start_url = (can't share)
sso_region = (can't share)
sso_registration_scopes = (can't share)
```

### What is the expected behavior?

Same result from
bun run index.ts 

And:
```
bun build index.ts --target=bun --outfile index.js 
bun run index.js
```

### What do you see instead?

When I run bun run index.ts, the code works as expected.

When I run:
```
bun build index.ts --target=bun --outfile index.js 
bun run index.js
```

I get the error bellow:

```js
26731 | // node_modules/@aws-sdk/client-sso/dist-es/SSOClient.js
26732 | class SSOClient extends Client {
26733 |   constructor(...[configuration]) {
26734 |     const _config_0 = getRuntimeConfig4(configuration || {});
                              ^
TypeError: getRuntimeConfig4 is not a function. (In 'getRuntimeConfig4(configuration || {})', 'getRuntimeConfig4' is undefined)
      at new SSOClient (/Users/pedrolunardelli/code/generateSecureBastionConnection/index.js:26734:23)
      at /Users/pedrolunardelli/code/generateSecureBastionConnection/index.js:27108:30

Error: 31541 |   try {
31542 |     const { publicKey, privateKey } = generateKeyPair();
31543 |     await prepareDir();
31544 |     const keyUpdated = await pushSSHPublicKey(publicKey);
31545 |     if (!keyUpdated)
31546 |       throw new Error("Failed to update the SSH public key.");
                    ^
error: Failed to update the SSH public key.
      at /Users/pedrolunardelli/code/generateSecureBastionConnection/index.js:31546:13
```

For some context of index.js (generated by bun build index.ts --target=bun --outfile index.js ):
```js
  // node_modules/@aws-sdk/client-sso/dist-es/runtimeConfig.js
var getRuntimeConfig4;
var init_runtimeConfig2 = __esm(() => {
  init_package2();
  init_dist_es37();
  init_dist_es41();
  init_dist_es11();
  init_dist_es42();
  init_dist_es31();
  init_dist_es14();
  init_dist_es28();
  init_dist_es43();
  init_dist_es20();
  init_runtimeConfig_shared2();
  init_dist_es30();
  init_dist_es44();
  init_dist_es30();
  getRuntimeConfig4 = (config7) => {
    emitWarningIfUnsupportedVersion(process.version);
    const defaultsMode = resolveDefaultsModeConfig(config7);
    const defaultConfigProvider = () => defaultsMode().then(loadConfigsForDefaultMode);
    const clientSharedValues = getRuntimeConfig3(config7);
    emitWarningIfUnsupportedVersion3(process.version);
    return {
      ...clientSharedValues,
      ...config7,
      runtime: "node",
      defaultsMode,
      bodyLengthChecker: config7?.bodyLengthChecker ?? calculateBodyLength,
      defaultUserAgentProvider: config7?.defaultUserAgentProvider ?? defaultUserAgent({ serviceId: clientSharedValues.serviceId, clientVersion: package_default3.version }),
      maxAttempts: config7?.maxAttempts ?? loadConfig(NODE_MAX_ATTEMPT_CONFIG_OPTIONS),
      region: config7?.region ?? loadConfig(NODE_REGION_CONFIG_OPTIONS, NODE_REGION_CONFIG_FILE_OPTIONS),
      requestHandler: config7?.requestHandler ?? new NodeHttpHandler(defaultConfigProvider),
      retryMode: config7?.retryMode ?? loadConfig({
        ...NODE_RETRY_MODE_CONFIG_OPTIONS,
        default: async () => (await defaultConfigProvider()).retryMode || DEFAULT_RETRY_MODE
      }),
      sha256: config7?.sha256 ?? Hash.bind(null, "sha256"),
      streamCollector: config7?.streamCollector ?? streamCollector,
      useDualstackEndpoint: config7?.useDualstackEndpoint ?? loadConfig(NODE_USE_DUALSTACK_ENDPOINT_CONFIG_OPTIONS),
      useFipsEndpoint: config7?.useFipsEndpoint ?? loadConfig(NODE_USE_FIPS_ENDPOINT_CONFIG_OPTIONS)
    };
  };
});

class SSOClient extends Client {
  constructor(...[configuration]) {
    const _config_0 = getRuntimeConfig4(configuration || {});
    const _config_1 = resolveClientEndpointParameters3(_config_0);
    const _config_2 = resolveRegionConfig(_config_1);
    const _config_3 = resolveEndpointConfig(_config_2);
    const _config_4 = resolveRetryConfig(_config_3);
    const _config_5 = resolveHostHeaderConfig(_config_4);
    const _config_6 = resolveUserAgentConfig(_config_5);
    const _config_7 = resolveHttpAuthSchemeConfig3(_config_6);
    const _config_8 = resolveRuntimeExtensions2(_config_7, configuration?.extensions || []);
    super(_config_8);
    this.config = _config_8;
    this.middlewareStack.use(getRetryPlugin(this.config));
    this.middlewareStack.use(getContentLengthPlugin(this.config));
    this.middlewareStack.use(getHostHeaderPlugin(this.config));
    this.middlewareStack.use(getLoggerPlugin(this.config));
    this.middlewareStack.use(getRecursionDetectionPlugin(this.config));
    this.middlewareStack.use(getUserAgentPlugin(this.config));
    this.middlewareStack.use(getHttpAuthSchemeEndpointRuleSetPlugin(this.config, {
      httpAuthSchemeParametersProvider: this.getDefaultHttpAuthSchemeParametersProvider(),
      identityProviderConfigProvider: this.getIdentityProviderConfigProvider()
    }));
    this.middlewareStack.use(getHttpSigningPlugin(this.config));
  }
  destroy() {
    super.destroy();
  }
  getDefaultHttpAuthSchemeParametersProvider() {
    return defaultSSOHttpAuthSchemeParametersProvider;
  }
  getIdentityProviderConfigProvider() {
    return async (config7) => new DefaultIdentityProviderConfig({
      "aws.auth#sigv4": config7.credentials
    });
  }
}
```
  

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by paperclover**
### What does this PR do?

This fixes a very subtle mistake when determining which parts are live. See https://github.com/oven-sh/bun/issues/12571#issuecomment-2244067465, After fixing this first bug, there were three or four other fixes which are all very subtle but now Bun is now correct when it comes to this dependency calculation instead of just getting lucky.

Not marking #12571 as fixed because want to keepthe issue open as it shows sourcemaps are broken, **which this PR does not address**.

Fixes #9037 (different repro, same underlying bug)

---

Note that for the provided reproduction in 12571, it now errors with when sending the callback.html

image

@davidgomes
For the file not found, I think that there is a bug with bun there, but this pattern works:

```
createReadStream(require.resolve("./callback.html")).pipe(response)
```

### CODE REVIEW

File: src/bundler/bundle_v2.zig [hunk 1]
```diff
@@ -4883,8 +4884,6 @@ const LinkerContext = struct {
                                 .exports_kind = exports_kind,
                                 .named_exports = this.graph.ast.items(.named_exports),
                             };
-                        } else {
-                            export_star_ctx.?.source_index_stack.clearRetainingCapacity();
```
Comment (Jarred-Sumner) [inline src/bundler/bundle_v2.zig:4887]: Is this intentional?

File: src/bundler/bundle_v2.zig [hunk 2]
```diff
@@ -5543,49 +5538,45 @@ const LinkerContext = struct {
...
-            var ptr = ns_export_dependencies.items.ptr + ns_export_dependencies.items.len;
-            ns_export_dependencies.items.len += parts.len;
 
-            for (parts, ptr[0..parts.len]) |part_id, *dependency| {
+            for (parts) |part_id| {
                 // Use a non-local dependency since this is likely from a different
                 // file if it came in through an export star
-                dependency.* = .{
-                    .source_index = export_.data.source_index,
+                ns_export_dependencies.appendAssumeCapacity(.{
```
Comment (Jarred-Sumner) [inline src/bundler/bundle_v2.zig]: Do we need to use `appendAssumeCapacity` here? We cannot use the slice? Every time you call .appendAssumeCapacity, it increments the length one-by-one

File: src/bundler/bundle_v2.zig [hunk 3]
```diff
@@ -10187,7 +10179,19 @@ const LinkerContext = struct {
...
         );
 
+        if (Environment.isDebug and part.dependencies.slice().len == 0) {
+            logPartDependencyTree("markPartLiveForTreeShaking {d}:{d} | EMPTY", .{
+                id, part_index,
+            });
+        }
+
         for (part.dependencies.slice()) |dependency| {
+            if (id != 0 and dependency.source_index.get() != 0) {
```
Comment (Jarred-Sumner) [inline src/bundler/bundle_v2.zig]:
```suggestion
if (comptime Environment.allow_logs) {
            if (id != 0 and dependency.source_index.get() != 0) {
```

File: src/bundler/bundle_v2.zig (hunk 1 above)
Comment (paperclover) [reply src/bundler/bundle_v2.zig:4887]: yes

File: src/bundler/bundle_v2.zig [hunk 4]
```diff
@@ -10924,14 +10907,13 @@ const LinkerContext = struct {
                 if (i == source_index)
                     return;
             }
-
-            this.source_index_stack.append(source_index) catch unreachable;
+            this.source_index_stack.append(source_index) catch bun.outOfMemory();
             const stack_end_pos = this.source_index_stack.items.len;
-            const id = source_index;
+            defer this.source_index_stack.shrinkRetainingCapacity(stack_end_pos - 1);
```
Comment (Jarred-Sumner) [inline src/bundler/bundle_v2.zig:10912]: `stack_end_pos` can never be 0 right?

File: test/bundler/bundler_edgecase.test.ts [hunk 5]
```diff
@@ -1443,6 +1443,32 @@ describe("bundler", () => {
       "/entry.ts": [`"Y" has already been declared`],
     },
   });
+  // This specifically only happens with 'export { ... } from ...' syntax
+  itBundled("edgecase/EsmSideEffectsFalseWithSideEffectsExportFrom", {
+    files: {
+      "/file1.js": `
+        import("./file2.js");
```
Comment (Jarred-Sumner) [inline test/bundler/bundler_edgecase.test.ts:1450]: Tests for:
- `require` but the same as this
- One with code splitting enabled where two entry points import the same other files

File: src/bundler/bundle_v2.zig (hunk 2 above)
Comment (paperclover) [reply src/bundler/bundle_v2.zig]: no; and im glad this was brought up since unusedCapacitySlice is even easier to read

image

File: src/bundler/bundle_v2.zig (hunk 4 above)
Comment (paperclover) [reply src/bundler/bundle_v2.zig:10912]: it cannot be 0

**Review by Jarred-Sumner — APPROVED** [review]
