### PR TITLE
Fix assertion failure on Windows in resolver

### LINKED ISSUE #21065: Devserver crash
### How can we reproduce the crash?

// a.html
```
<img src=":://filesystem">
```

```
bun --port=3456 a.html
```

(open localhost:3456 in browser)

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.2.18 ([`0d4089e`](<https://github.com/oven-sh/bun/tree/0d4089ea7c48d339e87cc48f1871aeee745d8112>)) on windows x86_64 [AutoCommand]

**panic**: Internal assertion failure

- [`resolve_path.zig:1323`](<https://github.com/oven-sh/bun/blob/0d4089ea7c48d339e87cc48f1871aeee745d8112/src/resolver/resolve_path.zig#L1323>): `_joinAbsStringBuf`
- [`lol-html.zig:567`](<https://github.com/oven-sh/bun/blob/0d4089ea7c48d339e87cc48f1871aeee745d8112/src/deps/lol-html.zig#L567>): `deinit`
- `_ZN7lolhtml16rewriter_builder28ExternElementContentHandlers32as_safe_element_content_handlers28_$u7b$$u7b$closure$u7d$$u7d$17h03d6caa395ea657bE.llvm.15211960869409622836`
- `_ZN8lol_html8rewriter19handlers_dispatcher34ContentHandlersDispatcher$LT$H$GT$12handle_token17h9727b16c73514cd0E`
- `??`
- `_ZN8lol_html16rewritable_units6tokens8capturer13TokenCapturer4feed17h1bd54752b2e25116E`
- `_ZN119_$LT$lol_html..transform_stream..dispatcher..Dispatcher$LT$C$C$O$GT$$u20$as$u20$lol_html..parser..lexer..LexemeSink$GT$10handle_tag17he7cd9169603b4fc3E`

Features: tsconfig, tsconfig\_paths, process\_dlopen, Bun.stderr, Bun.stdout, bunfig, http\_server, jsc, dev\_server

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6747300971/">BUN-QTY</a></strong></sub>

### PR DESCRIPTION
**Pull request by zackradisic**
### What does this PR do?

We had `bun.strings.assertIsValidWindowsPath(...)` in the resolver, but we can't do this because the path may come from the user. Instead, let our error handling code handle it.

Also fixes #21065

### CODE REVIEW

**Comment by robobun** [comment]
<div><sup>Updated 8:12 PM PT - Jul 30th, 2025</sup></div>

@zackradisic, your commit ec878d6b4c32b0adc3948ce8a017e99ba21093b9 is building: [`#21843`](https://buildkite.com/bun/bun/builds/21843)

File: src/resolver/resolver.zig [hunk 1]
```diff
@@ -3755,7 +3755,8 @@ pub const Resolver = struct {
         }
 
         const dir_path = bun.strings.withoutTrailingSlashWindowsPath(Dirname.dirname(path));
-        bun.strings.assertIsValidWindowsPath(u8, dir_path);
+        // Don't validate the path, let our error handling if it is invalid
```
Comment (Jarred-Sumner) [inline src/resolver/resolver.zig]:
```suggestion

```

File: src/resolver/resolver.zig [hunk 2]
```diff
@@ -3755,7 +3755,8 @@ pub const Resolver = struct {
...
+        // bun.strings.assertIsValidWindowsPath(u8, dir_path);
```
Comment (Jarred-Sumner) [inline src/resolver/resolver.zig]:
```suggestion

```
