### PR TITLE
[jest] fix and improve hooks

### LINKED ISSUE #1688: Test suite `beforeAll` is not executed
### What version of Bun is running?

0.4.0

### What platform is your computer?

WSL / Windows

### What steps can reproduce the bug?

Use Surreal.JS with Bun:

```ts
import { beforeAll, it, describe, expect, afterAll } from 'bun:test';
import Surreal from 'surrealdb.js';

const TEST_DB = 'tests';
const db = new Surreal(process.env.SURREAL_HOST);

describe('Database', async () => {
	beforeAll(async () => {
		await db.signin({
			user: 'root',
			pass: 'root',
		});

		await db.use('test_namespace', TEST_DB);

		await db.query('DEFINE DATABASE tests');
		console.log('beforeAll');
	});

	afterAll(async () => {
		await db.query('REMOVE DATABASE tests');
		db.close();

		console.log('afterAll');
	});

	it('Database connection', async () => {
		expect(db).toBeDefined();
	});
});

```

### What is the expected behavior?

I expect the code provided in `beforeAll` to be executed but there are no DB calls or console.logs

### What do you see instead?

Only the `afterAll` is executed and logged

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alexlamsl**
- wait for async hooks to complete before running tests
- add support for `done(err)` callbacks in hooks

fixes #1688

### CODE REVIEW

File: test/bun.js/jest.test.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+});
+
+describe("describe", async () => {
+  var before = false;
+  var after = false;
+
+  beforeAll(async () => {
+    if (before) throw new AssertionError("before should be false");
+    if (after) throw new AssertionError("after should be false");
+    before = await new Promise(resolve => setTimeout(() => resolve(true), 1000));
```
Comment (Jarred-Sumner) [inline test/bun.js/jest.test.js]: this test will take a second to run

can you make this 1ms instead

File: test/bun.js/jest.test.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+  if (after) throw new AssertionError("after should be false");
+  await new Promise(resolve => setTimeout(() => resolve(before = true), 1000));
+});
+
+it("should run after beforeAll()", async () => {
+  expect(before).toBe(true);
+  expect(after).toBe(false);
+});
+
+afterAll(() => {
```
Comment (Jarred-Sumner) [inline test/bun.js/jest.test.js]: we have tests for the non-async versions here https://github.com/oven-sh/bun/blob/b86915c80819e61e6e1932d7802a4c31c73094e9/test/bun.js/bun-test/jest-hooks.test.ts#L1-L30

**Comment by Jarred-Sumner** [comment]
In a future PR we should support the `done` callback too

File: test/bun.js/jest.test.js [hunk 3]
```diff
@@ -0,0 +1,43 @@
+import { beforeAll, it, describe, expect, afterAll } from 'bun:test';
+
+var before = false;
+var after = false;
+
+beforeAll(async () => {
+  if (before) throw new AssertionError("before should be false");
```
Comment (Jarred-Sumner) [inline test/bun.js/jest.test.js]: Where is `AssertionError` defined?

File: test/bun.js/jest.test.js (hunk 1 above)
Comment (alexlamsl) [reply test/bun.js/jest.test.js]: Even with 500ms this test will pass most of the time :sweat_smile:

File: test/bun.js/jest.test.js (hunk 2 above)
Comment (alexlamsl) [reply test/bun.js/jest.test.js]: Ah okay, I'll lump these tests together then.

File: test/bun.js/jest.test.js (hunk 3 above)
Comment (alexlamsl) [reply test/bun.js/jest.test.js]: I might have misread the resulting `ReferenceError` as a sign this was working :sweat_smile:

File: test/bun.js/jest.test.js (hunk 1 above)
Comment (alexlamsl) [reply test/bun.js/jest.test.js]: Since `beforeEach()` fails reliably without `setTimeout()`, and this PR does fix the common logic for both, I've updated the tests such that `beforeAll()` will _not_ fail (most of the time) without this fix, but won't be holding up dead time.

**Comment by alexlamsl** [comment]
> In a future PR we should support the done callback too

rolled into this PR :wink:

File: src/bun.js/test/jest.zig [hunk 4]
```diff
@@ -1486,16 +1487,63 @@ pub const DescribeScope = struct {
...
+                this.done_result = null;
+                const done_func = JSC.NewFunctionWithData(
+                    ctx,
+                    ZigString.static("done"),
+                    0,
+                    DescribeScope.onDone,
+                    false,
+                    this,
+                );
+                _ = cb.call(ctx, &.{done_func});
```
Comment (Jarred-Sumner) [inline src/bun.js/test/jest.zig]: what if the result is an async function? it won't wait for it to return

File: src/bun.js/test/jest.zig [hunk 5]
```diff
@@ -1486,16 +1487,63 @@ pub const DescribeScope = struct {
...
+                var vm = VirtualMachine.get();
+                while (true) {
+                    if (this.done_result) |result| {
+                        break :brk result;
```
Comment (Jarred-Sumner) [inline src/bun.js/test/jest.zig]: this would allow you to do

```js
beforeAll((done) => {
  done(fetch("https://example.com"))
});
```

and it would wait for fetch to fulfill

which is kind of interesting

but I don't think jest does that

File: src/bun.js/test/jest.zig [hunk 6]
```diff
@@ -1398,6 +1398,7 @@ pub const DescribeScope = struct {
     file_id: TestRunner.File.ID,
     current_test_id: TestRunner.Test.ID = 0,
     value: JSValue = .zero,
+    done_result: ?JSValue = null,
```
Comment (Jarred-Sumner) [inline src/bun.js/test/jest.zig]: This technically can be .zero instead of optional, but its okay

Comment (alexlamsl) [reply src/bun.js/test/jest.zig]: turns out I want it to just be `bool` after all :rofl:

File: src/bun.js/test/jest.zig (hunk 5 above)
Comment (alexlamsl) [reply src/bun.js/test/jest.zig]: Indeed not &minus; that value is solely for error reporting, now fixed.

File: src/bun.js/test/jest.zig (hunk 4 above)
Comment (alexlamsl) [reply src/bun.js/test/jest.zig]: Fixed in https://github.com/oven-sh/bun/pull/1689/commits/01649b435a67ef33e991e9f8daf68beae3349478

**Comment by Jarred-Sumner** [comment]
great
