### PR TITLE
'let' statements before using statements are now properly converted into 'var' statements

### LINKED ISSUE #12407: `using` hoisting bug with generator functions in module scope
In Bun v1.1.18

The following input emits a `ReferenceError`:
```ts
const env = {}
using server = Bun.serve({
  port: 0,
  fetch(req) {},
});
for (let k of run()) {

}
function* run() {
  console.log(env)
}
```

Error:
```ts
2 | const env = {}
3 | using server = Bun.serve({
4 |   port: 0,
5 |   fetch(req) {},
6 | });
7 | for (let k of run()) {
                  ^
TypeError: undefined is not an object (evaluating 'run()')
      at /private/tmp/b.mjs:7:15

Bun v1.1.18-canary.1+da1b3d200 (macOS arm64)
```

Output:
```ts
var __dispose = Symbol.dispose || Symbol.for("Symbol.dispose");
var __asyncDispose = Symbol.dispose || Symbol.for("Symbol.dispose");
var __using = (stack, value, async) => {
  if (value != null) {
    if (typeof value !== "object" && typeof value !== "function")
      throw TypeError('Object expected to be assigned to "using" declaration');
    var dispose;
    if (async)
      dispose = value[__asyncDispose];
    if (dispose === undefined)
      dispose = value[__dispose];
    if (typeof dispose !== "function")
      throw TypeError("Object not disposable");
    stack.push([async, dispose, value]);
  } else if (async) {
    stack.push([async]);
  }
  return value;
};
var __callDispose = (stack, error, hasError) => {
  var E = typeof SuppressedError === "function" ? SuppressedError : function(e, s, m, _) {
    return _ = Error(m), _.name = "SuppressedError", _.error = e, _.suppressed = s, _;
  }, fail = (e) => error = hasError ? new E(e, error, "An error was suppressed during disposal") : (hasError = true, e), next = (it) => {
    while (it = stack.pop()) {
      try {
        var result = it[1] && it[1].call(it[2]);
        if (it[0])
          return Promise.resolve(result).then(next, (e) => (fail(e), next()));
      } catch (e) {
        fail(e);
      }
    }
    if (hasError)
      throw error;
  };
  return next();
};

// /tmp/b.mjs
var __stack = [];
try {
  let run = function() {
    console.log(env);
  };
  const env = {};
  var server = __using(__stack, Bun.serve({
    port: 0,
    fetch(req) {
    }
  }), 0);
  for (let k of run()) {
  }
} catch (_catch) {
  var _err = _catch, _hasErr = 1;
} finally {
  __callDispose(__stack, _err, _hasErr);
}
```

We are hoisting generator and async generator functions outside of the scope of the using declaration we wrap it in, causing a ReferenceError

### PR DESCRIPTION
**Pull request by snoglobe**
### What does this PR do?

fixes #12407 and the regression demonstrated in #11083 where a `let` statement before a `using` would not be converted into a `var` so anything referencing it outside of the generated try/catch would raise a `ReferenceError`

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### CODE REVIEW

**Comment by robobun** [comment]
@snoglobe, your commit 4077e3c9a351f46388abe640b0a31a19fb2032f6 is building: [`#4092`](https://buildkite.com/bun/bun/builds/4092)

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
Several test failures

File: src/js_parser.zig [hunk 1]
```diff
@@ -22197,29 +22198,37 @@ fn NewParser_(
...
                                     var end: usize = 0;
+                                    var any_decl_in_const_values = local.kind == .k_const;
                                     for (decls) |decl| {
                                         if (decl.binding.data == .b_identifier) {
-                                            const symbol = p.symbols.items[decl.binding.data.b_identifier.ref.innerIndex()];
-                                            if (p.const_values.contains(decl.binding.data.b_identifier.ref) and symbol.use_count_estimate == 0) {
-                                                continue;
+                                            if (p.const_values.contains(decl.binding.data.b_identifier.ref)) {
+                                                any_decl_in_const_values = true;
+                                                const symbol = p.symbols.items[decl.binding.data.b_identifier.ref.innerIndex()];
```
Comment (Jarred-Sumner) [inline src/js_parser.zig:22209]:
```suggestion
                                                const symbol = &p.symbols.items[decl.binding.data.b_identifier.ref.innerIndex()];
```

File: src/js_parser.zig [hunk 2]
```diff
@@ -22197,29 +22198,37 @@ fn NewParser_(
...
+                                                }
                                             }
                                         }
                                         decls[end] = decl;
                                         end += 1;
                                     }
                                     local.decls.len = @as(u32, @truncate(end));
-                                    if (end == 0) {
-                                        stmt.* = stmt.*.toEmpty();
+                                    if (any_decl_in_const_values) {
```
Comment (Jarred-Sumner) [inline src/js_parser.zig]: should this if be there? i'm confused

Comment (snoglobe) [reply src/js_parser.zig]: it's the only side effect that happens if it being const/in const_values is true. so we don't want it to happen if the check is false

Comment (snoglobe) [reply src/js_parser.zig]: (the locals.decls.len assignment is a no-op if it's false because end will be the len value. it should probably be moved into the if statement too though then)

**Review by Jarred-Sumner — CHANGES_REQUESTED** [review]
merge conflict

**Comment by snoglobe** [comment]
fixed
