### PR TITLE
WebKit upgrade

### LINKED ISSUE #12084: Object expansion is broken
### What version of Bun is running?

1.1.16

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```
Object.defineProperty(Object.prototype, 'some', { value: 1, enumerable: false, writable: true, configurable: true })
console.log(({} as any).some)

const found = /.+ (?<a>\d+) (?<b>\d+)/.exec('a 22 45')
console.log(({ ...(found?.groups || {}) } as any).some)
```

### What is the expected behavior?

1
1

### What do you see instead?

1
undefined

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jarred-Sumner**
### What does this PR do?

WIP.

**JavaScriptCore functions on Windows now must use the (unix) SysV ABI**
- [x] All of our functions which are directly called from JavaScript must be changed to use the SysV ABI. In most cases in C++, there's not much to change. In Zig, many functions need to use `callconv(JSC.conv)` instead of `callconv(.C)`. `JSC.conv` will do the right thing for the target platform.
- [x] This change will break TinyCC (bun:ffi) on Windows. Still need to figure out what to do about this. Worst case: we add a wrapper function when used on Windows

Fixes #12084 
Fixes https://github.com/oven-sh/bun/issues/11667 (thanks to @Constellation)
~https://github.com/oven-sh/bun/issues/5970~ does not fix that one

### CODE REVIEW

File: src/bun.js/BuildMessage.zig [hunk 1]
```diff
@@ -89,7 +89,7 @@ pub const BuildMessage = struct {
         this: *BuildMessage,
         globalThis: *JSC.JSGlobalObject,
         callframe: *JSC.CallFrame,
-    ) callconv(.C) JSC.JSValue {
+    ) JSC.JSValue {
```
Comment (dylan-conway) [inline src/bun.js/BuildMessage.zig:92]:
```suggestion
    ) callconv(JSC.conv) JSC.JSValue {
```

File: src/bun.js/api/BunObject.zig [hunk 2]
```diff
@@ -886,22 +899,22 @@ pub fn getMain(
...
+) callconv(conv) JSC.JSValue {
     return JSC.Node.Process.getArgv(globalThis);
 }
 
 const Editor = @import("../../open.zig").Editor;
 pub fn openInEditor(
     globalThis: js.JSContextRef,
     callframe: *JSC.CallFrame,
-) callconv(.C) JSValue {
+) JSValue {
```
Comment (dylan-conway) [inline src/bun.js/api/BunObject.zig:917]:
```suggestion
) callconv(conv) JSValue {
```

File: src/bun.js/ResolveMessage.zig [hunk 3]
```diff
@@ -119,7 +119,7 @@ pub const ResolveMessage = struct {
         this: *ResolveMessage,
         globalThis: *JSC.JSGlobalObject,
         callframe: *JSC.CallFrame,
-    ) callconv(.C) JSC.JSValue {
+    ) JSC.JSValue {
```
Comment (dylan-conway) [inline src/bun.js/ResolveMessage.zig:122]:
```suggestion
    ) callconv(JSC.conv) JSC.JSValue {
```

File: src/bun.js/api/BunObject.zig [hunk 4]
```diff
@@ -4518,12 +4531,12 @@ pub const FFIObject = struct {
...
         globalObject: *JSC.JSGlobalObject,
         _: *JSC.JSObject,
-    ) callconv(.C) JSC.JSValue {
+    ) callconv(conv) JSC.JSValue {
         return FFIObject.toJS(globalObject);
     }
 };
 
-fn stringWidth(globalObject: *JSC.JSGlobalObject, callframe: *JSC.CallFrame) callconv(.C) JSC.JSValue {
+fn stringWidth(globalObject: *JSC.JSGlobalObject, callframe: *JSC.CallFrame) JSC.JSValue {
```
Comment (dylan-conway) [inline src/bun.js/api/BunObject.zig:4539]:
```suggestion
fn stringWidth(globalObject: *JSC.JSGlobalObject, callframe: *JSC.CallFrame) callconv(conv) JSC.JSValue {
```

**Comment by dylan-conway** [comment]
Is it intentional some functions didn't have `callconv(.C)` replaced with `callconv(JSC.conv)` and only removed?

File: src/bun.js/base.zig [hunk 5]
```diff
@@ -934,6 +934,7 @@ pub fn DOMCall(
     comptime ResultType: type,
     comptime dom_effect: DOMEffect,
 ) type {
+    _ = ResultType; // autofix
```
Comment (dylan-conway) [inline src/bun.js/base.zig]: can we delete this arg?
